### ISSUE TITLE
AuRa test coverage not shown in the latest code coverage

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1040]
![image](https://user-images.githubusercontent.com/498913/69883633-e900e600-12cc-11ea-8e8a-e5be770e62ab.png)

**Comment by matilote** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/33068017/70128791-cf212380-167d-11ea-898e-63f9429b2f3a.png)
