### ISSUE TITLE
Was the Windows BLS dll stripped? (994kb)

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1045]
![image](https://user-images.githubusercontent.com/498913/69915332-b2021000-1445-11ea-88e5-747e6a876e1f.png)

**Comment by matilote** [comment]
Yes it was, the file size remains quite large anyway.
![image](https://user-images.githubusercontent.com/33068017/69945253-77ea4a00-14e9-11ea-8c80-16e5443617ea.png)
