### ISSUE TITLE
Implement handler for deposit contract (from Eth1)

### ISSUE THREAD

**Issue by sgryphon** [NethermindEth/nethermind#1076]
The deposit contract itself is in the Eth1 chain.

Need to add an interface / way for an Eth1 watcher to push new Eth1Data into the beacon node as needed (as it appears on the Eth1 chain).

This interface can have alternative implementations. For testing, the mocked start details from Eth2 Project Management (PM) as a way to test arrival of Eth1 data.

Another implementation can interface with Nethermind Eth1.

Maybe also provide an implementation that can lookup an Internet source / Eth1 block explorer to get the data, for people not running local Nethereum Eth1.

**Comment by tkstanczak** [comment]
This should be simple - just an interface for asking Eth1 for info and then an implementtion thatwould probably talk to either JSON RPC or directly to an embedded node for Eth1. We can deploy / use a Goerli contract - you can sync Goerli in 30 mins or so for ETH1 and try our CLI to ask questions.

I can build both an ABI layer or JSON RPC layer for invoking contract methods.

**Comment by tkstanczak** [comment]
As for the Internet source - we cn use Infura or any other JSON RPC endpoint
