### ISSUE TITLE
Basic Eth 2 PM interop for quick start

### ISSUE THREAD

**Issue by sgryphon** [NethermindEth/nethermind#1079]
Implement quick start from the Eth 2 PM interop specifications.

Note that a basic implementation is already done, and works for 3 validators, but fails on the fourth, so it is probably generating them wrong.

Need to add some unit test to check it is correctly creating at least the first 3, then investigate and fix the problem.

Additional functions, like loading from file, are in a separate work item.

**Comment by tkstanczak** [comment]
What do you mean by interop? (I see interop as a networking part to be able to talk to other nodes, especially Prysm and Shasper and so on).

**Comment by sgryphon** [comment]
Kind of related to that. It is the terminology used in the spec "Interop Standards in Eth2 PM", https://github.com/ethereum/eth2.0-pm/tree/master/interop

But really it is not about the actual network connectivity, but configuring nodes with the same test data, i.e. same genesis block, same validator keys. In lieu of having an actual Eth1 deposit contract and link.

Will be useful for live testing of the API and honest validator, so that there is a chain with Eth1 data (mocked), I have a key for the validator to use, etc.

There is a second part, to loading a specific state from an input file (SSZ or YAML), in order to test specific conditions. That is a separate work item. There are also several different ways to specify, e.g. generate the known validator keys vs loading them from a pre-generated file. (also in the other work item).

This work item is to get just a basic mocked start up of a chain (and is already partially working, but crashes generating the 4th key).
