### ISSUE TITLE
Add Eth 2 metrics

### ISSUE THREAD

**Issue by sgryphon** [NethermindEth/nethermind#1081]

**Comment by tkstanczak** [comment]
there is a class for metrics already added - also Grafana and metrics system work - if you let me know your Grafana Labs user then you can see the results - we just need a dashboard

**Comment by tkstanczak** [comment]
Our Grafana (for Goerli):
https://nethermind.grafana.net/d/nQaRO6Yiz/nethermind?refresh=5s&orgId=1&var-group=nethermind&var-enode=Goerli%20Validator
