### ISSUE TITLE
Add general test formats for phase 0 beacon chain and fork choice (genesis, block ops, epoch ops, fork choice ops)

### ISSUE THREAD

**Issue by sgryphon** [NethermindEth/nethermind#1082]

**Comment by tkstanczak** [comment]
I was planning to pick these next and add them to EThereum2 solution.
Let me know if you have started anything here so we do not duplicate the work.

**Comment by sgryphon** [comment]
I didn't mean to assign it to myself, so must have accidentally. I'm not working on it (not in the in-progress column), so have at it. I'll update work items if I do stuff on them.
