### ISSUE TITLE
Change Log for Releases

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#1112]
It would be nice to have some sort of change log for the release versions for people to know what is fixed, what is new, etc.

**Comment by tkstanczak** [comment]
this will require more stringent approach to feature branches / commits - then we can build it automatically from the closed issues
@matilote @sgryphon I think we can get that organized

**Comment by MysticRyuujin** [comment]
You guys are doing change logs pretty regularly now, idk if this needs to remain open? It's not automated but I'm happy lol
