### ISSUE TITLE
Rethink Rpl encoding design

### ISSUE THREAD

**Issue by Scooletz** [NethermindEth/nethermind#1127]
Currently, Rpl encoding is based on a common interface that might fit some scenarios but make the evolution of the encoding a bit hard to change. It requires a common denominator, which in various cases might be harmful or time-consuming to implement. Below, you can find a draft of the change

### Current state

Currently, Rpl encoding is based on a the following interface.

https://github.com/NethermindEth/nethermind/blob/062d52d0e4adeb332fafb8635899bbd985af86b3/src/Nethermind/Nethermind.Core/Encoding/IRlpDecoder.cs#L27-L33

and a method dispatching the call to the specific implementation

https://github.com/NethermindEth/nethermind/blob/062d52d0e4adeb332fafb8635899bbd985af86b3/src/Nethermind/Nethermind.Core/Encoding/Rlp.cs#L154-L166

The interface specifies the way to encode and decode a value of a specific type to various formats. According to my understanding:

1. all of the types (or majority of them) are known when encoding/decoding happens 
1. there's no need for dynamic dispatch
1. there might be various needs when encoding/decoding specific values
1. specific values might be decodable/encodable to different payload formats (some for instance might be able to use `Span<byte>` etc).
1. a large part of encoding goes through the mentioned `Encode<T>` when the type is already known.

### Design Proposition

My proposition is to move majority/all `Encode` and `Decode` method to the types themselves, or implement them as extension methods. Extensions methods can handle `null` value of `this` so it might be even better. This would allow much easier evolution and implementing the needed approach for a specific case.

For every type that is currently encoded decoded, it would make it much easier to dispatch the operation, as the following call

```csharp
Rpl.Encode<Address> (address);
```

would become a direct call on the address

```csharp
address.Encode();
```

This would allow different types of outputs and addressing different needs for different items.

Additionally, it could possibly support a better chaining of `Rpl`s which is currently done by nested copying like in the following example.

https://github.com/NethermindEth/nethermind/blob/062d52d0e4adeb332fafb8635899bbd985af86b3/src/Nethermind/Nethermind.Network/Discovery/Serializers/PongMessageSerializer.cs#L35-L39

### Expected results

Less allocations, more performance. This requires some serious thinking though and understanding of Rpl format and its needs

**Comment by Scooletz** [comment]
This is a rough description of the design change that I mentioned @tkstanczak It's for sure exploratory but maybe it's worth it to consider. I applied labels according to my understanding of their meaning.

**Comment by Scooletz** [comment]
Note to a reviewer: There's `ValueDecoderContext` for span based decoding and its counterpart `IRlpValueDecoder` but there's no support for writing for example to `IBufferWriter<T>`. Again, this requires revisiting when thinking about the issue.

**Comment by tkstanczak** [comment]
There is much more to it:

```
        public void Serialize(IByteBuffer byteBuffer, BlockHeadersMessage message)
        {
            int contentLength = 0;
            for (int i = 0; i < message.BlockHeaders.Length; i++)
            {
                contentLength += _headerDecoder.GetLength(message.BlockHeaders[i], RlpBehaviors.None);
            }
            
            int length = Rlp.LengthOfSequence(contentLength);
            byteBuffer.EnsureWritable(length, true);
            
            RlpStream rlpStream = new NettyRlpStream(byteBuffer);
            rlpStream.StartSequence(contentLength);
            for (int i = 0; i < message.BlockHeaders.Length; i++)
            {
                rlpStream.Encode(message.BlockHeaders[i]);
            }
        }

        public BlockHeadersMessage Deserialize(IByteBuffer byteBuffer)
        {
            RlpStream rlpStream = new NettyRlpStream(byteBuffer);
            return Deserialize(rlpStream);
        }
```

**Comment by tkstanczak** [comment]
Most of the projects include RLP serilization in types but I preferred to keep them POCO and not pollute with serialization.

**Comment by tkstanczak** [comment]
network Discovery classes are some of the oldest unfixed classes so RLP there is also very old style

**Comment by tkstanczak** [comment]
nesting is inefficient and was replaced by better approches in wherever it was the most significant in the perf tests

**Comment by tkstanczak** [comment]
Encoding address for example was optimized in RlpStream to:
```
public void Encode(Address address)
        {
            if (address == null)
            {
                WriteByte(EmptyArrayByte);
            }
            else
            {
                WriteByte(148);
                Write(address.Bytes);
            }
        }
```

**Comment by tkstanczak** [comment]
and the RlpStream has two implementations:

```
```
        protected virtual void WriteByte(byte byteToWrite)
        {
            Data[Position++] = byteToWrite;
        }
```

and

        protected override void WriteByte(byte byteToWrite)
        {
            _byteBuffer.EnsureWritable(1, true);
            _byteBuffer.WriteByte(byteToWrite);
        }
```

**Comment by tkstanczak** [comment]
generally I agree with many of the points and you probably analyzed mostly the old classes that I would like to replace too with the RlpStream approach wherever possible - given time to implement which may be significant

**Comment by tkstanczak** [comment]
> Note to a reviewer: There's `ValueDecoderContext` for span based decoding and its counterpart `IRlpValueDecoder` but there's no support for writing for example to `IBufferWriter<T>`. Again, this requires revisiting when thinking about the issue.

This has been implemented by Konrad for a very specific use case which account for a huge percentage of RLP encoding - ValueKeccak in Patricia Tree:

```
        public byte[] Get(UInt256 index)
        {
            Span<byte> key = GetKey(index);
            byte[] value = Get(key);
            if (value == null)
            {
                return new byte[] {0};
            }

            Rlp.ValueDecoderContext rlp = value.AsRlpValueContext();
            return rlp.DecodeByteArray();
        }
```

**Comment by tkstanczak** [comment]
so the RLP code has multiple duplications dependening on whether we upgraded all the depending code to the new methods while transitioning from:
object-based RLP -> byte[] RLP -> MemoryStreamRLP -> RecyclableMemoryStreamRLP -> RlpStream RLP

**Comment by tkstanczak** [comment]
the new model is: use RlpStream for storage and use NettyRlpStream for network, use some ultra optimizations in PatriciaTree independently

**Comment by tkstanczak** [comment]
look at the TreeNode class to find the most convoluted optimizations for the PatriciaTree - they are extremely important for the general performance - if you can improve the code there we would immediately see a boost in the Nethermind perf @Scooletz
