### ISSUE TITLE
nethermind seem to only work on ubuntu - probably rocksdb

### ISSUE THREAD

**Issue by thereapman** [NethermindEth/nethermind#1160]
I'm unable to run the images from dockerhub (specifically `nethermind/nethermind:1.2.6`) on any host other than ubuntu.

I've confirmed the crash on:
- ArchLinux
- Debian 10

I've confirmed it working on:
- Ubuntu 17.10

The error is:
```
2019-12-17 18:14:25.6907|Using database directory /nethermind/nethermind_db/mainnet/blocks|
Illegal instruction (core dumped)
```

I have a similar issue running an image build locally on archlinux from the git repo (from `Dockerfile` and `Dockerfile_full`). This is very weird as the docker host system should not make a difference (apart from the hosts kernel).

The following combinations i've tried for `nethermind/nethermind:1.2.6`:

* Debian 10 / kernel 4.19.0-5-amd64 / docker 17.12.1 ==> crash
* Debian 10 / kernel 4.19.0-5-amd64 / docker 19.03.5 ==> crash
* ArchLinux / kernel 5.4.3-arch1-1 / docker 19.03.5 ==> crash
* ArchLinux / kernel 5.4.3-arch1-1 / local dotnet 3.0.1 build ==> crash (no message)
* Ubuntu 17.10 / kernel 4.13.0-46-generic / docker 17.10 ==> works fine

i've tracked it down to `src/rocksdb-sharp/RocksDbSharp/AutoNativeImport.cs` line 160. So i guess there is some problem when the rocksdb lib gets loaded but an `strace` didn't reveal anything.

I tried to build librocksdb (v6.4.6) myself from the sources and put this into the lib search path but `dlopen()` won't load it with an `dlopen: /usr/lib/libjemalloc.so.2: cannot allocate memory in static TLS block` error thrown at `AutoNativeImport.cs` line 421

**Comment by thereapman** [comment]
Just saw the announcement for v1.3.6. seems to have the same issue.

**Comment by mmhh1910** [comment]
Same problem for me on a "CentOS Linux 7" host. 

With 1.2.6 I get:
```
...
2019-12-17 18:56:42.7029|Using database directory /nethermind/nethermind_db/mainnet/blocks|
Illegal instruction (core dumped)
```

With 1.3.6 the last line is missing, but the container stops after the same time.

**Comment by thereapman** [comment]
Just tried it on two of our servers:
- srv #1 / Debian 9.11 / kernel 4.9.0-11-amd64 / docker 19.03.2 => crash
- srv #2 / Debian 9.11 / kernel 4.9.0-11-amd64 / docker 19.03.2 => OK

Both servers have the same versions for kernel, os and docker. I'll try to find the difference.

**Comment by mmhh1910** [comment]
Not sure if this help in this case:

https://forums.docker.com/t/getting-illegal-instruction-when-i-run-my-program-inside-container/43919

**Comment by thereapman** [comment]
i guess that's the issue. 
I compared CPU flags on both systems. the working one has way more cpu flags than the other one. Also my system here is an older xeon workstation from ~2012 which might lack some of the newer flags.

Now would be good to know which version of `librocksdb.so` is used and how it was build initially. maybe the `PORTABLE` might help here.

**Comment by mmhh1910** [comment]
Same here... Older HP Z420 workstation with Intel(R) Xeon(R) CPU E5-1650.

```
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear spec_ctrl intel_stibp flush_l1d
```

**Comment by mmhh1910** [comment]
If this

https://github.com/NethermindEth/rocksdb-sharp/blob/master/native-build/build-rocksdb.sh

was actually used to build the librocksdb.so used in the image, then PORTABLE=1  was actually set.

**Comment by tkstanczak** [comment]
since version 1.2.0 we used a different build for RocksDB - for Linux it is the one from facebook page
we need to set PORTABLE - this should be fixed tomorrow

thanks for reporting @mmhh1910 @thereapman

**Comment by thereapman** [comment]
Ok i've figured out a (nasty) workaround

1. Build rocksdb
```
git clone git@github.com:facebook/rocksdb.git
git checkout v6.4.6
git checkout -b nethermind-build
PORTABLE=1 CFLAGS=-static-libstdc++ make -j20 shared_lib
cp librocksdb.so.6.4.6 ~/dev/nethermind/src/Nethermind/Nethermind.Runner/bin/Debug/netcoreapp3.0/runtimes/linux-x64/native/librocksdb-6.4.6.so
```
At this point starting the runner will complain about a `libjemalloc.so` error (at least on my ArchLinux)

2. Preload libjemalloc.so
to run nethermind now add `LD_PRELOAD=/usr/lib/libjemalloc.so` to either the execution environment or in fornt of `dotnet run`

haven't tried it with docker yet but i guess tomorrow i can pimp the Dockerfile to build the rocksdb lib and use the newly build one.

**Comment by tkstanczak** [comment]
https://github.com/NethermindEth/nethermind/blob/master/.github/workflows/rocksdb-build.yml

**Comment by roninkaizen** [comment]
i guess we had this rocksdb questions before,
i have allmost the same errors, therefor i start reading here,
before wasting time with own investigations this time ;)
merry christmas to all of the nethermind-crew!

**Comment by tkstanczak** [comment]
I think that PORTABLE may be responsible for Ronin issues while centOS may be a separate thing related to RocksDB

**Comment by tkstanczak** [comment]
we will push 1.3.7 with PORTABLE set and then we will test other Linux distros

**Comment by tkstanczak** [comment]
There is no official ArchLinux support from .NET Core:
https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-linux

**Comment by thereapman** [comment]
> There is no official ArchLinux support from .NET Core:
> https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-linux

Yeah but it works fine. We're actively developing .net core services and apps with arch. 

Will run my little test-suite from above again once v1.3.7 is out.

**Comment by thereapman** [comment]
`PORTABLE` seems to have fixed it (tried with the `nethermind/nethermind:latest` released a couple minutes ago).
Verified on my HP Z840's archlinux hosts system as well as the Debian 10 VM.
I'm too lazy to get my work laptop out to test on our company servers, tho.

@mmhh1910 @roninkaizen  Could you try to verify as well?

**Comment by matilote** [comment]
Just tested on CentOS 7.6 x64, seems to be working fine.

**Comment by mmhh1910** [comment]
Yep, https://hub.docker.com/layers/nethermind/nethermind/latest/images/sha256-943f63c8e9a4e228702aa3f04ce299004b05a48564fc2f36ffdeb345eabd6e6d works for me, too.

Thanks or the quick fix!

**Comment by tkstanczak** [comment]
Thanks a lot for testing / reporting it!
