### ISSUE TITLE
Docker configs docs incorrect

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1162]
had some problems due to ENV vars didn’t work as it’s written in the docs
Here https://nethermind.readthedocs.io/en/latest/docker.html it saying
It's also possible to modify each configuration property via environment variable, using a simple convention:
NETHERMIND_{MODULE}_{PROPERTY}
So it should be like NETHERMIND_ETHSTATS_ENABLED: 'true'

but it works only if add CONFIG to module name

NETHERMIND_ETHSTATSCONFIG_ENABLED: 'true'

**Comment by one-three-three-seven** [comment]
`docker run -it --network host --JsonRpc.Enabled true --Network.DiscoveryPort 30312 --Network.P2PPort 30312 nethermind/nethermind`

has to be

`docker run -it --network host nethermind/nethermind --JsonRpc.Enabled true --Network.DiscoveryPort 30312 --Network.P2PPort 30312`
