### ISSUE TITLE
Test the issue that is failing for ronin

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1166]
http://releases.ubuntu.com/bionic/ubuntu-18.04.3-live-server-amd64.iso

**Comment by roninkaizen** [comment]
![123](https://user-images.githubusercontent.com/17592883/71048225-e876a500-213e-11ea-932a-2f0c945762dc.png)
![124](https://user-images.githubusercontent.com/17592883/71048226-e90f3b80-213e-11ea-81e8-d60d214a2496.png)
![125](https://user-images.githubusercontent.com/17592883/71048227-e90f3b80-213e-11ea-9b01-73f319df9e15.png)

**Comment by thereapman** [comment]
Guess it's closely related to https://github.com/NethermindEth/nethermind/issues/1160

**Comment by tkstanczak** [comment]
fixed for Ronin. Thanks guys, you are great!

**Comment by roninkaizen** [comment]
agree, works for me, thanks and nice christmas to everyone from the nΞthΞrmind-crew
