### ISSUE TITLE
stuck after displaying --help

### ISSUE THREAD

**Issue by one-three-three-seven** [NethermindEth/nethermind#1174]
Nethermind does not quit after the help is displayed. I can't even close it. (CentOS)

![3elRZAy4Uu](https://user-images.githubusercontent.com/35700046/71089897-0b867080-21a2-11ea-9b2d-2a88f7ded3a7.png)

**Comment by tkstanczak** [comment]
https://www.youtube.com/watch?v=2Q_ZzBGPdqE

**Comment by tkstanczak** [comment]
on it

**Comment by tkstanczak** [comment]
thanks for reporting @one-three-three-seven - this is fixed and merged to master now - will be available in 1.3.8
