### ISSUE TITLE
RPC result type for net_peerCount should be hex encoded string

### ISSUE THREAD

**Issue by mmhh1910** [NethermindEth/nethermind#1175]
https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding states that all results should be hex encoded, however at least **net_peerCount** (maybe others?) returns

```{'id': 1, 'jsonrpc': '2.0', 'result': 7}```

I think that should be:

```{'id': 1, 'jsonrpc': '2.0', 'result': '0x07'}```

**Comment by tkstanczak** [comment]
fixed
https://github.com/NethermindEth/nethermind/pull/1176

**Comment by tkstanczak** [comment]
not so obvious :/ - from what I remember net_version returns 63

**Comment by tkstanczak** [comment]
will be released in 1.3.8
