### ISSUE TITLE
Corrupted parameters with rpc eth_call

### ISSUE THREAD

**Issue by mmhh1910** [NethermindEth/nethermind#1182]
I'm calling  this function

`function tokenBalances(address user,  address[] calldata tokens) external view returns (uint[] memory balances)`

from this https://etherscan.io/address/0xBF320B8336B131E0270295c15478d91741f9fC11#code contract with around 700 token contract addresses in the second "tokens" parameter array. 
The function returns the token balances of an owner/user address (first parameter) for lots of tokens (second parameter) with just one call.

This usually works with nethermind, but sometimes I get:

`{"id":107,"jsonrpc":"2.0","result":"invalid","error":{"code":-32015,"message":"VM execution error."}}`

If the error happens, nethermind prints out the passed parameters like this:

```
2019-12-19 16:05:03.0747|Error when handling ID 530107, eth_call({
"to": "0xBF320B8336B131E0270295c15478d91741f9fC11",
"data": 
"0x3ad206cc000000000000000000000000000be27F560fef0253CAc4Da8411611184356549000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000002ef
... [lots of token contract addresses] ...
000000000000000000000000aa0bb10cec1fa372eb3abc17c933fc6ba863dd9e000000000000000000000000ba2184520a1cc49a6159c57e61e1844e085615b6"
},latest) | {"id":530107,"jsonrpc":"2.0","result":"invalid","error":{"code":-32015,"message":"VM execution error."}}|
```

Inside the large block of token addresses in this parameter list, there are one or two places that look corrupt. I can't copy and paste it this, because these non-printable characters are gone then, but here's screenshot from the portainer log view: https://imgur.com/a/3YzSQIN

**Comment by tkstanczak** [comment]
This returns internal EVM error. With exactly the same parameters on the
same block height does it work on other clients?

The calls should be all fine but we will experiment.

**Comment by mmhh1910** [comment]
It not only always works against geth, but even worse, it usually works with nethermind, just sometimes it does not. 

I've repeated the calls that failed with the same parameter again against nethermind and the worked...

It feels like some kind of random memory corruption.

**Comment by tkstanczak** [comment]
is it eth_call?

**Comment by tkstanczak** [comment]
of course it is eth_call :) ok, so it may be similar thing as with txpool content - there may be incorrect separatiom of parallel calls

**Comment by tkstanczak** [comment]
we will use you example to test it

**Comment by mmhh1910** [comment]
Here is some sample calldata, that checks the whale account 0x000be27F560fef0253CAc4Da8411611184356549 for 697 token balances.

https://gist.github.com/mmhh1910/d37fa8505a4fb52380fb917cf0802f72

I guess you would need to paralyze this add repeat it lots of times to run into the error.

**Comment by tkstanczak** [comment]
@matilote could you try this one against the synchronized mainnet - can be on latest block with data as in gist and to: address as provided:

**Comment by tkstanczak** [comment]
@mmhh1910 we will try to look at it closer now, I wonder if that was something with .net core infra or json serializers - looks strange

**Comment by tkstanczak** [comment]
I wonder if this is something simple like 'out of gas' on VM
We have added recently a configurable gas cap

**Comment by tkstanczak** [comment]
@mmhh1910 there has been multiple changes in the area - are you able to check against 1.8.2?
