### ISSUE TITLE
ARM64 Docker image: App crashes after few minutes

### ISSUE THREAD

**Issue by mcgravier** [NethermindEth/nethermind#1199]
System: Manjaro ARM (64bit)
Hardware: Raspberry Pi 4 (4GB version)
Kernel ver: Linux manjaro 5.4.3-2-MANJARO-ARM # 1 SMP PREEMPT Wed Dec 25 07:08:38 UTC 2019 aarch64 GNU/Linux (Same issue happens with official Raspbian 64bit kernel)
Docker ver: 19.03.5-ce, build 633a0ea838
Console log: [manjaro_nethermind.txt](https://github.com/NethermindEth/nethermind/files/4008337/manjaro_nethermind.txt)

It's worth noting that arm32 image seems to work fine

**Comment by tkstanczak** [comment]
@matilote would you note down your comments here, I think you have tested but were not able to reproduce? would be great to track that here

**Comment by matilote** [comment]
Haven't tested on Manjaro yet. It was running smoothly on ubuntu arm64 so far. I am going to test in on Manjaro once I got my last raspberry pieces finally shipped.
