### ISSUE TITLE
Return value for txpool_content rpc call should be like in geth

### ISSUE THREAD

**Issue by mmhh1910** [NethermindEth/nethermind#1231]
Nethermind devs implemented the txpool_content rpc call like it is documented in https://github.com/ethereum/go-ethereum/wiki/Management-APIs#txpool. 

However, the documentation is wrong and geth does not return an inner array.

See: https://github.com/ethereum/go-ethereum/issues/20502 and https://github.com/ethereum/go-ethereum/issues/16144 

I think nethermind should act like geth here and remove the inner array from the result.

**Comment by mmhh1910** [comment]
Geth documentation at https://github.com/ethereum/go-ethereum/wiki/Management-APIs#txpool is now corrected by Péter.

**Comment by LukaszRozmej** [comment]
This is more than just simple change in JSON API. Geth moved to store just 1 tx/sonder-nonce in this PR: https://github.com/ethereum/go-ethereum/pull/2742 , we would have to do the same. @tkstanczak could you take a look on that and give your opinion?

**Comment by tkstanczak** [comment]
@LukaszRozmej I would change only the RPC call for now to return the tx with the highest gas price for a given account and nonce and leave the tx pool unchanged
I believe that th tx pool storing multiple tx for the same nonce is important for some dapps (including data marketplace) to be able to track their various requests and their cancellation / speed-up options

**Comment by tkstanczak** [comment]
@LukaszRozmej worth to ask @kasiaturbiarz and @spetz about the role of it in NDM
