### ISSUE TITLE
Setup Chocolatey package

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#134]

**Comment by KanarekLife** [comment]
Hi! I would like to help with this issue, however I do have two questions:
- Chocolatey automaticly adds all exes into PATH. Should any shortcut be added into desktop?
- Should I just send you all the chocolatey package files for you to upload it or should I become the maintainer?
Greetings

**Comment by KanarekLife** [comment]
I've created very simple package that just downloads and unzips nethermin client and makes it available through PATH. I didn't know where to put it in your repo in order to make PR so I just created my own [repo](https://github.com/KanarekLife/nethermind-chocolatey) with the package files.

**Comment by tkstanczak** [comment]
@KanarekLife sorry, we did not react properly at that time in May (I have assigned to DevOps and then we lost the priority). Do you have these changes available? How much effort is to maintain the chocolatey package with each new release?

**Comment by digitalcoyote** [comment]
@tkstanczak I couldn't look at the repo to check it (404'ed on me), but the recommended way to maintain chocolatey packages is with a fork of the AU repo and AppVeyor. As part of this, you write an update script that detects releases, and updates the files. Then the AU repo scripts publish it automatically. I maintain about 35 packages and I only have to look into failures when someone changes the naming convention of a release file.

**Comment by tkstanczak** [comment]
@digitalcoyote  what is the AU repo?

**Comment by tkstanczak** [comment]
this thing: https://github.com/majkinetor/au ?

**Comment by tkstanczak** [comment]
@matilote , what do you think? can we do that in November?

**Comment by tkstanczak** [comment]
there were never enough requests for this, I think chocolatey is mildly popular even among long term windows users
