### ISSUE TITLE
Not all ethereum tests running on MacOs and Linux

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1343]
![image](https://user-images.githubusercontent.com/498913/73134646-5022e880-4039-11ea-81b5-ecf595ae43b4.png)
![image](https://user-images.githubusercontent.com/498913/73134654-603ac800-4039-11ea-98b3-d53954265bf5.png)

I have these failing tests on one of the branches (proofs). It fails on Windows build but passed on Linux and MacOS. After short investigation I can see that Linux and MacOS simply do not run some of the tests.

**Comment by matilote** [comment]
Looks like it is working now. Must have been a runner's bug. Currently 253 Ethereum.Trie.Tests are passing on each OS.
