### ISSUE TITLE
testchain with wrong eth_call response

### ISSUE THREAD

**Issue by simon-jentzsch** [NethermindEth/nethermind#1382]
We have created a simple developer chain with `NethDev`.

Here I deployed a simple TestContract:

```js
pragma solidity ^0.4.19;
pragma experimental ABIEncoderV2;

contract TestContract {
    event LogInc(uint256 counter, address caller);

    uint256 public counter;

    function increase() public {
        counter = counter + 1;
        LogInc(counter, msg.sender);
    }
}

```

When I try to do a `proof_call` or `eth_call` to `counter()` I get 
```
  "result":"0x"
```
This is false, since it should be `0x0000000000000000000000000000000000000000000000000000000000000000`

(to reproduce, just comment out the 2nd transaction in reproduce.sh)

But then, if I send a transactrion to `increase()` first, I get the a different, but now **wrong** answer:
```
  "result":"0x0000000000000000000000000000000000000000000000000000000000000000"
```
`proof_call` does show me  in the proof that the storage value is `0x01`, but the return value is still wrong.

## to reproduce
just unpack the 3 files in this zip into a directory and call `./reproduce.sh` 

[reproduce.zip](https://github.com/NethermindEth/nethermind/files/4148834/reproduce.zip)

**Comment by tkstanczak** [comment]
wow, this is a quality report

**Comment by tkstanczak** [comment]
will aim at getting a fix overnight

**Comment by tkstanczak** [comment]
pragma solidity ^0.4.24;

contract TestContract {
    event LogInc(uint256 counter, address caller);

    uint256 public counter;

    function blockNumber() public view returns(uint) {
        return block.number;
    }

    function coinbase() public view returns(address) {
        return block.coinbase;
    }

    function difficulty() public view returns(uint) {
        return block.difficulty;
    }

    function gasLimit() public view returns(uint) {
        return block.gaslimit;
    }

    function timestamp() public view returns(uint) {
        return block.timestamp;
    }

    function blockhash1() public view returns(bytes32) {
        return block.blockhash(block.number - 1);
    }

    function blockhash2() public view returns(bytes32) {
        return block.blockhash(block.number - 2);
    }

    function msgData() public view returns(bytes) {
        return msg.data;
    }

    function msgSender() public view returns(address) {
        return msg.sender;
    }

    function msgValue() public view returns(uint) {
        return msg.value;
    }

    function msgGas() public view returns(uint) {
        return msg.gas;
    }

        function origin() public view returns(address) {
        return tx.origin;
    }

        function gasPrice() public view returns(uint) {
        return tx.gasprice;
    }

    function increase() public {
        counter = counter + 1;
        emit LogInc(counter, msg.sender);
    }
}

**Comment by tkstanczak** [comment]
compared with Ganache and have consistent fixes but need to find a way to test all of these on Geth as well

**Comment by tkstanczak** [comment]
![image](https://user-images.githubusercontent.com/498913/73759247-f70b3100-476b-11ea-8d97-08342846f1c2.png)
version 1.5.9

due to amount of changes in 1.5.9 please feel free to use it for confirming this fix but it may not be the most stable version yet

**Comment by tkstanczak** [comment]
you can also use the contract above to analyze differences in eth_call between Neth and Geth for particular calls

**Comment by simon-jentzsch** [comment]
ok, I'll test it with the 1.5.9

**Comment by simon-jentzsch** [comment]
I think we can close this. This is fixed ;-)
