### ISSUE TITLE
Biased Data Consumers

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1426]
Create a pool of DataConsumers with specific tasks:
* download all storage for contract X
* download all sender accounts for block X
* download  all leaves

Maintain a shared cache between them for asking for the trie nodes.
Set various priorities for their requests.

Include them as inputs to request builder strategies.
Merge this with MultiBatches

Prioritize them.

**Comment by LukaszRozmej** [comment]
Not relevant now.
