### ISSUE TITLE
JSON-RPC response **MUST** contain an ID property.

### ISSUE THREAD

**Issue by MicahZoltu** [NethermindEth/nethermind#1439]
Request:
```
{"jsonrpc":"2.0","id":null,"method":"eth_getCode","params":["0x7a0d94f55792c434d74a40883c6ed8545e406d12","latest"]}
```
Response:
```
{"jsonrpc":"2.0","result":"0x"}
```
Per JSON-RPC specification, the response **MUST** contain an `id` field, and the `id` **MUST** match the `id` of the request (even if the request id was null).  https://www.jsonrpc.org/specification#response_object

It is worth noting that per spec, `id` in the response should be `null` if the response is due to failing to decode the `id` in the request (e.g., JSON parsing error).

**Comment by tkstanczak** [comment]
fixed
