### ISSUE TITLE
JSON-RPC id field can be null.

### ISSUE THREAD

**Issue by MicahZoltu** [NethermindEth/nethermind#1440]
Per JSON-RPC specification (https://www.jsonrpc.org/specification#request_object), the `id` property on a request object can be a `string`, `number`, or `null`.  Currently, Nethermind will respond with an incorrect JSON-RPC response object when it receives a request with a `null` `id` (see #1439 for example situation).

I thought I fixed this in https://github.com/NethermindEth/nethermind/pull/1384, but it would appear that I actually made things worse.  😢  Rather than blundering in the dark again, figured I would create a GitHub issue and let someone who knows what they are doing fix it instead.

**Comment by tkstanczak** [comment]
fixed
