### ISSUE TITLE
CLI issues - eth.getBlockTransactionCountByHash

### ISSUE THREAD

**Issue by matilote** [NethermindEth/nethermind#1468]
input:

`eth.getBlockTransactionCountByHash("0x3192f11e2932111103d7aef259851c9fea4f02528b9e0cc3d2b04cb39723fa8e")`

output:

```
Request complete in 2803,311μs
SyntaxError: Unexpected token x
null
```

![image](https://user-images.githubusercontent.com/33068017/74933707-df2ae280-53e4-11ea-91fb-700786c0f113.png)

**Comment by tkstanczak** [comment]
fixed on master
