### ISSUE TITLE
trace_replayBlockTransactions minor difference in responses (goerli chain)

### ISSUE THREAD

**Issue by matilote** [NethermindEth/nethermind#1498]
![image](https://user-images.githubusercontent.com/33068017/75579620-8a334000-5a66-11ea-8f7f-483e282264a5.png)

Missing property creationMethod from the object on the left side (Nethermind response)

[Nethermind_response.txt](https://github.com/NethermindEth/nethermind/files/4268669/Nethermind_response.txt)
[Parity_response.txt](https://github.com/NethermindEth/nethermind/files/4268670/Parity_response.txt)
[Request.txt](https://github.com/NethermindEth/nethermind/files/4268671/Request.txt)

**Comment by tkstanczak** [comment]
thanks, cool report

**Comment by tkstanczak** [comment]
Fixed
