### ISSUE TITLE
Automatically create a PR with sensible fast blocks settings

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1517]
For mainnet, goerli, ropsten, rinkeby the fast blocks settings should be retrieved from various sources (etherscan and similar) for few thousand blocks back and suggests as config updates PRs:

    "PivotNumber" : 9250000,
    "PivotHash" : "0x65d8bb33d698e3bbad1332afd6282fb81a1f845c6fa903e37ed95e7fad59fa98",
    "PivotTotalDifficulty" : "13628278799957806402453",

**Comment by matilote** [comment]
Closed with #1537 & #1548
