### ISSUE TITLE
EstimateGas results differ from geth

### ISSUE THREAD

**Issue by mmhh1910** [NethermindEth/nethermind#1542]
I've noticed that the results for gas estimations for token transfers differ from the results returned by geth. If the estimates from nethermind are used, the transactions will fail with "Out of gas" (meaning the numbers returned by geth are correct).

The gas needed is different depending on if the source balance goes down to zero (the complete balance is transfered, thus storage is freed in the token contract) and if the target address already holds some of the token (if not, gas for the storage in the token contract needs to be paid).

Below is the code for four test cases in python for geth and nethermind.

Case 1: Transfer not all tokens to an address that already holds the token - no storage slot taken or freed
Case 2: Transfer all tokens to an address that already holds the token - one storage slot freed
Case 3: Transfer not all tokens to an address that does not hold the token yet - one storage slot taken
Case 4: Transfer all tokens to an address that does not hold the token yet - one storage slot taken, one freed

The output for me is:

```
Geth:       37042 37042 52030 52030
Nethermind: 23384 23384 23320 23320
```

There seems to be a general offset between geth and nethermind and additionally, nethermind does not seems to calculate correctly when the target account does not hold any of the token yet (case 3 and 4). 

For whoever takes a look at this, my understanding is that estimateGas in geth returns more than the tx will actually need when storage is freed, since, as far as I understand, the bonus for freeing storage is only calculaed at the very end of the tx in the EVM. So, you can't substract this bonus upfront when sending the tx. This means that Geth does not actually return the gas needed for the tx, but the gas needed to not run into "Out of gas" along the way.

```
web3_geth = Web3(HTTPProvider("..."))
web3_nethermind = Web3(HTTPProvider("..."))

token_address="0x6B175474E89094C44Da98b954EedeAC495271d0F" # DAI
source_address_with_dai="0x8AeCc5526F92A46718f8E68516D22038D8670E0D" # random DAI token holder

target_address_with_dai="0x6B175474E89094C44Da98b954EedeAC495271d0F" # another random DAI token holder
target_address_without_dai="0x6b175474e89094c44DA98b954eedeAC495271d00" # unused/empty address

tokenContract_geth = web3_geth.eth.contract(address=token_address, abi=TokenABI)
tokenContract_nethermind = web3_nethermind.eth.contract(address=token_address, abi=TokenABI)
GAS_TOKEN_TRANSFER = 150000

amount_con = tokenContract_geth.functions.balanceOf(Web3.toChecksumAddress(source_address_with_dai)).call()

estimate1_geth = tokenContract_geth.functions.transfer(target_address_with_dai,   amount_con-1).estimateGas({'from': Web3.toChecksumAddress(source_address_with_dai), 'gas': GAS_TOKEN_TRANSFER})
estimate2_geth = tokenContract_geth.functions.transfer(target_address_with_dai,   amount_con).  estimateGas({'from': Web3.toChecksumAddress(source_address_with_dai), 'gas': GAS_TOKEN_TRANSFER})
estimate3_geth = tokenContract_geth.functions.transfer(target_address_without_dai,amount_con-1).estimateGas({'from': Web3.toChecksumAddress(source_address_with_dai), 'gas': GAS_TOKEN_TRANSFER})
estimate4_geth = tokenContract_geth.functions.transfer(target_address_without_dai,amount_con).  estimateGas({'from': Web3.toChecksumAddress(source_address_with_dai), 'gas': GAS_TOKEN_TRANSFER})
print(estimate1_geth,estimate2_geth,estimate3_geth,estimate4_geth)

estimate1_nethermind = tokenContract_nethermind.functions.transfer(target_address_with_dai,   amount_con-1).estimateGas({'from': Web3.toChecksumAddress(source_address_with_dai), 'gas': GAS_TOKEN_TRANSFER})
estimate2_nethermind = tokenContract_nethermind.functions.transfer(target_address_with_dai,   amount_con).  estimateGas({'from': Web3.toChecksumAddress(source_address_with_dai), 'gas': GAS_TOKEN_TRANSFER})
estimate3_nethermind = tokenContract_nethermind.functions.transfer(target_address_without_dai,amount_con-1).estimateGas({'from': Web3.toChecksumAddress(source_address_with_dai), 'gas': GAS_TOKEN_TRANSFER})
estimate4_nethermind = tokenContract_nethermind.functions.transfer(target_address_without_dai,amount_con).  estimateGas({'from': Web3.toChecksumAddress(source_address_with_dai), 'gas': GAS_TOKEN_TRANSFER})
print(estimate1_nethermind,estimate2_nethermind,estimate3_nethermind,estimate4_nethermind)
```

**Comment by tkstanczak** [comment]
Hi @mmhh1910 
There were significant changes to the gas estimator in the last month.
I assume you executed this on the latest version?

It may be some edge case with refunds that I will need to analyze.

**Comment by mmhh1910** [comment]
Yes, I've used docker image nethermind/nethermind:1.6.25.

**Comment by tkstanczak** [comment]
@mmhh1910 I may be able to pick this up this weekend, sorry for the delay, needed to finish the peering changes

**Comment by mmhh1910** [comment]
With docker image nethermind/nethermind:1.7.3 I now get:

```
Geth:       37018 37018 52006 52006
Nethermind: 38519 38519 53507 53507
```

This seems to be correct. Don't know where the off-by-1501 comes from, but at least the transactions using the these values will not result in  "Out of gas".

**Comment by tkstanczak** [comment]
@mmhh1910 from what I have heard - Geth and Parity use binary search to estimate gas while we run a single pass estimator (which is not perfect but much faster)

I remember one potential reason for difference so I need to go back to that code

**Comment by MicahZoltu** [comment]
I *believe* Nethermind will incorrectly estimate the gas for a call to `incrementOncePerBlock` if the `latest` block had a call to the function.  I *suspect* that Nethermind is using `latest` block's timestamp for the timestamp of the estimator, which will result in this code incorrectly evaluating.
```solidity
contract Apple {
    uint256 value;
    uint256 lastUpdate;
    function incrementOncePerBlock() external {
        if (lastUpdate == block.timestamp) return;
        lastUpdate = block.timestamp;
        value += 1;
    }
}
```
While I can appreciate that code that diverges by timestamp is nearly impossible to estimate correctly, I think the above pattern is common enough and simple enough to handle that it is worth fixing.  The pattern is used by Uniswap, for example, to save gas on all but the first transaction in each block.  I think having the estimator use latest block's timestamp +1 would be good enough, just to ensure that the estimator isn't using a timestamp that is *equal* to a block that has already mined.

**Comment by tkstanczak** [comment]
https://github.com/NethermindEth/nethermind/pull/2008

**Comment by tkstanczak** [comment]
@MicahZoltu I believe this is fixed and can be closed

**Comment by MicahZoltu** [comment]
@tkstanczak I am not the person who opened the issue, so I cannot close it.  😃 

cc @mmhh1910
