### ISSUE TITLE
RPC call trace_block returns 0 as transactionPosition for all items

### ISSUE THREAD

**Issue by kwix** [NethermindEth/nethermind#1626]
**Nethermind version:** v1.7.13-0-fcd450ac3-20200401
**Chain:** Ethereum mainnet
**JSONRPC method:** `trace_block`

**Expected behavior:** 
The property `transactionPosition` should be equal to transaction's index (`transactionIndex`), in integer format. 

**Actual behavior:**
`transactionPosition` is 0 for all items in the response

**Comment by tkstanczak** [comment]
thanks, checking

**Comment by tkstanczak** [comment]
fixed, pushed to master, will be included in the next version, thanks for reporting @kwix

**Comment by kwix** [comment]
That was fast. Thank you!
