### ISSUE TITLE
Returns address hash when creating new Account in Nethermind.CLI

### ISSUE THREAD

**Issue by matilote** [NethermindEth/nethermind#1633]
![image](https://user-images.githubusercontent.com/33068017/78353006-a5372980-75a9-11ea-8e91-12e91a864127.png)

Would be nice to have an account address returned from ``personal.newAccount`` method

**Comment by tkstanczak** [comment]
fixed, in master
![image](https://user-images.githubusercontent.com/498913/78403368-26b3a980-75f4-11ea-9f8a-39a9048556f2.png)
