### ISSUE TITLE
Write C# bindings for Tarsnap/scrypt

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#167]
Remove any other scrypt implementation

**Comment by xas** [comment]
@tkstanczak can you give a little more insights about this issue ?

I am not sure if it's just some cleanup in `FileKeyStore` or you're looking for something more (re-use a more updated code like [here](https://github.com/ChrisMcKee/cryptsharp/blob/master/src/CryptSharp/Utility/SCrypt.cs)) ?

**Comment by dceleda** [comment]
@tkstanczak is it still valid?
