### ISSUE TITLE
Improve ethash performance

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#175]
public (byte[], byte[], bool) Hashimoto(ulong fullSize, IEthashDataSet dataSet, Keccak headerHash, Keccak expectedMixHash, ulong nonce)

**Comment by tkstanczak** [comment]
Discussed with geth team - approach is similar where not every block is verified immediately during the sync / block spine is built first

**Comment by tkstanczak** [comment]
Improve speed / allocations of public (byte[], byte[], bool) Hashimoto(ulong fullSize, IEthashDataSet dataSet, Keccak headerHash, Keccak expectedMixHash, ulong nonce)

**Comment by LukaszRozmej** [comment]
Ethash is obsolete, will not implement
