### ISSUE TITLE
WHen sending info about Smoke Test to Slack include more info

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1754]
Just include a few sentences explaining what smoke tests executed and where to find the script.

**Comment by matilote** [comment]
Added some more data as per below screenshot:

![image](https://user-images.githubusercontent.com/33068017/80388587-5b8ce680-88aa-11ea-8912-5543d421a509.png)

**Comment by tkstanczak** [comment]
Opis co robi smoke test - po ludzku - jedno dwa zdania
