### ISSUE TITLE
Nethermind vulnerable to being used for DDoS amplification

### ISSUE THREAD

**Issue by holiman** [NethermindEth/nethermind#1778]
Name

SpoofAmplification(v4014)
Description

v4014 amplification attack test: The test spoofs a ping from a different ip address('victim ip'),and later on sends a spoofed 'pong'.

The spoofed 'pong' will have an invalid reply-token (since the target will send the 'pong' to 'victim ip'), and should thus be ignored by the target. If the target fails to verify reply-token, it will believe to now be bonded with a node at 'victim ip'.

The test then sends a spoofed 'findnode' request. If the 'target' responds to the findnode-request, sending a large'neighbours'-packet to 'victim ip', it can be used for DoS attacks.

Details

test failed: unsolicited reply

ref: https://hivetests.ethdevops.io/?suite=1587975030-98eaa7a1b3cf6e4b616571f537bab476.json

**Comment by tkstanczak** [comment]
thanks @holiman, assigning it now for a fix

**Comment by tkstanczak** [comment]
@holiman hopefully this will be fixed with this PR:
https://github.com/NethermindEth/nethermind/pull/1793

**Comment by tkstanczak** [comment]
hmmm actually not sure how this would fix it...

**Comment by tkstanczak** [comment]
1.8.29

**Comment by holiman** [comment]
Yup, seems fixed: https://hivetests.ethdevops.io/?suite=1588405867-6b9628432c369c50a397d39d8f279908.json
