### ISSUE TITLE
Exit after import

### ISSUE THREAD

**Issue by holiman** [NethermindEth/nethermind#1783]
Here is a log file of a Nethermind node being booted up, and instructed to import ten blocks: 
https://hivetests.ethdevops.io/viewer.html?file=results/nethermind_latest/client-ca6c6be6.log

There's some exeption here: https://hivetests.ethdevops.io/viewer.html?file=results/nethermind_latest/client-ca6c6be6.log#L44 
```

  | 2020-04-27 07:54:54.6621\|Step SetupHive                failed after 13ms Nethermind.Runner.Ethereum.Steps.StepDependencyException: BlockTree
-- | --
  | at Nethermind.Runner.Ethereum.Steps.SetupHive.Execute() in /src/Nethermind/Nethermind.Runner/Ethereum/Steps/SetupHive.cs:line 41
  | 2020-04-27 07:54:54.6718\|FAILED TO INIT SetupHive Nethermind.Runner.Ethereum.Steps.StepDependencyException: BlockTree
  | at Nethermind.Runner.Ethereum.Steps.SetupHive.Execute() in /src/Nethermind/Nethermind.Runner/Ethereum/Steps/SetupHive.cs:line 41
  | 2020-04-27 07:54:54.6937\|Block tree initialized, last processed is 0, best queued is 0, best known is 0, lowest inserted header , body

```
After that, the client does not exit. 

All other nodes, when doing an `import` of blocks, exit afterwards. I'm not sure if it's by-design that the node doesn't exit, or if it's related to the error above...?

It would be great if an `import` command could just import the blocks, and then exit.

**Comment by tkstanczak** [comment]
the Hive code on Nethermind side is to be fixed - this will be addressed by @SebastianDremo Sebastian

**Comment by tkstanczak** [comment]
@SebastianDremo is it fixed now?
