### ISSUE TITLE
Accepting Private IP Address from http://checkip.amazonaws.com

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#1788]
You're using `http://checkip.amazonaws.com/` as your primary external IP address check, however, you accept whatever it returns, even if it returns a private IP address.

In an environment where HTTP requests are proxied (either manually or transparently), and the proxy sets `X-Forwarded-For` as the client's IP address, then (apparently) amazon returns the private IP address...

That's not really your fault, but I think it would better if you checked the returned IP address from your sources and reject a reply if it's an RFC 1918 address?

**Comment by tkstanczak** [comment]
@LukaszRozmej would you be able to look at this?
I believe it was the case before your change as well.

**Comment by tkstanczak** [comment]
@MysticRyuujin thank you, this is very helpful

**Comment by MysticRyuujin** [comment]
One more thing...I don't think this matters or is a big deal, but I thought I'd mention it, just in case.

Even when external IP is determined correctly, when I start Nethermind, the initial logs show:
```
======================== Nethermind initialization completed ========================
Version      : 1.8.26-0-8c43ca573-20200427/X64-Microsoft Windows 10.0.18363/Core3.1.1
...
Ethereum     : tcp://<PUBLIC_IP>:30305
Discovery    : udp://<PRIVATE_IP>:30305
...
```

I imagine it's just displaying the interface IP that it's listening on for UDP packets. Just visually it seems strange.
