### ISSUE TITLE
Why do we call Rlp.Encode during fast sync?

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1811]
![image](https://user-images.githubusercontent.com/498913/80629974-73e83700-8a4b-11ea-9564-28ff5de8df14.png)

**Comment by kamilchodola** [comment]
@tkstanczak @LukaszRozmej @MarekM25 

Not exactly sure if I picked proper metrics but on EnergyWeb it is not a case anymore so probably it was fixed somewhere in meantime:
![image](https://github.com/NethermindEth/nethermind/assets/43241881/6aa648de-df68-42cc-bd22-1816919d53d1)

You see clear moment where encoding started - it was right after FasySync completed and OldBodies have started.

Probably to be closed, but will wait for any input

**Comment by kamilchodola** [comment]
Added also HashCalculation metric (which probably is what was represented by Keccak on main thread) and it matches exactlhy when Encoding started to appear:
![image](https://github.com/NethermindEth/nethermind/assets/43241881/77166a9d-88d3-4314-8148-3dfc5544e85f)

Is first screenshot for sure from the fastSync moment or right after fastSync?

**Comment by kamilchodola** [comment]
I know why this issue appeared.
We had Grafana metrics labeled wrong ;D 

![image](https://github.com/NethermindEth/nethermind/assets/43241881/b5e35420-f3ee-480b-8263-bc8329730ffe)

To be closed.
