### ISSUE TITLE
Nethermind process closes randomly

### ISSUE THREAD

**Issue by mishell-trickster** [NethermindEth/nethermind#1821]
Process just exited randomly when try to sync in fast mode. No errors or info about it in logs. It look like this: 
![image](https://user-images.githubusercontent.com/32033869/80803522-31456c80-8bbb-11ea-82f9-97611265eac6.png)

My server configuration:
Image: Ubuntu 20.04 Server Cloud
Memory (RAM): 1024 MB
Virtual CPUs: 2
Storage: 325 GB HDD

It is weaker than needed in the recommendations. But it seems to me that the сrashes are not due to this because crashes seem random. Process run from root, but maybe this is "Leaking Socket Descriptors". But how I can verify this?

**Comment by tkstanczak** [comment]
hi @mishell-trickster let me have a look

**Comment by tkstanczak** [comment]
1024MB memory will not be enough to sync mainnet currently

**Comment by tkstanczak** [comment]
the spec seems low - maybe 1024MB would be possible if many config changes are added to squeeze as much as possible from the node - we can experiment with it over the next days

**Comment by tkstanczak** [comment]
most likely your OS is killing the process when it runs out of memory

**Comment by mishell-trickster** [comment]
Thank you for answer. I try nethermind on another server with 16GB RAM, Six cores and 400GB SSD, and now it never crash. Seems it really was RAM problem, thank you. 

But now after 20 hours my node always fall behind from really state of blockchain. Its a slightly different issue.
I see logs like this all day
`2020-05-05 17:28:10.6550|Downloaded 10006987 / 10007019 | current     0.14bps | total     0.07bps 
2020-05-05 17:28:10.6550|Changing state to StateNodes at processed:0|state:0|block:0|header:10006987|peer block:10007019 
2020-05-05 17:28:10.7141|State Sync 01.02:42:59 | ~100.00% | 41724.31MB / ~41180.00MB | kB/s:    23 | accounts 85738812 | nodes 491458406 | diagnostics: 3825.87.70ms 
`
New blocks always grower then my current. Difference 20-30 blocks. And my state always StateNodes or StateNodes,FastSync. And JSON-RPC dont working correctly, I think because of my state. It means I must wait for full sync?

**Comment by tkstanczak** [comment]
Yes, if you do not enable beam sync you will need to wait for the sunc to
finish before issuing JSON RPC request.

It will be synced when it starts displaying messages starting with
'Processed' like here:

https://nethermind.readthedocs.io/en/latest/start.html

By the way, which version are you running?

**Comment by tkstanczak** [comment]
actually the numbers in diagnostics do not look good, the node did not transition well to full sync, is it 1.8.30? restart should help but I am surprised to see this happening on the latest version

**Comment by psswrd12345** [comment]
I am also unable to sync mainnet for same issue.  Really, really slowed down before essentially stopping at ~30GB.  My machine only has 8gb ram, waiting on some upgrades in the mail before trying again.

**Comment by mishell-trickster** [comment]
@tkstanczak now Im using 1.8.29. Thank you for explanation, I will try to use latest version for sync.

**Comment by tkstanczak** [comment]
@psswrd12345 and that was on 1.8.30?
What config were you running - with beam sync or without? With receipts and bodies or without?

**Comment by psswrd12345** [comment]
This was fast sync on 1.8.29.  I will give beam sync a shot with 1.8.30

**Comment by mishell-trickster** [comment]
Client 1.8.30, Beam Sync give me balances but cant execute contract functions. There is error when call one
`Beam sync request [JSON RPC eth_call] for key 823c452ebad024d17a3d10574434343bf446a414838d85a08222ff4e2bc8e502 with last update on 11:44:40.919 has expired`

So, how beam really work? Cant find enough info in pdf and docs.

**Comment by tkstanczak** [comment]
Sometimes it will not manage to find all the data and then it expires. You
can retry a few times and most likely it will pass after a few retries
(standard timeout is conservative plus you may connect to new peer nodes in
the meantime). Also going ~8 blocks behind head increases your chances of
finding nodes with the missing state. Documentation is on its way.

**Comment by psswrd12345** [comment]
I upgraded my ram to 32GB and tried syncing full archive, fast, and beam sync with 1.8.30, but I am still unable to sync a fresh node.  Memory leaks until computer freezes up. I was able to sync geth on the same machine, so I do not think it is user error (but also wouldn't be surprised if it is..)

**Comment by tkstanczak** [comment]
bizarre, would you share the config file used?

**Comment by tkstanczak** [comment]
@psswrd12345, @mishell-trickster we have just discovered that we published the default configs with an InMemory database for beam sync and fast sync in 1.8.30.

**Comment by tkstanczak** [comment]
To sync on 1.8.30 you would need to update the config files by changing     "DiagnosticMode": "MemDb" to     "DiagnosticMode": "None" in the config folder in mainnet.cfg (for fast sync) and mainnet_beam.cfg (for beam sync)

**Comment by matilote** [comment]
Closing as the original cause of the issue has been resolved.
