### ISSUE TITLE
Confusing block numbers in logs

### ISSUE THREAD

**Issue by WyseNynja** [NethermindEth/nethermind#1828]
I think I'm seeing block heights for blocks that are on a different chain. This log from a multigeth client gave me a block num that doesn't currently exist on ETH. ETH is on 9995313 and it gave block 10313420.

```
nethermind_1       | 2020-05-03 20:21:13.1711|Discovered a new block  10313420 20:21:00 (0x495922...ba9614), tx count: 0 mined by 0xdf7d7e053933b5cc24372f878c90e62dadad5d42, sent by [Peer|eth65|10313420|MultiGeth/v1.9.13-stable-fcc9e0d7/linux-amd64/go1.13.10|18.221.101.36:47035] 
nethermind_1       | 2020-05-03 20:21:17.2312|Discovered a new block   9995313 20:20:41 (0xec452e...b7f1d6), tx count: 197 mined by Ethermine, sent by [Peer|eth63|9995313|Parity-Ethereum/v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.0|159.89.152.16:30303] 
```

Assuming my guess is correct, could the logs should be tweaked to make this more clear?

**Comment by tkstanczak** [comment]
@WyseNynja this is a ETC block - it is discovered and discarded but I see what we can do here - I will move the notification to slightly later stage

also - ont=e thing that is important - discovered blocks are not added to the chain - look at the log lines starting with 'Processed'

**Comment by tkstanczak** [comment]
Also this multigeth node should get disconnected after some time automatically as the node will understand that it sends ETC blocks.
