### ISSUE TITLE
FR: Sync over network

### ISSUE THREAD

**Issue by cerealkill** [NethermindEth/nethermind#1836]
### Intro/Problem
Hi Nethermind team, first of all, thanks for the great work. I run Nethermind on a VPS and my instance has run out of storage. Unfo the provider doesn't offer larger instances but offers storage instances that I can connect over NFS/SMB or any other network-file-system.
### Feature
Execute the client with recent blocks on one store and use a remote database to scale. Best if the user can determine when the database starts storing on execution. i.e. 
`mainnet.cfg`
```json
{
...
"RemoteDBURL": "192.168.2.43:134",
"RemoteDBFromLatest": 50,
...
}
```
This would start storing blocks on this second, remote, slower database.
### Dream feature
The best scaling scenario would be to have multiple storages that can be added later, as chains get larger, and benefit from parallelism, maybe even redundancy, HDFS-style.
i.e. 
`mainnet.cfg`
```json
{
...
"RemoteDBEnabled": true,
"RemoteDBFromLatest": 50
"RemoteDBConfig: [
  {"RemoteDBIndex": 0,
    "RemoteDBURL": "192.168.2.43:134",
    "RemoteDBCapacity": 10001337
  },
  {"RemoteDBIndex": 1,
    "RemoteDBURL": "192.168.2.45:134",
    "RemoteDBCapacity": 1337
  }],
...
}
```

**Comment by tkstanczak** [comment]
This is a cool idea. We can experiment with it soon (although need to close some high priority items, one of which is pruning which may also address your issue).

I think this would be relatively easy done but not sure yet how much it would slow the block execution (but I assume this would be not an issue for you?)

**Comment by tkstanczak** [comment]
Actually, I think the biggest issue will be ensuring that the DB does not go beyond capacity on a given drive so it may be a bit more of a challenge.

Ideally each database would have a ladder of locations.

**Comment by cerealkill** [comment]
Hi @tkstanczak ! Thanks for the reply, really appreciate you considering it!

Sure, block execution is not a big issue, if the user really needs it, we will wait for the Http timeout and/or use the WebSocket API for a fully async response.

About the storage limit issue, that is why I suggested the user would set it manually under the kw`RemoteDBCapacity`, so if it gets bigger or smaller, it can be managed from outside, and if the user sets it falsely, the client can detect that the DB is read-only but did not reach size limit.

I noticed I made a mistake, I wanted to say HDFS, not IPFS! Hadoop FS is a beautiful concept that could speed block search up, solve data indexing, and minimize chances of data corruption/unavailability.

**Comment by tkstanczak** [comment]
Sounds really cool, I think we just cannot pick it up at the moment but I will remember this as a potential improvement post pruning. I think we have the skills to deliver this now but it may take time to prioritize.

**Comment by MysticRyuujin** [comment]
Wouldn't it be easier to simply mount the remote location in the VM?

In Linux you can modify your /etc/fstab - in Windows you can map a network drive.

**Comment by cerealkill** [comment]
Hi @MysticRyuujin, That is what I did there and got locking issues. Were you able to successfully do it using Nethermind? If so, would you be so kind to share configuration details? That would really save me a great deal of trial and error I already spent on this. I tried both NFS and SMB, both failed with geth, parity and nethermind in the past.

**Comment by kamilchodola** [comment]
@MysticRyuujin @cerealkill Wondering if after 4 years you found the solution for that and if it requires some custom addon to nethermind or it worked well oob?

**Comment by LukaszRozmej** [comment]
just mount and use `symlink` if needed
