### ISSUE TITLE
Linux version fails at first because libsnappy not installed

### ISSUE THREAD

**Issue by vbuterin** [NethermindEth/nethermind#1870]
Version 1.8.32, on Ubuntu 19.10:

```
===================================================================================== 
2020-05-13 16:39:34.9297|Waiting for peers... 1s 
2020-05-13 16:39:34.9348|Sync peers - Initialized: 0 | All: 0 | Max: 100 
2020-05-13 16:39:35.1568|Connected to 8 bootnodes, 8 trusted/persisted nodes 
2020-05-13 16:39:35.3677|Channel is active DotNetty.Codecs.EncoderException: Exception of type 'DotNetty.Codecs.EncoderException' was thrown.
 ---> System.DllNotFoundException: Unable to load shared library 'snappy' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libsnappy: cannot open shared object file: No such file or directory
```

Running `sudo apt install libsnappy-dev` fixes this. Still though, ideally it would install the dependency more automatically.

**Comment by tkstanczak** [comment]
@vbuterin - agreed and some form of package manager support has been in the backlog for some time - below more detailed response.

---

The line below is required to support snappy and rocksdb on Ubuntu:

`sudo apt-get update && sudo apt-get install libsnappy-dev libc6-dev libc6`

We include it in all release notes.

we were considering a package manager (like Geth) or a bash script (like Parity) and discussed it with the community - majority of responses were that the transparency of the project was preferred over the convenience of the packager for security reasons so we have not prioritized it yet. There were attempts from the community but none was finished.

**Comment by LukaszRozmej** [comment]
Package manager support is now live, release docs have all instructions.
