### ISSUE TITLE
Safe upgrades

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1902]
When upgrading to a new version we need to confirm:
 * that the pivot transition will not cause trouble
 * that any database migrations will be executed or suggested to the users
 * that the sync state will be restored
 * that the config changes are non braking

**Comment by kamilchodola** [comment]
We test that every time on every validator we have in our infra - we also experimented with GH action which will be doing such things automatically (sync every fork-supported version and upgrade to most recent one - worked well, needs more love to be more frequently used).

But for now it is pretty well covered by validator upgrades on each supported chain.

Closing
