### ISSUE TITLE
eth_getTransactionByHash returns null for all pending txs

### ISSUE THREAD

**Issue by Austin-Williams** [NethermindEth/nethermind#1913]
After setting up a new pending transaction filter via `eth_newPendingTransactionFilter`, I can call `eth_getFilterChanges` and get a `result` that contains an array of tx hashes.

If I then pass any of those tx hashes to `eth_getTransactionByHash` I always receive a `result` of `null`.

**Steps to reproduce:**

1. Set up a new pending transaction filter.

2. Call `eth_getFilterChanges` and then pass any/all of the tx hashes it returns to `eth_getTransactionByHash` and log the results.

E.g.:

```
// CREATE RPC SERVER OBJECT
const rpc = require('node-json-rpc')
const options = { port: 8545, host: '127.0.0.1', path: '/', strict: true }
const client = new rpc.Client(options)


function test() {
    console.log("BEGIN TEST")
    // check mempool for new txs
    client.call(
        {"jsonrpc": "2.0", "method": "eth_getFilterChanges", "params": [newPendingTransactionFilterId], "id": 1},
        function (error, response1) {
            if (error) {
                console.log("Error, eth_getFilterChanges:", error)
                throw "Failed on eth_getFilterChanges"
            }

            if (response1.result.length == 0) { return }

            // log the results of eth_getFilterChanges
            console.log("response1:\n", response1)

            // when we find some new pending txs, let's call eth_getTransactionByHash
            response1.result.forEach(txHash => {
                client.call(
                    {"jsonrpc": "2.0", "method": "eth_getTransactionByHash", "params": [txHash], "id": 0},
                    function (error, response2) {
                        if (error) {
                            console.log("Error, eth_getTransactionByHash:\n", error, "\n")
                            return
                        } else {
                            // log the results of eth_getTransactionByHash
                            console.log("\n    txHash:\n", txHash)
                            console.log("\n    response2:\n", response2)
                        }
                    }
                )
            })

        }
    )
}
```

Here is an example of an actual output:

```
BEGIN TEST
response1:
 { jsonrpc: '2.0',
  result:
   [ '0xfbc487801387d4c3a4d34b56f0822190cabc51264b868970da1efa312764e57a',
     '0xc8366df184e5bb2e3dd95226b6538762b3419ef8b65067567717a79bbb8c06ee' ],
  id: 1 }

    txHash:
 0xfbc487801387d4c3a4d34b56f0822190cabc51264b868970da1efa312764e57a

    response2:
 { jsonrpc: '2.0', result: null, id: 0 }

    txHash:
 0xc8366df184e5bb2e3dd95226b6538762b3419ef8b65067567717a79bbb8c06ee

    response2:
 { jsonrpc: '2.0', result: null, id: 0 }
```

At first I thought maybe it was a race condition causing this. I've tried adding synchronous delays before the calls to  `eth_getTransactionByHash`. It didn't help. 🤔

I'm using this version: nethermind-linux-amd64-1.8.35-af34150-20200519.zip

**Comment by Austin-Williams** [comment]
UPDATE: After some manual testing, it appears as though this issue is limited to pending txs.

That is `eth_getTransactionByHash` returns `result: null` for all pending tx.

Once a tx is mined, `eth_getTransactionByHash` will return the correct `result`.

But `eth_getTransactionByHash` _should_ also return a correct `result` when a tx is pending.

**Comment by tkstanczak** [comment]
Hi @Austin-Williams checking it now

**Comment by tkstanczak** [comment]
trying to reproduce - not able to reproduce on local Goerli, checking further

tested local Goerli:
nethermind> eth.getTransactionByHash("0xce3cfe06a710d52e35833412327843c03c41eaa76338a9f839dbf6b789601e1e")
Request complete in 5208.2µs
{
  "hash": "0xce3cfe06a710d52e35833412327843c03c41eaa76338a9f839dbf6b789601e1e",
  "nonce": "0x5e5",
  "blockHash": null,
  "blockNumber": null,
  "transactionIndex": null,
  "from": "0x55cfa4458f854d973c77222ed255283791918749",
  "to": "0x3b19954a4237a41aa3b4711650dcb717f57f0bd7",
  "value": "0x0",
  "gasPrice": "0x3b9aca00",
  "gas": "0xacae0",
  "data": "0xc1f7dcb60000000000000000000000006814dd7d02567390e20d8f3031022edff992ddab0000000000000000000000000000000000000000000000056bc75e2d63100000",
  "input": "0xc1f7dcb60000000000000000000000006814dd7d02567390e20d8f3031022edff992ddab0000000000000000000000000000000000000000000000056bc75e2d63100000",
  "v": "0x2d",
  "s": "0x31bf09c1165ddab3d31ad1bf21a12e90d1bf3bd629c4e26cf9544256529ee0a0",
  "r": "0xb615fba8f924bce985d4a07c3573cf33ed6b728e6aee094bd691878cd6ae6f0b"
}

**Comment by tkstanczak** [comment]
I wonder if I do something idfferently:
![image](https://user-images.githubusercontent.com/498913/82717214-416cdb00-9c93-11ea-9b24-7cd563ab800a.png)

**Comment by tkstanczak** [comment]
postman on the current master works as well...

![image](https://user-images.githubusercontent.com/498913/82717570-e0460700-9c94-11ea-8d69-fa521305fdab.png)

**Comment by tkstanczak** [comment]
@Austin-Williams 
I have a few ideas:
transactions in the txPool are removed in a few cases:
 * when the node knows many transactions with better gasPrice - it just removes the low gas price transactions from the pool then
 * when the transaction is included in the block
 * then the transaction is very old

Have you tried:
 * txpool_content
 * txpool_inspect

**Comment by Austin-Williams** [comment]
I tested manually by grabbing a pending tx from Etherscan and then doing:

```
curl -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["<TX_ID_HERE>"],"id":3}' http://127.0.0.1:8545 | json_pp
```

That was returning `null` result until the tx got mined. Then is was returning a correct result.

If you are unable to reproduce then it must be something weird on my end. This started happening only after I replaced my old version with the latest. Perhaps I did that sloppily. 🤷‍♂️

I'll trying reinstalling from scratch.

Feel free to close this issue. I'll reopen if I run into it again after reinstalling on a fresh AWS instance.

**Comment by tkstanczak** [comment]
@Austin-Williams was the transaction created by you locally? (the one that you broadcast?)
I will test such scenario too

**Comment by Austin-Williams** [comment]
No, it was not. It was just a random pending tx I got from Etherscan. I tried with a few different ones with the same result.

**Comment by tkstanczak** [comment]
@Austin-Williams your node will have a different set of transactions than Etherscan - you know only about a subset of pending transactions

Still, in the case when you create a filter and the filter results are missing from txHash - this makes less sense (unless you poll very long time after creating the filter and the transactions got removed)

**Comment by Austin-Williams** [comment]
I really must have borked something when I installed the new version.

When I installed the new version over the old one I had to re-sync from scratch. And only then did I start experiencing this.

I'm going to start again from scratch.

Thank you for taking a look though!

**Comment by tkstanczak** [comment]
It is unlikely that the resync will fix it. Which version did you use before? (so I can check what changes we have made since then)
Is it for mainnet or Goerli or some other chain?

**Comment by tkstanczak** [comment]
OK, let me know - I have no more ideas for now.
I remember I was testing tx broadcasting from 1.8.35 and I was able to push a transaction to mainnet via the mempool so the whole flow worked well. Maybe tomorrow I will have some fresh ideas.

**Comment by tkstanczak** [comment]
@Austin-Williams did the problem remain for you?

**Comment by Austin-Williams** [comment]
Yes, but I made some progress.

I installed GETH and ran the same tests. I got similar results but with important exceptions.

It seems that the nodes (both GETH and Nethermind) are hearing the txs and then dropping them -- as you suspected.

With GETH, txs are getting dropped when the gas price is too low, or when the tx is from an account that has another pending tx with a lower nonce in the tx pool. (That's to be expected, because these txs are unlikely to be mined soon).

But Nethermind seems to be dropping many more txs and its not clear to me why.

For example, Nethermind regularly seems to be dropping txs that end up getting mined into a block a few seconds later. So I'm not sure why those txs are getting dropped from the tx pool.

**Comment by tkstanczak** [comment]
I am working on some mempool code now so I will look at it again.

We only drop the transactions based on gas price but the default mempool size is smaller
Have you tried increasing the mempool size?

I will check if there is anything around the signature / chain ID that maybe we process wrong here.

**Comment by Austin-Williams** [comment]
> Have you tried increasing the mempool size?

Ah, that may have been it!

I don't have a node running rn so I can't test. But that would make a lot of sense.
