### ISSUE TITLE
Replace Nethermind JSON RPC with streamjsonrpc?

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1931]
https://github.com/microsoft/vs-streamjsonrpc/tree/master/src/StreamJsonRpc

**Comment by tkstanczak** [comment]
just an idea, not a necessity

**Comment by LukaszRozmej** [comment]
will not pursue, was easier to optimize our own JSON RPC. As its important part of the node we want to have control over it.
