### ISSUE TITLE
Add Http/2 support in JSON RPC

### ISSUE THREAD

**Issue by LukaszRozmej** [NethermindEth/nethermind#1934]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#listenoptionsprotocols-1

**Comment by kamilchodola** [comment]
@benaadams 
What went wrong with PR linked? Anything to be refactored or more work required?

**Comment by LukaszRozmej** [comment]
no point in implementing this ATM.

**Comment by benaadams** [comment]
Do need a https cert to serve http2/3 which isn't great if localhost; so would only be for non-engine
