### ISSUE TITLE
Missing protocol size limitation

### ISSUE THREAD

**Issue by holiman** [NethermindEth/nethermind#2048]
Here's a log from an attempt to sync (goerli) against a nethermind node: 

```
DEBUG[06-24|11:14:19.748] Ethereum peer connected                  id=1de6fc6c000adb83 conn=dyndial name="Nethermind/v1.8.51-0-e1adba9c9-20200619/X64-Linux 4.15.0-74-generic/Core3.1.3"
...
DEBUG[06-24|11:14:53.525] Fetching batch of receipts               id=1de6fc6c000adb83 conn=dyndial count=227
DEBUG[06-24|11:14:53.535] Fetching batch of state data             id=1de6fc6c000adb83 conn=dyndial count=384
DEBUG[06-24|11:14:53.562] Fetching batch of headers                id=1de6fc6c000adb83 conn=dyndial count=192  fromnum=2923961 skip=0   reverse=false
DEBUG[06-24|11:14:53.604] Fetching batch of block bodies           id=1de6fc6c000adb83 conn=dyndial count=128
DEBUG[06-24|11:14:53.605] Inserting fast-sync blocks               items=201     firstnum=2921579 firsthash="311da4…5fb1a7" lastnumn=2921779 lasthash="db43dc…bb4a2b"
INFO [06-24|11:14:53.612] Imported new block receipts              count=201  elapsed=6.312ms     number=2921779 hash="db43dc…bb4a2b" age=1d6h10m   size=347.59KiB
INFO [06-24|11:14:53.685] Imported new block headers               count=192  elapsed=122.192ms   number=2923960 hash="a3cbbc…39021d" age=21h4m54s
DEBUG[06-24|11:14:55.717] Ethereum message handling failed         id=1de6fc6c000adb83 conn=dyndial err="Message too long - 14780254 > 10485760"
```

It seems Nethermind delivers messages exceeding the max message size for eth messages

```golang
const protocolMaxMsgSize = 10 * 1024 * 1024 // Maximum cap on the size of a protocol message
```
Was just trying to find it in the specs -- not sure if it's in there. @fjl ?

**Comment by tkstanczak** [comment]
Do you expect a disconnect there on seing such a request or just limit the
number of responses?

I think that we disconnect others when they send too big a message and
deliver messages that match the request size limits (number of bodies).

Since the messages are chunked and we already loaded the data it makes
sense to just send it over.

**Comment by holiman** [comment]
Geth limits either by the request-items or a soft response limit, and stop whenever we hit one of them. Our soft response limit is 2Mb. 

https://github.com/ethereum/go-ethereum/blob/45352300592cf68feb64d67aefa607eec2c9a1de/eth/handler.go#L550

**Comment by tkstanczak** [comment]
This is very important piece of knowledge and it explains the pace of
bodies download.

Maybe we could increase the soft limits at least to 4MB? Is the maximum
block size nowadays not bigger than 2MB?

**Comment by tkstanczak** [comment]
No, I have checkes, it is smaller than 2MB, probably around 700kb. Still the bodies download rate could be improved a lot if we changed these limits.

**Comment by holiman** [comment]
> Maybe we could increase the soft limits at least to 4MB? 

cc @fjl @karalabe ?

**Comment by karalabe** [comment]
devp2p is limited by protocol to 10MB

**Comment by karalabe** [comment]
At least that's what I thought. Generally large messages are super bad since they hog your link and things will start timing out all over the place.

**Comment by holiman** [comment]
Right -- the reason I tagged you Peter was not beacuse of the `10Mb` limit, but the soft `2Mb` limit that we enforce on outgoing eth-messages

**Comment by karalabe** [comment]
QoS. Nodes are free to limit responses by size, time or whatever then wish. The 2MB limit is specifically because we don't want a network connection to block everything just because it's responding to some huge query. The 2MB is actually an insane limit already, SNAP uses 500KB package limits.

**Comment by karalabe** [comment]
Quoting from the bittorrent specs: "In order to have as little impact as possible on slow congested links, uTP adjusts its packet size down to as small as 150 bytes per packet. Using packets that small has the benefit of not clogging a slow up-link, with long serialization delay."

**Comment by karalabe** [comment]
Though there's a catch, BT uses UDP so it's a bit of a different game, but the point kind of stands that if you make big packets, things will start failing.

The target reply time in BT is 100ms, is we were to expect the same for Ethereum, pushing out 4MB/100ms to a single peer would mean 320mbps connection, without even talking about multiple peers.

If we're more generous as say that ok, 1s top is acceptable, then we're down to 32mbps/peer, but imho 1s is pushing it.

**Comment by karalabe** [comment]
Yes, the larger the packet the better for the peer leeching. But should the leeching peer be the priority when serving free data or the server?

**Comment by tkstanczak** [comment]
@karalabe, I trust your judgement here, I think that the server actually has less operations if it can read the wider chunk of blocks and does not have to discard blocks after reading them -> usually the block count number will be higher than the soft limit so you read them from the db many times and discard them each time before sending response

**Comment by tkstanczak** [comment]
@karalabe maybe we should add a soft limit in Nethermind - I will check if this is already affecting us on the nodes that we are running publicly

**Comment by tkstanczak** [comment]
shall we maybe introduce back the message chunking? we removed the frames after adding the Snappy serialization?

**Comment by holiman** [comment]
As it is right now, a large majority of the network will discard your >10Mb answers, which is even more wasteful :)

**Comment by tkstanczak** [comment]
makes sense, thanks for reporting it, maybe we can pick it up straightaway

**Comment by tkstanczak** [comment]
@holiman I have added a code that is counting the bodies size

**Comment by tkstanczak** [comment]
need to do the same for receipts

**Comment by tkstanczak** [comment]
done for receipts as well

**Comment by fjl** [comment]
I think you already cleared up the issue here, but the original reason for those limits is avoiding head-of-line blocking.
We could work around it by changing the underlying protocol to chunk up the messages for you, but it's much simpler
not to send such large messages in the first place. The recipient of a large message might need to buffer it in order to
respond, which is annoying for messages > 2MB. You can process the message as a stream while receiving it to improve
response latency, but still need to read all of it.

**Comment by fjl** [comment]
Need to add a note to the spec about this.

**Comment by tkstanczak** [comment]
@fjl no problem at all, thanks for reporting!
