### ISSUE TITLE
Fix behaviour of eth_sendRawTransaction when account has no Ether

### ISSUE THREAD

**Issue by SebastianDremo** [NethermindEth/nethermind#2064]
I call eth_sendRawTransaction to my spaceneth node, it gives me a transaction hash, then I spin while asking for the receipt for that transaction hash every 1 second and I get back null every time.
I do see it sealing a block after my eth_sendRawTransaction, like normal.  I just cannot get a receipt back for the transaction.

Interesting, if I send the transaction again, I don't get an error (which I would expect since the nonce would be too low).
I get the same transaction hash, but still just spins on the receipt.
Ah, the specific problem was that I didn't have enough ETH in the account to cover the gas cost.
So, bug report: eth_sendRawTransaction doesn't return an error if the account doesn't have enough ETH to cover transaction costs.

I suppose that may be intentional (I can certainly see situations where I want to get the transaction into the pending pool before I fund the account), but the behavior is different from Geth.

**Comment by tkstanczak** [comment]
1) Prepare example developer chains (`spaceneth` in Nethermind and its matching solution in `Geth`)
2) Create a raw, signed transaction to send from an account that does not have enough `Ether`
3) Check the behaviour of `Geth`
4) Reproduce exactly the same behaviour in `Nethermind`

**Comment by LukaszRozmej** [comment]
fixed
