### ISSUE TITLE
Create a JSON RPC performance benchmark and continuously run it against a synchronized mainnet VM.

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2067]
Setup a VM with a synchronized `Nethermind` `mainnet` node.
Setup a  process on the same machine that will generate multiple concurrent connections generating thousands of requests of various types (`eth_blockNumber`, `eth_call`, `eth_getBlockByNumber`).
Report results to the team weekly or monthly or after releases.

**Comment by roninkaizen** [comment]
sounds interesting
could be tested with a combination usage of nethermind-mainnet/ NDM-somewhere constellation-
autoclicking any 15 seconds on NDM ;)

**Comment by kamilchodola** [comment]
Not exactly like described here but now we have it:
https://github.com/NethermindEth/nethermind/actions/workflows/rpc-comparison.yml

You have few modes here:
1. Check two nodes in equality mode (check if two nodes producing exact same output to various requests)
2. Compare two nodes performance on various requests
3. Compare against archive node or Infura (useful only for equality mode)

Issue of this is that every time it syncs new set of nodes (it has pros and cons; obviously execution time is a minus but also make sure that there is no hidden issue on freshly synced nodes and reduces costs).

Would add in future option to test against other EL clients.

For now will close that as foundation is here and will improve on that over time.
