### ISSUE TITLE
SyncMode changed event logic is wrong

### ISSUE THREAD

**Issue by AndreaLanfranchi** [NethermindEth/nethermind#2108]
Investigating why this snippet never got executed
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Synchronization/Reporting/SyncReport.cs#L78-L90
found that here
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs#L186-L196
SyncModeChangedEventArgs is valued with Previous and Current being the same value.
Also all subsequent events are triggered regardless newModes is different from Current causing unneded code being executed

**Comment by tkstanczak** [comment]
checking this now

**Comment by tkstanczak** [comment]
Fixed, thank you @AndreaLanfranchi
