### ISSUE TITLE
PRs from external contributors do not invoke the merge checks

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2127]

**Comment by matilote** [comment]
There is one way of achieving this: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target

Although: ```Combining pull_request_target workflow trigger with an explicit checkout of an untrusted PR is a dangerous practice that may lead to repository compromise.```
The risks seem to outweigh the benefits.
More: https://securitylab.github.com/research/github-actions-preventing-pwn-requests
