### ISSUE TITLE
Unable to find an entry point named 'blsSetETHmode' in DLL 'bls384_256'.

### ISSUE THREAD

**Issue by Enigmatic331** [NethermindEth/nethermind#2164]
I am playing around with the Nethermind.Cryptography.Bls package at the moment, and it seems that I am getting the below error whenever the interop project tries to find an entrypoint in the bls384_256.dll:

![image](https://user-images.githubusercontent.com/28551011/88420874-24cb5b80-ce1a-11ea-8437-1ccd88c4bf57.png)

Which is strange as of course, the entrypoint does exist:

![image](https://user-images.githubusercontent.com/28551011/88420948-43c9ed80-ce1a-11ea-9727-42a34ea5ff62.png)

Perhaps it's just me being dumb after staring at this for the past couple of hours - Could there be something I am missing? Perhaps a proper way to reference the bls384_256.dll file?

Thanks in advance.

**Comment by Enigmatic331** [comment]
Gotten myself sorted. Cheers.

**Comment by tkstanczak** [comment]
Hi @Enigmatic331, what was the solution in the end?

**Comment by Enigmatic331** [comment]
Ah..... I ended up rather puzzled and went ahead deleting my entire project, recreating one and re-added the references.... Which sorted it out somehow.

Sorry, I know this isn't too helpful, though wished it was! If I do come across something more concrete I will document it here for the benefit of others.
