### ISSUE TITLE
Tracing failed for partialy reverted transaction

### ISSUE THREAD

**Issue by Gdocal** [NethermindEth/nethermind#2171]
Transaction:
https://etherscan.io/tx/0xd0649b8e818f77f27b040a08b2ae52f3209a5f4d0487e419a925fa3ea2f058ac/advanced

When tracing it with  TraceType.stateDiff options I do not get result back. In nethermind console I see next exception:
```
2020-07-31 16:57:57.7139|Connection id "0HM1LCK8ALP0V", Request id "0HM1LCK8ALP0V:00000001": An unhandled exception was thrown by the application. System.NullReferenceException: Object reference not set to an instance of an object.
   at Nethermind.Core.Extensions.Bytes.ByteArrayToHexViaLookup32Safe(Byte[] bytes, Boolean withZeroX) in F:\Projects\NethermindEth2\nethermind\src\Nethermind\Nethermind.Core\Extensions\Bytes.cs:line 534
   at Nethermind.Serialization.Json.ByteArrayConverter.WriteJson(JsonWriter writer, Byte[] value, JsonSerializer serializer) in F:\Projects\NethermindEth2\nethermind\src\Nethermind\Nethermind.Serialization.Json\ByteArrayConverter.cs:line 27
   at Nethermind.JsonRpc.Modules.Trace.ParityAccountStateChangeConverter.WriteChange(JsonWriter writer, ParityStateChange`1 change, JsonSerializer serializer) in F:\Projects\NethermindEth2\nethermind\src\Nethermind\Nethermind.JsonRpc\Modules\Trace\ParityAccountStateChangeConverter.cs:line 57
   at Nethermind.JsonRpc.Modules.Trace.ParityAccountStateChangeConverter.WriteJson(JsonWriter writer, ParityAccountStateChange value, JsonSerializer serializer) in F:\Projects\NethermindEth2\nethermind\src\Nethermind\Nethermind.JsonRpc\Modules\Trace\ParityAccountStateChangeConverter.cs:line 140
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Nethermind.JsonRpc.Modules.Trace.ParityTxTraceFromReplayConverter.WriteJson(JsonWriter writer, ParityTxTraceFromReplay value, JsonSerializer serializer) in F:\Projects\NethermindEth2\nethermind\src\Nethermind\Nethermind.JsonRpc\Modules\Trace\ParityTxTraceFromReplayConverter.cs:line 43
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Nethermind.Serialization.Json.EthereumJsonSerializer.Serialize[T](Stream stream, T value, Boolean indented) in F:\Projects\NethermindEth2\nethermind\src\Nethermind\Nethermind.Serialization.Json\EthereumJsonSerializer.cs:line 113
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__2>d.MoveNext() in F:\Projects\NethermindEth2\nethermind\src\Nethermind\Nethermind.Runner\Startup.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at Nethermind.Runner.Startup.<>c__DisplayClass3_0.<<Configure>b__2>d.MoveNext() in F:\Projects\NethermindEth2\nethermind\src\Nethermind\Nethermind.Runner\Startup.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
![image](https://user-images.githubusercontent.com/11136265/89054347-8cb8ff00-d350-11ea-8550-39a3fddc89f5.png)

Expected result:
No exception is thrown.

**Comment by SebastianDremo** [comment]
Working on it

**Comment by SebastianDremo** [comment]
method:`{"method":"trace_replayTransaction","params":["0xd0649b8e818f77f27b040a08b2ae52f3209a5f4d0487e419a925fa3ea2f058ac",["stateDiff"]],"id":1,"jsonrpc":"2.0"}`

response:`{"jsonrpc":"2.0","result":{"output":null,"stateDiff":{"0x0000000000004946c0e9f43f4dee607b0ef1fa1c":{"balance":"=","code":"=","nonce":"=","storage":{"0x0000000000000000000000000000000000000000000000000000000000000003":{"*":{"from":"0x000000000000000000000000000000000000000000000000000000000005acae","to":"0x000000000000000000000000000000000000000000000000000000000005acc7"}},"0x33aa8c1648339322d7da98c2f4a92a8d5e9ee93e5490592269f3f461be8a2294":{"*":{"from":"0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffee","to":"0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd5"}},"0xada52e17469006775f6cb5d38adf0ecb7533d3bcbb9bbdeb132f3583e8b2a965":{"*":{"from":"0x0000000000000000000000000000000000000000000000000000000000000030","to":"0x0000000000000000000000000000000000000000000000000000000000000017"}}}},"0x07156d789932aa9384eeb8f10e07affb5af30c65":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0x07326b9ba367d7450bcd1fbb2f0ade0719fd71a4":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0x0bc529c00c6401aef6d220be8c6ea1667f6ad93e":{"balance":"=","code":"=","nonce":"=","storage":{"0x5da1dee3074bf604094b4c815e532af6ae89f52f1a463856475abd03ba38d671":{"*":{"from":"0x000000000000000000000000000000000000000000000000007390a84a742fd4","to":"0x0000000000000000000000000000000000000000000000000000000000000000"}},"0xada52e17469006775f6cb5d38adf0ecb7533d3bcbb9bbdeb132f3583e8b2a965":{"*":{"from":"0x000000000000000000000000000000000000000000000000007390a84a742fd4","to":"0x0000000000000000000000000000000000000000000000000000000000000000"}},"0xcbd54bc1c0c3a89fc361baaef1c506990b33cadefb412365914f1ff2c2bf8e82":{"*":{"from":"0x000000000000000000000000000000000000000000000018e90292fae0648fc1","to":"0x000000000000000000000000000000000000000000000018e97623a32ad8bf95"}},"0xf22b188504aba7c118845a0ae8789485cd220db155fccfa88aac32d54d533d8c":{"*":{"from":"0xfffffffffffffffffffffffffffffffffffffffffffffffe0c40f0652d7f7a19","to":"0xfffffffffffffffffffffffffffffffffffffffffffffffe0bcd5fbce30b4a45"}}}},"0x0c9d4093d103d527611726ff2f3b56d377848fb2":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0x2260fac5e5542a773aa44fbcfedf7c193bc2c599":{"balance":"=","code":"=","nonce":"=","storage":{"0x0d2a19d3ac39dc6cc6fd07423195495e18679bd8c7dd610aa1db7cd784a683a8":{"*":{"from":"0x0000000000000000000000000000000000000000000000000000000308055b66","to":"0x0000000000000000000000000000000000000000000000000000000307f09b4a"}},"0x3f9b33db4f60d7fd13291e6e66a9d8c93d062cbdda84e8ada4f9d54b80f54d3b":{"*":{"from":"0x000000000000000000000000000000000000000000000000000000015f7fa8d7","to":"0x000000000000000000000000000000000000000000000000000000015f9468f3"}}}},"0x293ea599ddffbea63946883a40975004f46ad6d2":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0x294de1cde8b04bf6d25f98f1d547052f8080a177":{"balance":"=","code":"=","nonce":"=","storage":{"0x0f96d37f060a4c4d24b5db5a43f3ef48b5939bb9eee99c945607ea1d4c0038c6":{"*":{"from":"0x000000000000000000000000000000000000000000000000000000015f7fa8d7","to":"0x000000000000000000000000000000000000000000000000000000015f9468f3"}},"0xd0bcf4df132c65dad73803c5e5e1c826f151a3342680034a8a4c8e5f8eb0c13f":{"*":{"from":"0x00000000000000000000000000000000000000000000006a667bd5a066bf8800","to":"0x00000000000000000000000000000000000000000000006a60369d895f410f60"}}}},"0x2ace794c840155efb0faff14bcde3bf168c0e124":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0x2fdbadf3c4d5a8666bc06645b8358ab803996e28":{"balance":"=","code":"=","nonce":"=","storage":{"0x0000000000000000000000000000000000000000000000000000000000000008":{"*":{"from":"0x5f2374fe000000000159c27a0735c3fa4318000000000018e90292fae0648fc1","to":"0x5f23750b000000000159bc3ae1ab42e0da37000000000018e97623a32ad8bf95"}},"0x0000000000000000000000000000000000000000000000000000000000000009":{"*":{"from":"0x00000000000000000000000000000082641b1d3f4fddf81eaaf7e7ac3a8fadf7","to":"0x0000000000000000000000000000008264cf8eb5da6a5d976064ef0919c53a5a"}},"0x000000000000000000000000000000000000000000000000000000000000000a":{"*":{"from":"0x00000000000000000000000000000002e497d8a4536c25a9f5f419aac6e2a364","to":"0x00000000000000000000000000000002e498c868364851fa50ffcefee7bf6f8b"}}}},"0x407cfd1c7152890936cd86d2b7ed63b1db080afb":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0x408599ce5050226af82d264061ce2647af34165d":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0x503fabdc1bef955ef5ca278414aacee0c053a6d2":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0x5a311fbb62a3b5ec51a7152e66480879f957e6fa":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0x5da8b15e7552954f6a5f65fe8062659f2b83438d":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0x5e7ddf53cf49c08ba79dc00a0fbc29f6b7dbf765":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0x61ca3bbda5fe68a31da954a59fa2e9bb8609de86":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0x653bc6af5ac182bfcbb26e606c9e5177a59de9a1":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0x686082905213fa13dde479a5633f070f508ebc12":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0x6c4e2b057725b40cd12cd0696e9822d16efa8209":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0x8335d9ebe7bcc5bb1101c4ff2db1ead69d5a01f2":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0x9a124fbf207e5b349b76ad8b309139a4d183257b":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0xa34f9fc644e0dc563465ead98ee9645353432147":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0xb5201714f0e6cfbc8b1454b7c637c51f6d3e14bb":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0xbb2b8038a1640196fbe3e38816f3e67cba72d940":{"balance":"=","code":"=","nonce":"=","storage":{"0x0000000000000000000000000000000000000000000000000000000000000008":{"*":{"from":"0x5f23726d0000000000e8e2f521b75efd2e7e0000000000000000000308055b66","to":"0x5f23750b0000000000e8e9344741e016975f0000000000000000000307f09b4a"}},"0x0000000000000000000000000000000000000000000000000000000000000009":{"*":{"from":"0x00000000000000000000230a570e1e587cc1088d6538268535c3c1c0f0993cf5","to":"0x00000000000000000000230b201fdc816e0ebf5220448d68db62b7a1d4d8203f"}},"0x000000000000000000000000000000000000000000000000000000000000000a":{"*":{"from":"0x00000000000000000000000000000000000000010c5db1797c7813a6929a196d","to":"0x00000000000000000000000000000000000000010c666a09bec1469a5401829b"}}}},"0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2":{"balance":{"*":{"from":"0x2a3da5659e31705edaab3","to":"0x2a3da5014aafffe6f3213"}},"code":"=","nonce":"=","storage":{"0x427092be1e260fea0aba490a10b5976129d4b8d28ddc845ca8488b36bf5c0808":{"*":{"from":"0x00000000000000000000000000000000000000000000006a667bd5a066bf8800","to":"0x00000000000000000000000000000000000000000000006a60369d895f410f60"}},"0x46f70a702121cc6383b14ae13b98d1d58c70a291d047b67750f3824cd24745ce":{"*":{"from":"0x000000000000000000000000000000000000000000000159c27a0735c3fa4318","to":"0x000000000000000000000000000000000000000000000159bc3ae1ab42e0da37"}},"0x7fba2702a7d6e85ac783a88eacdc48e51310443458071f6db9ac66f8ca7068b8":{"*":{"from":"0x0000000000000000000000000000000000000000000000e8e2f521b75efd2e7e","to":"0x0000000000000000000000000000000000000000000000e8e9344741e016975f"}}}},"0xc62b7e0440e74c1a51776b39323f5bff6769923d":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0xcdc95a5a12111fdda913586b7f8d4de4fbe204b9":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0xcdc96bec0f21133bf7ed2829527548c175042390":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0xe312df11664b1ee1934a67d418f9952d72c0f324":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0xe3b1209dd2ad3c9c7dde8dcef8440b924ce2cc26":{"balance":{"*":{"from":"0x301a477375ab83c","to":"0x8d0a95636af62dc"}},"code":"=","nonce":{"*":{"from":"0x2d","to":"0x2e"}},"storage":{}},"0xea674fdde714fd979de3edf0f56aa9716b898ec8":{"balance":{"*":{"from":"0x30790a9b4c6080912b","to":"0x307980ce8468aa5f2b"}},"code":"=","nonce":"=","storage":{}},"0xf1feb47ea6751399a88e1b3d372534e3947d4597":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}},"0xf8ea46f074e6f2f0ea41a0f9cb4b6cfcda0bffea":{"balance":{"*":{"from":"0x0","to":null}},"code":{"*":{"from":"0x6d4946c0e9f43f4dee607b0ef1fa1c3318585733ff","to":null}},"nonce":{"*":{"from":"0x1","to":null}},"storage":{}}},"trace":[],"vmTrace":null},"id":1}`

should be ok now
