### ISSUE TITLE
Discrepancy with OpenEthereum's block.number in public getters

### ISSUE THREAD

**Issue by varasev** [NethermindEth/nethermind#2184]
I'm testing POSDAO features in Nethermind using our [`posdao-test-setup`](https://github.com/poanetwork/posdao-test-setup/tree/nethermind) tool and today discovered that commit/reveal phase starts with 1-block delay in comparison to OpenEthereum's behaviour (actually not, but I was initially confused looking to the logs).

I attached two log files of the [`watcher.js`](https://github.com/poanetwork/posdao-test-setup/blob/nethermind/scripts/watcher.js) script output (see below): one for OpenEthereum and another for Nethermind. There are only first 50 blocks in the logs.

In OpenEthereum's logs we see that the watcher script detects `Block 19` as in the `COMMITS PHASE`, but Nethermind's logs show the same block as already `REVEALS PHASE`.

The same is observed for block 38: OpenEthereum shows it is in `REVEALS PHASE`, but Nethermind shows as the block in `COMMITS PHASE`.

I guess, the reason is in [`isCommitPhase`](https://github.com/poanetwork/posdao-contracts/blob/229d6441ae32fd4250884e1c8d53f7fec10a9e9e/contracts/RandomAuRa.sol#L259-L261) getter which takes [`block.number`](https://github.com/poanetwork/posdao-contracts/blob/229d6441ae32fd4250884e1c8d53f7fec10a9e9e/contracts/RandomAuRa.sol#L366-L368) as a current block number. Seems for public getters Nethermind returns a future block number in the `block.number` instead of the latest one. I checked that with a separate small test and it confirmed my assumption.

Could you make its behaviour the same as OpenEthereum's?

Please also check other `block.*` properties for Solidity: https://solidity.readthedocs.io/en/v0.5.10/units-and-global-variables.html?highlight=block.number#block-and-transaction-properties

Attached logs:
[watcher.nethermind.log](https://github.com/NethermindEth/nethermind/files/5028808/watcher.nethermind.log)
[watcher.openethereum.log](https://github.com/NethermindEth/nethermind/files/5028810/watcher.openethereum.log)

**Comment by tkstanczak** [comment]
![image](https://user-images.githubusercontent.com/498913/89437195-290f4700-d73f-11ea-8c75-09de2f89f80a.png)

**Comment by tkstanczak** [comment]
![image](https://user-images.githubusercontent.com/498913/89437216-2f9dbe80-d73f-11ea-997b-e69d488f014b.png)
