### ISSUE TITLE
Nethermind doesn't create a specified log file

### ISSUE THREAD

**Issue by varasev** [NethermindEth/nethermind#2185]
We have the following config parameter for Nethermind node: https://github.com/poanetwork/posdao-test-setup/blob/342ea62180edb119a537ebcea45e0b2fbf3501ff/config/node0.nethermind.json#L9 - but while the client is running it doesn't create the log file for some reason.

We use `stdout` for logs instead: https://github.com/poanetwork/posdao-test-setup/blob/342ea62180edb119a537ebcea45e0b2fbf3501ff/scripts/start-test-setup#L15

**Comment by matilote** [comment]
@varasev 
Could you please try adding the `LogDirectory` to Init Config section, so it would look like this:
```
"LogFileName": ".nethermind.logs.txt",
"LogDirectory": "./data/node0"
```

**Comment by varasev** [comment]
@matilote that didn't help, unfortunately: https://github.com/poanetwork/posdao-test-setup/commit/0078d504e0abf6bf822e4daf544adb4bfbc40530 - still can't see `nethermind.logs.txt`

**Comment by varasev** [comment]
In `Nethermind v1.8.102` it works fine but only with `LogDirectory` config option. If I try to remove it and change `LogFileName` to `./data/node0/nethermind.logs.txt`, the log file is not created.
