### ISSUE TITLE
Allow setting target gas limit.

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2189]
Nethermind validators need to be able to actively change the gas limit.

In Geth and Parity it is done via config.
I believe it should be allowed to set it by miner_setTargetGasLimit in JSON RPC.

Then this value should be passed further to the block producers.

IConfig is not supporting any dynamic configurations which are supported via Options in .NET Core.
It may be too big a change to try to introduce options.

Instead we can create a separate interface or just set the value on the IBlockProducer interface.

**Comment by varasev** [comment]
Could you please clarify how I can use this in the config file?

Is this the right way to set block gas limit to `10 000 000`?

```
...
"MiningConfig":
{
  "TargetBlockGasLimit": "10000000"
}
...
```
