### ISSUE TITLE
Feature Request: No Special WebSocket URI

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#2267]
I would like it if we could just use the same URI for both JSON RPC and WebSocket.

Geth simply exposes one port and path

Nethermind has 1 port and 2 paths

I'm not sure there's really a need to have the extra `/ws/json-rpc` path at the end of the URI? Is there?

Not very important, but it is a minor annoyance.

**Comment by tkstanczak** [comment]
Thanks, I think there have been an architectural issue when ws was being added that made us do it this way. It is a bigger thing to fix unless I am wrong.

**Comment by tkstanczak** [comment]
In general JSON RPC and ws endpoints are not exposed in the same way so they need to be unified before we can fix it.

**Comment by kamilchodola** [comment]
Correct me if I'm wrong but we use the same port for rpc and ws
![image](https://github.com/NethermindEth/nethermind/assets/43241881/57a9fb2c-b52e-46f9-ba0d-698db75197e2)
![image](https://github.com/NethermindEth/nethermind/assets/43241881/60151aea-c493-42fe-b455-bab202edec7f)

Only difference in requests sending is that prefix should be http:// or ws://

**Comment by quickchase** [comment]
I'm pretty sure this was resolved a long time ago, I just never came back to it 😂

**Comment by kamilchodola** [comment]
That's what I'm thinking as well :D

Making some cleanup here and there - so will close this one and in case something is not clear will reopen.
