### ISSUE TITLE
Target Block Gas Limit mismatch with OpenEthereum

### ISSUE THREAD

**Issue by varasev** [NethermindEth/nethermind#2291]
I noticed that there is a little mismatch in the block gas limit between Nethermind v1.8.98 and OpenEthereum v3.0.1 when using `TargetBlockGasLimit`/`gas_floor_target` config option.

That can be a rounding error, I think.

Attaching two log files for the same configs and runs for different clients (Nethermind and OpenEthereum), for the first 14 blocks (because `blockGasLimitContractTransitions` [activates on 15th block](https://github.com/poanetwork/posdao-contracts/blob/8a145233e6e1eaec64bb49fd58e6d27be82db86a/templates/spec.json#L25)):

[Nethermind.log](https://github.com/NethermindEth/nethermind/files/5187153/Nethermind.log)
[OpenEthereum.log](https://github.com/NethermindEth/nethermind/files/5187151/OpenEthereum.log)

We see that `Gas limit` doesn't match for each block. It starts to mismatch right from the first block (Nethermind calculates it as `10009765`, but OpenEthereum as `10009764`) and continues to increase delta for each new block.

### Steps to reproduce

1. Run https://github.com/poanetwork/posdao-test-setup with `Nethermind v1.8.98` following the instructions https://github.com/poanetwork/posdao-test-setup#nethermind (use `npm run all-nethermind` command).

2. In a separate console run `npm run watcher` to collect logs.

3. Wait for the first few blocks and stop everything with `npm run cleanup`.

4. Run https://github.com/poanetwork/posdao-test-setup with `OpenEthereum v3.0.1` following the instructions https://github.com/poanetwork/posdao-test-setup#openethereum (use `npm run all` command).

5. In a separate console run `npm run watcher` to collect logs.

6. Wait for the first few blocks and stop everything with `npm run cleanup`.

The logs will show the mismatch.

**Comment by LukaszRozmej** [comment]
This is openethereum gas limit calculation: https://github.com/openethereum/openethereum/blob/5be4924672e5d58399ee1701ade075569fb61a2e/ethcore/machine/src/machine.rs#L220-L247

Especially this part looks very fishy to me: https://github.com/openethereum/openethereum/blob/5be4924672e5d58399ee1701ade075569fb61a2e/ethcore/machine/src/machine.rs#L240
