### ISSUE TITLE
RPC Parameter Logging Improvement

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#2310]
When making RPC calls Nethermind will report back something like this:

`Executing JSON RPC call eth_getblockbynumber with params 0xa5b7d6,False`

I was wondering if this could be made easier to parse with something like:

`Executing JSON RPC call method='eth_getblockbynumber' params='["0xa5b7d6",False]'`

Also, when the params are empty, it currently just doesn't list the params, but params is typically sent as `"params":[]` so I think it would make more sense to return `params='[]'` instead of nothing?

Also, less important but would be helpful: if the RPC method could actually match the 'case' of the official spec:

`eth_getblockbynumber` vs `eth_getBlockByNumber`

**Comment by tkstanczak** [comment]
@MysticRyuujin fixed the casing, as for the logging format - we can look at it later, I assume it is lower priority?

**Comment by MysticRyuujin** [comment]
Yeah, it's all nice to have, but it's not critical. Just makes parsing, reporting and reproducing easier

**Comment by tkstanczak** [comment]
@MysticRyuujin this can only be addressed properly with a bigger improvement of JSON RPC.
We simply do not have the param types details at the stage we are logging this:
![image](https://user-images.githubusercontent.com/498913/94620399-796dd580-02a6-11eb-98f0-f54bad240f98.png)
And this would be costly to push the properly formatted JSON params here.

**Comment by MysticRyuujin** [comment]
I'm fine with the generic array, comma separated, as long as it's actually surrounded by `[` and `]`

**Comment by tkstanczak** [comment]
Added [] brackets @MysticRyuujin , PR ready. (small thing)
