### ISSUE TITLE
hive: allow loading chain.rlp file in hive runner

### ISSUE THREAD

**Issue by renaynay** [NethermindEth/nethermind#2332]
We are trying to run some eth protocol tests on several eth clients at the moment, but we need a way for nethermind to load the chain from a chain.rlp file in addition to the individual block RLP files from the blocks directory.

In all other clients, the client first loads the chain.rlp file, then imports the individual blocks. Please make it work like that.

**Comment by SebastianDremo** [comment]
On it, thanks for the issue

**Comment by SebastianDremo** [comment]
#2339 will add this in the next release
