### ISSUE TITLE
Weird return error with eth_call

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#2336]
I got this JSON RPC call data from here: https://infura.io/docs/ethereum/json-rpc/eth-call

I was just messing around trying to find a sample `eth_call` to query the node with and I got an unexpected response from Nethermind.

```
curl -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"eth_call","params": [{"from": "0xb60e8dd61c5d32be8058bb8eb970870f07233155","to": "0xd46e8dd67c5d32be8058bb8eb970870f07244567","gas": "0x76c0","gasPrice": "0x9184e72a000","value": "0x9184e72a","data": "0xd46e8dd67c5d32be8d46e8dd67c5d32be8058bb8eb970870f072445675058bb8eb970870f072445675"}, "latest"],"id":1}' http://archive02.archivenode.io:8545 | jq

{
  "jsonrpc": "2.0",
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "Nethermind.State.InsufficientBalanceException: Exception of type 'Nethermind.State.InsufficientBalanceException' was thrown.\n   at Nethermind.State.StateProvider.SetNewBalance(Address address, UInt256& balanceChange, IReleaseSpec releaseSpec, Boolean isSubtracting)\n   at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer, Boolean isCall)\n   at Nethermind.Facade.BlockchainBridge.CallAndRestore(BlockHeader blockHeader, Int64 number, UInt256 timestamp, Transaction transaction, ITxTracer tracer)\n   at Nethermind.Facade.BlockchainBridge.Call(BlockHeader blockHeader, Transaction transaction)\n   at Nethermind.JsonRpc.Modules.Eth.EthModule.eth_call(TransactionForRpc transactionCall, BlockParameter blockParameter)"
  },
  "id": 1
}
```

The same call performed against Turbo-Geth results in:
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"insufficient funds for gas * price + value"}}
```

**Comment by tkstanczak** [comment]
hey, the response is the same and just the error message have different text. Error messages are not part of the standard (yet) and each client returns a different message.

This call account (0xb60e8dd61c5d32be8058bb8eb970870f07233155) simply has not enough ETH to pay for the gas.

**Comment by MysticRyuujin** [comment]
I figured as much but I thought the error should be clear and concise and not what looks like an unhandled exception 😄 

Not a big deal, just thought I'd bring it to your attention.

**Comment by tkstanczak** [comment]
> I figured as much but I thought the error should be clear and concise and not what looks like an unhandled exception 😄
> 
> Not a big deal, just thought I'd bring it to your attention.

O lol, I did not scroll right. It is a full stack trace, yes - this needs to change

**Comment by LukaszRozmej** [comment]
fixed
