### ISSUE TITLE
Split call environment and transaction environment

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2407]
GasPrice, Originator, BlockHeader can all be in the transaction execution environment.
Other items can be in the call execution environment.

**Comment by tkstanczak** [comment]
![image](https://user-images.githubusercontent.com/498913/97079602-5ad0d500-15ed-11eb-9cc9-d880f3124f6c.png)

**Comment by LukaszRozmej** [comment]
achieved with `TxExecutionContext` and `BlockExecutionContext`
