### ISSUE TITLE
eth_getTransactionReceipt returns null for recently mined transactions

### ISSUE THREAD

**Issue by cag** [NethermindEth/nethermind#2424]
Trying to use Spaceneth Nethermind as a test node, and after sending a transaction with a sealed block, eth_getTransactionReceipt returns `null`. This causes `web3` to hang when trying to `sendTransaction` with it, and also means Truffle migrations can't be run.

Edit: Digging a bit more, it seems that the latest blocks that get sealed and added have no transactions, whereas adding another block somehow makes the previous block's transactions' information available.

**Comment by tkstanczak** [comment]
@LukaszRozmej can you check if this is by any chance the effect of the recent txpool changes?

@cag - can you describe the scenario in more details? potentially send trace level logs? (--log TRACE)
we will investigate - at the moment we have smoke tests deploying an ERC20 contract on each new version which should pick up such issues - maybe something went wrong

**Comment by tkstanczak** [comment]
> Trying to use Spaceneth Nethermind as a test node, and after sending a transaction with a sealed block, eth_getTransactionReceipt returns `null`. This causes `web3` to hang when trying to `sendTransaction` with it, and also means Truffle migrations can't be run.
> 
> Edit: Digging a bit more, it seems that the latest blocks that get sealed and added have no transactions, whereas adding another block somehow makes the previous block's transactions' information available.

hi @cag -> this is fixed now in the latest master

**Comment by cag** [comment]
Ah sweet, I'll test it out soon :)
