### ISSUE TITLE
Nethermind.Launcher is not in the nethermind directory created by unzip

### ISSUE THREAD

**Issue by randyramig** [NethermindEth/nethermind#2425]
Doc bug:  I don't see NetherMind.Launcher but [the directions ](https://nethermind.readthedocs.io/en/latest/download.html)say:

```
start the Nethermind launcher

./Nethermind.Launcher
```

I see Nethermind.Runner, is that what it should be?  Nethermind 1.9.14

**Comment by tkstanczak** [comment]
which package did you download? let me double check our latest packages, doing it now

**Comment by tkstanczak** [comment]
@matilote did we change Nethermind.Launcher to nethermind without updating documentation?

**Comment by tkstanczak** [comment]
![image](https://user-images.githubusercontent.com/498913/97787492-74a08800-1baa-11eb-9967-fd68b49aab0e.png)
this is what I see on Windows

**Comment by tkstanczak** [comment]
hi @randyramig sorry for the trouble, it seems that the Nethermind.Launcher was changed to nethermind and not all the documentation was fixed

![image](https://user-images.githubusercontent.com/498913/97787548-e7116800-1baa-11eb-9f0d-db550754dc3f.png)

**Comment by tkstanczak** [comment]
@matilote the documentation should describe separately versions before change and after change
Please make sure that all the references to ./Nethermind.Launcher are updated properly

**Comment by tkstanczak** [comment]
Fixed, closing.
