### ISSUE TITLE
No ARM64 binaries

### ISSUE THREAD

**Issue by randyramig** [NethermindEth/nethermind#2426]
The directions should really say that only x86/x64 is supported.  I'm running a RasPi4 which is ARM64 and got well into setup before realizing the only [downloads ](https://downloads.nethermind.io/)available are for x86/64

**Comment by tkstanczak** [comment]
hi @randyramig - matilote prepared the arm64 docker image so it is definitely supported

![image](https://user-images.githubusercontent.com/498913/97787432-107dc400-1baa-11eb-93bf-60641761dd8e.png)

**Comment by tkstanczak** [comment]
https://hub.docker.com/r/nethermind/nethermind/tags

**Comment by tkstanczak** [comment]
@randyramig what is your way of downloading? @matilote can we ensure that the version from downloads also has the arm64 libs

**Comment by randyramig** [comment]
I went here: https://downloads.nethermind.io/
I can try the tagged url, so you do support arm64?

**Comment by tkstanczak** [comment]
@randyramig yes we tested arm64 last week

**Comment by matilote** [comment]
I can confirm that arm64 is working via docker, we are currently not supporting arm64 binaries, but I am going to pick it up and build these soon.

**Comment by matilote** [comment]
`Arm64` & `Armv7` binaries are available on https://downloads.nethermind.io/ at `Beta releases` section since 1.10.1-beta version.
