### ISSUE TITLE
Ability to store only receipts from some block onwards

### ISSUE THREAD

**Issue by mpetrunic** [NethermindEth/nethermind#2499]
Having flag that would not store receipt older than block X would greatly increase appeal for running nethermind eth1 node alongside eth2 node. Currently a lot of validators are opting for Infura or some other cloud provider since it expensive to store all receipts while we don't actually need those from before deposit contract.

**Comment by tkstanczak** [comment]
in PR #2500

**Comment by mpetrunic** [comment]
Closing since it's release in 1.9.35. Super thankful for such fast response and implementation :smile:
