### ISSUE TITLE
Receipts barrier logs "bodies" text

### ISSUE THREAD

**Issue by yorickdowne** [NethermindEth/nethermind#2501]
In `src/Nethermind/Nethermind.Synchronization/FastBlocks/ReceiptsSyncFeed.cs`, line 81 currently reads `if(_logger.IsInfo) _logger.Info($"Using pivot {_pivotNumber} and barrier {_barrier} in bodies sync");` and should arguably read `if(_logger.IsInfo) _logger.Info($"Using pivot {_pivotNumber} and barrier {_barrier} in receipts sync");`

**Comment by tkstanczak** [comment]
👍 https://github.com/NethermindEth/nethermind/commit/e4be4b662ee890dbc655e506a9d1ad263b10a077
