### ISSUE TITLE
MaxActivePeers and ActivePeersMaxCount other way round

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2509]
![image](https://user-images.githubusercontent.com/498913/100249739-d0093000-2f34-11eb-85ce-1fc765c86ba4.png)

**Comment by dcposch** [comment]
I just ran into this issue, using env variables:

- `NETHERMIND_NETWORKCONFIG_MAXACTIVEPEERS` results in an invalid config warning.

- `NETHERMIND_NETWORKCONFIG_ACTIVEPEERSMAXCOUNT` works.

**Comment by LukaszRozmej** [comment]
fixed
