### ISSUE TITLE
Our ARM secp256k1 build may not have ECDH enabled

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2521]
[discord] <y4nne> thanks a lot tkstanczak, looking at the logs I think there's an issue with the secp256k1 library:
2020-11-26 21:56:10.4625|Handshake failure in communication with [Node|159.69.89.155:30303||]: System.EntryPointNotFoundException: Unable to find an entry point named 'secp256k1_ecdh' in shared library 'secp256k1'.
I ran sudo apt-get install libsecp256k1-dev because the compiler complained that it was missing that library. After that there were no issues building but maybe I did something wrong there.
Running dotnet test Nethermind.sln  also fails because of this
System.EntryPointNotFoundException : Unable to find an entry point named secp256k1_ecdh in shared library secp256k1.

**Comment by tkstanczak** [comment]
I provided y4nne with the steps to build secp256k1 locally with ECDH from Nethermind secp fork and it helped

![image](https://user-images.githubusercontent.com/498913/100396210-34fb7d80-303c-11eb-92f4-708ac1c17201.png)

**Comment by matilote** [comment]
For future references:
As of now the `libsecp256k.so` file needs to be located at `nethermind/src/Nethermind/Nethermind.Runner/bin/Release/netcoreapp3.1/runtimes/linux-x64/native/` while `librocksdb.so` should be inside either `nethermind/src/Nethermind/Nethermind.Runner/bin/Release/netcoreapp3.1/runtimes/linux-arm/native/` or at `nethermind/src/Nethermind/Nethermind.Runner/bin/Release/netcoreapp3.1`

Working binares for ARM32 of secp256k1 and rocksdb to be found here: https://github.com/NethermindEth/nethermind/tree/master/arm/arm32
