### ISSUE TITLE
Batch BlockByNumber Call Leads to Invalid Block Headers Being Returned

### ISSUE THREAD

**Issue by nisdas** [NethermindEth/nethermind#2525]
A batch `eth_getBlockByNumber` rpc call has lead to invalid headers being returned without their Number being set. Due to this,users running Nethermind are unable to process deposit logs when running them with Prysm(our Ethereum 2.0 client). For  
 `eth_getBlockByNumber` , we only request block headers without their bodies. It would be pertinent to note that some users have had success with restarting their nethermind client to finally get it to return a block header with its `Number` field correctly set. This has been observed as of: https://github.com/NethermindEth/nethermind/releases/tag/1.9.37 . Let me know if more data is required.

**Comment by christianhau** [comment]
I have added the latest flag Sync.FixReceipts to the mainnet.cfg for nethermind, but I still experience the same proble as described above where I cant get the prysm client to connect properly to the nethermind eth1 node. When running the prysm beacon I get the following error message:

[2020-11-28 10:05:30]  INFO gateway: Starting JSON-HTTP API address=127.0.0.1:3500
[2020-11-28 10:05:30]  INFO powchain: Connected to eth1 proof-of-work chain endpoint=http://192.168.1.127:8545
[2020-11-28 10:05:30] ERROR powchain: Unable to process past logs cannot convert block header with nil block number
[2020-11-28 10:05:36]  INFO powchain: Connected to eth1 proof-of-work chain endpoint=http://192.168.1.127:8545
[2020-11-28 10:05:37] ERROR powchain: Unable to process past logs cannot convert block header with nil block number

**Comment by nisdas** [comment]
To add more data to this @christianhau peformed a rpc call to test if the nethermind node was able to give back the correct block.

```
  curl -X POST --header "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0xAAA98C", false],"id":1}' 'http://127.0.0.1:8545'

```

Initial result:
```
{"jsonrpc":"2.0","result":null,"id":1}
```
after a few tries, he finally managed to get the correct block number:
```
 {"jsonrpc":"2.0","result":{"author":"0x829bd824b016326a401d083b33d092293333a830","difficulty":"0xc49cb2800c9ec","extraData":"0x7070796520e4b883e5bda9e7a59ee4bb99e9b1bc010d","gasLimit":"0xbea3bf","gasUsed":"0xbe9907","hash":"....
```

But then it reverted to the earlier no result in the next few tries. Due to this, it is difficult for our client to process the required block headers and data.

**Comment by tkstanczak** [comment]
@christianhau - did you add the Sync.FixReceipts flag with version 1.9.39 or you are still running 1.9.37?
Would you kindly share you config for this 4 items:

Sync.DownloadBodiesInFastSync
Sync.DownloadReceiptsInFastSync
Sync.AncientBodiesBarrier
Sync.AncientReceiptsBarrier

**Comment by tkstanczak** [comment]
@christianhau I guess that this was not enabled: Sync.DownloadReceiptsInFastSync

**Comment by prestonvanloon** [comment]
@tkstanczak we have a new report that this issue exists in version 1.9.41. prysmaticlabs/prysm#7989

**Comment by christianhau** [comment]
I will update once my fresh sync on .41 is complete. I did run it with Sync.FixReceipts flag for 1.9.39.

**Comment by Mr-Lim** [comment]
Synced on .39 and ran into similar error getting Prysm to initialize beacon-node. Wouldn't load ETH1 deposits.

Added flags above, by upgrading to .41 and ran with Sync.FixReceipts. Synced receipts and bodies.

Thought it was fixed!

Prysm now initializes, successfully loads ETH1 deposits, but starts throwing "Unable to process past logs cannot convert block header with nil block number" again after the beacon-node appears to be running:

> ←[90m[2020-11-28 12:57:39]←[0m ←[32m INFO←[0m←[36m powchain:←[0m Processing deposits from Ethereum 1 chain ←[32mdeposits←[0m=20480 ←[32mgenesisValidators←[0m=20470
> ←[90m[2020-11-28 12:57:43]←[0m ←[32m INFO←[0m←[36m powchain:←[0m Processing deposits from Ethereum 1 chain ←[32mdeposits←[0m=20992 ←[32mgenesisValidators←[0m=20982
> ←[90m[2020-11-28 12:57:44]←[0m ←[32m INFO←[0m←[36m powchain:←[0m Minimum number of validators reached for beacon-chain to start ←[32mChainStartTime←[0m=2020-12-01 07:00:23 -0500 EST
> ←[90m[2020-11-28 12:57:44]←[0m ←[33m WARN←[0m←[36m blockchain:←[0m ProcessAttestations routine waiting for genesis time
> ←[90m[2020-11-28 12:57:44]←[0m ←[33m WARN←[0m←[36m blockchain:←[0m Genesis time received, now available to process attestations
> ←[90m[2020-11-28 12:57:45]←[0m ←[32m INFO←[0m←[36m blockchain:←[0m Initialized beacon chain genesis state
> ←[90m[2020-11-28 12:57:45]←[0m ←[32m INFO←[0m←[36m initial-sync:←[0m Genesis time has not arrived - not syncing ←[32mgenesisTime←[0m=2020-12-01 07:00:23 -0500 EST
> ←[90m[2020-11-28 12:57:45]←[0m ←[32m INFO←[0m←[36m p2p:←[0m Started discovery v5 *removed*
> ←[90m[2020-11-28 12:57:45]←[0m ←[32m INFO←[0m←[36m p2p:←[0m Node started p2p server *removed*
> ←[90m[2020-11-28 12:57:50]←[0m ←[31mERROR←[0m←[36m powchain:←[0m Unable to process past headers cannot convert block header with nil block number
> ←[90m[2020-11-28 12:57:57]←[0m ←[32m INFO←[0m←[36m powchain:←[0m Connected to eth1 proof-of-work chain ←[32mendpoint←[0m=http://localhost:8545
> ←[90m[2020-11-28 12:57:57]←[0m ←[31mERROR←[0m←[36m powchain:←[0m Unable to process past headers cannot convert block header with nil block number
> ←[90m[2020-11-28 12:58:03]←[0m ←[32m INFO←[0m←[36m powchain:←[0m Connected to eth1 proof-of-work chain ←[32mendpoint←[0m=http://localhost:8545
> ←[90m[2020-11-28 12:58:03]←[0m ←[31mERROR←[0m←[36m powchain:←[0m Unable to process past headers cannot convert block header with nil block number

Tested with some manual RPC calls, and blocks after 11330000 always return null:

> curl -X POST --header "Content-Type: application/json" --data "{\"jsonrpc\":\"2.0\",\"method\":\"eth_getBlockByNumber\",\"params\":[\"0xACe1d1\", false],\"id\":1}" http://127.0.0.1:8545
> 
> {"jsonrpc":"2.0","result":null,"id":1}

Calls before 11330000 are always fine:

> curl -X POST --header "Content-Type: application/json" --data "{\"jsonrpc\":\"2.0\",\"method\":\"eth_getBlockByNumber\",\"params\":[\"0xACe1d0\", false],\"id\":1}" http://127.0.0.1:8545
> 
> {"jsonrpc":"2.0","result":{"author":"0x5a0b54d5dc17e0aadc383d2db43b0a0d3e029c4c"...

**Comment by tkstanczak** [comment]
@Mr-Lim let us know if resync fixes it - just to confirm that the previous issue was cause by the fact that the initial DB sync was done without the bodies and receipts and then 1.9.41 was running on top of it.

**Comment by Mr-Lim** [comment]
@tkstanczak resync did resolve, and confirm that your description appears to have been the cause. Thanks for your help!

**Comment by nisdas** [comment]
@tkstanczak Just for closure, for users running nethermind, which flags should they run to avoid this issue ?
Only 0.41 onwards with ` Sync.FixReceipts` ? Would this be the only flag required

**Comment by tkstanczak** [comment]
@nisdas users can run just the default mainnet config now (unless they use Teku). For Teku they need to change --Sync.AncientReceiptsBarrier 1

**Comment by nisdas** [comment]
Ok great, thanks a lot :+1:
