### ISSUE TITLE
Some fast syncs fail with invalid block after syncing

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2531]
Reported by @mysticryuujin and @jaoxcz on Discord channel

Dev Solution:
1) add verified mode where every single state item loaded from the database has its Keccak recalculated (we already have it but only for beam sync)
2) test the beam fix mode and allow people to enable both together to heal databases when it happens

**Comment by jao** [comment]
![not me](https://media.giphy.com/media/VJBS3mdO8vB04wyjgL/giphy.gif)

**Comment by tkstanczak** [comment]
heh @jao you do not like the proposed solution? we need it to get more insight into whether it is an EVM memory issue (e.g. maybe some memory corruption leads to wrong numbers being generated by crypto library and leading to invalid state calculation) or it is the corruption of fast synced nodes

**Comment by jao** [comment]
I should probably have explained a little better, but, someone else reported this. It just wasn't me.

**Comment by jaoxcz** [comment]
@tkstanczak "jao from brazil" just got involved by accident here, please igore him...

**Comment by jaoxcz** [comment]
[mainnet.logs.zip](https://github.com/NethermindEth/nethermind/files/5615381/mainnet.logs.zip)
