### ISSUE TITLE
When catching up with a long branch - dump state to DB every X blocks to avoid memory pressure

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2534]
![image](https://user-images.githubusercontent.com/498913/100666907-bc553380-3351-11eb-8d27-2eeaa2b5c10a.png)

**Comment by tkstanczak** [comment]
we have tried some one by one approach but the node simply could not cope with mainnet processing at 8gb ram on the box

**Comment by LukaszRozmej** [comment]
Maybe this branch can be processed in parts of X blocks?

**Comment by tkstanczak** [comment]
I mean, I have tried 1 by 1 block and it still failed on 8GB.
