### ISSUE TITLE
Multiple documentation

### ISSUE THREAD

**Issue by kuzdogan** [NethermindEth/nethermind#2543]
I've been trying to run an existing Parity AuRa node of our [private chain](https://bloxberg.org/) on Nethermind, possibly migrating to Nethermind. I was trying to figure out how to import an existing key and was not able to do so because I was referring to [readthedocs](https://nethermind.readthedocs.io/) docs. I came across a [second documentation](https://docs.nethermind.io/nethermind/guides-and-helpers/validator-setup/aura-validator#config-file) (Gitbook) and found the related info in the second docs. 

Is there a specific reason for multiple documentation? Seems to be confusing to me. Opening the issue as a future reference for others. 

Thanks a lot for your support.

**Comment by tkstanczak** [comment]
@kuzdogan we discussed yesterday decommissioning of the old docs page
We agree with you 100%
