### ISSUE TITLE
Add secure NodeId key management for goerli validators

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#255]
when launching goerli validator in secure mode we need to ask for password and then use the password when signing the blocks

**Comment by 5chdn** [comment]
In memory would be nice. Not sure why geth and pantheon require to have this persistently on disk

**Comment by tkstanczak** [comment]
I am thinking about one of the two
1) launching the app and providing the private key in as a secure input and then keeping it in protected memory
2) keeping the key on hard drive encrypted with salt and then using a password to decrypt it whenever signing the block and removing the key from memory straight after - the password would be introduced the same way as in 1) so I think that 1) is less convenient but more secure as there is only one attack vector - memory and not two - memory and hard drive (both are susceptible to intercepting key inputs on launch)

this is for the nodes that would not have hardware signer connected

**Comment by tkstanczak** [comment]
This is now in progress as part of the key store wallet. In-memory solution to be added.

**Comment by tkstanczak** [comment]
duplicate / related to validator keys
