### ISSUE TITLE
add --nodekey cli flag for specifying node privatekey file

### ISSUE THREAD

**Issue by mFarghaly** [NethermindEth/nethermind#2555]
We're working on adding support for Nethermind in https://kotal.co
we want to be able to start Nethermind node with a pre-defined nodekey to get the same enodeURL everytime the node start.

```
nethermind --nodekey /path/to/nodekey.file
```

thank you

**Comment by mFarghaly** [comment]
@tkstanczak

**Comment by tkstanczak** [comment]
@LukaszRozmej exactly what you suggested today
