### ISSUE TITLE
Uptime metrics calculation

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#2562]
14:00: uptime = 16 min
![image](https://user-images.githubusercontent.com/9356351/101464940-9c200880-393f-11eb-876a-4e9637d520b4.png)
after ~1 hour, uptime = 41 min instead of about 76 min
![image](https://user-images.githubusercontent.com/9356351/101465019-b659e680-393f-11eb-9315-97bb82aae3c2.png)

![image](https://user-images.githubusercontent.com/9356351/101464871-84e11b00-393f-11eb-99ed-0ac88667eec2.png)

**Comment by tkstanczak** [comment]
@MarekM25 is it based on CPU time. Maybe we just change the name?

**Comment by MarekM25** [comment]
> @MarekM25 is it based on CPU time. Maybe we just change the name?

@tkstanczak okay. Maybe just "CPU Time"? :) For me, uptime is misleading.

**Comment by tkstanczak** [comment]
Fixed on Grafana dashboard
