### ISSUE TITLE
Add `health_nodeStatus` RPC handling (/health HTTP request)

### ISSUE THREAD

**Issue by varasev** [NethermindEth/nethermind#2563]
When using RPC node on Nethermind, we don't have an ability to know its health status.

Parity/OpenEthereum has a simple Health API to help sysadmin monitor node's status.

It works in a form of `parity_nodeStatus` RPC request: https://github.com/openethereum/openethereum/blob/ca3a82f3c417aa6e54b41f888198822ab15c004c/rpc/src/v1/impls/parity.rs#L464-L478

Its response can also be got using HTTP request `/api/health`: https://github.com/openethereum/openethereum/blob/ca3a82f3c417aa6e54b41f888198822ab15c004c/rpc/src/lib.rs#L167

It gives `200 OK` status with `null` response result if the node has at least one peer and is not syncing.

If it loses peers, it returns `Node is not connected to any peers.`: https://github.com/openethereum/openethereum/blob/ca3a82f3c417aa6e54b41f888198822ab15c004c/rpc/src/v1/helpers/errors.rs#L514

If it is syncing, the response is `Still syncing.`: https://github.com/openethereum/openethereum/blob/ca3a82f3c417aa6e54b41f888198822ab15c004c/rpc/src/v1/helpers/errors.rs#L169

Please, add the same behaviour to Nethermind, but please also add one more kind of error:

If the node is turned on, but stopped handling blocks for some reason (i.e. it is red in Netstats and its last block number is not being increased), the error should look something like `Stopped handling blocks.`

**Comment by varasev** [comment]
One more condition (for validator nodes only): it should return `Healthy` status (and 200 status code) if the node has at least 1 peer **AND** (is syncing **OR** already fully synced AND producing blocks).

So, if some validator stops producing blocks for some reason (because of some exception/error), but has peers and is fully synced, it should be treated as `Unhealthy` (and return 503 status code). And if the validator has peers and is syncing, it should be treated as `Healthy` (with 200 status code).

**Comment by varasev** [comment]
We also support the issue https://github.com/NethermindEth/nethermind/issues/2623 to include the health checking plugin to the docker image.

**Comment by MarekM25** [comment]
I updated documentation https://docs.nethermind.io/nethermind/ethereum-client/monitoring-node-health 
We will release improvements of health checks in version v1.10.18 :)
