### ISSUE TITLE
InsufficientBalanceException on eth_estimateGas

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2589]

**Comment by tkstanczak** [comment]
I believe this should be a high priority -> one of the most common issues on the public RPC logs that I have seen.

**Comment by LukaszRozmej** [comment]
@kjazgar I belive this is fixed?

**Comment by kjazgar** [comment]
This issue seems to be fixed for eth_estimateGas however this exception is handled wrong for trace_call (https://github.com/NethermindEth/nethermind/pull/3604).
