### ISSUE TITLE
Provide Docker image for nethtest binary

### ISSUE THREAD

**Issue by MariusVanDerWijden** [NethermindEth/nethermind#2599]
It would be pretty cool to have a docker image for the nethtest binary.
This would enable us to automatically update nethermind to the latest release during fuzzing.
Which would increase the chances that regressions in the EVM are caught quickly.

**Comment by tkstanczak** [comment]
hi @MariusVanDerWijden 
shall we wait for our t8n tool implementation first?

**Comment by tkstanczak** [comment]
otherwise we can just add the nethtest

**Comment by MariusVanDerWijden** [comment]
I don't know, for me it would be best to have the nethtest docker as soon as possible. I would say do whatever works for you best

**Comment by SebastianDremo** [comment]
Hey @MariusVanDerWijden, are we talking about this one?
https://hub.docker.com/r/nethermindeth/nethtest

**Comment by MariusVanDerWijden** [comment]
@SebastianDremo Oh wow, thats perfect thanks!
