### ISSUE TITLE
DB grow very fast

### ISSUE THREAD

**Issue by Bombommi** [NethermindEth/nethermind#2605]
I am sorry, i don`t know, this is issue or it`s normal.
Today, 12 hours ago, i full sync Nethermind client as ETH1 endpoint, with minimal --Sync.AncientBodiesBarrier 11052984 --Sync.AncientReceiptsBarrier 11052984
DB size after sync ~117.5gb, after 12 hours it is grow to 122GB! 
4.5 GB fo 12 hours it is normal?

my mainnet.cfg
```

 },
  "Db": {
    "CacheIndexAndFilterBlocks": false
  },
  "Sync": {
    "FastSync": true,
    "PivotNumber": 11460000,
    "PivotHash": "0x788037cc5700aa945f459c8b65227959fa5990c98d5c3e9de3bc6d806de4c45b",
    "PivotTotalDifficulty": "19426245517997356249943",
    "FastBlocks": true,
    "DownloadBodiesInFastSync": true,
    "DownloadReceiptsInFastSync": true,
    "AncientBodiesBarrier": 11052984,
    "AncientReceiptsBarrier": 11052984,
    "UseGethLimitsInFastBlocks": true
  },

```
Maybe you need to change something in the settings? 
i plan to use Nethermind client as ETH1 endpoint with the minimum viable config to serve ETH2 validator

**Comment by tkstanczak** [comment]
Hi @Bombommi - limiting the DB growth requires pruning to be deployed which is being tested for version 1.10 now.

**Comment by Bombommi** [comment]
Hi **tkstanczak** and thank you for answer.
But right now can i somehow reduce the speed of DB growth by using the settings like this or it will break DB for ETH2 validator ?
```
mainnet.cfg
 },
  "Db": {
    "CacheIndexAndFilterBlocks": true,
    "HeadersDbCacheIndexAndFilterBlocks": false,
    "BlocksDbCacheIndexAndFilterBlocks": false,
    "BlockInfosDbCacheIndexAndFilterBlocks": false
  },
```

Сan you give me some advice? Thank you !
9gb day it is very much, i don`t have so much free space.

**Comment by Bombommi** [comment]
I don`t understand how this is working???
```
/dev/sdc       184733024 134368600  50348040  73% /mnt/disks/ssd   Dec 26 0:00:00 UTC 2020
/dev/sdc       184733024 143744088  40972552  78% /mnt/disks/ssd   Dec 28 0:01:00 UTC 2020
/dev/sdc       184733024 153378356  31338284  84% /mnt/disks/ssd   Dec 27 0:00:54 UTC 2020
/dev/sdc       184733024 153643664  31072976  84% /mnt/disks/ssd   Dec 28 17:03:54 UTC 2020
```
Why today, for 17 last hour DB growed only on 280mb ?

**Comment by tmm360** [comment]
I've the same problem, 2.3GB consumed in less than a day on Gnosis Chain full synced. The grow is constant in time, in 6 days the db size increased of 15.9GB. An average of 2.65GB a day. It's really too much, I'm running nethermind v1.12.3.

**Comment by tmm360** [comment]
More data. I've monitored on these what directories grow most. I'm on Gnosis Chain (ex xDai), this is the state of volume mounted to `/nethermind/nethermind_db` from docker two days ago. Expressed values are in kB:

```
2022-01-13 16:36; used 113GB, free 35.4GB

44388692        ./state
26403856        ./receipts
23071444        ./blocks
6347940 ./headers
5368736 ./bloom
1086848 ./blockInfos
224776  ./code
9132    ./witness
9132    ./canonicalHashTrie
2320    ./discoveryNodes
140     ./peers
```

this is now:
```
2022-01-16 01:34; used 119GB, free 29.0GB

50104160        ./state
26595572        ./receipts
23176556        ./blocks
6366328 ./headers
5381724 ./bloom
1090672 ./blockInfos
226868  ./code
10672   ./witness
10672   ./canonicalHashTrie
2172    ./discoveryNodes
144     ./peers
```
In 57h it consumed 6.4GB of disk space, an average of 2,69GB per day. 5.7GB are on `state` directory. It increased of 4.80% in only one day. What I think is that it doesn't prune old states at all when processing new blocks.

**Comment by tmm360** [comment]
I've discovered now that pruning is not enabled by default... I've tried to enable it now, will update if solved.

**Comment by LukaszRozmej** [comment]
Closing old issue, pruning is there. We are also moving to work on different state implementation.
