### ISSUE TITLE
Add health check plugin to Docker image.

### ISSUE THREAD

**Issue by MicahZoltu** [NethermindEth/nethermind#2623]
Adding plugins to docker images is a bit of a pain, and the healthcheck plugin is incredibly useful.  Adding it to the docker images wouldn't increase size by a significant amount and would add a lot of utility to users.

**Comment by tkstanczak** [comment]
@matilote are the plugins 72kb only?
If they do not load automatically (disabled by default) then would be worth to include them.
I remember it was me who insisted on having them separate.

**Comment by matilote** [comment]
@tkstanczak yes, they're very light. I will add `HealthChecks` plugin both to packages and docker images by default.

**Comment by matilote** [comment]
Available since `1.9.51` and `1.10.1-beta` versions.
