### ISSUE TITLE
Initial sync does not complete on 1.10.2-beta

### ISSUE THREAD

**Issue by yorickdowne** [NethermindEth/nethermind#2648]
NM 1.10.2-beta, compiled from source and running in Docker, on Ubuntu 20.04 LTS

Initial sync went well until it reached around 98% state. At that point, it stopped adding to state. Blocks were never fully synced and always stayed exactly 32 blocks behind.

Nethermind was shut down at this point, restarted once, then shut down again, then finally started again to get data for this issue.

I did not capture logs for the first restart. What I saw was that Nethermind stayed 32 blocks behind, state was progressing very slowly - possibly in sync with each block that was downloaded, not entirely sure of correlation - and branch was shown at 0.00% instead of the 97/98-ish it was before Nethermind was restarted.

After the days-long pause and restart, Nethermind catches back up to near head, and then stays 32 blocks behind again. Once it's close, state sync resumes. As before, state sync does not complete, and branches shows 0.00%.

Logs for initial sync attached. Also attaching logs for the second restart. ZIPed because of size.

[nm-beta-sync-logs.zip](https://github.com/NethermindEth/nethermind/files/5795688/nm-beta-sync-logs.zip)

**Comment by tkstanczak** [comment]
@MarekM25 @LukaszRozmej it seems that we need to revert this change

**Comment by tkstanczak** [comment]
have a look at the logs

**Comment by yorickdowne** [comment]
This may be an issue with insufficient IOPS. This VPS is slow at 3,000 read / 1,000 write. It may never be able to finish sync unless IO is improved in Nethermind. For reference, Geth syncs fine.

I am now running a sync from scratch test on a local machine with 16k3 read / 6k1 write, and 1.10.7-beta. Will update when I have results.

**Comment by yorickdowne** [comment]
VPS test stopped after 3 days. IOPS is not sufficient to get branches in the time between state root changes. This VPS has 3k read / 1k write. Better than HDD, but pretty low for SSD.

Logs attached. One that greps for just state root with -B5 and -A3, to show the branches progress or lack thereof, and one that has the log after restarting on Nethermind 1.10.5 as 1.10.4's memory leak was causing issues.

[nm-vps-low-iops-logs.zip](https://github.com/NethermindEth/nethermind/files/5845206/nm-vps-low-iops-logs.zip)

**Comment by Legogris** [comment]
I get the same thing on a fresh fast sync tracing node (DownloadReceiptsInFastSync=true) on 1.9.52:

Indefinitely stuck on 11638122 / 11638154 (which is a bit odd since earlier in the sync it was aware of later blocks.

It is not an IOPS problem. Disk is almost completely idle, rarely goes over 1% (30GB RAM vs 13GB on disk; everything still fits in cache).  CPU fairly stable at ~15%.

[Truncated log](https://gist.github.com/Legogris/68d17b88e972c0e8d9ce8c610b4f79ea)

**Comment by tkstanczak** [comment]
We will push 1.10.7 as a main version soon. Something inconsistent on
1.9.52+ . Maybe we should withdraw all 1.9.x versions above 1.9.47

**Comment by Legogris** [comment]
@tkstanczak I tried just reverting #2633 from the same instance - will see what gives, progressing sync for now.

**Comment by tkstanczak** [comment]
@Legogris @yorickdowne we believe that there was a deadlock in the fast sync switch.
Have you tried syncing with 1.10.17?

**Comment by Legogris** [comment]
@tkstanczak Upgraded to 1.10.17 4-5 days ago.

It's no longer stuck 32 blocks behind, but now the state sync progresses extremely slowly (between 5~100 kBps, with periods of no data). 

MaxPeers is set to 100 and connected sync peers vary between 60~90.

I notice in the prometheus metrics that:

* `nethermind_blocks` is still 0
* `nethermind_fast_headers` is a constant `11710000` (which is also the configured `PivotNumber`
* `nethermind_fast_bodies` and `nethermind_fast_receipts` are both 0
* There's a lot of disconnects. (average ~300/min `client_quitting_disconnects`, ~100/min `too_many_peers_disconnects`)

**Comment by tkstanczak** [comment]
@Legogris was it a temporary issues? If this is after restarting a node that has been previously synced then the catch up will show very 'slow' numbers because it spends more time reading the database rather than writing. But there is less to load.

**Comment by Legogris** [comment]
It's still progressing, very very slowly. State got synced yesterday, at branches now. Not sure if it will ever catch up at this rate. I can't fully exclude something's odd on this side, but I do have otherwise identical already synced nodes that are running just fine.

**Comment by guijun** [comment]
1.10.72 , docker, mainnet and goerli .

2021-06-15 10:07:02.8336|Changing state StateNodes to FastSync, StateNodes at processed:0|state:0|block:0|header:4972564|peer block:4972567
2021-06-15 10:07:02.8336|Sync mode changed from StateNodes to FastSync, StateNodes
2021-06-15 10:07:03.8368|Changing state FastSync, StateNodes to StateNodes at processed:0|state:0|block:0|header:4972565|peer block:4972567
2021-06-15 10:07:03.8368|Sync mode changed from FastSync, StateNodes to StateNodes
2021-06-15 10:07:07.7628|Peers | with known best block: 49 | all: 49 |
2021-06-15 10:07:14.2938|State Sync 00.04:49:50 | ~54.93 % | 2476.78MB / ~4509.00MB | branches: 0.00 % | kB/s:     0 | accounts 2285522 | nodes 28921754 | diagnostics: 0.182.05ms
2021-06-15 10:07:16.2303|State Sync 00.04:57:30 | ~54.93 % | 2476.78MB / ~4509.00MB | branches: 0.00 % | kB/s:     0 | accounts 2285522 | nodes 28921754 | diagnostics: 5.182.61ms
2021-06-15 10:07:17.8911|Changing state StateNodes to FastSync, StateNodes at processed:0|state:0|block:0|header:4972565|peer block:4972568
2021-06-15 10:07:17.8911|Sync mode changed from StateNodes to FastSync, StateNodes
2021-06-15 10:07:18.8951|Changing state FastSync, StateNodes to StateNodes at processed:0|state:0|block:0|header:4972566|peer block:4972568
2021-06-15 10:07:18.8951|Sync mode changed from FastSync, StateNodes to StateNodes
