### ISSUE TITLE
Verify libraries list in the plugins folder

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#2656]
![image](https://user-images.githubusercontent.com/9356351/104712825-58c96e80-5723-11eb-8568-289818da4782.png)
I think we miss some dlls in plugins folder, which we release. For example, for Baseline and Vault I expect to have: Nethermind.Baseline.Plugin.dll, Nethermind.Vault.dll, provide.dll.

We should check if plugins work correctly and add missing dlls if it is needed.

**Comment by MicahZoltu** [comment]
`Nethermind.Baseline` plugin has a dependency on `Nethermind.Cli` plugin, but the latest two releases include `Baseline` but not `Cli` so it fails on startup.
