### ISSUE TITLE
Is the sample configuration correct?

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2717]
![image](https://user-images.githubusercontent.com/498913/106361248-d04af080-6314-11eb-8a64-2baa2e28ebb8.png)

**Comment by marcindsobczak** [comment]
There are some differences between version above and from Nethermind.Runner/configs/mainnet.cfg (e.g. in Init MemoryHint)
I can update it manually right now and add auto-updating this to Nethermind.Gitbook with the next upgrade. Do it?
