### ISSUE TITLE
Obscure "VM execution error." message

### ISSUE THREAD

**Issue by aliveli186** [NethermindEth/nethermind#2718]
When I make a call to estimate the gas of a contract function with specific arguments which normally will fail the function due to "required" statement in the contract, Nethermind throws an exception: "VM execution error." and nothing more while Geth on the other hand also returns the message in the "required" statement which the creator specified as the reason of the failure.
Is there a way to get the message of why the transaction failed like Geth client?

**Comment by tkstanczak** [comment]
Hi @aliveli186 , yes that should be displayed, we may have lost this after some recent changes.

**Comment by tkstanczak** [comment]
We need to add a test (like truffle deployment) with a simple revert that would display the error message.

**Comment by aliveli186** [comment]
Any estimated time of the implementation?

**Comment by tkstanczak** [comment]
Not prioritized yet, will discuss on Monday.

**Comment by LukaszRozmej** [comment]
This was fixed, reverts are shown in eth_estimateGas for some time now.
