### ISSUE TITLE
Runner tests do not seem to be running as part of the code coverage / test checks.

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2723]
![image](https://user-images.githubusercontent.com/498913/106385267-5889ce00-63c7-11eb-87f6-f52dee5e8539.png)

**Comment by SebastianDremo** [comment]
#2730 brings back runner tests to standard workflow checks

**Comment by tkstanczak** [comment]
That was not done properly. The change had no effect and was not tested properly.
