### ISSUE TITLE
debug_traceTransaction Tracer Support

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#2757]
Nethermind doesn't seem to support the "tracer" parameter?

Example:

```
curl -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1,"method":"debug_traceTransaction","params":["0xc5b8151a3e5e8374f0c980764e0e3825cddf59492d6440ce3d6cf04061399464",{"tracer":"{r:\"hello world!\",step:function(log,db){},fault:function(log,db){},result:function(ctx, db){return this.r;}}"}]}'
```

With Geth or Turbo-Geth this would result in:
```
{"jsonrpc":"2.0","id":1,"result":"hello world!"}
```

With Nethermind, it simply returns the full debug for the transaction given?

Is this expected?

**Comment by tkstanczak** [comment]
yes, this is a JavaScript tracer definition? not sure what language that is in but seems like pretty hard to reproduce the exact support for javascript?

**Comment by MysticRyuujin** [comment]
So basically it's another "this isn't standardized" problem? lol

**Comment by tkstanczak** [comment]
when I saw this one for the first time I thought it was one hell of a door that I will not open
we would need to have some kind of very well maintained javascript interpreter in C#. We have one but it is not supporting everything.

I will ask Geth team during the next standards call.

**Comment by tkstanczak** [comment]
@MysticRyuujin we discussed it on JSON RPC standards call and probably not something that we want to add as even the Geth team has regrets about it
