### ISSUE TITLE
Abrupt slow down of sync state process.

### ISSUE THREAD

**Issue by riccardope** [NethermindEth/nethermind#2775]
I started syncing my eth node 2 days ago, and initially it was processing 1% of states every 10 minutes, downloading an average of 1000kb/s. Once the node state syncing arrived at 96% I started experiencing a huge decrease in speed. I now process 1% every 7 course and nethermind downloads 4kb/s of state data.

**Comment by tkstanczak** [comment]
Hi @riccardope it is normal towards the end of the sync
Please read more here:
https://docs.nethermind.io/nethermind/ethereum-client/sync-modes#fast-sync

At the last stages of the sync the node will be repeatedly displaying the branch sync progress and changing the block number to which it tries to catch up. This stage should take between 30 minutes and two hours. If it lasts much more then it is possible that you will not be able to catch up with the network progress.

**Comment by tkstanczak** [comment]
Actually you say 2 days?
This seems slow. What is your IO speed?

**Comment by riccardope** [comment]
random-write: (groupid=0, jobs=1): err= 0: pid=73968: Wed Feb 10 21:19:48 2021
  write: IOPS=5740, BW=22.4MiB/s (23.5MB/s)(1921MiB/85673msec); 0 zone resets

My IOPS is 5740, which is quite strange since I am renting a good digital ocean VPS with 8gb ram and 4 cores.

**Comment by riccardope** [comment]
I'm continuing to receive this log:
Changing state StateNodes to FastSync, StateNodes at processed:0|state:0|block:11830178|header:11830897|peer block:11830900 

So maybe my node is stuck at block 11830178?

**Comment by riccardope** [comment]
@tkstanczak

**Comment by tkstanczak** [comment]
@riccardope have we moved this to discord or is it still unsolved?

**Comment by LukaszRozmej** [comment]
This looks stale, please reopen if still relevant
