### ISSUE TITLE
Check docker image behaviour (core dump on RHEL 1.13 docker)

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#278]
fedora, 4.10.x kernel, docker 1.18.x - all works
Rhel 3.10.x, 1.13 docker - won't work (core dump error)
so we either suspect docker version, or kernel version

**Comment by JohnnySheffield** [comment]
Thank you for the issue, i'm tagging my colleague @dec- to provide additional info if required.

**Comment by JohnnySheffield** [comment]
Logs from the pod:
```

Reading config file from configs/goerli.cfg
--
  | Enter 'e' to exit
  | 2018-11-22 12:32:52.6761\|INFO\|1\|Runner.RunnerAppBase\|Running Nethermind Runner, parameters:
  | {
  | "JsonRpcEnabled": false,
  | "DiscoveryEnabled": true,
  | "SynchronizationEnabled": true,
  | "NetworkEnabled": true,
  | "ProcessingEnabled": true,
  | "PeerManagerEnabled": true,
  | "RunAsReceiptsFiller": false,
  | "IsMining": false,
  | "HttpHost": "127.0.0.1",
  | "HttpPort": 8345,
  | "DiscoveryPort": 30312,
  | "P2PPort": 30312,
  | "ChainSpecPath": "chainspec/goerli.json",
  | "BaseDbPath": "nethermind_db/goerli",
  | "LogFileName": "goerli.logs.txt",
  | "GenesisHash": "0xfa57319d09fd8a32faaf18d338c8a925a5a7975285bf29ecd024e083cba8abb1",
  | "JsonRpcEnabledModules": [
  | "Clique",
  | "Eth",
  | "Net",
  | "Web3",
  | "Db",
  | "Nethm",
  | "Debug",
  | "TxPool"
  | ],
  | "RemovingLogFilesEnabled": false,
  | "LogPerfStatsOnDebug": false,
  | "ReceiptsFillerStart": 0,
  | "ReceiptsFillerEnd": 1,
  | "ObsoletePendingTransactionInterval": 15,
  | "RemovePendingTransactionInterval": 600,
  | "PeerNotificationThreshold": 20
  | }
  | \|
  | 2018-11-22 12:32:52.7090\|INFO\|1\|Runner.Runners.EthereumRunner\|Initializing Ethereum\|
  | 2018-11-22 12:32:52.7424\|INFO\|1\|Runner.Runners.EthereumRunner\|Loading chain spec from chainspec/goerli.json\|
  | 2018-11-22 12:32:53.0661\|INFO\|1\|Runner.Runners.EthereumRunner\|DB WriteBufferSize: 67108864\|
  | 2018-11-22 12:32:53.0661\|INFO\|1\|Runner.Runners.EthereumRunner\|DB WriteBufferNumber: 6\|
  | 2018-11-22 12:32:53.0661\|INFO\|1\|Runner.Runners.EthereumRunner\|DB BlockCacheSize: 67108864\|
  | 2018-11-22 12:32:53.0661\|INFO\|1\|Runner.Runners.EthereumRunner\|DB CacheIndexAndFilterBlocks: True\|
  | 2018-11-22 12:32:53.0939\|INFO\|1\|Db.DbOnTheRocks\|Using database directory nethermind_db/goerli/blocks\|
  | Illegal instruction (core dumped)

```

**Comment by tkstanczak** [comment]
from log position it would suggest RocksDB failure to launch the DB on this docker version - @spetz will check this for you

**Comment by spetz** [comment]
Hi @JohnnySheffield, Docker images have been added to the repository root (on master branch).
You shall find 2 images:
* `Dockerfile` - builds `Nethermind.Runner` using the source code from a cloned repository.
* `Dockerfile_full` - builds `Nethermind.Runner` without a need of cloning the repository (can be run anywhere, as it will clone a repository during the first step).

Please let me know whether you succeeded to build them and if the problem still occurs on RHEL.

**Comment by JohnnySheffield** [comment]
Hi @spetz, thanks for the docker files, will try to build the image soon 👍

**Comment by Dec-** [comment]
The same error appear on RHEL server.

**Comment by tkstanczak** [comment]
Hi, seems that we missed the submodules when cloning the repo in dockerfile, checking with @spetz if it can be resolved quickly. Sorry for the trouble.

**Comment by tkstanczak** [comment]
@Dec , @spetz says that there should be no problem if you run Dockerfile_full as the default one requires you to clone repo with --recursive (to get the submodules)

**Comment by spetz** [comment]
@Dec- I've just updated the `Dockerfile` (added a required command to update submodules), please give it a try now.

**Comment by Dec-** [comment]
Look's good on Fedor! Tomorow i will do more tests on RHEL.

Thx.

**Comment by spetz** [comment]
Great to hear!

**Comment by spetz** [comment]
@Dec- I did a test on RHEL 7.6 (3.10.0-957) using the latest version of Docker CE and the runner works just fine. So it seems, that the issue could be related to Docker, not the OS kernel.

**Comment by tkstanczak** [comment]
@Dec have you managed to get the node running?
