### ISSUE TITLE
How easy to provide release notes before pressing release?

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2786]
![image](https://user-images.githubusercontent.com/498913/107817719-74e61d00-6d6e-11eb-81ac-aab5f413b7a3.png)

**Comment by matilote** [comment]
We would need to provide a single line string input, each note line separated, then parse the input and pass it down. Feels like a waste of time, to be honest.

**Comment by LukaszRozmej** [comment]
I don't think its worth pursuing, marking release stable is manual process, we can add release note then.
