### ISSUE TITLE
Investigate the report on problems with overriding JSON RPC issues:

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2810]
[discord] <Raid> Ok, just letting you know
Also on the new version I can't suppress the JSON RPC logging for some reason
 
       <logger name="JsonRpc.*" minlevel="Off" writeTo="file-async"/>
       <logger name="JsonRpc.*" minlevel="Off" writeTo="auto-colored-console-async"/>
       <logger name="JsonRpc.*" final="true"/>
Maybe I missed something in the NLog file

**Comment by LukaszRozmej** [comment]
Must have been some issue on your setup. Works fine for me.
