### ISSUE TITLE
When running CI pipeline Docker image should only be built once

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2839]
I would like to revisit dependencies between:

Docker image building
Truffle test
Vault test
NethTest upload

**Comment by tkstanczak** [comment]
We are using 6 days old truffle test for smoke testing current version?
![image](https://user-images.githubusercontent.com/498913/109863955-2d123180-7c5a-11eb-9c2f-5d049707c2fc.png)

**Comment by kamilchodola** [comment]
@rubo 
Do You know something about this? You were refactoring quite a lot of things recently on Actions so maybe this is already solved?

**Comment by rubo** [comment]
@kamilchodola Never looked at Truffle tests. At a glance, they can be improved. Vault is obsolete and will be removed soon.
