### ISSUE TITLE
[NDM] installation instructions for openSUSE

### ISSUE THREAD

**Issue by aspiers** [NethermindEth/nethermind#2844]
https://docs.nethermind.io/nethermind/nethermind-datamarketplace/setting-up-ndm-for-manual-testing currently only lists Linux installation instructions for Ubuntu.  On openSUSE, the corresponding command for installing dependencies is:

    sudo zypper install libsnappy-devel glibc-devel

**Comment by SebastianDremo** [comment]
Added to doc page, thank you.
