### ISSUE TITLE
[NDM] installation instructions for Ubuntu

### ISSUE THREAD

**Issue by aspiers** [NethermindEth/nethermind#2845]
There are a few typos in https://docs.nethermind.io/nethermind/nethermind-datamarketplace/setting-up-ndm-for-manual-testing:

- The Ubuntu dependencies installation command should say `libc6` not `lic6`
- The word `dependecies` is missing an `n` in both the Ubuntu and Mac OS sections :-)

Are the docs on GitHub?  If so I could submit PRs which would be quicker than reporting typos here.

**Comment by matilote** [comment]
Thanks, just fixed those. Link to docs repo -> https://github.com/NethermindEth/docs
