### ISSUE TITLE
netzermind.launcher doesnt continue, stucks

### ISSUE THREAD

**Issue by Chris1992GR** [NethermindEth/nethermind#2860]
hello,

i need help. the launcher stucks when i try to sync with goerli. 
he asks me :

? Do you want to configure ethstats registration now? No
EthStats configuration process will be skipped.

and after taht there happens nothing.

i configuredn json file and opened port 8545 for everyone, alos the oder 2 ports.
i dont know what could be the pronblem.

Thank you

**Comment by tkstanczak** [comment]
Hi @Chris1992GR , please try running the ./Nethermind.Runner directly (launcher is just there to help you with some minimal interface)

./Nethermind.Runner --config goerli

**Comment by tkstanczak** [comment]
@Chris1992GR -> https://discord.gg/k3k7tyPj and reach out to tkstanczak for live support :)
