### ISSUE TITLE
'eth_getLogs' with 'fromBlock', 'toBlock' and 'address' filters returns all logs since 'fromBlock'

### ISSUE THREAD

**Issue by jaensen** [NethermindEth/nethermind#2871]
Hi!  

I send the following request to the websocket rpc endpoint and get different results when doing this locally vs. on rpc.xdaichain.com:
```json
{
	"jsonrpc":"2.0",
	"id":12,
	"method":"eth_getLogs",
	"params":[{
		"fromBlock":"0xbf2f32",
		"toBlock":"latest",
		"topics":[
			"0xe60c754dd8ab0b1b5fccba257d6ebcd7d09e360ab7dd7a6e58198ca1f57cdcec",
			"0x000000000000000000000000de374ece6fa50e781e81aac78e811b33d16912c7",
			null
		],
		"address":"0x29b9a7fbb8995b2423a71cc17cf9810798f6c543"
	}]
}
```
When executed locally (either with v1.10.27-0 or v1.10.32-0) it looks like I get all logs since "fromBlock" as result (52MB) and the other filters are ignored:  
![getLogs_unfiltered_response](https://user-images.githubusercontent.com/4954577/110385791-ae553400-805f-11eb-83c5-8cf8f070917b.jpg)

However if I do the same against wss://rpc.xdaichain.com/wss I get a filtered response weighing only 115 KByte:
![getLogs_correct_response](https://user-images.githubusercontent.com/4954577/110385815-b57c4200-805f-11eb-8d59-f6a7da28acec.jpg)

I already tried removing the "bloom" directory and enabled migrate as suggested in #1980 but it had no effect on the issue.  

Another Issue is that I don't get a receipt for transactions sent with 'eth_sendRawTransaction'.
The attached images show the json-rpc calls for the public and my local node.  

wss://rpc.xdaichain.com/wss:
![nethermind_wsrpc_xdaichain_com](https://user-images.githubusercontent.com/4954577/110385237-ff185d00-805e-11eb-8f52-1318ec723768.jpg)  

localhost:  
![nethermind_wsrpc_no_receipt](https://user-images.githubusercontent.com/4954577/110385290-0e97a600-805f-11eb-88b8-70505bf9d808.jpg)

I used the same database as in #2868 but with binaries built from source (master).

Thanks in advance!

**Comment by tkstanczak** [comment]
@LukaszRozmej this touches both AuRa and Bloom filters so no better person than you to look at this

**Comment by LukaszRozmej** [comment]
Hi @jaensen:
I've synced a node and ran your eth_getLogs query, got 113KB response
[local.zip](https://github.com/NethermindEth/nethermind/files/6124864/local.zip)

got same response from rpc.xdaichain.com.

As for eth_sendRawTransaction, your transaction was mined here: https://blockscout.com/xdai/mainnet/tx/0xc3a6dd78c16c464f5f23e73f4c33053db2a08641355ccbc9e2fd862f23377fb0/internal-transactions

And I see proper responses in the screen you provided from rpc.xdaichain.com:
![image](https://user-images.githubusercontent.com/12445221/110830050-180c5280-8299-11eb-9525-af99469dd5c4.png)

In the screen from localhost the time part was cut so its hard to say if the request wasn't too early. But we see that later subscription for newHeads is working so it should get the receipt after it got the block processed.

**Comment by jaensen** [comment]
Thanks for your investigating. I will look into it this weekend and double-check my code.

**Comment by jaensen** [comment]
Hi! I updated to 1.10.41 and web3js now understands the receipts correctly.
The other issue (unfiltered response) persists (kept the DB). I try to build a small case to reproduce the behavior and also sync another node with 1.10.41 to see if that makes a difference.

**Comment by jaensen** [comment]
Turns out that the error with the big response was a bug on my side. I had problems with concurrency and passed an empty parameter under rare circumstances. It is quite possible that the other bug stems from the same source as well. Haven't experienced it since I added a fix to my code.

Thanks for looking into it!
