### ISSUE TITLE
Change ModuleType.cs to support adding new modules

### ISSUE THREAD

**Issue by SebastianDremo** [NethermindEth/nethermind#2908]
Right now we have an enum with all of the available json rpc modules. 
When we want to add a new module type we either add new value into it or somehow add it on the runtime. 

Need to change it for Nethermind plugins which add new json rpc modules.

**Comment by MicahZoltu** [comment]
This is particularly impactful to plugins, because plugins **cannot** add a new value into the `ModuleType` enum.  It can be hacked around by using a raw number, but this means the user needs to enable the module via `--JsonRpc.EnabledModules eth,web3,100` rather than a meaningful name.
