### ISSUE TITLE
Broken MacOs library for Rocks (unverified source)

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2951]
![image](https://user-images.githubusercontent.com/498913/113635732-100dbb80-9669-11eb-9d9a-4a0344e77ebf.png)

![image](https://user-images.githubusercontent.com/498913/113635874-56631a80-9669-11eb-8f8a-3112de51e155.png)

**Comment by tkstanczak** [comment]
not sure why it talks about Brave :)
maybe this is something local for me (some mess)

**Comment by LukaszRozmej** [comment]
Maybe we need to sign it?

**Comment by LukaszRozmej** [comment]
we are using official build at the moment.
