### ISSUE TITLE
Dumping connection logs on Debug logger mode takes too long at the shutdown

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#296]

**Comment by tkstanczak** [comment]
A few options to discuss:
1) save it in a separate file per node on an ongoing basis
2) only dump the data when configuration specifically says so or when closing with a special keywork
  * this may actually be cool where depending on the way we close we send different shutdown calls
3) dump the data on an debug_dumpConnectionDetails RPC call

**Comment by tkstanczak** [comment]
**2018-11-28 14:47:59.8940**|INFO|46|Network.Discovery.DiscoveryApp|Discovery shutdown complete.. please wait for all components to close|
**2018-11-28 14:52:08.9736|**INFO|25|Network.PeerManager|Peer Manager shutdown complete.. please wait for all components to close|

**Comment by glesniakiewicz** [comment]
Changed logic significantly:
- capture of node events enabled by default - controlled by CaptureNodeLatencyStatsEventHistory in StatsConfig
- session logging moved to separate component PeerSessionLogger
- session logs are placed in separate files under log dir \ logEvents directory
- while closing with e, only general session stats are logged - generalStats.log file
- while closing with q, session stats for each node (with more events then NodeDiscovered) are logged in separate files with nodeId as file name
- additionally session stats log can be triggered while app is running with debug_dumpPeerConnectionDetails json rpc method call included in DebugModule
