### ISSUE TITLE
Experiment with adding compression to JSON-RPC

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#3008]
When dealing with large debugs, adding compression to them can save literally GB in bandwidth.

E.G. the `debug_traceTransaction` of `0x7a97e47f9399b46c3e8ee444778763a4f331fa182b5c28c1ba98709721f71f7d` will result in a stream that is `2849M` in size. A simple gz of that output is `44M`

Luk asked me to make an issue to experiment.

> MysticRyuujin — Today at 10:30 AM
appears to work now
It's just streaming out to my system
lmao that's a 2849M stream, gzip into 44M
luk — Today at 10:35 AM
I could add compression to JSON RPC
MysticRyuujin — Today at 10:36 AM
I think that would make sense honestly, but idk how well zipping while streaming works if there's no buffer
maybe it works, idk :slight_smile:
luk — Today at 10:36 AM
we can experiment, can you add issue?
MysticRyuujin — Today at 10:36 AM
Sure

**Comment by tkstanczak** [comment]
fantastic idea

**Comment by LukaszRozmej** [comment]
Added to http, webcockets can get compression with .Net 6: https://github.com/dotnet/runtime/issues/31088
