### ISSUE TITLE
Too many peers stored for long running nodes

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#302]
After restarting a peer that has been running for a month we experienced a significant performance degradation.

It was most likely caused by the node trying to connect to its 200k peers. Deleting peers and discoveryNodes DBs helped.

**Comment by glesniakiewicz** [comment]
Added configurable limits for persisted nodes and candidate peers
defaults:
        public int MaxPersistedPeerCount { get; set; } = 2000;
        public int MaxCandidatePeerCount { get; set; } = 10000;

persisted peers - connected and validated peers (proper p2p, same chain id) - cleanup by worst reputation
candidate peers - all discovered peers (up, down, any network etc) - cleaning logic removes first incompatible nodes (wrong p2p, other chain id, etc) and then nodes with the worst reputation
