### ISSUE TITLE
Rayonism: missing success field in consensus_setHead

### ISSUE THREAD

**Issue by paulhauner** [NethermindEth/nethermind#3026]
Hi there :wave: :relaxed: I've fixed the issue with Lighthouse sending an incorrect `logs_bloom` value and have been able to make progress. Thanks for reporting that on Discord.

I'm working with the `consensus_setHead` call and Nethermind seems to be missing the `success` field from [the docs](https://github.com/ethereum/rayonism/blob/master/specs/merge.md#set-head):

### Nethermind

```
Request:
{
  "jsonrpc": "2.0",
  "method": "consensus_setHead",
  "params": [
    "0xc0caf8693193f5ba1e3f04368377ad63884468b13d72e4b08ade49a9e1203f6f"
  ],
  "id": 42
}

Response:
{
  "jsonrpc": "2.0",
  "result": {
    "value": false
  },
  "id": 42
}
``` 

### Geth

```
Request:
{
  "jsonrpc": "2.0",
  "method": "consensus_setHead",
  "params": [
    "0xc0caf8693193f5ba1e3f04368377ad63884468b13d72e4b08ade49a9e1203f6f"
  ],
  "id": 42
}

Response:
{
  "jsonrpc": "2.0",
  "id": 42,
  "result": {
    "success": true
  }
}
```

**Comment by tkstanczak** [comment]
thanks @paulhauner , looking into it

**Comment by tkstanczak** [comment]
@paulhauner a fix is on its way but I need @LukaszRozmej to review it when he is up so you should have a new version in around 3 hours if that is ok

#3027

**Comment by paulhauner** [comment]
No worries at all, the error isn't causing any functional issues on our end anyway.

**Comment by paulhauner** [comment]
FYI, the script I used to produce the output in the issue description is here: https://github.com/protolambda/mergenet-tutorial/pull/17
