### ISSUE TITLE
Websockets eth methods missing

### ISSUE THREAD

**Issue by yorickdowne** [NethermindEth/nethermind#3056]
Nethermind 1.10.70 from docker image, with websockets enabled and no `--JsonRpc.EnabledModules`, taking the defaults. Also tried with `--JsonRpc.EnabledModules Net,Eth,Web3,Subscribe`

The `eth_getBlockByNumber` and `eth_getTransactionCount` methods are shown as not supported on websockets.

Nethermind logs these errors:
```
eth_1           | 2021-05-13 12:16:35.5089|Initializing WebSockets for client: ''.
eth_1           | 2021-05-13 12:16:35.6442|Waiting for peers... 2s
eth_1           | 2021-05-13 12:16:35.6517|Error when handling ID 1, eth_getBlockByNumber(latest,False) | {"jsonrpc":"2.0","error":{"code":-32601,"message":"Method eth_getBlockByNumber is not supported"},"id":1}
eth_1           | 2021-05-13 12:16:35.6606|Error when handling ID 2, eth_getTransactionCount(0x05dec0ea0bac10333149b8860720957a3ff2f85a,pending) | {"jsonrpc":"2.0","error":{"code":-32601,"message":"Method eth_getTransactionCount is not supported"},"id":2}
eth_1           | 2021-05-13 12:16:35.6710|Closing WebSockets for client: ''.
```

**Comment by tkstanczak** [comment]
@matilote @LukaszRozmej this may explain the trouble that Edgar had?

**Comment by LukaszRozmej** [comment]
> @matilote @LukaszRozmej this may explain the trouble that Edgar had?

No, MEV branch is now quite behind master. 
This works fine from source and package for me gonna check docker.

**Comment by LukaszRozmej** [comment]
Works ok on my docker in windows. Can you share whole logs?

**Comment by yorickdowne** [comment]
Closing this, cannot reproduce now. I likely missed a `docker-compose build --pull` and was on an old version. Apologies, and thank you for taking the time!
