### ISSUE TITLE
eth_getTransactionByHash wrong V property and missing chainId

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#3057]
`Version      : 1.10.67-0-cff76f48d-20210513`

Repro:
```
curl -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":1,"method":"eth_getTransactionByHash","params":["0xc7a20d6fc41b358c2039f0b0aa0b650d2a5876d82960a45a6a18eb84e13fde6b"]}'
```

`"v": "0x1b"` this is wrong, should be `"v": "0x0"`

`chainId` property is missing entirely.

Also, `type` field in a legacy transaction is `0x00` but every other client just returns `0x0`

**Comment by MysticRyuujin** [comment]
bump

**Comment by fvictorio** [comment]
Btw, this also seems to happen in the baikal network with EIP-1559 txs

**Comment by tkstanczak** [comment]
@marcindsobczak @LukaszRozmej
