### ISSUE TITLE
Goerli-Testnet observation

### ISSUE THREAD

**Issue by roninkaizen** [NethermindEth/nethermind#3121]
![grafik](https://user-images.githubusercontent.com/17592883/121882484-e0d29500-cd10-11eb-98a5-afcced2270f8.png)

feel free to contact me-
it looks as if something is wrong, and if i could help with this,
just give me a sign-
as it seems to me, some empty block also occured

**Comment by LukaszRozmej** [comment]
Yes, we are filling blocks way batter now with latest version: https://goerli.etherscan.io/address/0x4c2ae482593505f0163cdefc073e81c63cda4107#mine

There will be one more small change in upcoming releases, but I consider this good for now.
