### ISSUE TITLE
nethtest: blockhash doesn't match other clients

### ISSUE THREAD

**Issue by MariusVanDerWijden** [NethermindEth/nethermind#3201]
So I finally know what the difference/problem is between nethermind and the others.
Nethermind returns keccak(blocknumber) as blockhash for every number.
Others return keccak(blocknumber) only for "available blocks" which means it returns keccak(blocknumber) only for blocknumber 0, all others are returned as 0
I think your TestBlockhashProviders should implement this logic too: https://github.com/NethermindEth/nethermind/blob/1d2f21ba04d4fd14cada95479d57b8d368b70af7/src/Nethermind/Nethermind.Blockchain/BlockhashProvider.cs#L41
This would mean we could finally test the clients against each other without having a failure whenever the BLOCKHASH opcode is executed

**Comment by tkstanczak** [comment]
@MarekM25 seems like a quick win for you?

**Comment by holiman** [comment]
What @MariusVanDerWijden was _almost_ true, but somewhat simplified. 

Example case  `565138.json` which was submitted by @guidovranken 
It has `currentNumber` set: 
```
    "env": {
      "currentGasLimit": "0xb71b00",
      "currentTimestamp": "0x03e8",
      "previousHash": "0x5e20a0453cecd065ea59c37ac63e079ee08998b6045136a8ce6635c7912ec0b6",
      "currentCoinbase": "0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba",
      "currentDifficulty": "0x020000",
      "currentBaseFee": "0x0a",
      "currentRandom": "0x0000000000000000000000000000000000000000000000000000000000020000",
      "currentNumber": "0xc5d488"
````
What @MariusVanDerWijden wrote is only true if we execute on BLOCKNUMBER `1` , in which case `0` is the only one "eligible" for blockhash. If we're on a later number, there are other blocks which are 'eligible'. 
Some printouts from a run: 
```
{"pc":27,"op":64,"gas":"0x8910","gasCost":"0x14","memSize":32,"stack":["0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b","0x0","0x0","0x20","0x18","0x0"],"depth":97,"refund":0,"opName":"BLOCKHASH"}
Requested blockhash 0. Scope for blockhash: [12964744 - 12965000[
{"pc":28,"op":89,"gas":"0x88fc","gasCost":"0x2","memSize":32,"stack":["0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b","0x0","0x0","0x20","0x18","0x0"],"depth":97,"refund":0,"opName":"MSIZE"}

```
In this case, blocks `[12964744 - 12965000[` are eligible, and the test queries `BLOCKHASH(0)`. Which is not part of the scope.

**Comment by MariusVanDerWijden** [comment]
I also can't reopen the issue unfortunately

**Comment by holiman** [comment]
Ok, opened a new ticket instead
