### ISSUE TITLE
Move static DB Metrics to dynamic ones

### ISSUE THREAD

**Issue by dceleda** [NethermindEth/nethermind#3205]
**Is your feature request related to a problem? Please describe.**
Currently every database has own metric properties in Nethermind.Db.Metrics. 
For example Bloom -> BloomDbReads and Blocks -> BlocksDbReads
The code that initiates these databases is not very flexible and updaters to these metrics are hardcoded and passed via delegates.

**Describe the solution you'd like**
We could use dynamic metrics stored in the MetricsDict dictionary.

Relies on #3204

**Comment by tkstanczak** [comment]
@dceleda this code is performance critical and static variables are used for a reason

**Comment by dceleda** [comment]
Closed
