### ISSUE TITLE
Method miner_start is not supported.

### ISSUE THREAD

**Issue by sonygod** [NethermindEth/nethermind#3291]
I run xdai chain with nethermind fast sync mode .alway got this error?

Error when handling ID 1, miner_start(16) | {"jsonrpc":"2.0","error":{"code":-32601,"message":"Method miner_start is not supported"},"id":1}

what's for this error?how to fixed that? thank you .

**Comment by matilote** [comment]
Somebody is querying your node through JSON RPC. I suggest setting up a firewall on the JSON RPC port.
