### ISSUE TITLE
Null type in trace_replayBlockTransactions for service transactions

### ISSUE THREAD

**Issue by vbaranov** [NethermindEth/nethermind#3298]
Null type in `trace_replayBlockTransactions` JSON RPC method for service transactions from an archive node. London HF + POSDAO activated, `trace` module enabled.

Nethermind client version:
```
{"jsonrpc":"2.0","result":"Nethermind/v1.10.79-0-e45db5fb5-20210810/X64-Linux/5.0.8","id":1}
```

An example of call:
`
curl --data '{"method":"trace_replayBlockTransactions","params":["0x7AA0",["trace"]],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST ...
`

The response is:
`
{"jsonrpc":"2.0","result":[{"output":"0x","stateDiff":null,"trace":[{"action":{"callType":"call","from":"0xc236e0172b6cdcbd3e5353e4d7b5ae15f94fe926","gas":"0x186a00","input":"0x0b61ba85c5f657e45b69c2fa118d1151e694fbee58ecb7a6828e81a7a16fb43b1a8d14390000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000009104a446399c13ad01bf2a38c9dacf3c15ad042eec9e9f4dfec9c52300d57e1b0add6c0ee9b72ec51681d9720802ab3778866aecc188c8f66064003b823ca3e32e566f051a0c4fd9a32d29e929a386a1212d8a91f8ab8170330d122acdfc7a6e422e34204bbd3786193934a6bac0a10cd73e51d4511e280ae4474a71f097844ad37d58337cbd66606d0b4e3545c1baa5779e000000000000000000000000000000","to":"0x3000000000000000000000000000000000000001","value":"0x0"},"error":"miner premium is negative","subtraces":0,"traceAddress":null,"type":null}],"transactionHash":"0x275fe5f14335e17fbd1cb8274602af559093bd78860e9933a3b8a50456061766","vmTrace":null}],"id":1}
`

**Comment by MarekM25** [comment]
Resolved in https://github.com/NethermindEth/nethermind/releases/tag/1.11.7
