### ISSUE TITLE
Major Issue: Break in Harmonious Coding AuRa Block Reward Contracts re: OpenEthereum's AuRa implementation.

### ISSUE THREAD

**Issue by chris-shyft** [NethermindEth/nethermind#3350]
**Describe the bug**
Nethermind does not have an identical implementation for account "kinds" in block rewards.
"EmptyStep" and "External" have been switched, while the the "system address" remains consistent across implementations of OE and NM.

This results in, when coding for the implementations in *any* google-searchable documentation, finding, and only finding, the OpenEthereum implementation:
https://openethereum.github.io/Block-Reward-Contract

<img width="643" alt="Screen Shot 2021-08-27 at 10 11 23 PM" src="https://user-images.githubusercontent.com/34154131/131203006-f64539b8-d10c-498a-a489-2c8b43a10bf3.png">

This indicates a mistake, and gravely, the smart contracts behaving at this level do not know about any other implementations.

our network (mainnet) was affected -  ending up, in a mainnet situation, as having our assets incorrectly burned at each step, with our "external" configuration being OE's documented example:

<img width="687" alt="Screen Shot 2021-08-27 at 10 23 24 PM" src="https://user-images.githubusercontent.com/34154131/131203274-51d8abd7-aa97-49a7-b4f7-56df09c07dc1.png">

https://bx.shyft.network/address/0x9f2Ad39F951a810A52b3838749779B90E9eb66d4/coin-balances
was supposed to receive double this amount, based on the the configuration:

<img width="696" alt="Screen Shot 2021-08-27 at 10 30 15 PM" src="https://user-images.githubusercontent.com/34154131/131203454-02ed013a-7ac6-44ff-aa8a-285d95bae99c.png">

**Expected behavior**
Nethermind and OpenEthereum have identical implementations for the behaviour relating to block reward contracts, **or** the system address is not identical (visually as well, preferably, using aBBaB etc instead of FeeFFe etc) to OpenEthereum's, so that the block reward contract could detect the implementation.

However, this latter solution would be almost impossible to properly code to unless there was **significantly** more documentation and code examples, to the level (at least) of OpenEthereum's documentation and relative SEO to get it to the 1st google page.

In this, I'd expect it's actually simpler to change it up locally, and hopefully there are no deployed projects that are dependent on this non-matching implementation on Nethermind clients.

**Screenshots**
<img width="315" alt="Screen Shot 2021-08-27 at 10 08 23 PM" src="https://user-images.githubusercontent.com/34154131/131202939-a3d66b5a-81d4-4dce-b412-2b55c106a4ed.png">

**Desktop (please complete the following information):**
 - OS: OSX

**Additional context**

**Comment by LukaszRozmej** [comment]
Hi @chris-shyft, I am developer who coded AuRa in Nethermind. While I see that you are right in that the values in our enum are flipped, I fail to see how it would affect your networks rewards.

Explanation:
1. Nethermind currently doesn't support empty steps. I think your network doesn't use empty steps.
2. Based on docs, that you also linked:

"Currently the engine supports the following types of rewards:
0 - Author - Reward attributed to the block author
2 - Empty step - Reward attributed to the author(s) of empty step(s) included in the block (AuthorityRound engine)
3 - External - Reward attributed by an external protocol (e.g. block reward contract)
101-106 - Uncle - Reward attributed to uncles, with distance 1 to 6 (Ethash engine)
The reward contract will receive as input reward types of 0, 2 or 101-106, and any reward attributed by it will be labelled as external (this is visible when tracing rewards)."

So input kinds that contract can get are 0 - Author, 2 - EmptyStep (out of scope for Nethermind and probably your network), 101-106 Uncles. Your contract will output rewards that will be marked as External. Those rewards will override input rewards. So when your contract doesn't return a reward for authors address for example, then authors address won't be rewarded. This works like this in both OE and Nethermind.

Nethermind works like this with reward contracts on multiple networks that both use OE and Nethermind. If Nethermind would calculate rewards incorrectly on any of them, we would have consensus issue and the network would split.

The reward type (external) is later only used in tracing, but its used there by name (string), not value 3, so even this issue in enum isn't a bug in Nethermind at current time (not supporting empty steps), but its confusing and we will change it.

Can you then clarify what is your issue? Maybe I am missing something.

**Comment by LukaszRozmej** [comment]
For calculating parameters, this correct value are used: https://github.com/NethermindEth/nethermind/blob/169b4318b410c87ca7de020dfa045e10e41d744a/src/Nethermind/Nethermind.Consensus.AuRa/Rewards/AuRaRewardCalculator.cs#L140-L142

**Comment by LukaszRozmej** [comment]
Interaction with contract is as designed, there was confusion on what exact input will go into it.
