### ISSUE TITLE
ExecutingDirectory set not correctly

### ISSUE THREAD

**Issue by kryvel** [NethermindEth/nethermind#3358]
**Describe the bug**
ExecutingDirectory set in [PathUtils](https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Logging/PathUtils.cs#L38) not correctly. Currently it uses directory name of executed binary, which is wrong.
So, when Nethermind executed from /somewhere/nethermind directory by running /usr/bin/Nethermind.Runner it will crash. Because process could not create log directory in /usr/bin/

**To Reproduce**
1. copy Nethermind binary to /usr/bin/nethermind
2. cd /data/nethermind
3. /usr/bin/nethermind --datadir /data/nethermind --config mainnet 

**Expected behavior**
Client is running

**Actual behavior**
```
Aug 30 16:06:37 host-2 nethermind[20009]: 2021-08-30 16-06-37.4713|Setting LogDirectory to: /data/nethermind/logs, from: logs
Aug 30 16:06:37 host-2 nethermind[20009]: Unhandled exception. System.UnauthorizedAccessException: Access to the path '/usr/bin/logs' is denied.
Aug 30 16:06:37 host-2 nethermind[20009]:  ---> System.IO.IOException: Permission denied
Aug 30 16:06:37 host-2 nethermind[20009]:    --- End of inner exception stack trace ---
Aug 30 16:06:37 host-2 nethermind[20009]:    at System.IO.FileSystem.CreateDirectory(String fullPath)
Aug 30 16:06:37 host-2 nethermind[20009]:    at System.IO.Directory.CreateDirectory(String path)
Aug 30 16:06:37 host-2 nethermind[20009]:    at Nethermind.Logging.NLog.NLogLogger.Init(String fileName, String logDirectory)
Aug 30 16:06:37 host-2 nethermind[20009]:    at Nethermind.Logging.NLog.NLogLogger..ctor(String fileName, String logDirectory, String loggerName)
Aug 30 16:06:37 host-2 nethermind[20009]:    at Nethermind.Runner.Program.Main(String[] args)
```

**Desktop (please complete the following information):**
 - OS: Debian
 - Version 1.11.0

**Comment by kryvel** [comment]
Hi,
Any update on this?

**Comment by attila-lendvai** [comment]
i suspect this has been fixed:

https://github.com/NethermindEth/nethermind/pull/4517

https://github.com/NethermindEth/nethermind/issues/4231
