### ISSUE TITLE
Nethermind not starting

### ISSUE THREAD

**Issue by DockBoss** [NethermindEth/nethermind#3390]
**Describe the bug**
* I have just downloaded Nethermind for the first time and I am unable to start it up without it crashing on me.
* I tried it with the current and previous versions of Nethermind and got the same results 
* I have node and .net up to date

**Screenshots**
![Screenshot 2021-09-08 165817](https://user-images.githubusercontent.com/56698307/132591728-ca5f9d6d-cbcb-4f69-b11d-80566455a4ba.jpg)

![Screenshot 2021-09-08 165933](https://user-images.githubusercontent.com/56698307/132591789-567e060c-589d-402b-937c-dc24de37afd9.jpg)

It will get to this point then crash on me.

**Comment by LukaszRozmej** [comment]
@DockBoss do you get any crash message? Maybe if you start launcher from command prompt (cmd) directly?

**Comment by DockBoss** [comment]
@LukaszRozmej  I tried that and I got the same issue. I don't get any error message it just closes once it hits this line.
I sent a gif on the nethermind [discord](https://discord.com/channels/629004402170134531/869971250208981013/885353122879373412)

**Comment by DockBoss** [comment]
It was a permissions issue on my side. I got it my bad.
