### ISSUE TITLE
Block Processing stops when cleaning peers

### ISSUE THREAD

**Issue by ehabhussein** [NethermindEth/nethermind#3411]
This issue has been observed on a Full node as well as an Archive node.

There seems to be an issue with Block processing once cleaning of peers happens. We solved this issue by increasing the number of peers to 1000 , and left it running for a day and then reconfigured the number of peers back to 300. The node seems to be running again smoothly.

**Comment by LukaszRozmej** [comment]
Can you elaborate? Did it replicate?

**Comment by ehabhussein** [comment]
the latest update seems to have fixed this hasnt happened after the latest update.
