### ISSUE TITLE
PPA package requires curl, but does not list it as a dependency

### ISSUE THREAD

**Issue by anisoptera** [NethermindEth/nethermind#3474]
**Describe the bug**
PPA package requires curl, but does not list it as a dependency

**To Reproduce**
1. Set up the PPA nethermind repository.
2. `apt remove curl`
3. `apt install nethermind`

**Expected behavior**
Nethermind is installed correctly

**Actual behavior**
Nethermind fails to get its binaries off github because curl is required but not listed as a dependency

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS

**Comment by 1swaraj** [comment]
Fixed
