### ISSUE TITLE
MetricsConfig.Enabled must be true to enable prometheus endpoint

### ISSUE THREAD

**Issue by anisoptera** [NethermindEth/nethermind#3475]
**Describe the bug**
MetricsConfig.Enabled must be true to enable the prometheus /metrics endpoint. However, this setting is also the flag to enable the metrics _pusher_. This means that even if I don't have a push service running on my machine, I have to enable it to be able to get the metrics endpoint working.

This wouldn't be a big deal except that the logs get spammed with a failure message every five seconds and it's very hard to filter out.

**To Reproduce**
1. Enable a Prometheus metrics endpoint.
2. Disable `MetricsConfig.Enabled` (documented as controlling the push metrics behavior, not the entire metrics subsystem)
3. Start Nethermind.
4. Attempt to connect to the metrics endpoint.

**Expected behavior**
I should get back metrics as an HTTP response.

**Actual behavior**
Connection refused, because the endpoint is not enabled, since at https://github.com/NethermindEth/nethermind/blob/26848dbea0db49b9e37be8dc8909a7a69ed7d758/src/Nethermind/Nethermind.Init/Steps/StartMonitoring.cs#L50 `MetricsConfig.Enabled` is checked to determine whether the entire metrics subsystem should be started.

**Comment by tkstanczak** [comment]
thanks for report, reviewed, will discuss

**Comment by LukaszRozmej** [comment]
Better solution is to keep as is and set: "PushGatewayUrl" to empty string in the config.

**Comment by iSOcH** [comment]
> Better solution is to keep as is and set: "PushGatewayUrl" to empty string in the config.

Should this work now? When I set it to empty string, the exposed port remains closed and the log contains:

```
Mar 22 19:54:41 nethermind-goerli Nethermind.Runner[3891]: 2022-03-22 19:54:41.0575|Step StartMonitoring          failed after 11ms System.ArgumentNullException: Value cannot be null. (Parameter 'pushGatewayUrl')
Mar 22 19:54:41 nethermind-goerli Nethermind.Runner[3891]:    at Nethermind.Monitoring.MonitoringService..ctor(IMetricsUpdater metricsUpdater, IMetricsConfig metricsConfig, ILogManager logManager)
Mar 22 19:54:41 nethermind-goerli Nethermind.Runner[3891]:    at Nethermind.Init.Steps.StartMonitoring.Execute(CancellationToken cancellationToken)
```

I guess this is due to https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Monitoring/MonitoringService.cs#L53-L55

(driveby: how would I set this to empty string using the env file for systemd?)
