### ISSUE TITLE
Prepare a common interface for TrieStore / FlatStore

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#3479]
**Is your feature request related to a problem? Please describe.**
When moving to flat DB we will need an interface that will allow us to separate StateProvider from Trie

**Describe the solution you'd like**
StateProvider.Get(Keccak stateRoot)
  * main state provider
  * temporary state provider

IStateStore
 * Account Get(Address)
 * Set(Address, Account)
 * Set(StorageCell, Value)
 * Value Get(StorageCell)
 * Commit(BlockNumber)
 * Dump(TargetStream)
 * StateStats CollectStats()
 * MoveToStateRoot(StateRoot) // how this works on the flat state? either unsupported or keeps layers, or has some time machine injected that resolves by state root
 * StateRoot GetStateRoot()

PatriciaStateStore : IStateStore
PruningPatriciaStateStore : IStateStore
FlatStateStore : IStateStore

**Comment by tanishqjasoria** [comment]
Moving to VerkleTrees change this interface

we have to add methods for accessing account headers

byte[32] GetAccountVersion (Address)
byte[32] GetAccountBalance (Address)
byte[32] GetAccountNonce (Address)
byte[32] GetAccountCodeKeccak (Address)
byte[32] GetAccountCodeSize (Address)

byte[32] GetAccountCodeChunk (Address, ChunkId)
byte[32] GetAccountStorageSlot (Address, StorageSlot

Reason - gas cost depends on individual keys accesses. - https://github.com/ethereum/EIPs/blob/932f0529836508137786a8ad2e5386fc8989d457/EIPS/eip-4762.md

**Comment by LukaszRozmej** [comment]
IWorldState is serving this role
