### ISSUE TITLE
Clean up Nethermind solution directory

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#3487]
**Is your feature request related to a problem? Please describe.**
move subprojects to separate directories or separate repositories.

**Describe the solution you'd like**
DataMarketplace in a separate folder or repository
BeaconChain in a separate folder or repository

**Describe alternatives you've considered**
Removing files entirely
Moving to separate repos
Moving to separate directories
Maybe cleaning the repo history

**Additional context**
This is needed to simplify the first impact of the solution on the new contributors

**Comment by LukaszRozmej** [comment]
Partially solved by #5052

**Comment by tkstanczak** [comment]
@rubo can this be closed now?
