### ISSUE TITLE
to: Tomasz Kajetan Stańczak

### ISSUE THREAD

**Issue by richardschneider** [NethermindEth/nethermind#350]
You sent an email to me, which I cannot reply to.  Here's my response
-----------

Nice to hear from you.  I have [Ipfs.Engine](https://github.com/richardschneider/net-ipfs-engine) which implements the IPFS Core API.

It relies upon [Peer Talk](https://github.com/richardschneider/net-ipfs-engine/tree/master/PeerTalk) which is .Net Core for libp2p. 

Peer Talk works, .Net Core peers can talk to js/go nodes. The major components are the swarm and DHT.  It's at a beta level and really needs a  refactor.

I'm looking for collaborators.

**Comment by tkstanczak** [comment]
@richardschneider thanks for your reply! noted and hope to get back to you as soon as we look into libp2p more closely (in case you would like to look at integrating Nethermind with libp2p for Ethereum 2.0 we are looking for collaborators too!)

pm me any time or just post your preferred method of contact:
https://gitter.im/nethermindeth/nethermind

**Comment by lazaridiscom** [comment]
@tkstanczak , this one should be closable?

**Comment by tkstanczak** [comment]
@richardschneider if you could let me know the best way to get in touch (gitter / riot / other ways?) - I would like to start working on this

**Comment by richardschneider** [comment]
I'm UTC+1200 so chatting is not easy,  My email is  makaretu@gmail.com
