### ISSUE TITLE
Consider migration to SpanNetty

### ISSUE THREAD

**Issue by LukaszRozmej** [NethermindEth/nethermind#3525]
**Is your feature request related to a problem? Please describe.**
dotNetty is not developed

**Describe the solution you'd like**
SpanNetty is dotNetty fork, we could try migrating

**Describe alternatives you've considered**
Migrating to other libraries is not time-effective

**Comment by tkstanczak** [comment]
https://github.com/cuteant/SpanNetty/issues/88

**Comment by LukaszRozmej** [comment]
Don't expect to give meaningful improvements.
