### ISSUE TITLE
[TheMerge] Support more than one url for Json RPC/WebSockets

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#3535]
The current config allows us to set up only one URL for JsonRPC. For security reasons, our node has to be able to set up many URLs/ports. After the merge, we will need to listen to different ports for different RPC modules. The node should be able to duplicate RPC modules for many ports. AFAIK, the consensus clients use these modules: engine, eth, net, subscribe, web3, and maybe more.

 The question here is how to deliver it in the config, especially as command lines arguments. The solution could be to separate the config with extra characters like "|". 
Of course, because of backward compatibility, we don't want to change the existing configuration. 
```
AdditionalRPCUrls: ["http://localhost:8550|engine,eth,net,subscribe", "http://localhost:8560|debug,admin"],
AdditionalWebSocketsUrls: ["http://localhost:8551|engine,eth,net,subscribe", "http://localhost:8561|debug,admin"]
```
An alternative way:
```
AdditionalRPCUrls: ["http://localhost:8550|http,ws|engine,eth,net,subscribe", "http://localhost:8560|ws|debug,admin"]
```
Aside from the merge, such functionality could be beneficial for current users. Node operators could configure the administrative RPC, which are available only for them, for example, modules like Debug, Admin, Health. Theoretically, it could be done by firewall settings, but IMO the obligation to configure it after the merge isn't acceptable.

**Comment by MarekM25** [comment]
Hi @640774n6,

Thank you so much for contribution! 

> As far as backwards compatibility goes, it would still use Host/Port/WebSocketsPort/EnabledModules for the first url correct?

Yes, exactly.

> Is there a preferred method from the above suggestions? I would lean towards the second (alternative way).

More people prefer the second way, so we're choosing it!
`AdditionalRPCUrls: ["http://localhost:8550|http,ws|engine,eth,net,subscribe", "http://localhost:8560|ws|debug,admin"]`

**Comment by 640774n6** [comment]
Sounds good! I'm some tests.

How forgiving/flexible should the parser be? Do we want to assume default values for missing pipe sections? For example:
* "http://localhost:8550|http,ws" => Could be valid with the assumption being that if you don't specify the modules it will use the default modules. I can see this being useful.
* "http://localhost:8550" => Could be valid with the assumption being that if you don't specify the endpoint type it will use a default value (http?). Seems like this one may lead to confusion .

I was doing some testing and realized that url ports need to be unique. Going to refactor JsonRpcUrlCollection to ensure one url per unique port.

**Comment by LukaszRozmej** [comment]
@640774n6 big thx for great implementation!

**Comment by 640774n6** [comment]
No problem! Happy to be able to contribute!
