### ISSUE TITLE
eth_getTransactionReceipt returns wrong hash of block

### ISSUE THREAD

**Issue by vbaranov** [NethermindEth/nethermind#3541]
Nethermind/v1.11.3-0-fe90423bd-20211018/X64-Linux/5.0.7

Steps to reproduce:

1. Request block by number:
`curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["21562874", false],"id":1}' https://sokol-archive.blockscout.com`

`{"jsonrpc":"2.0","result":{"author":"0xcbbcd5ac86f9a50e13313633b262e16f695a90c1","difficulty":"0xfffffffffffffffffffffffffffffffe","extraData":"0xdb830302068c4f70656e457468657265756d86312e34372e30826c69","gasLimit":"0xbebc20","gasUsed":"0x12890","hash":❗0x49148ae57b5c4f0981d332fcb3459395b0cbb3575959a09da3bb3690e46dfc1f❗","logsBloom":"0x00000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000010000000000000000000000000000","miner":"0xcbbcd5ac86f9a50e13313633b262e16f695a90c1","number":"0x14905fa","parentHash":"0x5b2a5d7526c78c63065d9919922a5711a6e7e7614c3aff7b333e9fcd654ddd44","receiptsRoot":"0x3fd27516a4661e65b1daf3c7fc096af5d2a9038707f57ea330ceb4da279e0d9b","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","signature":"0x005b0f2e261524b88d5a8027f686e13760524cd683cd840ab305ce3335a6fc5775b097333331fbd255655327debd015eaba3e2840123d4b1dcf2518a05561e0c00","size":"0x6c1","stateRoot":"0xde749a9a71034247ae8e3edba31ec87a057b810ccbc988d206922511f2d3b9eb","step":325008504,"totalDifficulty":"0x14905f9ffffffffffffffffffffffffeb59bd8e","timestamp":"0x60dc2e58","transactions":0xe765123449efa2ba5b2c57ba9e02c5d2ce49946fb0d57796865ce70fb2b16b04"],"transactionsRoot":"0x3b20f92c61d379f78bf03be7fa935050ee713978993e3bd4c5a146743c9f7fba","uncles":[]},"id":1}`

2. Request transaction receipt from that block
`curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xe765123449efa2ba5b2c57ba9e02c5d2ce49946fb0d57796865ce70fb2b16b04"],"id":1}' https://sokol-archive.blockscout.com`

`{"jsonrpc":"2.0","result":{"transactionHash":"0xe765123449efa2ba5b2c57ba9e02c5d2ce49946fb0d57796865ce70fb2b16b04","transactionIndex":"0x0","blockHash":"❗0x340b5336cf5abb002674b89fde618b44a9c5f0540a33c2e17701a1ccaaa09cbf❗","blockNumber":"0x14905fb","cumulativeGasUsed":"0x12890","gasUsed":"0x12890","effectiveGasPrice":"0x2540be400","from":"0x33e0e07ca86c869ade3fc9de9126f6c73dad105e","to":"0x79dd14623c4d33413c0c28fdabc2285fdb1e572e","contractAddress":null,"logs":[{"removed":false,"logIndex":"0x0","transactionIndex":"0x0","transactionHash":"0xe765123449efa2ba5b2c57ba9e02c5d2ce49946fb0d57796865ce70fb2b16b04","blockHash":"0x340b5336cf5abb002674b89fde618b44a9c5f0540a33c2e17701a1ccaaa09cbf","blockNumber":"0x14905fb","address":"0x79dd14623c4d33413c0c28fdabc2285fdb1e572e","data":"0x000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000290597120000000000000000000000000000000000000000000000000000000060dc2e2c00000000000000000000000000000000000000000000000000000000006f4aa200000000000000000000000000000000000000000000000000000000000000035852500000000000000000000000000000000000000000000000000000000000","topics":["0xa20e495bf7cbb7bc0ecf70d514a8e6da116c9b8b2a4e1c25d06b6b176db0de0f"]},{"removed":false,"logIndex":"0x1","transactionIndex":"0x0","transactionHash":"0xe765123449efa2ba5b2c57ba9e02c5d2ce49946fb0d57796865ce70fb2b16b04","blockHash":"0x340b5336cf5abb002674b89fde618b44a9c5f0540a33c2e17701a1ccaaa09cbf","blockNumber":"0x14905fb","address":"0x79dd14623c4d33413c0c28fdabc2285fdb1e572e","data":"0x000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000001d90706344d00000000000000000000000000000000000000000000000000000000060dc2e2c00000000000000000000000000000000000000000000000000000000006f4aa200000000000000000000000000000000000000000000000000000000000000035946490000000000000000000000000000000000000000000000000000000000","topics":["0xa20e495bf7cbb7bc0ecf70d514a8e6da116c9b8b2a4e1c25d06b6b176db0de0f"]},{"removed":false,"logIndex":"0x2","transactionIndex":"0x0","transactionHash":"0xe765123449efa2ba5b2c57ba9e02c5d2ce49946fb0d57796865ce70fb2b16b04","blockHash":"0x340b5336cf5abb002674b89fde618b44a9c5f0540a33c2e17701a1ccaaa09cbf","blockNumber":"0x14905fb","address":"0x79dd14623c4d33413c0c28fdabc2285fdb1e572e","data":"0x0000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000002b0ef3000000000000000000000000000000000000000000000000000000000060dc2e1300000000000000000000000000000000000000000000000000000000006f4a9800000000000000000000000000000000000000000000000000000000000000034f4e540000000000000000000000000000000000000000000000000000000000","topics":["0xa20e495bf7cbb7bc0ecf70d514a8e6da116c9b8b2a4e1c25d06b6b176db0de0f"]},{"removed":false,"logIndex":"0x3","transactionIndex":"0x0","transactionHash":"0xe765123449efa2ba5b2c57ba9e02c5d2ce49946fb0d57796865ce70fb2b16b04","blockHash":"0x340b5336cf5abb002674b89fde618b44a9c5f0540a33c2e17701a1ccaaa09cbf","blockNumber":"0x14905fb","address":"0x79dd14623c4d33413c0c28fdabc2285fdb1e572e","data":"0x0000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000001619f5800000000000000000000000000000000000000000000000000000000060dc2e1300000000000000000000000000000000000000000000000000000000006f4a98000000000000000000000000000000000000000000000000000000000000000352454e0000000000000000000000000000000000000000000000000000000000","topics":["0xa20e495bf7cbb7bc0ecf70d514a8e6da116c9b8b2a4e1c25d06b6b176db0de0f"]}],"logsBloom":"0x00000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000010000000000000000000000000000","status":"0x1","type":"0x0"},"id":1}`

Block hashes are different in responses.

**Comment by LukaszRozmej** [comment]
You should be able to recover it with receipt migration
