### ISSUE TITLE
Transactions that revert with binary data reasons do not return the binary data reason: breaks gnosis safe relay

### ISSUE THREAD

**Issue by habdelra** [NethermindEth/nethermind#3574]
**Describe the bug**
This looks like a regression. There was originally a bug filed and fixed for this issue #3207. To recap, When a transaction fails a solidity require() that has a binary data "reason", the response from nethermind does not return the binary data. What I am seeing is that Nethermind is returning the error: `"sender has deployed code"`. This is very problematic for using gnosis safes. Specifically the gnosis safe relay server relies on intentional reverts in order to communicate gas estimate information in the revert reason code as binary data. You can see an example of this code here:
https://github.com/gnosis/safe-contracts/blob/main/contracts/GnosisSafe.sol#L306-L327 and here https://github.com/gnosis/safe-contracts/blob/main/contracts/common/StorageAccessible.sol#L44. When the gnosis relay server attempts to intentionally trigger a revert and read the revert reason as binary data using a nethermind node, it throws an exception because the revert reason completely obscures the original binary data that was to accompany the revert reason.

Now that nethermind is the recommended ethereum node for xDai, POA, and Sokol, this is a huge problem as we won't be able to reliably run gnosis safe transactions in those networks since they will be running nethermind. 

**To Reproduce**
To reproduce this issue, post the following message (this triggers the intentional revert):
POST https://rpc.xdaichain.com
```json
{
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [
        {
            "value": "0x0",
            "from": "0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC",
            "gasPrice": "0x0",
            "to": "0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC",
            "data": "0xc4ca3a9c000000000000000000000000333d72f54cf17ba7a1971e7c7e9acb91c8b709d20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004a2e6204500000000000000000000000000000000000000000000000000000000"
        }
    ],
    "id": 1
}
```
This returns the response:
```json
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32015,
        "message": "VM execution error.",
        "data": "sender has deployed code"
    },
    "id": 1
}
```
You can confirm that this node is actually a nethermind node by sending the following message:
POST https://rpc.xdaichain.com
```
{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}
```
This returns the response:
```json
{
    "jsonrpc": "2.0",
    "result": "Nethermind/v1.11.5-0-76b7f08ae-20211102/X64-Linux/5.0.7",
    "id": 1
}
```

**Expected behavior**
You can see an example of what we would expect to happen by issuing this same call to an OpenEthereum RPC node:

POST https://xdai-archive.blockscout.com
```json
{
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [
        {
            "value": "0x0",
            "from": "0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC",
            "gasPrice": "0x0",
            "to": "0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC",
            "data": "0xc4ca3a9c000000000000000000000000333d72f54cf17ba7a1971e7c7e9acb91c8b709d20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004a2e6204500000000000000000000000000000000000000000000000000000000"
        }
    ],
    "id": 1
}
```
This returns a response that includes the binary data the the safe contract reverted with (in this case the gas measurement information) as part of the revert reason:
```json
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32015,
        "message": "VM execution error.",
        "data": "Reverted 0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000c4a7"
    },
    "id": 1
}
```

You can confirm this node is an Open Ethereum node by sending the following message:
POST https://xdai-archive.blockscout.com
```
{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}
```
This returns the response:
```json
{
    "jsonrpc": "2.0",
    "result": "OpenEthereum//v3.3.0-rc.12-stable/x86_64-linux-musl/rustc1.47.0",
    "id": 1
}
```

**Additional context**
This particular issue is very disruptive to how Gnosis safes work. The Gnosis safe relay relies on intentional reverts that include binary information as a means of communicating gas consumption information to the gnosis relay server. Failure to support this functionality essentially breaks Gnosis safe functionality.

**Comment by LukaszRozmej** [comment]
Hi, this is in line with https://eips.ethereum.org/EIPS/eip-3607 , which was retroactively introduced to ethereum spec as we (core devs, all clients) found no on-chain transactions (on any known chain) that break this rule. This was introduced for security reasons. This is already implemented in Geth and Nethermind, not sure about other client status.

Now question is if this should also apply to JSON RPC, generally its best to make them behave similarly unless we have a good reason.

Will ping Geth team how they implemented it, but as a quick workaround the question is if 'from' part of your eth_call has to be the contract address? Or can you just change that to something else.

**Comment by habdelra** [comment]
I myself am not on the Gnosis team, but it would be great if we could get someone from that team to chime in on this issue, as they might also have insight here.

**Comment by habdelra** [comment]
@LukaszRozmej according the the spec you referenced:
> Clients might choose to disable this rule for RPC calls like eth_call and eth_estimateGas as some Multi-Sig contracts use these calls to create transactions as if they originated from the multisig contract itself.

this is literally our situation. Is there a param that we can pass in eth_call to disable this rule? Or will you be disabling it across the board for RPC?

**Comment by habdelra** [comment]
@LukaszRozmej will this also be disabled for estimate_gas?

**Comment by MarekM25** [comment]
> @LukaszRozmej will this also be disabled for eth_estimateGas?

Yes :)
