### ISSUE TITLE
Low gas limit estimation for Gnosis Safe

### ISSUE THREAD

**Issue by dasanra** [NethermindEth/nethermind#3577]
**Describe the bug**
Whenever we try to execute a transaction in Gnosis Safe we try to estimate the gas limit. In many cases we do this when one signature is still pending, so the last user can sign and execute in the same step. For some reason, Nethermind nodes are having problems into estimating the gas limit in this situation, and is the only type of node where we find this difficulties. 

For estimating the gas we are just calling the `estimateGas` function from web3.

Funny thing is that executing a `call` to check if the transaction will go through returns a revert message. When adding a higher gas limit manually the `call` method will return success when we get the correct value for gasLimit

**To Reproduce**
1. You have the option to create a Gnosis Safe for testing on xDai https://xdai.gnosis-safe.io/app/
2. You will need to setup a Safe with any configuration you want
3. When executing any kind of transaction you will find that sending the transaction with the last signer (at create time if threshold is just one signer), a potential error message is shown. If ignored and the transaction is sent will revert because out of gas. Adding more gas until the error is not visible will make the transaction work perfectly

**To avoid creating an xDai Gnosis Safe**
You could try using `estimateGas` method using the following transaction parameters: 
```
{
  data: 0x6a7612020000000000000000000000006484a2514aee516ddac6f67dd2322f23e0a4a7d6000000000000000000000000000000000000000000000000002386f26fc1000000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b26d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000160000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000410000000000000000000000006484a2514aee516ddac6f67dd2322f23e0a4a7d600000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000

  from: 0x6484a2514AEE516DdaC6f67Dd2322f23e0A4A7D6
  to: 0xD301E5fC7c9829568C0489EF9693003c891711A1
}
```

**Expected behavior**
I would expect that the node returns a valid gas limit to execute the transaction without issues

**Comment by tkstanczak** [comment]
Needs fixing EstimateGasTracer - discussed with @LukaszRozmej on the call.
