### ISSUE TITLE
unable to sync with the xdai chain (waiting for peers.....)

### ISSUE THREAD

**Issue by AnnandaleV** [NethermindEth/nethermind#3585]
my validator node is not syncing with the xdai chain.

1) i was able to successfully bring up a nethermind xdai package on hardware running dappnode os.  the the validator was able to sync with the xdai chain; however, i found that the dappnode nethermind xdai DAP package didn't have capability of being a validator.

2) so, I wiped the machine and started over using ubuntu desktop: same fixed internal fixed ip address & no changes to router / firewall. i was able to ping out (google.com, etc.), and was able to ping back to the ubuntu desktop machine from another subnet.

3) i used the xdaichain instructions here https://www.xdaichain.com/for-validators/new-validator-process-flow/nethermind-node-setup to install dockers, clone the repo, created the .env file from .env.example, and successfully start up the validator, and began to run docker-compose logs -f nethermind (see pic).  
![waiting for peers](https://user-images.githubusercontent.com/93607126/140527773-892c3d3b-8683-4f0d-a660-552592491d02.gif)

This seems to be something very basic.  nethermind xdai on dappnode os synced with the chain, but nethermind xdai on ubuntu does not sync -- same hardware; same network, router / firewall settings.  what have i missed?

**Comment by MarekM25** [comment]
Hi @AnnandaleV,

I can't see the pic - not sure it is only on my end. Could you send us the full txt file with logs?

**Comment by AnnandaleV** [comment]
> Hi @AnnandaleV,
> 
> I can't see the pic - not sure it is only on my end. Could you send us the full txt file with logs?

Here's a sample of what the logs are showing: 

xdai-validator | 2021-11-05 14:13:07.0459|Waiting for peers... 3s
xdai-validator | 2021-11-05 14:13:08.0467|Waiting for peers... 4s
xdai-validator | 2021-11-05 14:13:09.0488|Waiting for peers... 5s
xdai-validator | 2021-11-05 14:13:10.0499|Waiting for peers... 6s
xdai-validator | 2021-11-05 14:13:11.0518|Peers | with known best block: 0 | all: 0 |
xdai-validator | 2021-11-05 14:13:11.0518|Waiting for peers... 7s
xdai-validator | 2021-11-05 14:13:12.0515|Waiting for peers... 8s
xdai-validator | 2021-11-05 14:13:13.0559|Waiting for peers... 9s
xdai-validator | 2021-11-05 14:13:14.0527|Waiting for peers... 10s
xdai-validator | 2021-11-05 14:13:15.0543|Waiting for peers... 11s
xdai-validator | 2021-11-05 14:13:16.0559|Waiting for peers... 12s
xdai-validator | 2021-11-05 14:13:17.0541|Waiting for peers... 13s
xdai-validator | 2021-11-05 14:13:18.0604|Waiting for peers... 14s
xdai-validator | 2021-11-05 14:13:19.0623|Waiting for peers... 15s
xdai-validator | 2021-11-05 14:13:20.0594|Waiting for peers... 16s
xdai-validator | 2021-11-05 14:13:21.0613|Waiting for peers... 17s
xdai-validator | 2021-11-05 14:13:22.0593|Waiting for peers... 18s
xdai-validator | 2021-11-05 14:13:23.0619|Waiting for peers... 19s
xdai-validator | 2021-11-05 14:13:24.0617|Waiting for peers... 20s
xdai-validator | 2021-11-05 14:13:25.0582|Waiting for peers... 21s
xdai-validator | 2021-11-05 14:13:26.0618|Peers | with known best block: 0 | all: 0 |
xdai-validator | 2021-11-05 14:13:26.0618|Waiting for peers... 22s

**Comment by AnnandaleV** [comment]
as i mentioned, i can ping google.com, yahoo.com, etc.  i can ping localhost, and i can ping the node from an adjacent subnet.

**Comment by MarekM25** [comment]
We need full logs because something could have gone wrong on the application start. You can find the log file on your docker container in the directory named "logs".

What is more, you can:
- stop your container
- add this setting to your docker: --Network.DiagTracerEnabled true (it is only for diagnostics - you should remove this setting later) https://docs.nethermind.io/nethermind/ethereum-client/docker
- start your container
- stop the node after 5 mins 
- now you should find the network_diag.txt file in your container. Send us this file too.

You can add logs here or mail me: marek.nethermind.io

**Comment by AnnandaleV** [comment]
in the /validator-node-dockerized directory are:

/.git (directory)
---->/ branches
---->/hooks
---->/info
---->logs
---->/---->/refs
---->/---->/---->/heads/nethermind
---->/---->/---->/heads/remotes/origin/HEAD
---->/---->/HEAD
---->/objects
---->/refs
---->/config
---->/description
---->/head
---->/index
---->/packed-refs
/ docker-compose.yml
/ readme.md
/ .env
/ .env.example
/ .gitignore

**Comment by AnnandaleV** [comment]
In the nethermind file is:

"0000000000000000000000000000000000000000 87cd669a13817d61c01fea59e303ba9d17c83b5c Northampton <northampton@GB-BRR7H-4800.(none)> 1635523114 -0400	clone: from https://github.com/xdaichain/validator-node-dockerized"

**Comment by AnnandaleV** [comment]
i'm running the log files in a command window (docker-compose logs -f nethermind)

but i don't see where it is copying them to a log file in the file system.

**Comment by AnnandaleV** [comment]
> We need full logs because something could have gone wrong on the application start. You can find the log file on your docker container in the directory named "logs".
> 
> What is more, you can:
> 
> * stop your container
> * add this setting to your docker: --Network.DiagTracerEnabled true (it is only for diagnostics - you should remove this setting later) https://docs.nethermind.io/nethermind/ethereum-client/docker
> * start your container
> * stop the node after 5 mins
> * now you should find the network_diag.txt file in your container. Send us this file too.
> 
> You can add logs here or mail me: marek.nethermind.io

"add Network.DiagTracerEnabled true to my docker"  I'm not that technical, so am not quite clear on this.  Do I add this as a line in the .yml file?

**Comment by LukaszRozmej** [comment]
This looks like some network connectivity is off, maybe port 30303 or something with host setting. @matilote or @1swaraj can you advise?

**Comment by AnnandaleV** [comment]
So.... we have an internal NAT class c, and a couple of fixed IP addresses
provided by our ISP with routing in/out between them..

I began to suspect that the routing between the fixed internal NAT IP
address that the validator has been assigned is routing OUT through the
fixed IP address provided by our ISP, but is not routing back in.  For some
reason when the same machine was running dappnode os, it was working & the
nethermind xdai DAP was syncing.  But after I reached a dead end with the
nethermind xdai DAP, and I reloaded the hardware with ubuntu, it would not
sync.

**Comment by AnnandaleV** [comment]
Lukasz,

I believe I fixed the problem.  However, I'm holding off on going live with
this xDai Chain validator.  Earlier this week, the xDai Team made a joint
proposal with Gnosis to merge (with Gnosis as the dominant partner). I was
told by one of the xDai Team members that validators would have to swap
$STAKE for $GNO (as a part of the merger) by withdrawing their $STAKE,
converting it to $GNO, then re-stake their $GNO into the new Gnosis Chain.
I have no idea how big of a job the reprogramming of the Nethermind Gnosis
Chain validator would be for you.

So, the level of uncertainty in the xDai/Gnosis world is too big for me to
move forward at the moment.

I appreciate your help nevertheless.

**Comment by LukaszRozmej** [comment]
Thank you for sharing.
