### ISSUE TITLE
Nethermind will accept "invalid" transaction price parameters without complaint 

### ISSUE THREAD

**Issue by sambacha** [NethermindEth/nethermind#3588]
**Describe the bug**
When sending a transaction that is underpriced RPC providers respond with an error whereas Nethermind client will accept the transaction without complaint

**Example**
The same transaction sent to infura is returning an error:

{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"transaction underpriced"}}

Whereas nethermind accepts the tx without any complaint.

**Expected behavior**
A warning or error. Controlling this response by configuration would be preferable 

**Additional context**
Observed in clients from v1.11.1, will update if not observed in latest version 

**[this issue may have some sort of relevance as well](https://github.com/NethermindEth/nethermind/issues/3577)**

**Comment by marcindsobczak** [comment]
Nethermind returns an error "FeeTooLow" only if transaction is cheaper than the cheapest transaction in full TxPool, so is too cheap to be even included in the pool. If fee is good enough to store this transaction as a pending, we are just accepting it, it has a chance to be included in block in the future, when fee drops. It's standard behaviour of nodes, Geth works the same way - for test reasons I sent transaction with 1 wei gas price to Nethermind and Geth on goerli testnet and both accepted it.

**Comment by LukaszRozmej** [comment]
So we could potentially add a configuration value for min gas price for tx pool like mentioned here: https://github.com/ethereum/go-ethereum/issues/15612#issuecomment-349922848 , question is would it bring any value?

We already have similar config value for mining in MinGasPrice, but we don't apply it to TxPool, only block construction logic https://docs.nethermind.io/nethermind/ethereum-client/configuration/mining

**Comment by LukaszRozmej** [comment]
AFAIK Infura changed to accept lower priced tx's

**Comment by sambacha** [comment]
Thanks @LukaszRozmej and @marcindsobczak , appreciate the follow up!
