### ISSUE TITLE
implement dynamic block building

### ISSUE THREAD

**Issue by kristofgazso** [NethermindEth/nethermind#3592]
Currently, we are able to trigger the building of a block on top of a known head, however if we want to create another block a few seconds later (to include potentially more profitable txs) we would have to recreate the block from scratch.

Geth includes a mechanism for continuous block improvement, where the currently mined block is continuously improved with better incoming txs and tx ordering optimizations. We should implement something similar.

This will also be very critical for us after the merge because of the way consensus clients request blocks, as well as because then we will be a mining client so we should aim to maximize the profits of validators running Nethermind.

**Comment by tkstanczak** [comment]
@kristofgazso I think this is not true - in Geth the block is constructed from scratch as well (every 3 seconds)

**Comment by LukaszRozmej** [comment]
This is being implemented only in post-merge code.
