### ISSUE TITLE
Unable to sync full kovan network

### ISSUE THREAD

**Issue by nadavais** [NethermindEth/nethermind#3599]
**Describe the bug**
Kovan network sync is always stuck at the same block 6600422. I tried different clients: 1.11.2, 1.11.6, 1.11.7
 
**To Reproduce**
1. Start docker container with the nethermind client
2. Wait for block 6600422
3. See error:
Multipple `Deleting invalid block 0x600984d985be21e99e23a7e32fe9542e69aa17799d035ae4739f555651d8247a at level 26981375`
and
`2021-11-10 08:52:29.0321|Cannot create trace of blocks starting from 0xfeb91abaf1636a6fc3f0d711ea3e0543df3e3b2a73f42054f5b815374a481641 of type BlockReceiptsTracer System.InvalidOperationException: Not able to find block 0x5203de4a6dc636e5b9c16320e20e8c67de797c0d146b4cfdf54afcfb50841f72 from an unknown level 6600423
   at Nethermind.Blockchain.BlockTree.WasProcessed(Int64 number, Keccak blockHash) in /src/Nethermind/Nethermind.Blockchain/BlockTree.cs:line 991
   at Nethermind.Consensus.AuRa.AuRaBlockFinalizationManager.OnBlocksProcessing(Object sender, BlocksProcessingEventArgs e) in /src/Nethermind/Nethermind.Consensus.AuRa/AuRaBlockFinalizationManager.cs:line 100
   at Nethermind.Blockchain.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs:line 98
   at Nethermind.Blockchain.Processing.BlockchainProcessor.TraceFailin`

**Expected behavior**
Nethermind is able to sync all blocks

**Env:**
 - OS: Ubuntu Linux 20.04 5.11.0-25-generic
 - Version 1.11.7
- Nethermind config:
======================== Nethermind initialization completed ========================
Version      : 1.11.7-0-75f034a08-20211110/X64-Linux/5.0.7
This node    : 
RPC modules  : Eth, Net, Parity, Personal, Proof, Subscribe, Trace, TxPool, Web3
Node address : 0x28220fd6d14e372b0c5f5919708a52d7a5936e97 (do not use as an account)
Mem est tx   :   1077MB
Mem est DB   :  14542MB
JSON RPC     : http://0.0.0.0:8545 ; http://0.0.0.0:8546
Genesis hash : 0xa3c565fc15c7478862d50ccd6561e3c06b24cc509bf388941c25ea985ce32cb9
External IP  : 
Ethereum     : tcp://:30303
Discovery    : udp://:30303
Chainspec    : chainspec/kovan.json
Chain ID     : Kovan
Chain head   : 6600360 (0x2e4527...244536)
=====================================================================================

**Comment by LukaszRozmej** [comment]
Hi, Kovan in its history has some WebAssembly blocks: https://openethereum.github.io/WebAssembly-Home , this feature is not supported in any other client including Nethermind, hence we don't support Kovan FullSync (archive sync) - where node processes all blocks 1 by 1. Looks like this is what you tried to do.

We do support FastSync - where the node downloads current network state and execute only new blocks.

This is stated in our readme file under supported networks.
