### ISSUE TITLE
Nethermind vulnerable to being used for DDoS amplification

### ISSUE THREAD

**Issue by holiman** [NethermindEth/nethermind#3617]
This is a variant of https://github.com/NethermindEth/nethermind/issues/1778 . 

Original description: 

> v4014 amplification attack test: The test spoofs a ping from a different ip address('victim ip'),and later on sends a spoofed 'pong'.

> The spoofed 'pong' will have an invalid reply-token (since the target will send the 'pong' to 'victim ip'), and should thus be ignored by  the target. If the target fails to verify reply-token, it will believe to now be bonded with a node at 'victim ip'.

> The test then sends a spoofed 'findnode' request. If the 'target' responds to the findnode-request, sending a large'neighbours'-packet to 'victim ip', it can be used for DoS attacks.

The new issue is that Nethermind also fails another test (https://hivetests.ethdevops.io/?page=v-pills-results-tab&suite=1637148643-fb3cf1e60daee247e8087388b8920c41.json) , `Findnode/WithoutEndpointProof`. 

This is similar to the case above, but does not send an invalid reply-token -- it just sends a findnode request without completing the ping/pong. 

cc @fjl, please check that I didn't misunderstand the test.

**Comment by fjl** [comment]
I think this is actually a test fluke. It would be bad if Nethermind sent NODES as a response there, but it only sends Ping, which is kind of OK. 

The test needs to be adjusted to report this better.

**Comment by LukaszRozmej** [comment]
@fjl @holiman so considering this, we should say this is false positive and close this issue as not a problem and test should be adjusted?

**Comment by LukaszRozmej** [comment]
We internally decided to close this for now. We don't respond without proper handshake, there is no DDoS here.

**Comment by holiman** [comment]
I am not convinced. The response is Expected no response, got &{4 {127.0.0.1 30303 30303And 4 is a neighbors, not Pong. ??

**Comment by LukaszRozmej** [comment]
Expected no response, got &{4 {127.0.0.1 30303 30303} {172.17.0.7 48987 48987} 1637148661 0 []}
4- Version
{127.0.0.1 30303 30303} - from 
{172.17.0.7 48987 48987} - to 
1637148661  - expiration
0 [] - enr-seq

looks ping to me
