### ISSUE TITLE
Tx root validation flaw

### ISSUE THREAD

**Issue by holiman** [NethermindEth/nethermind#3618]
In the hive consensus tests, one of the failures are `wrongTransactionsTrie_Berlin` (although all networks are affected). 

This rlp is imported as block `1`: https://github.com/ethereum/tests/blob/develop/BlockchainTests/InvalidBlocks/bcInvalidHeaderTest/wrongTransactionsTrie.json#L17 . 

An rlpdump shows the tx root: 
```
[
  [
    aa6c733b954fb03814267ff4e698d18b5dd210aa85e7457d856718c43fa4d5f9,
    1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347,
    8888f1f195afa192cfee860698584c030f4c9db1,
    edf42f78d05a438f6408aef357002a7380f4aca2587645d674498efc64705bd4,
    55e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421,
    21f4ebc5b0fb1ad80a00f78d04e67d1b30af68cecb3a8a2bf55247f11df1e3ed,
```
The nethermind hive log: https://hivetests.ethdevops.io/viewer.html?file=results/nethermind/client-da87c1f4e208a929449f99b8e938ee8f2b725b4305e1eac8c6490688efb09ed9.log show that the txroot `0x55e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421` is accepted: 

```


  | 2021-11-17 09:11:28.1219\|HIVE suggested 1 (0xe12ca3...f819fd), now best suggested header Hash: 0xe12ca37219a6b8b0103d1a479bedb9ce1e52b09c5b8eb4a822c9c984b5f819fd
-- | --
  | Number: 1
  | Parent: 0xaa6c733b954fb03814267ff4e698d18b5dd210aa85e7457d856718c43fa4d5f9
  | Beneficiary: 0x8888f1f195afa192cfee860698584c030f4c9db1
  | Gas Limit: 3141592
  | Gas Used: 22027
  | Timestamp: 1422495849
  | Extra Data: 42
  | Difficulty: 131072
  | Mix Hash: 0x0000000000000000000000000000000000000000000000000000000000000000
  | Nonce: 0
  | Uncles Hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
  | Tx Root: 0x55e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
  | Receipts Root: 0x21f4ebc5b0fb1ad80a00f78d04e67d1b30af68cecb3a8a2bf55247f11df1e3ed
  | State Root: 0xedf42f78d05a438f6408aef357002a7380f4aca2587645d674498efc64705bd4
  | BaseFeePerGas: 0
  | , head 1 (0xe12ca3...f819fd)

```
If we check the geth-log for the same case (https://hivetests.ethdevops.io/viewer.html?file=results/go-ethereum/client-b6a15cd5f1ee5d6cde761eb677a9d7858ac7491967394fdddbdb6803bfe948b2.log), we see the expected error: 
```


  | ########## BAD BLOCK #########
-- | --
  | Chain config: {ChainID: 1 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: <nil>, Berlin: 0, London: 2000, Arrow Glacier: <nil>, Engine: ethash}
  |  
  | Number: 1
  | Hash: 0xe12ca37219a6b8b0103d1a479bedb9ce1e52b09c5b8eb4a822c9c984b5f819fd
  |  
  |  
  | Error: transaction root hash mismatch: have e7e93016861d480e9fd60fc3dfd935eff097aa94c7380ed8df2ca7ec5b578214, want 55e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
  | ##############################

```
Geth thinks that the txroot should be `0xe7e93016861d480e9fd60fc3dfd935eff097aa94c7380ed8df2ca7ec5b578214` and rejects the block. 

This should be "easy" to reproduce without running hive, simply parse the block [here](https://github.com/ethereum/tests/blob/develop/BlockchainTests/InvalidBlocks/bcInvalidHeaderTest/wrongTransactionsTrie.json#L17 ), and check if the _calculated_ tx root matches with the header-declared tx root. If it does not, which it shouldn't, then figure out why this isn't validated during block import.

**Comment by LukaszRozmej** [comment]
This turned out to be an issue with our hive integration code: https://github.com/NethermindEth/nethermind/commit/481a475f173c8562672b5faa4bee53f49c569485
