### ISSUE TITLE
Bug in AdaptiveCodeResolver

### ISSUE THREAD

**Issue by marcindsobczak** [NethermindEth/nethermind#3659]
**Describe the bug**
Adding a new network protocol during open session can break the connection.

When we add new network protocol, new AdaptiveCodeResolver is created:
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Network/P2P/Session.cs#L538-L564

It is used to calculate AdaptiveId when sending message:
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Network/P2P/Session.cs#L232
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Network/P2P/Session.cs#L609-L628

And to recognize protocols of incoming messages:
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Network/P2P/Session.cs#L254-L256
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Network/P2P/Session.cs#L592-L607

In constructor of AdaptiveCodeResolver, P2P protocol is hardcoded to be on first position (_alphabetically[0]) and other protocols are sorted alphabetically:
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Network/P2P/Session.cs#L580-L590

On current master we have enabled P2P and Eth protocols + optionally Wit. So we have:
_alphabetically[0] = P2P (with MessageIdSpaceSize = 16)
_alphabetically[1] = Eth (with MessageIdSpaceSize = 17)
_alphabetically[2] = Wit (optionally, with MessageIdSpaceSize = 3)

Sending/receiving P2P messages have AdaptiveId 0-15, Eth 16-32 and Wit 33-35
And it works fine.

When working on Account Abstraction and its network protocol, I added AaProtocol with a code "aa" and it broke the connection.
Then:
_alphabetically[0] = P2P (with MessageIdSpaceSize = 16)
_alphabetically[1] = Aa (with MessageIdSpaceSize = 4)
_alphabetically[2] = Eth (with MessageIdSpaceSize = 17)
_alphabetically[3] = Wit (optionally, with MessageIdSpaceSize = 3)

So sending/receiving P2P messages should have AdaptiveId 0-15, Aa 16-19, Eth 20-36 and Wit 37-39

When Eth Status message is sent by node before initializing Aa protocol, has AdaptiveId 16. But if AaProtocol was initialized in the meantime, receiving node is receiving message with AdaptiveId = 16 and recognizing it as Aa message, and it causes lack of properly processed Eth Status message and leads to disconnect because of timeout.

**Expected behavior**
Adding new network protocol should not broke node's connection.

**Additional context**
I did some hacky fix on account-abstraction branch. I hardcoded Eth protocol to always be on second position (_alphabetically[1]):
https://github.com/NethermindEth/nethermind/blob/account-abstraction/src/Nethermind/Nethermind.Network/P2P/Session.cs#L580-L599

It solves a problem for that particular use-case, but is not fixing this issue as a whole.

**Comment by tkstanczak** [comment]
Please confirm with Felix Lange @fjl or Peter Szilagyi @karalabe if they have any specific rules for satellite protocols.

**Comment by karalabe** [comment]
Unsure what "if AaProtocol was initialized in the meantime" means. The protocols are negotiated during devp2p handshake and cannot be extended later on a connection. You can advertise as many or as few protocols as you want with multiple versions too, but the number mappings are decided during handshake.

**Comment by dceleda** [comment]
> The protocols are negotiated during devp2

@karalabe 
Does it mean that the order ( and adaptive ids) is also decided during the handshake? 
It doesn't have to be alphabetical (?)
