### ISSUE TITLE
Filter with ID ___ already exists, Filter with id: ___ does not exist

### ISSUE THREAD

**Issue by NoltaPulta** [NethermindEth/nethermind#3672]
When running ethereumetl against a full archive sync of Nethermind, and attempting to export all, I will randomly receive one of those two errors. Either the filter already exists, or the filter does not exist. I increased the rpc idle times to over an hour, and adjusted several other parameters, with no difference. It runs into this error within several minutes every run, anyways.

After researching some, it sounded like the filter does not exist error might be an issue on the backend prematurely removing filters. Not really sure about the filter already exists error.

I wanted to create this issue in case anyone else ever runs into it with ethereumetl +  Nethermind (openethereum going dark means Nethermind is now the best backend for analysis). 

I worked around the issue by making two minor code changes and recompiling. One overwrites a filter ID if it already exists, rather than throwing an error. The other change disables the uninstalling of all filters. The changes will certainly result in a memory leak, so make sure you're running on a machine with plenty of ram to spare. And after export, a restart of Nethermind is a good idea.

*Updated the comment/patch after pulling the latest master changes from today that created a conflict which needed to be resolved.

Here is the diff:

diff --git a/src/Nethermind/Nethermind.Blockchain/Filters/FilterStore.cs b/src/Nethermind/Nethermind.Blockchain/Filters/FilterStore.cs
index 0c0520ec7..3335590e1 100644
--- a/src/Nethermind/Nethermind.Blockchain/Filters/FilterStore.cs
+++ b/src/Nethermind/Nethermind.Blockchain/Filters/FilterStore.cs
@@ -92,10 +92,13 @@ namespace Nethermind.Blockchain.Filters
         {
             if (_filters.ContainsKey(filter.Id))
             {
-                throw new InvalidOperationException($"Filter with ID {filter.Id} already exists");
+                //throw new InvalidOperationException($"Filter with ID {filter.Id} already exists");
             }
-
+	    else
+	    {
                 _nextFilterId = Math.Max(filter.Id + 1, _nextFilterId);
+	    }
+	    
 	    _filters[filter.Id] = filter;
         }
 
diff --git a/src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs b/src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
index 7f2fd49d1..8bd4e09ec 100644
--- a/src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
+++ b/src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
@@ -558,7 +558,7 @@ namespace Nethermind.JsonRpc.Modules.Eth
 
         public ResultWrapper<bool?> eth_uninstallFilter(UInt256 filterId)
         {
-            _blockchainBridge.UninstallFilter((int)filterId);
+            //_blockchainBridge.UninstallFilter((int)filterId);
             return ResultWrapper<bool?>.Success(true);
         }

**Comment by NoltaPulta** [comment]
[nethermind.patch.txt](https://github.com/NethermindEth/nethermind/files/7665757/nethermind.patch.txt)

**Comment by LukaszRozmej** [comment]
Could you record 
eth_newFilter
eth_newBlockFilter
eth_newPendingTransactionFilter
eth_uninstallFilter

calls from ethereumetl to Nethermind? Or do that in Nethermind logs and filter them?

**Comment by LukaszRozmej** [comment]
fixed with https://github.com/NethermindEth/nethermind/commit/088d858b9ca4282f135262bc092ddbb77de3f6d4
