### ISSUE TITLE
[Critical] Fully Synced Archive Node Always Stales

### ISSUE THREAD

**Issue by Texnomic** [NethermindEth/nethermind#3673]
**Description**

Fully Synced Archive Node Suddenly Stops Syncing/Downloading/Processing New Blocks. 

Health Check UI Reports `The node is now fully synced with a network. Peers: XX. The node stopped processing blocks.` 

**Observations**
1. The Node enters infinite loop of `Waiting for peers...` and `Peer Discovery` due to `100% of nodes did not respond to a Ping message`
2. The Node actually reports a number of connected Peers in Grafana with no block processing for hours.
3. The Node is actually couple of thousands of blocks far from chain-top.
3. No Errors Reported in Any Logs

**Reproduction**

1. Run Node
2. Leave it running for more than a day.

**Workaround**

A simple Shutdown & Restart for the Node sort things out. It even gets blocks faster than Etherscan!

**Environment**
 - Windows Server 2022 
 - Compiled from Source or Pre-Compiled Release
 - Version 1.12+

**Note**

Kindly consider the matter top urgent and don't hesitant in asking for any additional information.

**Comment by LukaszRozmej** [comment]
Hi @Texnomic do you run with this fix: https://github.com/NethermindEth/nethermind/pull/3637 ?

**Comment by Texnomic** [comment]
@LukaszRozmej Now I'm running fully updated complied from source.

**Comment by LukaszRozmej** [comment]
Can you:
1. Setup some static nodes it will try to force connection to
2. Send logs around the issue happening (some time before, some time after) - you can send all logs + mentioning the datetime where it started.

**Comment by Texnomic** [comment]
1. Fresh Static Nodes (In-Sync) List Generated & Applied: `Loaded 3753 static nodes from file: X:\Nethermind.Config\Ethernodes.json`
2. All Logs are sent to `Seq`

**Observations**

1. The node got In-Sync in a matter of seconds!
2. Health Sync UI Reports `The node is now fully synced with a network. Peers: 6. The node stopped processing blocks.`

I really don't get it.

**Comment by LukaszRozmej** [comment]
3753 static nodes sounds excessive, not sure if it was designed to handle so many peers. It was designed to keep those connections at all cost and expected it to be less than peer slots.

"ActivePeersMaxCount": 1000 looks excessive too, it may be just resource starvation. I would recommend 100, maybe 200 max on a very beefy machine.

Where in Seq I can find the logs? Can you point me to some datetime in seq when you encountered the issue?

**Comment by Texnomic** [comment]
Yes, the numbers are excessive because the node doesn't even try to maintain a stable connection with Peers.

I'm giving it way more resources than it needs but still, the number of connected peers jumps wildly from 50 to 9 to 30 without any sign of stability.  

Couple of hours more, and the node will get out of sync from network. no specific date/time, it can happen as we speak and testing.

![image](https://user-images.githubusercontent.com/1648586/145020012-527650ed-81da-4ef6-8e35-2946661d52e8.png)
****

**Comment by Texnomic** [comment]
@LukaszRozmej I'm out of sync. Node block `13758263` and top block `13758286` while Health Check Report `The node is now fully synced with a network. Peers: 10. The node stopped processing blocks.`

**Comment by LukaszRozmej** [comment]
@Texnomic I am trying to reach out on Discord

**Comment by LukaszRozmej** [comment]
I did find 3 archive nodes in our seq, but I don;t think any of them is yours, they are progressing nicely. I need more data what can be an issue for your setup.

![image](https://user-images.githubusercontent.com/12445221/145024583-c73c65f1-5b82-41e6-838a-9962abcda94a.png)

**Comment by LukaszRozmej** [comment]
also thinking about your timeouts in: https://github.com/NethermindEth/nethermind/issues/3668

What is your I/O performance?

**Comment by Texnomic** [comment]
@LukaszRozmej I've joined Discord chat with you.

Regarding I/O, I've enabled the Disk Pref. Collection, Seems almost idle to me:

![image](https://user-images.githubusercontent.com/1648586/145028820-a91b8d83-ad20-43ad-a549-ccfaa2c00a41.png)

**Comment by LukaszRozmej** [comment]
@matilote @1swaraj could you setup seq token for @Texnomic so he could push logs for us to diagnose?

**Comment by LukaszRozmej** [comment]
Potential cause resource starvation with parameters:
"ActivePeersMaxCount": 1000
"TxPool": "Size": 200000

testing with lower values

**Comment by LukaszRozmej** [comment]
Lower values looked ok, didn't get further feedback
