### ISSUE TITLE
trace_transaction - insufficient funds for transfer

### ISSUE THREAD

**Issue by jaredcassidyluna** [NethermindEth/nethermind#3674]
**Describe the bug**
While calling the trace_transaction via rpc there is an error returned of insufficient funds for transfer for certain transactions

```
# curl --data '{"method":"trace_transaction","params":["0x6c485e9acb4051a933ed06fa078131a76afdb4924e53e27dc853e3a59dc1a2c8"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545

{"jsonrpc":"2.0","error":{"code":-32000,"message":"insufficient funds for transfer: address 0x7939846a9d05469ebf6a1a232ebe64fb6a238f51"},"id":1}
```

**To Reproduce**
1. Query the rpc trace_transaction, example transaction `0x6c485e9acb4051a933ed06fa078131a76afdb4924e53e27dc853e3a59dc1a2c8`

**Expected behavior**
Sucessfull trace_transaction call or perhaps a controlled error

**Screenshots**
```
# curl --data '{"method":"trace_transaction","params":["0x6c485e9acb4051a933ed06fa078131a76afdb4924e53e27dc853e3a59dc1a2c8"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545

{"jsonrpc":"2.0","error":{"code":-32000,"message":"insufficient funds for transfer: address 0x7939846a9d05469ebf6a1a232ebe64fb6a238f51"},"id":1}
```

nethermind log output
```
2021-12-07 14:18:58.3091|Executing JSON RPC call trace_transaction with params [0x6c485e9acb4051a933ed06fa078131a76afdb4924e53e27dc853e3a59dc1a2c8] 
2021-12-07 14:18:58.3180|Error when handling ID 1, trace_transaction(0x6c485e9acb4051a933ed06fa078131a76afdb4924e53e27dc853e3a59dc1a2c8) | {"jsonrpc":"2.0","error":{"code":-32000,"message":"insufficient funds for transfer: address 0x7939846a9d05469ebf6a1a232ebe64fb6a238f51"},"id":1} 

```

**Server:**
 - OS: Docker on ubuntu linux
 - Version 1.12.1

**Additional context**
Today we upgraded from `1.11.4` to `1.12.1` and some of our `trace_transaction` queries are throwing errors
I noticed there have been a few updates to the trace calls so not sure which release exactly it started in

**Comment by nbailo** [comment]
I have the same issue

`2021-12-14 00:22:19.8468|WARN|382|Error when handling ID 48403, trace_transaction(0xaada5a9d37879a9146bd49477763584bd51bf67f49c879d8d496a5ba8f146929) | {"jsonrpc":"2.0","error":{"code":-32000,"message":"insufficient funds for transfer: address 0x03d3d1a901b5668aed6b21c0bcd24a5ece5294f1"},"id":48403}`
