### ISSUE TITLE
Aura stall with force sealing on a single node

### ISSUE THREAD

**Issue by mirokuratczyk** [NethermindEth/nethermind#3699]
**Describe the bug**

Nethermind gets stuck sealing the same block infinitely when run as a single node using Aura consensus and force sealing.

**To Reproduce**

Follow the instructions in README.md in https://github.com/mirokuratczyk/nethermind-bug/tree/f6e4c4771875e7a610bc177befd9fdcbf66d00ea. It may take a few attempts to reproduce the bug.

**Expected behavior**

It is expected that Nethermind will continue to produce and seal new blocks the second time it is run.

**Actual behavior**

Nethermind infinitely loops on sealing block 1.

**Desktop**
 - OS: macOS 11.4 (Big Sur)
 - Version 1.12.3

**Additional context**
Here is what I have uncovered.

Initial run:
Node mines blocks 1–N
<Shutdown the node>

Second run:
Node attempts to mine a new block M where 0<M.height<N.height, but it still has blocks 0–N in the database. At least the header database or some cache.

So when it proposes this new block M it checks if it has seen a block of the same height with greater difficulty. If there exists a block of the same height with greater difficulty, then this new block will be ignored.

1. The node retrieves the previously mined block O at the same height as M from the database and checks its difficulty. Since we’re using the AuRa consensus algorithm the [difficulty of a block is roughly proportional to the time elapsed since the parent block was mined](https://github.com/NethermindEth/nethermind/blob/f5f0d940ac4c357a4d1a5c77c37ffe0ef7b9f815/src/Nethermind/Nethermind.Consensus.AuRa/AuraDifficultyCalculator.cs#L37). So O has greater difficulty and M is ignored. But for some reason it never re-processes O and loops endlessly trying to propose blocks at O.height with decreasing difficulty — since more time has elapsed.

2. Nethermind always checks the [difficulty of a new block](https://github.com/NethermindEth/nethermind/blob/f5f0d940ac4c357a4d1a5c77c37ffe0ef7b9f815/src/Nethermind/Nethermind.Blockchain/BlockTree.cs#L563), regardless of its height, against the [difficulty of the block with the most height in its database](https://github.com/NethermindEth/nethermind/blob/f5f0d940ac4c357a4d1a5c77c37ffe0ef7b9f815/src/Nethermind/Nethermind.Blockchain/BlockTree.cs#L344). At least in this scenario. So the difficulty of block O is getting compared with the difficulty of block N. Which isn’t a problem until we hit 1.

***Debugging***

I tried to dig into the issue a little further and here is what I found. Hope this helps!

On the first run I see `StateHeadHashDbEntryAddress` set here every time a new block is processed (so it should be >0) https://github.com/NethermindEth/nethermind/blob/f5f0d940ac4c357a4d1a5c77c37ffe0ef7b9f815/src/Nethermind/Nethermind.Blockchain/BlockTree.cs#L1558

But then on the second run `StateHeadHashDbEntryAddress` returns 0, when i'd expect it to be the number of the last block mined in the first run. So the start block is set to the genesis block instead of block N. Although, I may have misunderstood the code and this could have nothing to do with the issue at hand. https://github.com/NethermindEth/nethermind/blob/f5f0d940ac4c357a4d1a5c77c37ffe0ef7b9f815/src/Nethermind/Nethermind.Blockchain/BlockTree.cs#L1145

Also on the second run I see this log:
```
Block tree initialized, last processed is 0, best queued is 16, best known is 16, lowest inserted header , body
```
But sometimes after a few runs, without resetting the database, I see:
```
Block tree initialized, last processed is 0, best queued is 0, best known is 0, lowest inserted header , body
```
And the node starts successfully mining blocks again starting from block 1.

**Comment by LukaszRozmej** [comment]
Not sure if fixed, but this is an edge case we won't investigate at the moment
