### ISSUE TITLE
Add support for TxPool module in JS CLI

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#371]
Also look at #372

Also read https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console

Currently, CLI works only with basic types and does not handle complex types.

In order to support complex types, we would need to find a way fro Jint to recognize objects that are returned by methods from these modules.

At the moment CLI code is in 345cli branch and the quick CLI implementation is to be found in Nethermind.Cli with most of the code in Console.Program and ApiBuilder.

I launch it in Rider with args:
for CLI: ../Nethermind.Runner/node.key.plain
for Runner: --config spaceneth --baseDbPath C:\nethcli_space --InitConfig.JsonRpcEnabled true --InitConfig.EnableUnsecuredDevWallet true

Example of CLI calls that are handled now:
gasPrice
20000000000

gasPrice * 2
40000000000
var accounts = personal.listAccounts
undefined
var from = accounts[0]
undefined
var to = accounts[1]
undefined
eth.getBalance(from)
1000000000000000000000000
eth.getBalance(to)
1000000000000000000000000
eth.sendEth(from, to, 1)
"0x15072e09cc9f7ab958d39471c6c05acbe084ae3aeb48b6fbcbaeadafca848a79"
eth.getBalance(to)
1000001000000000000000000
eth.getBalance(from)
999998999580000000000000

Module methods to be covered:

public interface ITxPoolModule : IModule
        ResultWrapper<TransactionPoolStatus> txpool_status();
        ResultWrapper<TransactionPoolContent> txpool_content();
        ResultWrapper<TransactionPoolInspection> txpool_inspect();

**Comment by SherifSK** [comment]
@tkstanczak I was testing the above code and the line
`var accounts = personal.listAccounts`
returns the following as the `responseString`
`"Method personal_listaccounts is not supported"`

Also, the following statement
`_jsonSerializer.Deserialize<JsonRpcResponse<T>>(responseString).Result;`

throws an exception
`{System.ArgumentException: Could not cast or convert from System.String to System.String[].
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType) in /_/Src/Newtonsoft.Json/Utilities/ConvertUtils.cs:line 616
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType) in /_/Src/Newtonsoft.Json/Utilities/ConvertUtils.cs:line 587
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 982}`

Any thoughts can be helpful.

Thanks.

**Comment by tkstanczak** [comment]
fixed
