### ISSUE TITLE
[Security] Workflow release-nethermind.yml is using vulnerable action hashicorp/vault-action

### ISSUE THREAD

**Issue by igibek** [NethermindEth/nethermind#3710]
The workflow release-nethermind.yml is referencing action hashicorp/vault-action using references v2.1.2. However this reference is missing the commit [8417c61f8a8d628e128b8a7c128d177d1aff38db](https://github.com/hashicorp/vault-action/commits/8417c61f8a8d628e128b8a7c128d177d1aff38db) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by HarshCasper** [comment]
Hi @igibek

I am working on this issue and I was not able to exactly find where the `hashicorp/vault-action` has been used across our GitHub Action workflow.

Can you please point me towards it so that I can submit a patch? Thanks a lot!
