### ISSUE TITLE
Add support and tests for all JSON RPC methods

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#373]
need to review what is tested

examples in PersonalModule, IPersonalModule, PersonalModuleTests, ApiBuilder / Program in Nethermind.Cli (#372)

https://github.com/ethereum/wiki/wiki/JSON-RPC
https://github.com/ethereum/go-ethereum/wiki/Management-APIs

| RPC method | implemented | by | unit test |
|------------|-------------|----------------|-----------|
|trace_call|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|trace_callMany|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|trace_newTransaction|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|trace_rawTransaction|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|trace_replayTransaction|<ul><li>[x] done</li></ul>||<ul><li>[x] done</li></ul>|
|trace_replayBlockTransactions|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|trace_block|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|trace_get|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|trace_transaction|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|

| RPC method | implemented | by | unit test |
|------------|-------------|----------------|-----------|
|admin_addPeer|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|admin_dataDir|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|admin_nodeInfo|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|admin_peers|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|admin_setSolc|<ul><li>[ ] depr</li></ul>||<ul><li>[ ] done</li></ul>|
|admin_startRPC|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|admin_startWS|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|admin_stopRPC|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|admin_stopWS|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|

| RPC method | implemented | by | unit test |
|------------|-------------|----------------|-----------|
|txpool_content|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|txpool_inspect|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|txpool_status|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|

| RPC method | implemented | by | unit test |
|------------|-------------|----------------|-----------|
|personal_ecRecover|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|personal_importRawKey|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|personal_listAccounts|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|personal_lockAccount|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|personal_newAccount|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|personal_unlockAccount|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|personal_sendTransaction|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|personal_sign|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|

| RPC method | implemented | by | unit test |
|------------|-------------|----------------|-----------|
|web3_clientVersion|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|web3_sha3|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|

| RPC method | implemented | by | unit test |
|------------|-------------|----------------|-----------|
|net_version|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|net_peerCount|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|net_listening|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|

| RPC method | implemented | by | unit test |
|------------|-------------|----------------|-----------|
|eth_protocolVersion|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_syncing|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_coinbase|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_mining|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_hashrate|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_gasPrice|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_accounts|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_blockNumber|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getBalance|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getStorageAt|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getTransactionCount|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getBlockTransactionCountByHash|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getBlockTransactionCountByNumber|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getUncleCountByBlockHash|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getUncleCountByBlockNumber|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getCode|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_sign|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_sendTransaction|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_sendRawTransaction|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_call|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_estimateGas|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getBlockByHash|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getBlockByNumber|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getTransactionByHash|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getTransactionByBlockHashAndIndex|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getTransactionByBlockNumberAndIndex|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getTransactionReceipt|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getUncleByBlockHashAndIndex|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getUncleByBlockNumberAndIndex|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getCompilers (deprecated)|<ul><li>[x] depr</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_compileLLL (deprecated)|<ul><li>[x] depr</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_compileSolidity (deprecated)|<ul><li>[x] depr</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_compileSerpent (deprecated)|<ul><li>[x] depr</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_newFilter|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_newBlockFilter|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_newPendingTransactionFilter|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_uninstallFilter|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getFilterChanges|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getFilterLogs|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getLogs|<ul><li>[x] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getWork|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_submitWork|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_submitHashrate|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|eth_getProof|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|

| RPC method | implemented | by | unit test |
|------------|-------------|----------------|-----------|
|db_putString|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|db_getString|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|db_putHex|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|
|db_getHex|<ul><li>[ ] done</li></ul>||<ul><li>[ ] done</li></ul>|

| RPC method | implemented | by | unit test |
|------------|-------------|----------------|-----------|
|shh_post (not planned)|<ul><li>[x] ignore</li></ul>||<ul><li>[ ] done</li></ul>|
|shh_version (not planned)|<ul><li>[x] ignore</li></ul>||<ul><li>[ ] done</li></ul>|
|shh_newIdentity (not planned)|<ul><li>[x] ignore</li></ul>||<ul><li>[ ] done</li></ul>|
|shh_hasIdentity (not planned)|<ul><li>[x] ignore</li></ul>||<ul><li>[ ] done</li></ul>|
|shh_newGroup (not planned)|<ul><li>[x] ignore</li></ul>||<ul><li>[ ] done</li></ul>|
|shh_addToGroup (not planned)|<ul><li>[x] ignore</li></ul>||<ul><li>[ ] done</li></ul>|
|shh_newFilter (not planned)|<ul><li>[x] ignore</li></ul>||<ul><li>[ ] done</li></ul>|
|shh_uninstallFilter (not planned)|<ul><li>[x] ignore</li></ul>||<ul><li>[ ] done</li></ul>|
|shh_getFilterChanges (not planned)|<ul><li>[x] ignore</li></ul>||<ul><li>[ ] done</li></ul>|
|shh_getMessages (not planned)|<ul><li>[x] ignore</li></ul>||<ul><li>[ ] done</li></ul>|

**Comment by tkstanczak** [comment]
this list is not up to date,

we started generating documentation automatically in https://nethermind.readthedocs.io/en/latest/jsonrpc.html

**Comment by parithosh** [comment]
Is there any update on eth_getProof? [(EIP: 1186)](https://github.com/ethereum/EIPs/issues/1186). Is there a specific command I have to invoke to enable this? Currently, i get "Method not supported as a response". (Tested on the Görli testnet, nethermind was run using v1.0rc22 from dockerhub)

**Comment by tkstanczak** [comment]
Hi,

It is only done on a branch. I will see if I manage to finish and merge it
today.

Tomasz

**Comment by parithosh** [comment]
That would be awesome, thank you!

**Comment by tkstanczak** [comment]
EIP-1186 is implemented although some edge cases may not be covered. Added tests for basic scenarios but it needs some more testing with various scenarios to confirm that it behaves same as Parity / Geth (in particular - for the missing account / missing storage)

**Comment by tkstanczak** [comment]
It is merged in master and will be in RC25.
