### ISSUE TITLE
Document Env variables

### ISSUE THREAD

**Issue by tmm360** [NethermindEth/nethermind#3741]
**Is your feature request related to a problem? Please describe.**
It's useful for example for have a reference guide configuring docker compose instances.

**Describe the solution you'd like**
A clear documentation listing all env variables, accepted values and default.

**Comment by tkstanczak** [comment]
https://docs.nethermind.io/nethermind/ethereum-client/configuration

https://docs.nethermind.io/nethermind/ethereum-client/docker

would any of these help? @tmm360

**Comment by tmm360** [comment]
No, I was looking for something like a tabular list:
| Name          | Value           | Default |
| ------------- |-------------| -----|
| NETHERMIND_JSONRPCCONFIG_ENABLED | bool | false |
| NETHERMIND_JSONRPCCONFIG_HOST      | string |   "127.0.0.1" |
| NETHERMIND_JSONRPCCONFIG_PORT | int      |    8545 |
| etc... |    |      |

Otherwise, also a complete configuration sample for docker-compose could be enough, like this https://docs.nethermind.io/nethermind/ethereum-client/configuration/sample-configuration, but with env variables.

**Comment by matilote** [comment]
We will autogenerate these env variables and push them to our docs. I agree that this is a desired feature, thanks for prompting it.
CC: @AntiD2ta
