### ISSUE TITLE
Nethermind syncing peers but not blocks

### ISSUE THREAD

**Issue by matto0201** [NethermindEth/nethermind#3782]
Hi, it has been some days since my Nethermind stopped to sync blocks and started to sync only the peers, resulting like this:

**Peers | with known best block: 99 | all: 99 |
Peers | with known best block: 100 | all: 100 |
Sync peers - Initialized: 100 | All: 100 | Max: 100
[Peer|eth66|14133967|Nethermind/v1.12.2-3-6a3c5d803-20220127/X64-Linux/6.0.0-rtm.21522.10|47.89.184.210:30303][156|1|0|0|0]
[Peer|eth66|14133967|Nethermind/v1.12.2-3-6a3c5d803-20220124/X64-Linux/6.0.0-rtm.21522.10|47.89.181.136:30303][176|1|0|0|0]
........
[Peer|eth66|14133967|OpenEthereum/v3.3.3-stable-6e06824c2-20220113/x86_64-linux-gnu/rustc1.48.0|8.210.14.154:30304][875|0|0|0|0]
[Peer|eth66|13044000|Nethermind/v1.11.1-0-919e4cc59-20220203/X64-Linux/5.0.9|143.198.189.155:30303][280|0|0|0|0]
Peers | with known best block: 100 | all: 100 |
Peers | with known best block: 100 | all: 100 |
Peers | with known best block: 100 | all: 100 |
Peers | with known best block: 100 | all: 100 |
Peers | with known best block: 100 | all: 100 |**

It had reached like 45% of the syncing, but suddently it stopped to syncronize blocks. If you need i can provide some logs.

**Comment by matilote** [comment]
We will need full logs to find the root cause.

**Comment by matto0201** [comment]
Hi @matilote , thanks for responding. I'm gonna upload the log files which contains the last time Nethermind synced the blocks 
Since github is giving me some errors, i had to upload it on G drive:

Here's where the block sync stopped:
https://drive.google.com/file/d/1mZG0DOZvkb-5gRYmZYD8od-NrJv45-k1/view?usp=sharing  ~ 32MB 

This is the last one instead:
https://drive.google.com/file/d/154BcPWlXBlS-hGvtF_av3AKTz3KH_iiG/view?usp=sharing ~ 1.5MB


Hope this can help!

**Comment by matilote** [comment]
I can see that you disk is not following with read/write ops and the diagnostics does not look good, are you using SSD?

**Comment by matto0201** [comment]
Yes @matilote. It's external, not a NVME, I know that influence a lot. But, I mean, it supports USB 3.0 and my laptop has a High Speed port which should reach 5Gbps. Do you think that's the problem? If so, why initially it worked fine?
Appreciate your help, thanks.
