### ISSUE TITLE
Obsoleted link in hub.docker

### ISSUE THREAD

**Issue by mikhail-khalizev** [NethermindEth/nethermind#3785]
Hi.

Link in [hub.docker.com](https://hub.docker.com/r/nethermind/nethermind) references to not existent page. Please, update `hub.docker.com` description.

![image](https://user-images.githubusercontent.com/18654696/152532558-1cb869ed-0794-4e7d-a528-4a06c85e26c8.png)

**Comment by matilote** [comment]
Hi, thanks. Just updated.
