### ISSUE TITLE
Running `master` with hybrid pruning leads to DB corruption on restart

### ISSUE THREAD

**Issue by yorickdowne** [NethermindEth/nethermind#3797]
**Describe the bug**

Run Nethermind compiled from `master` with hybrid pruning parameters, and restart it before it is synchronized fully from mainnet. This leads to DB corruption.

`Nethermind/v1.12.4-48-211fa1a25-20220208/X64-Linux/6.0.1`

Started with:
```
      - --Pruning.Mode
      - Hybrid
      - --Pruning.FullPruningTrigger
      - VolumeFreeSpace
```

Errors seen after restart:

```
execution_1  | 2022-02-08 15:42:23.7699|Sync mode update failed RocksDbSharp.RocksDbException: Corruption: bad entry in block
execution_1  |    at RocksDbSharp.Native.rocksdb_get(IntPtr db, IntPtr read_options, Byte[] key, Int64 keyLength, ColumnFamilyHandle cf) in /nethermind/src/rocksdb-sharp/RocksDbSharp/Native.Wrap.cs:line 109
execution_1  |    at Nethermind.Db.FullPruning.FullPruningDb.get_Item(Byte[] key) in /nethermind/src/Nethermind/Nethermind.Db/FullPruning/FullPruningDb.cs:line 71
execution_1  |    at Nethermind.Synchronization.ParallelSync.SyncProgressResolver.IsFullySynced(Keccak stateRoot) in /nethermind/src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncProgressResolver.cs:line 83
execution_1  |    at Nethermind.Synchronization.ParallelSync.SyncProgressResolver.SearchForFullState(BlockHeader startHeader) in /nethermind/src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncProgressResolver.cs:line 123
execution_1  |    at Nethermind.Synchronization.ParallelSync.SyncProgressResolver.FindBestFullState() in /nethermind/src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncProgressResolver.cs:line 96
execution_1  |    at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.TakeSnapshot(UInt256& peerDifficulty, Int64 peerBlock) in /nethermind/src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs:line 533
execution_1  |    at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.Update() in /nethermind/src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs:line 188
execution_1  |    at Nethermind.Synchronization.ParallelSync.MultiSyncModeSelector.TimerOnElapsed(Object sender, ElapsedEventArgs e) in /nethermind/src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs:line 247
```

The corrupted DB is small yet, ~20 GiB. Let me know whether it's of use to you, and I'll upload it to cloud storage somewhere.

**Comment by LukaszRozmej** [comment]
Hi generally FullPruning shouldn't affect syncing and please keep note that we will release it in beta status. Did your node crash by any chance or was it properly closed?

Can you try removing state directory only in database path and restart?

**Comment by yorickdowne** [comment]
The node was properly closed, with a 3 minute graceful shutdown window.

This is indeed beta testing I am doing.

It's entirely possible the issue is unrelated to the pruning method. That'd be potentially more concerning, as it'd mean GA code can also corrupt the DB.

I removed `0` in `nethermind_db/mainnet/state` and started Nethermind.  The error messages do not re-occur.

I'll restart it (gracefully) after giving it half an hour or so, to see how reproducible this is.

**Comment by yorickdowne** [comment]
Restart did not corrupt the state DB again. Restarted it a few times, cannot reproduce.
Since the corrupted DB has now been deleted, I'll close this issue. It does concern me that a clean shutdown left the state DB unusable.

**Comment by LukaszRozmej** [comment]
Yes, generally my opinion on RocksDB is very mixed. We might expect to migrating to different db engine in the future.
