### ISSUE TITLE
[Account Abstraction] Make eth_sendUserOperation return requestId instead of hash, calculate hash using abi encoding instead of RLP

### ISSUE THREAD

**Issue by kristofgazso** [NethermindEth/nethermind#3802]
https://github.com/eth-infinitism/account-abstraction/blob/29cafdf9917ccd6e692e477400aabe3eee7ce39a/contracts/EntryPoint.sol#L172-L174
Make sure the request id is returned the same way the EntryPoint smart contract above returns it, this also requires us to change the Hashing to happen over the abi of user operations instead of their RLP serialization

**Comment by jorem321** [comment]
I will work on this.
