### ISSUE TITLE
I'm sorry to call you this way

### ISSUE THREAD

**Issue by dislikediss** [NethermindEth/nethermind#3836]
Hello, is this your address, please?
https://goerli.etherscan.io/address/0x9d525e28fe5830ee92d7aa799c4d21590567b595
Now the faucet is broken, and our entrepreneurial team is in urgent need of some Goerli ETH to create our eth2.o pledge application. I don't know what channel to use to get it, so I have to bother you. Sorry, if possible, WE hope we can get 28900.
My address: 0 xda00bf75f613bfb4dbfece5c8f63051caa78bed5
My email is wozxd520@hotmail.com

**Comment by LukaszRozmej** [comment]
We don't run faucet.
try https://goerli-faucet.mudit.blog/
