### ISSUE TITLE
Discrepancy in Nethermind VS Geth for filter blocks

### ISSUE THREAD

**Issue by DaveWK** [NethermindEth/nethermind#3892]
**Describe the bug**
Nethermind has the Address field as required in the "filter" as specified at:
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.JsonRpc/Modules/Eth/Filter.cs#L40
and so it fails when this is null/empty with:
```
{'code': -32603, 'message': 'Internal error', 'data': "System.ArgumentNullException: Value cannot be null. (Parameter 'hexString')
   at Nethermind.Core.Extensions.Bytes.FromHexString(String hexString)
   at Nethermind.Core.Crypto.Keccak..ctor(String hexString)
   at Nethermind.Blockchain.Filters.FilterStore.<>c.<GetTopic>b__19_0(String t)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at Nethermind.Blockchain.Filters.FilterStore.GetTopic(Object obj)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at Nethermind.Blockchain.Filters.FilterStore.GetFilterTopics(IEnumerable`1 topics)
   at Nethermind.Blockchain.Filters.FilterStore.GetTopicsFilter(IEnumerable`1 topics)
   at Nethermind.Blockchain.Filters.FilterStore.CreateLogFilter(BlockParameter fromBlock, BlockParameter toBlock, Object address, IEnumerable`1 topics, Boolean setId)
   at Nethermind.Facade.BlockchainBridge.NewFilter(BlockParameter fromBlock, BlockParameter toBlock, Object address, IEnumerable`1 topics)
   at Nethermind.JsonRpc.Modules.Eth.EthRpcModule.eth_newFilter(Filter filter)"
   }
```
However this is an optional field on geth, and the call succeeds. 

**To Reproduce**
I made a python script to illustrate the problem. you will need the `web3` pip package for this to work, and to replace the `nether_url` (couldnt find a public nethermind node):

```
from web3 import Web3

ETH_ADDR = '0x046ca4A32a11638fC9F30E9c2e707A5A92435290'
to_block = 14418487
from_block = 14418471
# couldnt find a public nethermind node, used an internal one
nether_url = "<replace with nethermind rpc>"
nether_w3 = Web3(Web3.HTTPProvider(nether_url, request_kwargs={"timeout": 60}))
# a public geth node
geth_url = "https://nodes.mewapi.io/rpc/eth"
geth_w3 = Web3(Web3.HTTPProvider(geth_url, request_kwargs={"timeout": 60}))

transfer = nether_w3.keccak(text="Transfer(address,address,uint256)").hex()
addr = nether_w3.keccak(text=ETH_ADDR).hex()

try:
    print(f"Client: {nether_w3.clientVersion}")
    filt = nether_w3.eth.filter(
        {"fromBlock": from_block,
         "toBlock": to_block,
         "address": [],
         "topics": [transfer, [addr, None], [None, addr]]
         }
    )
    x = filt.get_all_entries()
    print(f"NETHERMIND SUCCESS")
except Exception as ex:
    print(f"NETHERMIND FAIL: {ex}")

transfer = geth_w3.keccak(text="Transfer(address,address,uint256)").hex()
addr = geth_w3.keccak(text=ETH_ADDR).hex()
try:
    print(f"Client: {geth_w3.clientVersion}")
    filt = geth_w3.eth.filter(
        {"fromBlock": from_block,
         "toBlock": to_block,
         "address": [],
         "topics": [transfer, [addr, None], [None, addr]]
         }
    )
    x = filt.get_all_entries()
    print(f"GETH SUCCESS")
except Exception as ex:
    print(f"GETH FAIL: {ex}")
```

**Expected behavior**
The rpc should accept the rpc params as valid, and either return:
`{'code': -32000, 'message': 'filter not found'}` (timing issue for pushing filter, but acceptable)
or return the list of entries matching the filter criteria.

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - Nethermind Version 1.12.6

**Comment by LukaszRozmej** [comment]
Interestingly this works in Geth, but it is out of spec and I wonder if we should implement it in Nethermind:

Looking at the spec: https://eth.wiki/json-rpc/API#a-note-on-specifying-topic-filters nulls aren't supported when specifying internal arrays.

Lets think what filter like: "topics": `[transfer, [addr, None], [None, addr]]` actually would mean:
position 1: transfer topic
position 2: address topic OR any topic
position 3: any topic OR address topic

This filter is equivalent to `[transfer, None, None]` and not directly covered by above spec.

I expect Geth to have implemented this recursively and hence support None/null on all levels by side-effect.

Question is why do you need this kind of filter then?

**Comment by LukaszRozmej** [comment]
Closing for now. Request is out-of-spec and is equivalent with a lot simpler one, making it unnecessary. @DaveWK feel free to reopen if you think otherwise.
