### ISSUE TITLE
Excessive resource utilization when ethstats reporting is enabled

### ISSUE THREAD

**Issue by nicexe** [NethermindEth/nethermind#3896]
**Describe the bug**
Nethermind is using excessive resources 

**To Reproduce**
1. Setup an AuRa network such [xdaichain/posdao-testnet-prepare](https://github.com/xdaichain/posdao-testnet-prepare)
2. Before launching the nodes for the first time (`./run_all.sh`), segregate the nodes into a different server for each one.
    1. Modify each node's `docker-compose.yml` and update `NETHERMIND_NETWORKCONFIG_EXTERNALIP` and `NETHERMIND_ETHSTATSCONFIG_SERVER` environment variables
    2. Optionally modify `run_all.sh` and `stop_all.sh` to only run/stop the specific node or ethstats for each server
4. Start nodes
5. On archive server, deploy staking contract ``cd .. # go back to the `compose` directory`` and `docker-compose start && docker-compose logs -f`
6. Observe system load. This is the baseline with ethstats reporting enabled
7. Stop the nodes
8. Modify each node's `docker-compose.yml` and update `NETHERMIND_ETHSTATSCONFIG_ENABLED` to false
9. Observe system load. This is with ethstats reporting disabled

**Screenshots**
Here you can see some system metrics with ethstats reporting enabled
Focus on system load average
The only outlier is validator1 which seems to report the wrong information yet has the least resource utilization
<img width="1680" alt="Screenshot 2022-03-22 at 4 40 14 PM" src="https://user-images.githubusercontent.com/867535/159507869-6289d9db-3eab-4255-b222-6ec249bbcfd5.png">
![image](https://user-images.githubusercontent.com/867535/159507699-ad41a50c-3ac0-4774-860a-a683bcf1751b.png)
Here you can see some system metrics with ethstats reporting disabled
<img width="1680" alt="Screenshot 2022-03-22 at 5 01 07 PM" src="https://user-images.githubusercontent.com/867535/159512614-bd7c23a2-a0d8-4363-8dc6-febc540760f4.png">

**System Information:**
 - Docker host: Ubuntu 20.04
 - Docker container images: [nethermind/nethermind:1.12.6](https://hub.docker.com/layers/nethermind/nethermind/1.12.6/images/sha256-53ff134f660a4601444b97ee97717db30c8d7ccdaf1dba2088dac47e8201ef5d)

**Additional notes**
I cannot really explain the discrepancy between validator1 and the other validators in the ethstats enabled scenario.
All validators have almost identical environment variables set. They only differ on node name, keys and external ip.
Each node lives on it own VM, each on a different host machine, some host machines on a different datacenters.
All VMs have identical specs.

**Comment by nicexe** [comment]
In the ethstats enabled scenario, validators are starting to struggle to parse/produce blocks on time and this results in lots of benign AuRa reports

**Comment by nicexe** [comment]
Logs in the ethstats disabled scenario:
<img width="1680" alt="Screenshot 2022-03-22 at 5 33 09 PM" src="https://user-images.githubusercontent.com/867535/159531978-d58dd1f9-666a-437f-bf5b-202e3e8300ba.png">

Logs in the ethstats enabled scenario
<img width="1680" alt="Screenshot 2022-03-22 at 5 47 10 PM" src="https://user-images.githubusercontent.com/867535/159531984-47b66378-21b4-4e6f-b183-0e26d075f76f.png">

**Comment by nicexe** [comment]
I forgot to mention the VM orientation shown in my screenshots:

|     archive    |   validator1   |   validator2   |
|:--------------:|:--------------:|:--------------:|
| **validator3** | **validator4** | **validator5** |

**Comment by varasev** [comment]
@nicexe Did you try that with v1.12.3?

**Comment by nicexe** [comment]
@varasev 1.12.3 definitely helped

system load
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/867535/159941712-f78d57f9-139c-4d54-88d2-4304271ea292.png">

ethstats
![image](https://user-images.githubusercontent.com/867535/159942782-ced69191-f9aa-4ca8-9195-ebf8545ca4dc.png)


I restored the archive node and validators from 1 to 4 and configured them to use 1.12.6. I removed all data for validator 5 and configured it to use 1.12.3.

After validator 5 synced with the rest of the nodes I let it rest for a few minutes and then checked the system load as seen in the screenshot.

Validator 5 has a system load average of about 1 on a 4 core VM and the other nodes have a system load average of about 8-10 on a 4 core VM each.

Again, the only outlier is validator 1 which has significantly lower CPU utilization and system load average of about 2 on a 4 core VM but it is also the only node reporting invalid stats to the ethstat server.

**Comment by LukaszRozmej** [comment]
Hi @nicexe looking into your issue, if 1.12.3 solves it then there is slight chance that the actual reason is  different and related to: https://github.com/NethermindEth/nethermind/pull/3901

**Comment by varasev** [comment]
@nicexe Can you try to run the setup using the `nethermindeth/nethermind:local_txs_broadcasting` docker image? It is the build from https://github.com/NethermindEth/nethermind/pull/3901

**Comment by LukaszRozmej** [comment]
Also pushed #3906

**Comment by varasev** [comment]
> Also pushed #3906

@LukaszRozmej Can you please make a docker image for this?

**Comment by LukaszRozmej** [comment]
@nicexe I fail to actually reproduce this:
![image](https://user-images.githubusercontent.com/12445221/160777268-4dd309d9-d1da-4f99-9eb8-0953c20091e4.png)
![image](https://user-images.githubusercontent.com/12445221/160777370-5c922228-e89e-4b47-b540-3f6be39d2749.png)

Would you be able to provide a performance trace from one of the misbehaving nodes? I am inquiring our devops on how to do that on nodes running inside docker as that is more complicated.

**Comment by LukaszRozmej** [comment]
@nicexe can you help us gather data here?

1. Please use image [nethermindeth/nethermind:test](https://hub.docker.com/layers/nethermind/nethermindeth/nethermind/test/images/sha256-fa30adf07a853a8e88068a2100c199439a913bfa61e1a345a63921af295ca5e5?context=explore)
2. After running it on one or multiple misbehaving nodes please do: 
`sudo docker exec -it  xdaitestnet-validatorX /bin/bash
mkdir dumps
/opt/tools/dottrace attach PID --save-to=dumps`
3. After some time like a minute or two close dottrace with Ctrl+C, it will take the snapshot and save it to dumps folder
4. Now you need to send us the dump, you can do it different ways. one potential is:
`apt update
apt install curl
apt install zip
zip -9 -r perf.zip dump
curl --upload-file ./perf.zip https://transfer.sh/perf.zip`
The last one would give you url with the file being available for download.

**Comment by MarekM25** [comment]
@nicexe we found one potential issue with our ethstats integration. It could be connected with your problem. We will release the fix soon

**Comment by LukaszRozmej** [comment]
#4249
