### ISSUE TITLE
Produce ARM64 Architecture Docker-Images

### ISSUE THREAD

**Issue by ghost** [NethermindEth/nethermind#393]
(related to #334)

## Task

Port the existent Dockerfile to work on **arm64v8** architecture (e.g. Raspberry Pi 3).

### Must
* be similar to the existent./Dockerfile
* support arm64v8
* support Raspberry Pi 3

### Should
* work on any **arm64v8**  machines

## Assistance Needed

* Possibly some assistance is needed to test/document the solution
  * => use gitter channels (Nethermind / Goerli)

## Questions

* currently none

### NET3.0 Path

- [ ] #394 Provide net3.0 development branch (nethermind need to work on net3.0)
- [ ] use the relevant .NET container

**Comment by tkstanczak** [comment]
@lazaridiscom I tried running:

sudo docker pull lazaridiscom/rocksdb
sudo docker tag lazaridiscom/rocksdb nethermind/rocksdb
sudo docker run -it lazaridiscom/nethermind-net2v2-arm32v7

on my BCM2837RIFBG

I was running it on Raspbian. Nethermind failed when loading rocksdb in this image.
I see that you suggest to run it from Ubuntu - is that required?

**Comment by lazaridiscom** [comment]
(i filed this issue here for future net3.0 work.)

See reply there: https://github.com/NethermindEth/nethermind/issues/334#issuecomment-469203884

**Comment by lazaridiscom** [comment]
@tkstanczak should be actual now?

**Comment by tkstanczak** [comment]
@lazaridiscom good question - GA will be in Spetember but there is already RC6 available:
https://github.com/dotnet/core/blob/master/release-notes/3.0/README.md

**Comment by tkstanczak** [comment]
we already started discussing creation of the .net core 3.0 branch but I think it has not been done yet

**Comment by matilote** [comment]
Closed with PR #1118 
New ARM64 image will be pushed to docker by the next release (1.2.7)
