### ISSUE TITLE
Try recover rocksdb on corruption

### ISSUE THREAD

**Issue by LukaszRozmej** [NethermindEth/nethermind#3938]
We can try what OE does: https://github.com/openethereum/parity-ethereum/pull/7630

**Comment by smartprogrammer93** [comment]
Is this done here, or does it need more investigation @LukaszRozmej @dceleda 
https://github.com/NethermindEth/nethermind/pull/4911

**Comment by asdacap** [comment]
It sometimes works, sometimes not.
