### ISSUE TITLE
Merge: Bug: Unable to filter engine RPC logging

### ISSUE THREAD

**Issue by yorickdowne** [NethermindEth/nethermind#3940]
**Describe the bug**

Despite `--JsonRpc.MethodsLoggingFiltering={"engine_forkchoiceUpdatedV1","engine_newPayloadV1"}`, these calls continue to be logged together with their payload.

This is configured according to the help text: `--JsonRpc.MethodsLoggingFiltering                            Defines method names of Json RPC service requests to NOT log. Example: {"eth_blockNumber"} will not log "eth_blockNumber" requests.`

The engine calls come in via 8551, configured as `--JsonRpc.AdditionalRpcUrls=http://0.0.0.0:8551|http;wss|engine;eth;net;web3;subscribe`

**Comment by Hrugved** [comment]
@yorickdowne which branch is this issue related to?

**Comment by MarekM25** [comment]
@yorickdowne On the kiln branch, we have more extensive logging. It is/was useful for us during the testing. If you want to reduce logging, these settings could be ignored. You can modify NLog set to Trace for JSON.RPC. You can change NLog.config from Kiln -> https://github.com/NethermindEth/nethermind/blob/kiln/src/Nethermind/Nethermind.Runner/NLog.config to master -> https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Runner/NLog.config

**Comment by MarekM25** [comment]
I'm closing it now, but if you have any more problems feel free to reopen/ask questions :)
