### ISSUE TITLE
eth_syncing returns also latest blocks though the node it's up to date

### ISSUE THREAD

**Issue by baxy** [NethermindEth/nethermind#397]
I have a Nethermind node running on Goerli testnet. Not sure if replicable on other networks. Though it is up to date, when running `eth_syncing`, the json rpc call also returns as syncing status the latest received blocks. According to the docs here https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_syncing if the node is up to date, the returned status should be `false`.

**Comment by tkstanczak** [comment]
I guess it is related:

[Test]
[Ignore("We always return true")]
[Todo(Improve.MissingFunctionality, "Add correct reporting of not syncing")]

Fixing now

**Comment by tkstanczak** [comment]
Fixed, thanks for reporting.
