### ISSUE TITLE
Proposal to add an ability to disable some JSON RPC API methods

### ISSUE THREAD

**Issue by varasev** [NethermindEth/nethermind#3971]
(we have the same proposal for OpenEthereum: https://github.com/openethereum/openethereum/issues/647)

In some cases we may need to close some API methods leaving others available. For example, for enabled `eth` namespace we could disable `eth_accounts`.

I'd propose to add

```
DisabledMethods
```

to the set of config options for [JsonRpc module](https://docs.nethermind.io/nethermind/ethereum-client/configuration/jsonrpc), and a similar `DisabledWebSocketMethods` for WebSocket connections.

The method names are comma-separated, e.g.:

```
"DisabledMethods": "[eth_accounts,eth_sendTransaction]"
```

Such an option would close access for the listed methods for all network interfaces and ports. I think we don't need to delimit them by ip/port.

If `DisabledWebSocketMethods` is not defined, its value would be implicitly taken from `DisabledMethods` for the case when a user forgot to disable the same methods for WebSockets (and vice versa).

**Comment by LukaszRozmej** [comment]
We have the opposite, whitelisting with CallsFilterFilePath

https://docs.nethermind.io/nethermind/ethereum-client/configuration/jsonrpc

**Comment by varasev** [comment]
@LukaszRozmej Ah, got it. Ok, closing it
