### ISSUE TITLE
UDP payloads too big?

### ISSUE THREAD

**Issue by LukaszRozmej** [NethermindEth/nethermind#3974]
From: https://discord.com/channels/629004402170134531/629004402170134537/965954507483779172

"When troubleshooting internet connectivity issues I noticed my nethermind instances (mainnet & goerli) sometimes send UDP payloads which need to be fragmented.
This is an issue for my shitty Cable bridge (don't ask), but also in general appears to be something which is best avoided. Is this intended to happen or maybe a bug?

![image](https://user-images.githubusercontent.com/12445221/164346231-0e818aae-f8df-41cc-9a8a-40c52e217ff8.png)

https://github.com/ethereum/devp2p/blob/master/discv4.md#wire-protocol says The maximum size of any packet is 1280 bytes. ... then this would clearly be a bug?

From what I can say, those messages seem to all have 0x04 at index 0x61, which seems to indicate they are NeighborsMsg.
is the UDP payload enough?"

Example payloads for investigation:
[nethermind-discov4-large-udp-payloads.txt](https://github.com/NethermindEth/nethermind/files/8526283/nethermind-discov4-large-udp-payloads.txt)

**Comment by iSOcH** [comment]
I have now also seen some incoming fragmented packets (on the consensus net this apparently even happens to TCP).

Anyway, it looks like setting `NETHERMIND_DISCOVERYCONFIG_BUCKETSIZE=12` reduces (maybe eliminates completely) this behavior. Should I expect any problems with this change?

**Comment by asdacap** [comment]
Seems like geth is using 12 as it's max neighbors. When sending 16 nodes, it seems that nethermind is taking 1373 byte.

**Comment by LukaszRozmej** [comment]
So we should limit ourselves to 12 too?

**Comment by asdacap** [comment]
I think so yes.

**Comment by iSOcH** [comment]
But would that reliably keep the message size below 1280? I am not very familiar with the code/spec, but it appears the records can also carry IPv6 addresses?

**Comment by LukaszRozmej** [comment]
If not we can just count the bytes as we would be adding items and not add if we go beyond the limit

**Comment by asdacap** [comment]
They seems to have tested this with ipv6. https://github.com/ethereum/go-ethereum/blob/master/p2p/discover/v4wire/v4wire.go#L113

In any case, we probably should log a warn when this happen.
