### ISSUE TITLE
Remove hard dependency on `git` CLI available to the build system.

### ISSUE THREAD

**Issue by MicahZoltu** [NethermindEth/nethermind#3999]
**Describe the bug**
Previously, I could `dotnet build ...` on my machine without any problems.  Now when I try I get the following error:
```
  ---> Generating Git Hash file Before Build
  'git' is not recognized as an internal or external command,
  operable program or batch file.
C:\...\src\Nethermind\Nethermind.Runner\Nethermind.Runner.csproj(119,5): error MSB3073: The command "git describe --tags --long --always > git-hash" exited with code 9009.
```

**To Reproduce**
1. Install Windows 11
2. Install dotnet SDK
3. Acquire Nethermind source code
4. `cd src/Nethermind`
5. `dotnet build --configuration Release Nethermind.sln`
6. Notice that the build fails

**Expected behavior**
I don't need any tooling besides `dotnet` to build.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: `1.12.8`

**Additional context**
While I do have `git` installed, I don't have it on my path because I *never* use it from the CLI, I always use it from higher level tooling.

**Comment by LukaszRozmej** [comment]
Fixed in #7131
