### ISSUE TITLE
[Workaround] Handle incoming requests in SnapSync

### ISSUE THREAD

**Issue by dceleda** [NethermindEth/nethermind#4010]
Currently we don't handle incoming requests at all in SnapProtocolHandler.. Maybe we should send empty replies until we have snapshots implemented.
We turn off snap sync capability anyway after the sync is finished.

**Comment by marcindsobczak** [comment]
My idea here is different - disconnect peers which send snap requests.
When we are synced, we are turning off snap capability. So we can receive snap requests only when we are not synced. In this state we are useless for syncing peers, so I think we can disconnect them and both - we and them - can find more useful peers.
I was testing it a bit together with eth67 + new snap healing, working fine as far, but it's still undertested
