### ISSUE TITLE
Support for state overrides on eth_call and trace_call

### ISSUE THREAD

**Issue by raster21** [NethermindEth/nethermind#4021]
It would be great to get the ability to do state overrides with nethermind.

State overrides are supported in geth for `eth_call` and `trace_call`.

Here's an example snippet (from geth):
`debug.traceCall({from: addr, to: zero, value: '0x1'}, 'latest', {'stateOverrides': {[addr]: {'balance': '0x0'}}})`

This blog post explains the use case for state overrides quite well: https://www.libevm.com/2022/01/12/advance-geth-pt-2-stateoverrides/

**Comment by tkstanczak** [comment]
after the merge @raster21 but the request is reasonable

@kristofgazso ?

**Comment by dceleda** [comment]
https://twitter.com/koeppelmann/status/1564541835615379456?s=20&t=PUQN_tl7C8HkAMN0nLgwqg

**Comment by Termina1** [comment]
+1 for this feature

**Comment by OlegJakushkin** [comment]
Will post similar functionality in [5530 PR](https://github.com/NethermindEth/nethermind/pull/5530) soon.
