### ISSUE TITLE
MaxActivePeers not working on xDai?

### ISSUE THREAD

**Issue by andreujuanc** [NethermindEth/nethermind#4026]
**Describe the bug**
Set `--Network.MaxActivePeers  X` logs `Incorrect config settings found`:
![image](https://user-images.githubusercontent.com/360052/168424521-f30b04f5-1592-4557-86e2-b9e86fc15b24.png)
It does not matter the amount I set it to.

**To Reproduce**
My setup https://github.com/andreujuanc/nodes

**Expected behavior**
If this setting is invalid for certain chains, maybe there should be a chain specific config doc?

**Desktop (please complete the following information):**
Ubuntu: 18

**Comment by LukaszRozmej** [comment]
Hi please use `ActivePeersMaxCount`, there is an issue in mapping the config values, we will fix it.

**Comment by andreujuanc** [comment]
Thanks @LukaszRozmej !!
![image](https://user-images.githubusercontent.com/360052/168596316-0408b118-a55d-4fef-beb9-0097f6e42bea.png)
