### ISSUE TITLE
On AMD Ubuntu 22.04, can't run nethermind due to missing RocksDB

### ISSUE THREAD

**Issue by garyrob** [NethermindEth/nethermind#4039]
**Describe the bug**
I installed nethermind v1.13.0 on Ubuntu 22.04 on an Intel system according to the PPA instructions at https://github.com/NethermindEth/nethermind/releases.

When I try to run it using those instructions, I get a long set of errors, beginning with "2022-05-19 08:20:44.7240|RocksDb was not found, please make sure it is installed on your machine."

I tried installing RocksDB using a couple of different methods, but they haven't helped. Apparently I haven't installed it in a way that nethermind can connect to, and I don't know what to do about it.

It seems like, if RocksDB is required as a prerequisite, the instructions should say so, and it would be very helpful if you  say how to install it in a way that makes it useful for nethermind. 

**To Reproduce**
On Ubuntu 22.04 on an Intel machine:

sudo add-apt-repository ppa:nethermindeth/nethermind
sudo apt install nethermind
nethermind --config mainnet

**Expected behavior**
It works without exiting due to error

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser [e.g. chrome, safari]: None used

**Additional context**
I also tried installing nethermind by downloading the zip, using apt to install dependencies, etc. Those instructions are also listed on https://github.com/NethermindEth/nethermind/release. I get the same results as above. I notice that the instructions to install nethermind for Arm64 include installing librocksdb5.17 as a dependency. However, that library doesn't appear to exist for Amd64 Ubuntu and it isn't mentioned in the non-Arm64 Linux instructions on that page.

**Comment by FalcoXYZ** [comment]
@garyrob please run the following command as a temp fix: 
`sudo ln -s /usr/lib/x86_64-linux-gnu/libdl.so.2 /usr/lib/x86_64-linux-gnu/libdl.so`

**Comment by garyrob** [comment]
That seems to have fixed it, thanks!

**Comment by garyrob** [comment]
Does nethermind need the Rocksdb I installed, or nethermind self-contained? I'd like to get rid of the Rocksdb I installed if it isn't necessary.

**Comment by AntiD2ta** [comment]
Yeah, it needs Rocksdb, unless you use Nethermind docker image. The debian package use Nethermind binaries and this need dependencies such as Rocksdb to run.

**Comment by FalcoXYZ** [comment]
@mcdee The current fix is the symlink. Please feel free to contribute if you think you have a better fix. 
We opted for this fix as the libc6/libc6-dev packages don't use the libdl.so library anymore, but changed it to libdl.so.2. 

This is the symlink for amd64: sudo ln -s /usr/lib/x86_64-linux-gnu/libdl.so.2 /usr/lib/x86_64-linux-gnu/libdl.so
If you use arm64, you can use: sudo ln -s /usr/lib/aarch64-linux-gnu/libdl.so.2 /usr/lib/aarch64-linux-gnu/libdl.so

**Comment by paulhauner** [comment]
> Please feel free to contribute if you think you have a better fix.

I don't have a concrete solution but I would kindly and humbly suggest using static linking for the rocks dependency.

**Comment by mcdee** [comment]
> I don't have a concrete solution but I would kindly and humbly suggest using static linking for the rocks dependency.

Note I raised https://github.com/curiosity-ai/rocksdb-sharp/issues/26 for this, but haven't heard anything.

**Comment by mcdee** [comment]
@FalcoXYZ https://github.com/curiosity-ai/rocksdb-sharp/issues/26 contains reference to a potential fix for this issue.

**Comment by garyrob** [comment]
I deleted my rocksdb installation, and installed a recent Nevermind version from scratch and it seemed to work find. So, as far as I can tell, it's fixed...

**Comment by kamilchodola** [comment]
@FalcoXYZ 
This I believe can be already closed since new version are working smoothly on ubuntu 22, am I right?
