### ISSUE TITLE
Refine the overall Docker Setup

### ISSUE THREAD

**Issue by ghost** [NethermindEth/nethermind#404]
(continuation/extension of #334)

### Part A
- [ ] Reduce image sizes
- [ ] Provide elegant construct for custom-library-compilation
- [ ] Provide different start/stop/daemon (e.g. enable use of pi3 whilst running node) 

### Part B

- [ ] Enable multiarch images
- [ ] Refine existent main Dockerfiles (unify to one file)
- [ ] Integrate testing in Dockerfile
- [ ] Keep results generally usable (e.g. for other Ethereum projects)
- [ ] ?

**Comment by tkstanczak** [comment]
this will be handled by the new Docker ARM64 task
