### ISSUE TITLE
Nethermind in Docker shuts down incorrectly due to SIGTERM instead of SIGINT

### ISSUE THREAD

**Issue by jclapis** [NethermindEth/nethermind#4057]
**Describe the bug**
By default, Docker uses SIGTERM as the shutdown signal when a user calls `docker stop` or `docker-compose down`. Nethermind may not be handling this correctly, as evidenced by this log it produces when a shutdown is invoked:

```
eth1_1           | 2022-05-24 07:35:34.5371|Closing, please wait until all functions are stopped properly... 
eth1_1           | 2022-05-24 07:35:34.5407|Persisting trie... 
eth1_1           | 2022-05-24 07:35:34.5433|Stopping session monitor... 
eth1_1           | 2022-05-24 07:35:34.5433|Stopping discovery app... 
eth1_1           | 2022-05-24 07:35:34.5433|Stopping discovery udp channel 
eth1_1           | 2022-05-24 07:35:34.5433|Stopping block producer... 
eth1_1           | 2022-05-24 07:35:34.5433|Stopping sync peer pool... 
eth1_1           | 2022-05-24 07:35:34.5433|Discovery shutdown complete.. please wait for all components to close 
eth1_1           | 2022-05-24 07:35:34.5479|Fast blocks headers task completed. 
eth1_1           | 2022-05-24 07:35:34.5479|Stopping peer pool... 
eth1_1           | 2022-05-24 07:35:34.5479|Peer Pool shutdown complete.. please wait for all components to close 
eth1_1           | 2022-05-24 07:35:34.5479|Stopping peer manager... 
eth1_1           | 2022-05-24 07:35:34.5479|Peer Manager shutdown complete.. please wait for all components to close 
eth1_1           | 2022-05-24 07:35:34.5479|Stopping synchronizer... 
eth1_1           | 2022-05-24 07:35:34.5479|State sync task completed. 
eth1_1           | 2022-05-24 07:35:34.5479|Fast sync blocks downloader task completed. 
eth1_1           | 2022-05-24 07:35:34.5479|State sync task completed. 
eth1_1           | 2022-05-24 07:35:34.5479|Stopping blockchain processor... 
eth1_1           | 2022-05-24 07:35:34.5479|Fast blocks bodies task completed. 
eth1_1           | 2022-05-24 07:35:34.5479|Fast blocks receipts task completed. 
eth1_1           | 2022-05-24 07:35:34.5479|Full sync block downloader task completed. 
eth1_1           | 2022-05-24 07:35:34.5479|Stopping rlpx peer... 
eth1_1           | 2022-05-24 07:35:34.5514|Blockchain Processor shutdown complete.. please wait for all components to close 
rocketpool_eth1 exited with code 143
``` 

However, when changing the signal to `SIGINT`, it shows what I believe is the expected behavior (here is the tail since it's quite long):

![image](https://user-images.githubusercontent.com/627896/170183927-2a1d5c8d-77b7-4993-adf2-f7ba3f6d8dca.png)

This may be related to .NET itself, as suggested by this thread even though it's quite old now: https://github.com/dotnet/aspnetcore/issues/5932

**To Reproduce**
1. Run Nethermind in Docker
2. Wait a bit for it to start syncing the chain
3. Run `docker stop` on the container
4. Observe the improper shutdown behavior

5. Re-run Nethermind in the Docker container
6. Wait a bit for it to start syncing the chain
7. Stop the container using `docker kill --signal SIGINT <container>`
8. Observe the correct shutdown behavior

**Expected behavior**
See above

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux v20.04.4 x64, Docker v20.10.16
 - Browser N/A
 - Version `nethermind/nethermind:1.13.0`

**Comment by asdacap** [comment]
I can confirm same behaviour without docker.
