### ISSUE TITLE
Require option to disable log file

### ISSUE THREAD

**Issue by mcdee** [NethermindEth/nethermind#4095]
**Is your feature request related to a problem? Please describe.**

Nethermind appears to write to both stdout and a log file, which is superfluous when running under a control harness (e.g. systemd).  Being able to turn off the log file output would avoid the log taking up disk space unnecessarily.

**Describe the solution you'd like**

Add some sort of option to disable output to the log file, for example `--disable-log-file`.

**Comment by damian-orzechowski** [comment]
This potentially can be sorted using NLog.config.

**Comment by damian-orzechowski** [comment]
> You can set up NLog to log to console only:
> 
> https://github.com/NethermindEth/nethermind/blob/458e059e81b3f276a3763573c79c89548c2bd22b/src/Nethermind/Nethermind.Runner/NLog.config#L72-L73

Think the easiest is to set "Off" for the logger to be disabled:
`    <logger name="*" minlevel="Off" writeTo="file-async" />`

**Comment by emlautarom1** [comment]
I'll be closing this ticket since a solution has been already provided. If you face a new issue please open a new ticket.
