### ISSUE TITLE
readme leads to a death link

### ISSUE THREAD

**Issue by roninkaizen** [NethermindEth/nethermind#411]
https://github.com/NethermindEth/nethermind/blob/master/README.md

https://cloud.docker.com/u/nethermind/repository/docker/nethermind/nethermind is wrong

and could be exchanged by
https://hub.docker.com/r/nethermind/nethermind

**Comment by tkstanczak** [comment]
Thanks for reporting!

Fixed
https://nethermind.readthedocs.io/en/latest/docker.html
and
https://hub.docker.com/r/nethermind/nethermind
and readme

**Comment by roninkaizen** [comment]
thanks
