### ISSUE TITLE
debug_traceBlockByNumber - latest and finalized - invalid params

### ISSUE THREAD

**Issue by quickchase** [NethermindEth/nethermind#4133]
**Describe the bug**
It looks like `debug_traceBlockByNumber` is not accepting `"latest"` or `"finalized"` on the latest release on Ropsten post-merge.

**To Reproduce**
https://github.com/NethermindEth/nethermind/releases/tag/1.13.2

`{"method":"debug_traceBlockByNumber","params":["latest"],"id":1,"jsonrpc":"2.0"}`
`{"method":"debug_traceBlockByNumber","params":["finalized"],"id":1,"jsonrpc":"2.0"}`

> Invalid params

**Expected behavior**
We should be able to debug_traceBlockByNumber against `latest` or `finalized`

**Comment by quickchase** [comment]
This issue may pre-date the merge/latest release we only noticed after switching from OpenEthereum - I tested another node on mainnet and it has the same problem. Doesn't understand `"latest"`?

**Comment by LukaszRozmej** [comment]
Yes it doesn't similar to Geth which also accepts only numbers there - hence the name.
We can add another overload if you need debug_traceBlockByParameter or something?

**Comment by LukaszRozmej** [comment]
This can be viewed as a part of https://github.com/NethermindEth/nethermind/issues/4210
