### ISSUE TITLE
Duplicate traceAddresses in traces from block 0x15bb5d4 on xDai/Gnosis

### ISSUE THREAD

**Issue by jkylling** [NethermindEth/nethermind#4208]
**Describe the bug**
Duplicate traceAddresses appear in the traces for this transaction https://xdai.tokenview.com/en/tx/0x58d38ce04495c128d82bcbcc6070f8af088513ad35e1a3e5bf3c2654ed7dcad9 of block 0x15bb5d4 on the xDai/Gnosis chain when fetched with `trace_transaction` from our node provider (Quicknode). There are multiple traces with `traceAddress=[2]`. We get this when calling `trace_transaction` on the endpoint of our node provider. The raw traces of `xdai.tokenview` does not contain the extra traces.

**To Reproduce**
```
~$ curl -s -X POST   $ENDPOINT   --header 'Content-Type: application/json'   --data-raw '{
  "method": "trace_transaction",
  "params": [
    "0x58d38ce04495c128d82bcbcc6070f8af088513ad35e1a3e5bf3c2654ed7dcad9"
  ],
  "id": 1,
  "jsonrpc": "2.0"
}' | jq '.result[].traceAddress'
[]
[
  0
]
[
  1
]
[
  2
]
[
  2
]
[
  2
]
[
  2
]
[
  2
]
[
  2
]
[
  2
]
[
  2
]
[
  2
]
[
  2
]
[
  3
]
[
  4
]
[
  4,
  0
]
[
  4,
  1
]
```

As can be seen from the above response the trace address [2] appear multiple times.

**Expected behavior**
No duplicate traceAddresses.

**Screenshots**
NA

**Desktop (please complete the following information):**
This response was from Quicknode.

**Additional context**
All the traces with `traceAddress=[2]` have `to=0x0000000000000000000000000000000000000001` or `to=0x0000000000000000000000000000000000000002`.

**Comment by quickchase** [comment]
Chase from QuickNode here. Nethermind has the correct trace data, the output above is actually from OpenEthereum and this was my mistake. Very sorry.

**Comment by jkylling** [comment]
Thank you for clearing this up.

**Comment by quickchase** [comment]
Correction, this IS Nethermind. I got my nodes mixed up.

`Nethermind/v1.13.3-0-0e3289f55-20220624/X64-Linux/6.0.6`

**Comment by quickchase** [comment]
Still happening 1.14.1

**Comment by jmederosalvarado** [comment]
Need to check if PR #4472 will fixes this.
