### ISSUE TITLE
Cant get through Gray Glacier fork

### ISSUE THREAD

**Issue by krychla1** [NethermindEth/nethermind#4232]
Hi fellows!

**Describe the bug**
After months of running nethermind node it stuck a few blocks after Gray Glacier fork (client version 1.13.0). 
![image](https://user-images.githubusercontent.com/33096727/176993475-d475e4d6-4f68-4277-a188-8fa7962d3589.png)

I upgraded client to 1.13.4, after unsuccessful restart attempts I quit, disposed the db and synced again. No success, I again and again face difficulty discrepancies right after pivot block. 
![image](https://user-images.githubusercontent.com/33096727/176993497-80d419bf-e083-4aae-8407-9025a00db977.png)

I tried multiple different pivots/setups, still the same result.
Initial sync setup:
```  
"Sync": {
    "FastSync": true,
    "PivotNumber": 15057100,
    "PivotHash": "0x3681d30f14489ea2cb9caf891e8074b0e108c8e5ff10ddd37db5af8541b1a306",
    "PivotTotalDifficulty": "53010419136510774987329",
    "FastBlocks": true,
    "DownloadBodiesInFastSync": false,
    "DownloadReceiptsInFastSync": false,
  },
```

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version: 1.13.4-0-3e5972c24-20220701/X64-Linux/6.0.6
 - logs: [mainnet.log](https://github.com/NethermindEth/nethermind/files/9032677/mainnet.log)

Please take a look.
Thanks.

**Comment by tkstanczak** [comment]
@krychla1 thank you for the report, we will be looking into it. Since all our nodes are fine after transition I would suggest you to double check if you are running the newest Gray Glacier version binaries (we have seen reports in the past where old binaries would still be launched because of some configs) / deployment location.

**Comment by krychla1** [comment]
Thanks for quick feedback. Now I completely removed all the binaries and copied new instead of just replacing them like previously. Resync in progress, I will update you shortly.

**Comment by LukaszRozmej** [comment]
So the main change in the difficulty bomb was in the chainspec file (as is in most hardforks): https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Chains/foundation.json

So maybe that didn't get updated?

Our nodes are fine, I am resyncing one for test purposes.

**Comment by krychla1** [comment]
Seems guys, that this was the point. Thank you. 30minutes passed, no issues so far, I will get back and eventually close this one once I am fully synced again.

**Comment by krychla1** [comment]
I am fully synced again, thanks guys, you rock!
