### ISSUE TITLE
remote Execution Client TerminalBlockHash and TerminalBlockNumber are inconsistent

### ISSUE THREAD

**Issue by elopio** [NethermindEth/nethermind#4239]
**Describe the bug**
I'm testing teku + nethermind + mev-boost in kiln following this guide:
https://github.com/flashbots/mev-boost/wiki/Testing

At the end, when everything is running, Teku logs this error:

```
2022-07-02 17:59:16.856 ERROR - Merge       *** Transition Configuration error: remote Execution Client TerminalBlockHash and TerminalBlockNumber are inconsistent
  remote configuration: TransitionConfiguration{terminalTotalDifficulty=0x000000000000000000000000000000000000000000000000000012309ce54000, terminalBlockHash=0x0000000000000000000000000000000000000000000000000000000000000000, terminalBlockNumber=55127}
```

I reported this on [teku](https://github.com/ConsenSys/teku/issues/5884), where they told me this is a configuration error in Nethermind. So are the parameters in the guide wrong? Which is the right configuration?

**To Reproduce**
Follow the steps in:
https://github.com/flashbots/mev-boost/wiki/Testing

**Expected behavior**
Teku starts producing blocks built by the mev relay.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version 
```
~/workspace/kiln/nethermind/src/Nethermind/Nethermind.Runner$ dotnet run -c Release -- --version
Nethermind/v1.13.0-17-82f331a3e-20220704/X64-Linux/6.0.6
```

**Comment by MarekM25** [comment]
Hi! :) 

I think I fixed it some time ago. Are you using default kiln.cfg? Could you share your Nethermind config?. We shouldn't have Merge.TerminalBlockNumber set.

**Comment by elopio** [comment]
I'm starting it with:

```
dotnet run -c Release -- --config kiln --JsonRpc.Host=0.0.0.0 --JsonRpc.JwtSecretFile=/home/$USER/workspace/secret
```

So I guess that's the default kiln config. Let me know if there's more information I can share, I don't really know where to find it.

**Comment by MarekM25** [comment]
@elopio I tried it on master and I can confirm that we don't have this message with teku:
2022-07-02 17:59:16.856 ERROR - Merge       *** Transition Configuration error: remote Execution Client TerminalBlockHash and TerminalBlockNumber are inconsistent
  remote configuration: TransitionConfiguration{terminalTotalDifficulty=0x000000000000000000000000000000000000000000000000000012309ce54000, terminalBlockHash=0x0000000000000000000000000000000000000000000000000000000000000000, terminalBlockNumber=55127}
  
  from other issue https://github.com/NethermindEth/nethermind/issues/4253 I know that you're confused by docs, so I'm closing the issue but if you have still problem please let us know! :)

**Comment by elopio** [comment]
I'm testing again with teku using the latest commits on both, and this is not happening anymore.
