### ISSUE TITLE
stops running without any error indication in the logs

### ISSUE THREAD

**Issue by elopio** [NethermindEth/nethermind#4253]
**Describe the bug**
I'm running nethermind in ropsten from the kiln branch (which sounds weird but is what is suggested here: https://notes.ethereum.org/@launchpad/ropsten#Nethermind)

After a while, it just stops running. I cannot see any relevant information in the logs. If you tell me how to collect more information I can give it a try.

**To Reproduce**

Follow the instructions in https://github.com/flashbots/mev-boost/wiki/Testing/5540b9bfcc2324bf22dc5d56b18c69eca36115e1#nethermind

Execute with:
```
dotnet run -c Release -- --config ropsten --JsonRpc.Host=0.0.0.0 --JsonRpc.Enabled true --JsonRpc.JwtSecretFile=/home/$USER/workspace/secret --Merge.TerminalTotalDifficulty 100000000000000000000000 
```

Leave nethermind running for a while, then come back to find that it stopped running without any visible error messages.

The last thing in the console on this last try is:

```
2022-07-08 04:45:18.9881|State Sync 00.04:29:13 | ~19.01 % | 7835.80MB / ~41225.00MB | branches: 0.00 % | kB/s:    56 | accounts 5560873 | nodes 65802028 | diagnostics: 1.73.39ms 
2022-07-08 04:45:19.4675|Peers | with known best block: 5 | all: 9 | 
2022-07-08 04:45:20.1864|State Sync 00.04:29:14 | ~19.01 % | 7835.91MB / ~41225.00MB | branches: 0.00 % | kB/s:    86 | accounts 5560929 | nodes 65803334 | diagnostics: 2.72.68ms 
2022-07-08 04:45:20.5595|Peers | with known best block: 5 | all: 9 | 
2022-07-08 04:45:21.5654|State Sync 00.04:29:16 | ~19.01 % | 7836.11MB / ~41225.00MB | branches: 0.00 % | kB/s:   144 | accounts 5560933 | nodes 65806122 | diagnostics: 3.72.78ms 
```

**Expected behavior**
Nethermind starts providing blocks to the consensus client.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser none
 - Version  Nethermind/v1.13.0-17-82f331a3e-20220708/X64-Linux/6.0.6

**Comment by MarekM25** [comment]
HI @elopio,

This tutorial is outdated https://notes.ethereum.org/@launchpad/ropsten#Nethermind !. We merged everything to master: I will remove kiln branch today and update tutorial. I think we should try at first from master, because we changed many things since that time.

**Comment by elopio** [comment]
Ok, I'll try with master. Master for both kiln and ropsten, right?

**Comment by MarekM25** [comment]
yes, for both :) and for sepolia too

**Comment by MarekM25** [comment]
@elopio I'm closing it, because it was running on wrong-very old branch. If you notice any issues feel free to reopen/create a new issue

**Comment by elopio** [comment]
I've been running the master branch since last night and no error has appeared.
