### ISSUE TITLE
Embedd chainspecs as resources.

### ISSUE THREAD

**Issue by LukaszRozmej** [NethermindEth/nethermind#4266]
Chainspecs should be embedded in binaries. And allow being referenced by path (as now) and by name (embedded) from config files

**Comment by dceleda** [comment]
@LukaszRozmej could say more about the rationale?
It's always good to add them to an issue.

**Comment by LukaszRozmej** [comment]
So people won't use outdated chainspec when upgrading binaries for hardforks

**Comment by tkstanczak** [comment]
has some disadvantages too, does not allow for any quick fixes and adjustment or config fixes without release

**Comment by smartprogrammer93** [comment]
@tkstanczak you can still specify a chainspec from a file if needed. Please check the associated PR.
