### ISSUE TITLE
WebSocket subscription returns a confirmation but no subsequent data

### ISSUE THREAD

**Issue by SpeakinTelnet** [NethermindEth/nethermind#4268]
**Describe the bug**

When I make a webSocket subscription to my nethermind node I receive a confirmation that the subscription was properly registered but I don't receive any subsequent data.

**Versions**
 - OS:  Ubuntu 20.04 server
 - Nethermind Version : Nethermind/v1.13.4-0-3e5972c24-20220711/X64-Linux/6.0.6

**Relevent log and code**
Here's the RPC call I'm trying to make:
```
{'jsonrpc': '2.0',
 'id': '1',
 'method': 'eth_subscribe',
 'params': ['newPendingTransactions']}
```
URL:  `ws://127.0.0.1:8546`

following the call I receive this confirmation:

```
INFO     connected
INFO     {"jsonrpc":"2.0","result":"0x8523535fb20347dead97f1eeed36baec","id":1}
```
And on the Nethermind side:

```
Nethermind.Runner[137]: 2022-07-11 15:02:21.1195|Executing JSON RPC call eth_subscribe with params [newPendingTransactions]
```

After that I receive nothing and I hit my timeout at 60 sec.

**Additional relevent data**

my .env parameters:

```
NETHERMIND_CONFIG=xdai_validator

NETHERMIND_LOG_LEVEL=DEBUG

NETHERMIND_INITCONFIG_WEBSOCKETSENABLED=true
NETHERMIND_INITCONFIG_DISCOVERYENABLED=true

NETHERMIND_NETWORKCONFIG_MAXACTIVEPEERS=600
NETHERMIND_NETWORKCONFIG_DISCOVERYPORT=30304
NETHERMIND_NETWORKCONFIG_P2PPORT=30304

NETHERMIND_JSONRPCCONFIG_ADDITIONALRPCURLS=["http://localhost:8551|http;ws|net;eth;subscribe;engine;web3;client"]
NETHERMIND_JSONRPCCONFIG_ENABLED=true
NETHERMIND_JSONRPCCONFIG_ENABLEDMODULES=[Admin,Eth,Subscribe,Trace,TxPool,Web3,Net]
NETHERMIND_JSONRPCCONFIG_HOST="0.0.0.0"
NETHERMIND_JSONRPCCONFIG_PORT=8545
NETHERMIND_JSONRPCCONFIG_WEBSOCKETSPORT=8546

NETHERMIND_HEALTHCHECKSCONFIG_ENABLED=true
NETHERMIND_HEALTHCHECKSCONFIG_UIENABLED=true

NETHERMIND_PRUNINGCONFIG_CACHEMB=2048
```

I use the standard `xdai_validator.cfg` with the MEV module added

The same subscription method works for geth, avalanchego and matic Bor

The only error I can find is while checking the health it returns this:

```
{"status":"Unhealthy","totalDuration":"00:00:00.0002273","entries":{"node-health":{"data":{},"description":"The node is now fully synced with a network. Peers: 235. The node stopped processing blocks. The node stopped producing blocks.","duration":"00:00:00.0000274","status":"Unhealthy","tags":[]}}}
```

And while it returns as unhealthy my validator has no connection issue and doing http RPC calls returns the right values

**Comment by rubo** [comment]
@SpeakinTelnet We were unable to reproduce the issue on our end even with the configuration you provided. Is there anything else more specific we need to know? Are you able to constantly reproduce this issue?

**Comment by SpeakinTelnet** [comment]
Thank you for taking the time. I tried looking at why the node came out as unhealty but there wasn't much in the log except for  ``Could not find common ancestor with [HBR   ]`` which I couldn't find information on why it'd throw this error. 

The node is currently running in a LXC container so I've cloned it and started it exactly as-is but on a new database and it seems to work. I receive the websocket data on newHeads while it's syncing. I'll just wait until it is fully synced but it seems to indicate an issue with the db might be the culprit.

**Comment by SpeakinTelnet** [comment]
Ok so here's the end result in case someone ends up with a similar situation.

The database was definitely the culprit. It wasn't bad enough to make http calls unsuccessful neither did it cause any issue for my validators. It just threw off the websockets for some reason. 

I've sync the db on another node, everything was working. I did an nfs mount to the first node with the new database and it was also working. I still don't know how the db became in that state but it seems to be a really isolated issue.
