### ISSUE TITLE
Unable to deploy contracts on Gnosis

### ISSUE THREAD

**Issue by rickcain** [NethermindEth/nethermind#4276]
**Describe the bug**
We are unable to deploy the curve pool contract on Gnosis chain, always got the error message `PermissionDenied, permission denied for tx type: Create, actual permissions: None` no matter using any deployer addresses.

**To Reproduce**
1. Download and unzip the attached zip file: [permissionDeniedContract.zip](https://github.com/NethermindEth/nethermind/files/9098736/permissionDeniedContract.zip).
2. Run `yarn` to fetch the openzeppelin dependency.
3. Paste the private key in `.private_key` file.
4. `truffle-config.js` and `2_deploy_contracts.js` are already properly configured. Run `truffle migrate --network gnosis` to deploy the contract.
5. The error message `PermissionDenied, permission denied for tx type: Create, actual permissions: None` shows up.

**Expected behavior**
The contract can be deployed.

**Comment by dan-gnosis** [comment]
Tagging @alebanzas @Georgi87 @koeppelmann @igorbarinov into this issue

**Comment by LukaszRozmej** [comment]
Can you share more details about the deployment transaction, mainly: Sender address, Value, MaxFeePerGas, MaxPriorityFeePerGas, GasLimit, Data ?

Does the node you are using have  any custom local permissions set up? Or are you using standard gateway?

**Comment by rickcain** [comment]
@igorbarinov 
https://etherscan.io/address/0x5dbdd037e6f10fef42cac6d9129588fd49e2c0d9
https://bscscan.com/address/0x426223eef2e4f577767533aa1854E8b980b1Df5F

**Comment by rickcain** [comment]
Any updates?
@LukaszRozmej 
@igorbarinov

**Comment by 0xbeedao** [comment]
I get exactly the same response trying to deploy a contract today, using Hardhat.

`jsonRpcResponse: {"jsonrpc":"2.0","error":{"code":-32010,"message":"PermissionDenied, permission denied for tx type: Create, actual permissions: None"},"id":10}`

**Comment by 0xbeedao** [comment]
Same result with the same contract, trying to deploy via Remix

**Comment by pumpurum2** [comment]
@rickcain @0xbeedao 
It looks weird but try do decrease `runs` of optimizer. I used to get this error with 5000, but after changing to 1000 it deployed successfully

**Comment by jmederosalvarado** [comment]
Hi @rickcain @0xbeedao. See [issue in gnosis pm repo](https://github.com/gnosischain/pm/issues/1) explaining this. This error is something that the [TxPermissionContract](https://gnosisscan.io/address/0x7Dd7032AA75A37ea0b150f57F899119C7379A78b) is not liking about the transaction. Basically, there is a contract that determines whether a transaction has permission to execute or not. See the relevant code [here](https://github.com/poanetwork/posdao-contracts/blob/0315e8ee854cb02d03f4c18965584a74f30796f7/contracts/base/TxPermissionBase.sol#L250-L352).
