### ISSUE TITLE
Make proper formating of AggregateException in DnsClient

### ISSUE THREAD

**Issue by deffrian** [NethermindEth/nethermind#4283]
**Describe the solution you'd like**
Exception in DnsClient should be a warning and have nice log message

**Additional context**
This exception happens on sepolia.

Exception:
[dns_exception.log](https://github.com/NethermindEth/nethermind/files/9120091/dns_exception.log)

**Comment by dceleda** [comment]
Should be fixed in:
https://github.com/NethermindEth/nethermind/issues/3801
But was not.

**Comment by dceleda** [comment]
Related to:
https://github.com/NethermindEth/nethermind/pull/3705
