### ISSUE TITLE
Nethermind failing to provide ERC20 token balance

### ISSUE THREAD

**Issue by vyzaldysanchez** [NethermindEth/nethermind#4307]
**Describe the bug**
As RPC client consumer, I expect Nethermind properly return the balance of an ERC20 token for an specific address, as go-ethereum does. It appears to not do this.

**To Reproduce**

```
wscat -c "<Nethermind RPC URL>" -x '{"jsonrpc":"2.0","id":3,"method":"eth_call","params":[{"from":"0x0000000000000000000000000000000000000000","to":"<ERC20 Token address>","data":"0x70a08231000000000000000000000000<address with balance, removing the 0x off the address>"},"latest"]}'
```

It is responding with the following:

```
{"jsonrpc":"2.0","error":{"code":-32015,"message":"VM execution error.","data":"gas limit below intrinsic gas"},"id":3}
```

**Expected behavior**
It should properly return the available balance of the ERC20 token for the address.

**Screenshots**
Not Applicable

**Comment by rubo** [comment]
We couldn't reproduce the issue. For further investigation, could you please provide the Nethermind version, the network (chain) you're trying on, and if possible, the exact request causing the error.

**Comment by vyzaldysanchez** [comment]
@rubo thanks for taking a look, this is the specific request/call I'm trying to perform:

```
wscat -c "wss://link-eth.getblock.io/goerli/archive/axej8woh-seej-6ash-4Yu7-eyib1495dhno/" -x '{"jsonrpc":"2.0","id":3,"method":"eth_call","params":[{"from":"0x0000000000000000000000000000000000000000","to":"0x26aed131e6b13c20ee98284380e66ed010cf4a99","data":"0x70a082310000000000000000000000004f4f6a14fa0965da1c4bfce1e3cc7eaa962e6324"},"latest"]}'
```

This is resulting in the error described in the previously provided details.

**Comment by vyzaldysanchez** [comment]
@rubo as for the Nethermind version:

```
wscat -c "wss://link-eth.getblock.io/goerli/archive/axej8woh-seej-6ash-4Yu7-eyib1495dhno/" -x '{"jsonrpc":"2.0","id":3,"method":"web3_clientVersion"}'
```
Resulting in:

```
{"jsonrpc":"2.0","result":"Nethermind/v1.13.3-0-0e3289f55-20220721/X64-Linux/6.0.6","id":3}
```

I believe this is a really recent version, around 4 days old.

**Comment by rubo** [comment]
For balance, Nethermind reports `0x0000000000000000000000000000000000000000000000000000000000000000` with the request parameters you provided.

> I believe this is a really recent version, around 4 days old.

You're using the previous version while the latest one is 1.13.4. Nevertheless, we couldn't reproduce the problem on either of them. Also, the version string should contain today's timestamp (if you've run `web3_clientVersion` today, of course). That's weird and is a question to GetBlock as your BaaS provider about possible caching or node setup configuration. With this said, I'd recommend reporting the issue to them.

**Comment by jmank88** [comment]
> Also, the version string should contain today's timestamp (if you've run `web3_clientVersion` today, of course). That's weird and is a question to GetBlock as your BaaS provider about possible caching or node setup configuration. 

This is incorrect. The `web3_clientVersion` method reports client _build_ information. `v1.13.3-0-0e3289f55-20220721` is the full git tag for the official 1.13.3 release: https://github.com/NethermindEth/nethermind/releases/tag/1.13.3

**Comment by rubo** [comment]
@jmank88 Then where the `20220721` comes from? It should be `20220615` according to the release notes.

**Comment by jmank88** [comment]
Is July 21st not the date it was built?

**Comment by rubo** [comment]
@jmank88 The build date of the v1.13.3 is June 15, 2022.

**Comment by jmank88** [comment]
> @jmank88 The build date of the v1.13.3 is June 15, 2022.

I meant the day the binary was built by compiling the v1.13.13 from source. Regardless, I am now suspecting it is the day the binary was _launched_. Is the [ClientVersion class](https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Core/ClientVersion.cs) a singleton that effectively caches the date in the `_date` variable?

**Comment by rubo** [comment]
@jmank88 Sort of. In this case, I presume the timestamp shows the node's last start date. See the #4316.

**Comment by vyzaldysanchez** [comment]
Hi again @rubo,

We spun up a a couple of nodes on our side and we are still running into this issue, we would like some help debugging what could be wrong in our setup, if anything.

You can definitely reproduce the issue by using the following endpoints:

```
ws://54.88.171.72/ws
http://54.88.171.72/rpc
```

The call to perform is:

```
wscat -c "ws://54.88.171.72/ws" -x '{"jsonrpc":"2.0","id":3,"method":"eth_call","params":[{"from":"0x0000000000000000000000000000000000000000","to":"0x26aed131e6b13c20ee98284380e66ed010cf4a99","data":"0x70a082310000000000000000000000004f4f6a14fa0965da1c4bfce1e3cc7eaa962e6324"},"latest"]}'
```

**Comment by vyzaldysanchez** [comment]
We have two independently hosted instances that reproduce this bug and can share them.

**Comment by tkstanczak** [comment]
Strange, the message suggests that the gas limit is set too low. Can you explicitly try setting it to 2 million or sth and check if that works?

**Comment by rubo** [comment]
Their config has `JsonRpc.GasCap` set to `0`
