### ISSUE TITLE
Feature: Support `gnosis` as alias for `xdai`

### ISSUE THREAD

**Issue by yorickdowne** [NethermindEth/nethermind#4309]
**Is your feature request related to a problem? Please describe.**

With a merge-ready setup, the CL and EL network names are the same on Ethereum. For GBC, I need to special-case to supply `xdai` to Nethermind instead.

**Describe the solution you'd like**

It'd be helpful to have `--config=gnosis` as an option alongside `--config=xdai`

**Comment by MarekM25** [comment]
We implemented it - closing
