### ISSUE TITLE
Fix the timestamp in the version string

### ISSUE THREAD

**Issue by rubo** [NethermindEth/nethermind#4316]
**Describe the bug**
The version string shows the current date instead of the commit date. Thus, it shows a different version string each day (if restarted).

**To Reproduce**
Run Nethermind with the `--version` option.

**Expected behavior**
The version string must be the same for a given version regardless of the date.

**Screenshots**
![image](https://user-images.githubusercontent.com/337518/180880774-25eb8e7b-5ce6-4257-aab7-f1cb6cfc31de.png)

**Comment by dceleda** [comment]
@rubo can we close it?

**Comment by dceleda** [comment]
There is a side effect - to compile the solution now MsBuild has to be at least in v17.3
In other cases we'll get:
`error MSB4185: The function "UtcNow" on type "System.DateTimeOffset" is not available for execution as an MSBuild property function.`
