### ISSUE TITLE
Snap Healing

### ISSUE THREAD

**Issue by dceleda** [NethermindEth/nethermind#4324]
Introduce handling of Snap-specific methods - **GetTrieNodes** (0x06) and **GetByteCodes**  (0x04) - to healing and fast sync. 
Soon Geth will decommission old GetNodeData (eth protocol).

**Comment by kamilchodola** [comment]
@dceleda @asdacap 
Do you guys have any PRs related to this work?
I need to have any branch to test it out :) And info about what was exactly changed and what is already tested here.

**Comment by kamilchodola** [comment]
Now I see it (other view used) :)
