### ISSUE TITLE
Shutdown with warning when disk space is low

### ISSUE THREAD

**Issue by flcl42** [NethermindEth/nethermind#4325]
**Is your feature request related to a problem? Please describe.**
The database grows in size constantly when the client runs, it may lead to the situation when there is no more space on device
The client still tries to save the data, which results in data saving errors and possible database inconsistency

**Describe the solution you'd like**
To prevent from database issues that may appear when more space is allocated and the client continues running
Let the client shutdown gracefully with a warning message, that may look like that:
"Client execution is stopped because there is not enough space left on the device. Please, allocate more space for %db_path%, then start the client again"

**Describe alternatives you've considered**
The users may try to use pruning to free some space, should we inform about such option? How the client should behave when it starts and there is still not enough space, but the pruning is enabled?

**Additional context**

Full pruning should not break the database and rollback correctly when the client terminates due to lack of space.
// TODO: Add the current exceptions we get when out of space

**Comment by kamilchodola** [comment]
From my perspective:
Add a warnings about low disk space from about 5% of free space (constant warnings like every 5 minutes).
When disk is critically low (1%) stop node gracefully.

BUT
Keep a configuration option for warning and for stop and have option to disable it entirely (for testing purpose mostly - to be able to crash node this way, free some space and see if node will be able to restore).

**Comment by damian-orzechowski** [comment]
> From my perspective: Add a warnings about low disk space from about 5% of free space (constant warnings like every 5 minutes). When disk is critically low (1%) stop node gracefully.
> 
> BUT Keep a configuration option for warning and for stop and have option to disable it entirely (for testing purpose mostly - to be able to crash node this way, free some space and see if node will be able to restore).

Wondering if the thresholds should be in percentage - on large drives that might give early warning and report the node unhealthy in the HealthChecks.
