### ISSUE TITLE
Slow syncing of testnet

### ISSUE THREAD

**Issue by gelleson** [NethermindEth/nethermind#4334]
**Describe the bug**
The Sokol tenet full is syncing too slowly. I deployed 20 days ago but it is still syncing

**To Reproduce**
1. Deploy and wait
**Expected behavior**
I thought is no need for a lot of time to sync

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker
 - Version v1.13.3

**Additional context**
```shell
2022-07-29 17:51:45.4560|Downloaded 26867299 / 27096163 | current     0.00bps | total     0.01bps 
2022-07-29 17:51:46.3894|Sync mode changed from FastSync to Disconnected 
2022-07-29 17:51:46.4562|Waiting for peers... 0s 
```
mostly  I see this in console 
2022-07-29 17:51:50.4586|Waiting for peers... 4s 
2022-07-29 17:51:51.4594|Waiting for peers... 5s 
2022-07-29 17:51:52.4595|Waiting for peers... 6s 
2022-07-29 17:51:53.4597|Waiting for peers... 7s 
2022-07-29 17:51:54.4597|Waiting for peers... 8s 
2022-07-29 17:51:55.4602|Waiting for peers... 9s 

```shell
sh -ac exec /nethermind/Nethermind.Runner --config="sokol" --datadir=/data --baseDbPath=/data --Network.P2PPort=30303 --Network.DiscoveryPort=30303 --Network.LocalIp=$(POD_IP) --Network.ExternalIp=$(POD_IP) --JsonRpc.Enabled=true --JsonRpc.Host=0.0.0.0 --JsonRpc.Port=8545 --Init.WebSocketsEnabled=true --JsonRpc.WebSocketsPort=8545 --Metrics.Enabled=true --Metrics.ExposePort=6060 --Metrics.NodeName=$(POD_NAME) --HealthChecks.Enabled=true --JsonRpc.GasCap=100000000 --JsonRpc.Timeout=20000 --JsonRpc.MaxRequestBodySize=30000000
```

**Comment by gelleson** [comment]
Guys, we still have the same issue even when we have synced the node.

```bash
Waiting for peers...3s
```

Maybe you need some additional info regarding the node?

**Comment by gelleson** [comment]
@asdacap do you need additional info regarding the node? If need just ping me I will provide it :)

**Comment by jmederosalvarado** [comment]
I believe this is the same issue as #4332. @gelleson could you check if this is in fact the same issue and if the solution provided in my last comment there helps you?

**Comment by gelleson** [comment]
As we discussed it is doesn't work.

**Comment by asdacap** [comment]
Hi @gelleson , can you give some logs? And did you use the latest version? 1.14.5?

**Comment by kamilchodola** [comment]
@asdacap @gelleson 
Since sokol testnet is not supported anymore I'll close this issue.
