### ISSUE TITLE
RocksDbSharp.RocksDbException: IO error: While pread offset ... - potential problem with the new RocksDb

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#4349]
eth1_1        | 2022-08-01 21:30:53.9877|Processing loop threw an exception. Block: Nethermind.Consensus.Processing.BlockRef, Exception: RocksDbSharp.RocksDbException: IO error: While pread offset 31518720 len 4064: /ethclient/nethermind/nethermind_db/mainnet/receipts/121348.sst: Input/output error
eth1_1        |    at RocksDbSharp.Native.rocksdb_put(IntPtr db, IntPtr writeOptions, Byte[] key, Int64 keyLength, Byte[] value, Int64 valueLength, ColumnFamilyHandle cf) in /src/rocksdb-sharp/RocksDbSharp/Native.Wrap.cs:line 45
eth1_1        |    at Nethermind.Db.Rocks.ColumnDb.set_Item(Byte[] key, Byte[] value) in /src/Nethermind/Nethermind.Db.Rocks/ColumnDb.cs:line 61
eth1_1        |    at Nethermind.Blockchain.Receipts.PersistentReceiptStorage.Insert(Block block, TxReceipt[] txReceipts, Boolean ensureCanonical) in /src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs:line 178
eth1_1        |    at Nethermind.Consensus.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 203
eth1_1        |    at Nethermind.Consensus.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs:line 115
eth1_1        |    at Nethermind.Consensus.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 501
eth1_1        |    at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer) in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 335
eth1_1        |    at Nethermind.Consensus.Processing.BlockchainProcessor.RunProcessingLoop() in /src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 287

**Log file**
[log.txt](https://github.com/NethermindEth/nethermind/files/9239879/log.txt)

**Comment by dceleda** [comment]
I think it's a rocksdb bug (version included in 1.13.5):
https://github.com/facebook/rocksdb/issues/9220
Fixed here:
https://github.com/facebook/rocksdb/pull/9263
