### ISSUE TITLE
Question: `JsonRpc.GasCap` behaves differently from Geth's `rpc.gascap`

### ISSUE THREAD

**Issue by vyzaldysanchez** [NethermindEth/nethermind#4360]
As a result of [this issue](https://github.com/NethermindEth/nethermind/issues/4307) we were told that setting `--JsonRpc.GasCap 0` is problematic.

We see on the Geth documentation for [`rpc.gascap`](https://geth.ethereum.org/docs/interface/command-line-options) that it `sets a cap on gas that can be used in eth_call/estimateGas (0=infinite) (default: 50000000)`.

Why would the behavior for this be different on Nethermind that we cannot set it to 0 (infinite)?

**Comment by LukaszRozmej** [comment]
Hi @vyzaldysanchez we merged the fix will be in next release

**Comment by vyzaldysanchez** [comment]
Hi @LukaszRozmej, do you have a timeline on when is this release going out?

**Comment by rubo** [comment]
@vyzaldysanchez Although we don't have a confirmed deadline for the upcoming release, we expect it (either stable or unstable) next week if everything goes as planned.
