### ISSUE TITLE
Github CI is not running tests. 

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#4363]
![image](https://user-images.githubusercontent.com/9356351/182834247-bf6b506e-064d-40cf-8e50-719206725565.png)

Only first step - build is green. The rest of actions will never be finished.

**Comment by MarekM25** [comment]
Example: https://github.com/NethermindEth/nethermind/pull/4337

**Comment by LukaszRozmej** [comment]
It is blocked by another run
