### ISSUE TITLE
Illegal instruction: 4 upon first running the program

### ISSUE THREAD

**Issue by mcplums** [NethermindEth/nethermind#437]
All I'm trying to do is get this up and running with goreli. I've followed the instructions for macOS (10.14.3) using v0.9.6. When I enter ./Nethermind --config goerli I get the following:

```
2019-03-26 13:03:59.1003|INFO|1|Initializing Ethereum|
2019-03-26 13:03:59.1746|INFO|1|Loading chain spec from chainspec/goerli.json|
2019-03-26 13:03:59.3838|INFO|1|Using database directory nethermind_db/goerli/blocks|
Illegal instruction: 4
```

I've tried doing ./Nethermind.Runner --InitConfig.JsonRpcEnabled true --config goerli and it is the same error.

Am I being an idiot?

**Comment by tkstanczak** [comment]
AVX2 instruction missing likely. @mcplums please check if you have AVX2 supported by your processor:
http://csharpmulticore.blogspot.com/2014/12/how-to-check-intel-avx2-support-on-mac-os-x-haswell.html

for the workshop it will be possible to use in-memory DB instead that should load fine

**Comment by vicnaum** [comment]
I also have similar problem with dotnet crashing while syncing with goerli:

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [10412]

Deleting nethermind_db/goerli helped but not for long - after 70k blocks it crashed again.

As far as I checked - my CPU has AVX2 instruction, and the intel website also is positive about it:
Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz

What else can I check?

**Comment by tkstanczak** [comment]
@vicnaum, missed the message from you, can you try with the latest version (0.9.9) - we have updated the RocksDb version and the libs.
