### ISSUE TITLE
Get rid of ToArray from TreeSync

### ISSUE THREAD

**Issue by dceleda** [NethermindEth/nethermind#4377]
Maybe instead of allocating a new array in _TreeSync.PrepareRequest_ we could pass the existing collection?

`StateSyncItem[] requestedNodes = requestHashes.ToArray();`

**Comment by LukaszRozmej** [comment]
It's even worse on dispatch: https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Synchronization/StateSync/StateSyncDispatcher.cs#L38
