### ISSUE TITLE
estimateGas web3 API

### ISSUE THREAD

**Issue by sjmini** [NethermindEth/nethermind#4386]
**Describe the bug**

Below estimateGas Web3 API call produces "gas limit below intrinsic gas" error.
Is this expected behavior from the nethermind node?

**_web3.eth.estimateGas({ from: aa0, nonce: aa1, to: aa2, gas: 500, gasPrice: "20000000000", type: "0x0" });_**

**Expected behavior**
Different clients such as geth produce "21000" output.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version : Nethermind/v1.13.6-0-be7b4ab4c-20220808/X64-Linux/6.0.7

**Comment by LukaszRozmej** [comment]
I think this was fixed.
