### ISSUE TITLE
Nethermind appears synced but eth.getBlock('latest') returns an old block

### ISSUE THREAD

**Issue by ghost** [NethermindEth/nethermind#4391]
**Describe the bug**
My mainnet node seems to be working fine, but calling `eth.getBlock('latest')` returns an old block
![nethermind](https://user-images.githubusercontent.com/67484816/183644078-ccead17b-5329-4a39-aee2-cd67ccaaf069.png)

Looking through the logs around block `15304812` nethermind complained that:

`2022-08-09 02:02:22.8626|100% of nodes did not respond to a Ping message - 50/50`

(which is strange, because none of the other nodes on the same machine did have a problem at the time)
and then started syncing.

It synced up to `15304812` but then continued onwards from `15304815`. `15304813` and `15304814` do not appear in the logs 
[nethermind.log](https://github.com/NethermindEth/nethermind/files/9290233/nethermind.log)

Start Command:
```
dotnet run -c Release -- --config mainnet     \
--datadir=/node/mainnet/nethermind_data       \
--JsonRpc.Enabled=true                        \
--Sync.SnapSync=true                          \
--Network.P2PPort=10301                       \
--Network.DiscoveryPort=10301                 \
--JsonRpc.Port=10303                          \
--Network.ActivePeersMaxCount=50              \
--JsonRpc.Host=127.0.0.1            
```          

Version: `7b5b14f3534396e14c5bf6eb2be6a63b34c01007`

**Comment by aascft3** [comment]
Meanwhile `eth.getBlock('latest')` is returning the correct block again. Looking at the log I am realizing that Nethermind was reporting that a new block was discovered, but not that it was processed. Nethermind only started processing the blocks again 8.5 hours later. 
[nethermind_continued.log](https://github.com/NethermindEth/nethermind/files/9290448/nethermind_continued.log)
