### ISSUE TITLE
Incorrect gas value

### ISSUE THREAD

**Issue by sjmini** [NethermindEth/nethermind#4395]
**Describe the bug**
It seems that the Nethermind node sometimes estimates incorrect gas values.
When we execute the attached test case, the node produces 45811.
We think that the correct output is 43511.

**To Reproduce**
1. Download test files
[test_cases.zip](https://github.com/NethermindEth/nethermind/files/9292786/test_cases.zip)

2. Run the node with the following command
    Nethermind.Runner --config ./test_cases/nethermind.cfg

3. Execute the javascript test case

**Expected behavior**
43511

**Desktop (please complete the following information):**
 - OS: Linux
 - Version : Nethermind/v1.13.6-0-be7b4ab4c-20220808/X64-Linux/6.0.7

**Comment by sjmini** [comment]
Any comments or suggestions on this issue would be appreciated.

**Comment by DemuirGos** [comment]
The javascript code provided give the following error : ``[ERROR] TimeLock is not defined``

**Comment by sjmini** [comment]
@DemuirGos, Sorry for the error.

The error occurred because the TimeLock is a runtime contract object.

I will share you the source code of the TimeLock contract here for your reference.
[TimeLock.zip](https://github.com/NethermindEth/nethermind/files/9441560/TimeLock.zip)

In addition, this is not a TimeLock contract issue.
It seems that the Nethermind client calculates an incorrect gas value even when we do calling other contracts' function.

**Comment by dceleda** [comment]
@rubo the logic that estimates gas is quite complex. So take your time :)

**Comment by nlordell** [comment]
Just wanted to add to this issue, as we are seeing similar things.

For example, this `eth_estimateGas` call:
```json
{
  jsonrpc: "2.0",
  method: "eth_estimateGas",
  params: [
    {
      data: "0x13d79a0b000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000003600000000000000000000000000000000000000000000000000000000000000002000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000003635c9adc5dea000000000000000000000000000000000000000000000000000000000012d88aa058000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000003af210eec25e95f470fda218c9df9291adb7dcfd00000000000000000000000000000000000000000000000000038d7ea4c68000000000000000000000000000000000000000000000000000000000000013980400000000000000000000000000000000000000000000000000000000632cb5dd040495c3ef9351bd2138bc47e4018192d081a611e796cf906e2afc104355f85500000000000000000000000000000000000000000000000000038d7ea4c68000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000038d7ea4c6800000000000000000000000000000000000000000000000000000000000000001600000000000000000000000000000000000000000000000000000000000000041c1d85bef40ce5b68f8ca9c7ed61ab5db0aadccfbc3f67f753d106ff1aec9185a580ce393fbd948132f32b858a51fdd85aef09ac96d0ef8e2d640b42da21aeb931c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      from: "0xa21740833858985e4d801533a808786d3647fb83",
      to: "0x9008d19f58aabd9ed0d60971565aa8510560ab41"
    },
    "0xede586"
  ],
  id: 3748644
}
```

With Nethermind returns:
```json
{
  "jsonrpc": "2.0",
  "result": "0x23102",
  "id": 3748644
}
```

However, other nodes we've tested (Geth, Erigon, Tenderly) return:
```json
{
  "jsonrpc": "2.0",
  "id": 3748644,
  "result": "0x216d5"
}
```
