### ISSUE TITLE
trace_transaction includes extra calls in result

### ISSUE THREAD

**Issue by naddison36** [NethermindEth/nethermind#4410]
**Describe the bug**

`trace_transaction` of mainnet transaction [0xc21820596ea093f26f7afcbb114883c8fb31f7521d8bc2ff9c7c7ebe60fb7ea6](https://etherscan.io/tx/0xc21820596ea093f26f7afcbb114883c8fb31f7521d8bc2ff9c7c7ebe60fb7ea6) adds extra calls when comparing the results from `trace_replayTransaction`.

The second object in the `trace_transaction` results is a call to `0x0000000000000000000000000000000000000004` which is not a contract.
```json
{
      "action": {
          "callType": "call",
          "from": "0x803a2b40c5a9bb2b86dd630b274fa2a9202874c2",
          "gas": "0xac5f7",
          "input": "0x23b872dd",
          "to": "0x0000000000000000000000000000000000000004",
          "value": "0x0"
      },
      "blockHash": "0x22dd4a58533faa51295381734a861950295352693fb2c42e5e45964aef41ad1f",
      "blockNumber": 15309264,
      "result": {
          "gasUsed": "0x12",
          "output": "0x23b872dd"
      },
      "subtraces": 0,
      "traceAddress": [
          0
      ],
      "transactionHash": "0xc21820596ea093f26f7afcbb114883c8fb31f7521d8bc2ff9c7c7ebe60fb7ea6",
      "transactionPosition": 111,
      "type": "call"
  },
```

The third and sixth objects in the tx result also look incorrect and are not in the `result.trace` of `trace_replayTransaction` 

**To Reproduce**

Send a JSON RPC `trace_transaction` call to an archive node
```json
{
    "jsonrpc": "2.0",
    "method": "trace_transaction",
    "params": [
        "0xc21820596ea093f26f7afcbb114883c8fb31f7521d8bc2ff9c7c7ebe60fb7ea6"
    ],
    "id": 1
}
```

Send `trace_replayTransaction` for the same transaction and compare the `result.trace` output to the `result` of `trace_transaction`
```json
{
    "jsonrpc": "2.0",
    "method": "trace_replayTransaction",
    "params": [
        "0xc21820596ea093f26f7afcbb114883c8fb31f7521d8bc2ff9c7c7ebe60fb7ea6", ["trace"]
    ],
    "id": 1
}
```

**Expected behavior**

The `result` array in the `trace_transaction` response should be the same as the `result.trace` array in the `trace_replayTransaction` response.

**Desktop (please complete the following information):**
I'm calling [ArchiveNode.io](https://archivenode.io/)'s Nethermind node. I'm not sure what they are running it on.
 - OS: [e.g. Windows]

**Additional context**

You can also check against the Parity Trace on Etherscan https://etherscan.io/vmtrace?txhash=0xc21820596ea093f26f7afcbb114883c8fb31f7521d8bc2ff9c7c7ebe60fb7ea6&type=parity#raw

**Comment by naddison36** [comment]
It looks like the extra calls are to the precompiled `0x0000000000000000000000000000000000000004` contract  https://www.evm.codes/precompiled

**Comment by LukaszRozmej** [comment]
reverted in https://github.com/NethermindEth/nethermind/pull/4914
