### ISSUE TITLE
`EngineHost` only applied if `EnginePort` also specified

### ISSUE THREAD

**Issue by dbeal-eth** [NethermindEth/nethermind#4456]
**Describe the bug**
When configuring the `JsonRpc` module with `EngineHost`, the setting is not applied unless `EnginePort` is also specified (even if its the default value).

**To Reproduce**
1. Run nethermind with only parameter: `--JsonRpc.EngineHost=0.0.0.0`, which should expose the engine host to all open interfaces
2. Observe terminal output 

```
======================== Nethermind initialization completed ========================
...
JSON RPC     : http://localhost:8545 ; http://localhost:8551
...
=====================================================================================
```

3. attempt to run `curl <ip-of-nethermind>:8551`. It will be connection refused.

**Expected behavior**

Since specifying `--JsonRpc.Host=0.0.0.0` works with no additional configuration, `--JsonRpc.EngineHost=0.0.0.0` should also work with no additional configuration (aka `--JsonRpc.EnginePort`)

**Desktop (please complete the following information):**
 - OS: Linux x64, Nethermind Docker Image

 - Version 1.14.0

**Additional context**

Configuration works as expected when including `--JsonRpc.EnginePort=8551` after the given reproduction instructions above.

Specifying `--JsonRpc.Host=0.0.0.0` works as expected (i.e. `--JsonRpc.Port=8545` is not needed to apply host change)

**Comment by deffrian** [comment]
We can't change this behavior due to backward compatibility with clients configured with AdditionalRpcUrls. You have to specify EnginePort otherwise, it will use AdditionalRpcUrls(ttp://localhost:8551).

**Comment by dbeal-eth** [comment]
I don't completely understand your reasoning. You are saying there are people out there who are specifying one of `EngineHost` or `EnginePort` and `AdditionalRpcUrls` and expecting it to work a certain way?

maybe the best change would be to update the docs to make this requirement clear?

or, you could deprecate `EngineHost` and `EnginePort` and instead provide a combined option like `EngineHostPort` to completely prevent confusion over this
