### ISSUE TITLE
[Peers] When Peers number drop to 0, nethermind have problems to recover

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#4504]
**Describe the bug**
After some network issues peers number drops to 0. For about 20 minutes it was logging "Waiting for Peers" and nothing interesting happened. After restart of nethermind app, peers came back properly.

**To Reproduce**
Disconnect the network for a moment and check if peers dropped to 0 and then recover network connection.

**Expected behavior**
After reconnecting we should be able to recover and find peers back.

**Additional context**

**Comment by kamilchodola** [comment]
Additional logs and scenario. EL closed for longer time when CL was working. SNAP Phase1 is taking way much longer than in normal case, losing peers to 0 and recovering just few ones (1 to max 7). Progress really slow.
[goerli.logs.txt](https://github.com/NethermindEth/nethermind/files/9488761/goerli.logs.txt)

**Comment by kamilchodola** [comment]
After candidates cleanup progress speeded up but just for a moment and then slowed down again.

**Comment by smartprogrammer93** [comment]
Cannot reproduce this. and Ashraf's PR (#4528) solves the snapsync disconnecting peers issue.
My internet disconnected a couple of times, lost all peers. gained new peers again after connected right away. there was no need to restart the client or do anything manually.
