### ISSUE TITLE
Update to .NET 7

### ISSUE THREAD

**Issue by smartprogrammer93** [NethermindEth/nethermind#4512]
As part of performance improvement it is vital that we upgrade to .NET 7 once it is released. For details about performance improvements in .NET 7 checkout the following:
https://devblogs.microsoft.com/dotnet/performance_improvements_in_net_7/

**Comment by dceleda** [comment]
Related to https://github.com/NethermindEth/nethermind/issues/4570

**Comment by yamommasofat** [comment]
Trial and error brings forth progress and more needed solutions. Simplicity is the base compiled info merged from in growth to become a great knowledge BASE. Uneducated humans need simplicity to operate without becoming frustrated , thus becoming quitters. This is a thought factor for the masses. How many humans (per Capita) vs how many people use this information, vs how many people use this information correctly. 
       Great minds do not think alike. Great minds learn how to get along a teach others about what's happening on the way.
         Sincerely,
johnwesleyfuqua@gmail.com
