### ISSUE TITLE
No nonce field in PoA blocks

### ISSUE THREAD

**Issue by quickchase** [NethermindEth/nethermind#4545]
**Describe the bug**
It's unclear to me if this is a bug or intended behavior, but it is strange and it could affect Gnosis upcoming merge.

Currently, on xDai/Gnosis, Nethermind does not return a `nonce` field in the body of the response to `eth_getBlockByNumber`

On PoA networks this value is static, at `0x0000000000000000` (or it's `null`? Unclear) so I kind of understand why it's not returned on Gnosis.

However, on PoS networks it is ALSO set to `0x0000000000000000` and Nethermind does return it in the same request on Ropsten.

So, really, I think the "bug" is that Nethermind should return the `nonce` field in the block data, and it should be set to `0x0000000000000000`?

**To Reproduce**
Call `eth_getBlockByNumber` on a PoA chain, no `nonce` is returned.

**Expected behavior**
I would expect a `nonce` field to always exist in the response data, regardless of PoW, PoS, or PoA consensus.

**Comment by LukaszRozmej** [comment]
This is by design, `nonce` field doesn't make sense in AuRa networks. I think we followed OpenEthereum here. We potentially could include it but it wouldn't do much sense.

**Comment by quickchase** [comment]
Do you plan to start including it after the gnosis merge?

**Comment by ozgrakkurt** [comment]
`block.nonce` field is marked required in ethereum rpc spec so it would make sense to have it just to have compliance
