### ISSUE TITLE
Write RockssDB version info into the log file

### ISSUE THREAD

**Issue by dceleda** [NethermindEth/nethermind#4547]
We have a feature implemented by @flcl42 that logs RocksDB version to the console.
Unfortunately, it doesn't write that info into the log file. 
Maybe because the file stream is not initialized yet.
We should also write it to the file.

**Comment by smartprogrammer93** [comment]
Looks like we reverted logging the Db file version in #4351
also, #4333 only logged the Db file version for db patching.
@flcl42 can you confirm?

**Comment by flcl42** [comment]
@smartprogrammer93 yes, for db engine patching to be precise. Extracted from db metadata files, no other way found.
