### ISSUE TITLE
EIP-4844: Shard Blob Transactions

### ISSUE THREAD

**Issue by dceleda** [NethermindEth/nethermind#4558]
Implement [Shard Blob Transactions](https://www.eip4844.com/) 
https://eips.ethereum.org/EIPS/eip-4844

Devnet v6 scope is the most recent agreed set of features.

### Implementation and merging progress

Devnet-v6 ready on branch `feature/eip-4844-v6`.
The progress can be checked by revising [pull requests](https://github.com/NethermindEth/nethermind/pulls?q=label%3Aeip-4844) state

## Running locally

Docker image (Devnet-v6): `nethermindeth/nethermind:eip-4844-v6-36`
The source: [`feature/eip-4844-v6`](https://github.com/NethermindEth/nethermind/tree/feature/eip-4844-v6), see also: [Build Nethermind from source](https://github.com/NethermindEth/nethermind#build-from-source)

**Comment by kamilchodola** [comment]
Old issue, closing.
