### ISSUE TITLE
Specify hardware requirement for sync

### ISSUE THREAD

**Issue by dceleda** [NethermindEth/nethermind#4562]
We need to clearly specify in our docs what are minimal and recommended requirements to sync a node:
- network bandwidth
- IOPS
- IO (can be limited separately from IOPS)

**Comment by smartprogrammer93** [comment]
@FalcoXYZ finished the iops requirements and added them to docs

**Comment by FalcoXYZ** [comment]
https://docs.nethermind.io/nethermind/first-steps-with-nethermind/system-requirements#hardware-requirements
