### ISSUE TITLE
Nethermind stops syncing

### ISSUE THREAD

**Issue by jugene** [NethermindEth/nethermind#4569]
2022-09-15 10:42:21.2668|Processed   15537410 |    1,151ms of   1,151ms, mgasps   52.14 total   50.16, tps  615.37 total  394.52, bps    1.74 total    2.43, recv queue 0, proc queue 2
2022-09-15 10:42:21.2668|Rerunning block after reorg or pruning: 15537411 (0xd56cd6bf3eeaa0e33cce1035c7325b7a04b26c6cf04a1128f66e5d9f3e7a511f)
2022-09-15 10:42:21.6020|Rerunning block after reorg or pruning: 15537412 (0x3397fed8572b9d0b38da013d6d5db1fa6e1e1ef4e1615165f6d2c6997793f120)
2022-09-15 10:42:25.9589|Peers | with known best block: 44 | all: 44 |
2022-09-15 10:42:25.9763|Sync peers 44(44)/100
===[Active][Sleep ][Peer (ProtocolVersion/Head/Host:Port)    ][Transfer Speeds (L/H/B/R/N/S)      ][Client Info (Name/Version/Operating System/Language)     ]
--------------------------------------------------------------------------------------------------------------------------------------------------------------
2022-09-15 10:42:40.9780|Peers | with known best block: 83 | all: 84 |
2022-09-15 10:42:55.9782|Peers | with known best block: 96 | all: 96 |
2022-09-15 10:42:55.9782|Sync peers 96(96)/100
===[Active][Sleep ][Peer (ProtocolVersion/Head/Host:Port)    ][Transfer Speeds (L/H/B/R/N/S)      ][Client Info (Name/Version/Operating System/Language)     ]
--------------------------------------------------------------------------------------------------------------------------------------------------------------
2022-09-15 10:43:10.9837|Peers | with known best block: 97 | all: 97 |
2022-09-15 10:43:25.9827|Peers | with known best block: 98 | all: 98 |
2022-09-15 10:43:25.9827|Sync peers 98(98)/100
===[Active][Sleep ][Peer (ProtocolVersion/Head/Host:Port)    ][Transfer Speeds (L/H/B/R/N/S)      ][Client Info (Name/Version/Operating System/Language)     ]
--------------------------------------------------------------------------------------------------------------------------------------------------------------

After block 5537412

I have two node and issue is the same.
As I can see it can't find peers.

**Comment by MarekM25** [comment]
Did you run CL client?
Could you share full logs?
Did you read https://docs.nethermind.io/nethermind/first-steps-with-nethermind/running-nethermind-post-merge ?

**Comment by 1scrooge** [comment]
My three nodes stuck at block 15537393
Nethemind version is 1.14.1
Execution client config:
```
nethermind \
     --JsonRpc.Enabled=true 
     --HealthChecks.Enabled=true
     --JsonRpc.Host=0.0.0.0
     --config=mainnet
     --JsonRpc.EngineHost=0.0.0.0
     --JsonRpc.EnginePort=8551
     --JsonRpc.JwtSecretFile=/jwtsecret/jwtsecret
     --JsonRpc.AdditionalRpcUrls="ws|net;eth;subscribe;engine;web3;client|no-auth,http://0.0.0.0:8551|http;ws|net;eth;subscribe;engine;web3;client;trace"
     --JsonRpc.EnabledModules="Eth, Subscribe, Trace, TxPool, Web3, Personal, Proof, Net, Parity, Health, Rpc, Debug"
```
Last log from EC
```
ethereum_1  | 2022-09-15 11:07:13.5015|Executing JSON RPC call engine_exchangeTransitionConfigurationV1 with params [{
ethereum_1  |   "terminalTotalDifficulty": "0xc70d808a128d7380000",
ethereum_1  |   "terminalBlockHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
ethereum_1  |   "terminalBlockNumber": "0x0"
ethereum_1  | }]
ethereum_1  | 2022-09-15 11:07:14.5707|Executing JSON RPC call eth_getBlockByNumber with params [latest, False]
ethereum_1  | 2022-09-15 11:07:23.5012|Executing JSON RPC call engine_exchangeTransitionConfigurationV1 with params [{
ethereum_1  |   "terminalTotalDifficulty": "0xc70d808a128d7380000",
ethereum_1  |   "terminalBlockHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
ethereum_1  |   "terminalBlockNumber": "0x0"
ethereum_1  | }]
ethereum_1  | 2022-09-15 11:07:24.9336|Peers | with known best block: 96 | all: 97 |
ethereum_1  | 2022-09-15 11:07:28.5714|Executing JSON RPC call eth_getBlockByNumber with params [latest, False]
ethereum_1  | 2022-09-15 11:07:33.5017|Executing JSON RPC call engine_exchangeTransitionConfigurationV1 with params [{
ethereum_1  |   "terminalTotalDifficulty": "0xc70d808a128d7380000",
ethereum_1  |   "terminalBlockHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
ethereum_1  |   "terminalBlockNumber": "0x0"
ethereum_1  | }]
ethereum_1  | 2022-09-15 11:07:39.9345|Peers | with known best block: 98 | all: 99 |
ethereum_1  | 2022-09-15 11:07:39.9345|Sync peers - Initialized: 98 | All: 99 | Max: 100
ethereum_1  | ===[Active][Sleep ][Peer (ProtocolVersion/Head/Host:Port)    ][Transfer Speeds (L/H/B/R/N/S)      ][Client Info (Name/Version/Operating System/Language)     ]
```
Consensus client config:
```
/app/cmd/beacon-chain/beacon-chain --datadir=/data --execution-endpoint=http://192.168.50.32:8551 --jwt-secret=/jwtsecret/jwtsecret --mainnet --accept-terms-of-use
```
Consensus client log:
```
time="2022-09-15 11:10:58" level=warning msg="Execution client is not syncing" prefix=powchain
time="2022-09-15 11:10:58" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2022-09-15 11:11:03" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2022-09-15 11:11:08" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2022-09-15 11:11:12" level=warning msg="Execution client is not syncing" prefix=powchain
time="2022-09-15 11:11:13" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2022-09-15 11:11:18" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2022-09-15 11:11:23" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2022-09-15 11:11:26" level=warning msg="Execution client is not syncing" prefix=powchain
time="2022-09-15 11:11:28" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2022-09-15 11:11:33" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2022-09-15 11:11:38" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2022-09-15 11:11:40" level=warning msg="Execution client is not syncing" prefix=powchain
time="2022-09-15 11:11:43" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2022-09-15 11:11:48" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2022-09-15 11:11:53" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2022-09-15 11:11:54" level=warning msg="Execution client is not syncing" prefix=powchain
time="2022-09-15 11:11:58" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2022-09-15 11:12:03" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2022-09-15 11:12:08" level=warning msg="Execution client is not syncing" prefix=powchain
```
Any ideas?

**Comment by MarekM25** [comment]
time="2022-09-15 11:12:03" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
hmmm it looks like no peers on CL (prysm side?) 

Do you see any newPayload or forkchoiceUpdated messages in Nethermind?

**Comment by 1scrooge** [comment]
> time="2022-09-15 11:12:03" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0 hmmm it looks like no peers on CL (prysm or lighthouse?)
> 
its prysm
> Do you see any newPayload or forkchoiceUpdated messages in Nethermind?
>
no

**Comment by MarekM25** [comment]
So it looks like issue with peering on prysm side. Let me report it to the prysm team.

**Comment by MarekM25** [comment]
@1scrooge I have info from prysm team. 
You should check your firewall settings. More info: https://docs.prylabs.network/docs/prysm-usage/p2p-host-ip

**Comment by 1scrooge** [comment]
@MarekM25 Before merge it works with the same configuration

**Comment by MarekM25** [comment]
@1scrooge I can't help more. We need fcU and newPayload to work from prysm. Prysm is not sending these requests. We should create issue in prysm repo IMO. You can tag me of course. However, I don't think I can help you more on EL (Nethermind) side

**Comment by 1scrooge** [comment]
@MarekM25 could you recommend another CL?

**Comment by MarekM25** [comment]
All of them are great :)

**Comment by MarekM25** [comment]
I'm closing the issue. Feel free to comment and we will reopen if needed
