### ISSUE TITLE
Test .NET 7 before we migrate

### ISSUE THREAD

**Issue by dceleda** [NethermindEth/nethermind#4570]
.NET 7 is coming soon with many performance improvements. We could start testing the migration and see if we're able to notice any performance improvements.

**Comment by kamilchodola** [comment]
We should bring our SmokeTests and take some measurements on both .NET version to see a difference - same with Unit/Integrations tests

**Comment by tkstanczak** [comment]
@kamilchodola can this be closed now?

**Comment by tkstanczak** [comment]
closing
