### ISSUE TITLE
Health Check randomly returns Unhealthy Postmerge

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#4571]
**Describe the bug**
Discord topic:
https://discord.com/channels/629004402170134531/629004402170134537/1019934314189828166

/health endpoint has returned Unhealthy once during postmerge work.
On this configuration on user side pre_merge it never happened so maybe something is disturbing this endpoint a bit.

Logs:
[message (2).txt](https://github.com/NethermindEth/nethermind/files/9575072/message.2.txt)

**Comment by ThomasDalla** [comment]
Happened again: it briefly goes unhealthy (and alerts me) before going back healthy (seconds later).
I had been running for weeks before `The Merge` and did not have that issue.

New logs: [nethermind_logs_2.txt](https://github.com/NethermindEth/nethermind/files/9575774/nethermind_logs_2.txt)

**Comment by mrosack** [comment]
I can confirm this has been happening to me as well since the merge.

**Comment by darkobas2** [comment]
I can confirm. it says Unhealty because the node has stopped processing blocks instead of that its fully synced.
All my health checks are having issues now :) Would be cool to have a second status or something

**Comment by kamilchodola** [comment]
Hi all!

I'll monitor this endpoint for a moment but do you have anything specific about Your configurations? Do You use any webhook for uiHealthChecks or You have any kind of service which is pooling /health endpoint?

**Comment by mrosack** [comment]
I'm just pinging /health every 60 seconds.  I've been getting around it by adding a retry, it never fails on the retry.

**Comment by kamilchodola** [comment]
Can anyone of You just share You Nethermind + CL configs/run commands?
I'd try to reproduce it on our candidate for release with some more frequent checks but want to ensure if this is not configuration related stuff which may affect post-merge anything here.

**Comment by darkobas2** [comment]
> 

this should do
```
#!/bin/bash

health=0

while [ health != "1" ]
do
health=$(curl -s 0:8545/health |jq .status -r |grep -c Healthy)
  if [ "$health" != "1" ]
  then
    echo "NOT HEALTHY!"
  else
    echo "OK!"
    sleep 1
  fi

done
```

**Comment by kamilchodola** [comment]
@ThomasDalla 
Closed by mistake! Thanks for Your vigilance!

As for now we are trying to reproduce but with no luck - I just make a dummy code which was calling /health endpoint for more than 12 hours without any wait between calls and never had a Unhealthy. 
We are introducing some changes on healthchecks in next version which may fix this issue as well.

We are still investigating to ensure the root cause is fixed and will still try to reproduce :)

**Comment by daltonwide** [comment]
Same issue for me. Testing Nethermind+Lighthouse on Windows with Goerli. Everything seems fine otherwise.
<img width="319" alt="image" src="https://user-images.githubusercontent.com/8750603/193449944-cae73387-038f-44f4-911f-1603d3b05249.png">

**Comment by ostracoder** [comment]
Seems much better on my side with 1.14.3...

**Comment by kamilchodola** [comment]
Great @ostracoder @ThomasDalla! I can assume we can close this then.

@darkobas2, @mrosack - please give it a try and let us know even under this issue if it also worked for You :)

**Comment by mrosack** [comment]
Looking good for me as well!
