### ISSUE TITLE
[Smoke Tests] Test on slow VMs

### ISSUE THREAD

**Issue by dceleda** [NethermindEth/nethermind#4598]
We should run tests on low-performing VMs for example:
- low IO
- low IOPS
- slow network
- CPU
etc

**Comment by kamilchodola** [comment]
@dceleda 
Just wondering - as for now we are running smoke tests with this configuration:


![Image](https://user-images.githubusercontent.com/43241881/191781579-bb856430-a997-43d8-92c6-65eb3afd9f23.png)

Do we want to prepare separate SmokeTests pipeline which will run all of our chains and combinations with like 2 times slower or something? It would be nice to find at least 3 ranges to test in my opinion:
1. To weak
2. Minimum we want users to have
3. Optimal

**Comment by kamilchodola** [comment]
@FalcoXYZ @cbermudez97  It would be nice to consider that but it would surely requires a automatically removing VMs to avoid high costs

**Comment by kamilchodola** [comment]
Automatic removal of nodes on linode is applied.
We have a way to sync on weaker machines using NonValidatorNode=true OR using volumes which are having limited IOPS (7-10k).
Also we have 24/7 nodes running on highend linux amd machine, weak arm machine and disk-limited Windows machine so it is quite well covered.
