### ISSUE TITLE
[DOCS] Prysm config examples

### ISSUE THREAD

**Issue by dceleda** [NethermindEth/nethermind#4612]
In our docs we use `http-web3provider` in examples for Prysm:
https://docs.nethermind.io/nethermind/first-steps-with-nethermind/running-nethermind-post-merge

but its deprecated
`WARN The http-web3provider flag has been deprecated and will be removed in a future release,please use the execution endpoint flag instead execution-endpoint`

Check:
https://docs.prylabs.network/docs/install/install-with-script

**Comment by FalcoXYZ** [comment]
https://docs.nethermind.io/nethermind/first-steps-with-nethermind/running-nethermind-post-merge#running-prysm-with-nethermind
