### ISSUE TITLE
[DOCS] Checkpoint sync instructions

### ISSUE THREAD

**Issue by dceleda** [NethermindEth/nethermind#4615]
Instructions on how to configure checkpoint sync are terrible.
There are examples with Infura Urls including PROJECT-ID that are not even exaplained.
Why we don't have examples with 
https://eth-clients.github.io/checkpoint-sync-endpoints/

**Comment by FalcoXYZ** [comment]
Removed Infura (as it's deprecated) and changed example/instructions for each client. 
https://docs.nethermind.io/nethermind/first-steps-with-nethermind/running-nethermind-post-merge#checkpoint-sync
