### ISSUE TITLE
trace_block no longer returns miner records

### ISSUE THREAD

**Issue by tjayrush** [NethermindEth/nethermind#4616]
The same behaviour happens on Erigon (please see this issue: https://github.com/ledgerwatch/erigon/issues/5462).

While it is true that the miner no longer receives a reward for mining the block, the`eth_getBlockByNumber` routine continues to return a `miner` field. (In the case illustrated in the referenced issue, "miner": "0x57865ba267d48671a41431f471933aec32a7c7d1").

For our application, we use `trace_block` to find "every appearance of every address anywhere on the chain". By removing the miner from `trace_block` post-merge, the node now requires that we call the RPC twice for each block. Once (against `trace_block`) for all the `regular` address and once (against `eth_getBlockByNumber`) for the `miner`. This doubles our processing time when indexing the entire chain.

**Comment by LukaszRozmej** [comment]
@tjayrush Question mark does it makes sense to be included there as a 0 value reward? I am in doubt it does. The miner still does get all the fees so it should be there. I see that Erigon implemented it, though that doesn't make it right thing to do.

**Comment by tjayrush** [comment]
There's a positive reason to keep it as it reports addresses that are "involved: in the block even if there is no reward. Our application wants every appearance of every address. This is one of them.

What's the justification for removing it?
