### ISSUE TITLE
Nethermind.Trie.TrieException: Failed to load key 

### ISSUE THREAD

**Issue by pmalyszcf** [NethermindEth/nethermind#4619]
Hey everyone!

Im experiencing **random** exception throws: "Nethermind.Trie.TrieException: Failed to load key"
when i try to call **trace_block** or **trace_transaction** methods on my Nethermind node. **Consensus** client connected is **Lighthouse**.
The exception pops out **randomly**, on the **same blocks** that used to work just fine a moment ago.

Node ver. v1.14.1

**Example**:
I managed to pull trace_block/tx methods on this block and transaction yesterday:
15576000
0x48fe45fb1411f31e1db81a1ca9fbcb7e985db90366d80fc55d2350f96e343e79 

I tried to call them today and i got the exception:

**for trace_transaction**
`{
    "jsonrpc": "2.0",
    "error": {
        "code": -32603,
        "message": "Internal error",
        "data": "Nethermind.Trie.TrieException: Failed to load key ba21c5b18a875843c442f80df4c910475471938ec412d980b8ba56ccc9f3f8e1 from root hash 0x5cbd8a6090349991be4802a3ee4fb41bbbb64271257c4569c6565ad732d7903a.\n ---> Nethermind.Trie.TrieException: Node 0x5cbd8a6090349991be4802a3ee4fb41bbbb64271257c4569c6565ad732d7903a is missing from the DB\n   at Nethermind.Trie.Pruning.TrieStore.LoadRlp(Keccak keccak, IKeyValueStore keyValueStore)\n   at Nethermind.Trie.TrieNode.ResolveNode(ITrieNodeResolver tree)\n   at Nethermind.Trie.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Keccak startRootHash)\n   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash)\n   --- End of inner exception stack trace ---\n   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash)\n   at Nethermind.State.StateProvider.GetState(Address address)\n   at Nethermind.State.StateProvider.GetAndAddToCache(Address address)\n   at Nethermind.State.StateProvider.GetNonce(Address address)\n   at Nethermind.Consensus.Processing.TransactionProcessorAdapterExtensions.ProcessTransaction(ITransactionProcessorAdapter transactionProcessor, Block block, Transaction currentTx, BlockReceiptsTracer receiptsTracer, ProcessingOptions processingOptions, IStateProvider stateProvider)\n   at Nethermind.Consensus.Processing.BlockProcessor.BlockValidationTransactionsExecutor.ProcessTransactions(Block block, ProcessingOptions processingOptions, BlockReceiptsTracer receiptsTracer, IReleaseSpec spec)\n   at Nethermind.Consensus.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options)\n   at Nethermind.Consensus.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer)\n   at Nethermind.Consensus.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer)\n   at Nethermind.Consensus.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, ProcessingOptions options, IBlockTracer tracer)\n   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)\n   at Nethermind.Consensus.Processing.OneTimeChainProcessor.Process(Block block, ProcessingOptions options, IBlockTracer tracer)\n   at Nethermind.Consensus.Tracing.Tracer.Trace(Block block, IBlockTracer blockTracer)\n   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.Trace(Block block, ParityLikeBlockTracer tracer)\n   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.trace_transaction(Keccak txHash)"
    },
    "id": 1
}`

**and for trace_block:**
`{
    "jsonrpc": "2.0",
    "error": {
        "code": -32603,
        "message": "Internal error",
        "data": "Nethermind.Trie.TrieException: Failed to load key ba21c5b18a875843c442f80df4c910475471938ec412d980b8ba56ccc9f3f8e1 from root hash 0x5cbd8a6090349991be4802a3ee4fb41bbbb64271257c4569c6565ad732d7903a.\n ---> Nethermind.Trie.TrieException: Node 0x5cbd8a6090349991be4802a3ee4fb41bbbb64271257c4569c6565ad732d7903a is missing from the DB\n   at Nethermind.Trie.Pruning.TrieStore.LoadRlp(Keccak keccak, IKeyValueStore keyValueStore)\n   at Nethermind.Trie.TrieNode.ResolveNode(ITrieNodeResolver tree)\n   at Nethermind.Trie.PatriciaTree.Run(Span`1 updatePath, Int32 nibblesCount, Byte[] updateValue, Boolean isUpdate, Boolean ignoreMissingDelete, Keccak startRootHash)\n   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash)\n   --- End of inner exception stack trace ---\n   at Nethermind.Trie.PatriciaTree.Get(Span`1 rawKey, Keccak rootHash)\n   at Nethermind.State.StateProvider.GetState(Address address)\n   at Nethermind.State.StateProvider.GetAndAddToCache(Address address)\n   at Nethermind.State.StateProvider.GetNonce(Address address)\n   at Nethermind.Consensus.Processing.TransactionProcessorAdapterExtensions.ProcessTransaction(ITransactionProcessorAdapter transactionProcessor, Block block, Transaction currentTx, BlockReceiptsTracer receiptsTracer, ProcessingOptions processingOptions, IStateProvider stateProvider)\n   at Nethermind.Consensus.Processing.BlockProcessor.BlockValidationTransactionsExecutor.ProcessTransactions(Block block, ProcessingOptions processingOptions, BlockReceiptsTracer receiptsTracer, IReleaseSpec spec)\n   at Nethermind.Consensus.Processing.BlockProcessor.ProcessBlock(Block block, IBlockTracer blockTracer, ProcessingOptions options)\n   at Nethermind.Consensus.Processing.BlockProcessor.ProcessOne(Block suggestedBlock, ProcessingOptions options, IBlockTracer blockTracer)\n   at Nethermind.Consensus.Processing.BlockProcessor.Process(Keccak newBranchStateRoot, List`1 suggestedBlocks, ProcessingOptions options, IBlockTracer blockTracer)\n   at Nethermind.Consensus.Processing.BlockchainProcessor.ProcessBranch(ProcessingBranch processingBranch, ProcessingOptions options, IBlockTracer tracer)\n   at Nethermind.Consensus.Processing.BlockchainProcessor.Process(Block suggestedBlock, ProcessingOptions options, IBlockTracer tracer)\n   at Nethermind.Consensus.Processing.OneTimeChainProcessor.Process(Block block, ProcessingOptions options, IBlockTracer tracer)\n   at Nethermind.Consensus.Tracing.Tracer.Trace(Block block, IBlockTracer blockTracer)\n   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.TraceBlock(Block block, ParityLikeBlockTracer tracer)\n   at Nethermind.JsonRpc.Modules.Trace.TraceRpcModule.trace_block(BlockParameter blockParameter)"
    },
    "id": 1
}`

**Comment by MarekM25** [comment]
Your node wasn't synced or removed (pruned) data for this block. @LukaszRozmej is working on interesting plugin for tracing: https://github.com/NethermindEth/nethermind/pull/4535

However, Nethermind should return user-friendly error that we don't have a state for the block.

**Comment by pmalyszcf** [comment]
Thanks for help!
