### ISSUE TITLE
Better way of monitoring pruning progress?

### ISSUE THREAD

**Issue by ibhagwan** [NethermindEth/nethermind#4662]
I read the entire documentation regarding pruning so hopefully I didn't miss anything.

As per my understanding when using `Pruning.FullPruningTrigger=Manual` (which is the default), the way to initiate pruning is by enabling the `Admin` module via `JsonRpc.EnabledModules` and then caling `admin_prune`:
```sh
curl -X POST -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"admin_prune","params":[],"id":1}' \
  localhost:8545
```

The above, did start my pruning process, after which subsuequnt calls to `admin_prune` return `InProgress`:
```json
{
  "jsonrpc": "2.0",
  "result": "InProgress",
  "id": 1
}
```
That means that in order to check if the pruning is done I have to repeatedly call `admin_prune` (or check if there's more than one folder under `nethermind_db\<network>\state`?)

The issue I have with this approach is that the same API is used for **both starting and monitoring** the pruning, obviously there is `Pruning.FullPruningMinimumDelayHours` which defaults to 240 hours so once the pruning is done any subsequent call to `admin_prune` returns `Delayed`:
```json
{
  "jsonrpc": "2.0",
  "result": "Delayed",
  "id": 1
}
```

My issues/questions:
- I can't tell if the pruning succeeded or failed (for example, out of disk space) without shutting down the client by setting `Pruning.FullPruningCompletionBehavior="ShutdownOnSuccess"` which is undersireable for obvious reasons
- I don't wish to run pruning again at the end of `FullPruningMinimumDelayHours`, I just want to check if pruning was finished and wether it was succsful or not
- Following up on previous bullet: does `Delayed` mean pruning will automatically begin once the 240 hour timer set by `FullPruningMinimumDelayHours` ends? If so, that is also undesireable as I don't want to start pruning again automatically

**Comment by gituser** [comment]
Also there is a memory leak somewhere in Pruning if it's triggered manually.

My Nethermind crashed by OOM with 92GB in VM when I've activated pruning.

**Comment by dceleda** [comment]
> Also there is a memory leak somewhere in Pruning if it's triggered manually.
> 
> My Nethermind crashed by OOM with 92GB in VM when I've activated pruning.

@kkokosa

**Comment by ibhagwan** [comment]
Ty @kamilchodola!
