### ISSUE TITLE
Add ExtraData to PostMergeBlockProducer

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#4665]
We should change it here: https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PostMergeBlockProducer.cs#L96

1. Default ExtraData should be Nethermind https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Consensus/Producers/BlockProducerBase.cs#L319
2. Allow configuration of ExtraData in our application (maybe MergeConfig?)
3. Test on testnet validators (sepolia/goerli/ropsten). It could be tested together with: https://github.com/NethermindEth/nethermind/issues/4666

**Comment by OlegJakushkin** [comment]
Dear @MarekM25,
Added [PR 4734](https://github.com/NethermindEth/nethermind/pull/4734) to fix this issue.
Please review it.
