### ISSUE TITLE
Remove UtcNow from payload cleanups

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#4666]
I haven't noticed any bug connected to this. However, it would be great to remove the time clock dependency: https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs#L110

We could store N number of best payloads (order by timestamp).

Test on testnet validators (sepolia/goerli/ropsten). It could be tested together with: https://github.com/NethermindEth/nethermind/issues/4665

**Comment by OlegJakushkin** [comment]
Made a Draft PR
Currently starting testing (block creation on Sepolia, Volta, Goerli

**Comment by tkstanczak** [comment]
@OlegJakushkin can this be closed now?

**Comment by OlegJakushkin** [comment]
Yes
