### ISSUE TITLE
Typing error

### ISSUE THREAD

**Issue by elringo-tech** [NethermindEth/nethermind#4680]
Typing error on a tutorial

1. Go to https://docs.nethermind.io/nethermind/first-steps-with-nethermind/running-nethermind-post-merge#step-2-installing-consensus-client
2. "implementations to **_chose_** from"
**Expected behavior**
I think it should be "implementations to **_choose_** from"

 - OS: Windows 10
 - Browser: Brave 
 - [Version 1.43.93 Chromium: 105.0.5195.127 

![nether_type_error](https://user-images.githubusercontent.com/82232906/193162538-d38aa25c-ad48-427b-a14d-a77efc8b56a1.png)

**Comment by FalcoXYZ** [comment]
Fixed
