### ISSUE TITLE
State recovery

### ISSUE THREAD

**Issue by flcl42** [NethermindEth/nethermind#4684]
**Is your feature request related to a problem? Please describe.**
Sometimes it happens that a state requested during block processing is not found and need to be restored. Recovery should be applied to restore enough state for the block to be processed.

**Describe the solution you'd like**
The block processor may stop for short amount of time, state nodes (or codes) needed should be downloaded and the block should be re-run.

**Describe alternatives you've considered**
Fallback to synchronization from healthy status and restore all the state.

**Additional context**
The recovery should not be done for erroneously requested non-existent state.

**Comment by MarekM25** [comment]
@flcl42 I think this should be closed, isn't it?
