### ISSUE TITLE
[Gnosis/xDai] eth_getFilterLogs returns different output for the same parameters

### ISSUE THREAD

**Issue by a26nine** [NethermindEth/nethermind#4687]
**Describe the bug**
Trying to fetch the filter logs using `eth_getFilterLogs` after creating a new filter using `eth_newFilter` results in different outputs all the time.

**To Reproduce**
1. Create a new filter
```
{
  "jsonrpc": "2.0",
  "method": "eth_newFilter",
  "params": [
    {
      "blockHash": "0xe76c4a4be40f62a269668da1e38580dcff3726a129573f01565f8f494b23edb0",
      "topics": [
        "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
      ]
    }
  ]
}
```
2. Query the filter logs
```
{
  "jsonrpc": "2.0",
  "method": "eth_getFilterLogs",
  "id": 1,
  "params": [<FILTER_ID>]
}
```
3. Repeat steps 1 & 2 multiple times to see different results.

**Expected behavior**
`eth_getFilterLogs` should return identical data for the filter(s) with same parameters.

**Screenshots**
Test run for the above payload...
https://user-images.githubusercontent.com/103454930/193507773-62e86ebb-7e91-463d-9f1c-c551c327722c.mp4
Log: https://gist.github.com/qn-abraar/611cc866761767d4737a02fe7b96bb20

**Additional context**
Tested on Gnosis/xDai with Nethermind v1.14.1

**Comment by McSim85** [comment]
It seems like related to issue [2319](https://github.com/NethermindEth/nethermind/issues/2319)

**Comment by a26nine** [comment]
[`1.14.4`](https://github.com/NethermindEth/nethermind/releases/tag/1.14.4) fixes this. 🙌🏻

![Screenshot 2022-10-27 at 08 38 50](https://user-images.githubusercontent.com/103454930/198237010-b325550c-0cc3-4d2a-8c37-6f6e4ba94c5e.gif)
