### ISSUE TITLE
Include Docker steps for nethermind workshop

### ISSUE THREAD

**Issue by motatoes** [NethermindEth/nethermind#471]
Hello,

I have been experimenting with a Dockerfile workflow for use in the workshops which would build a base nethermind image compiled from source and then run a spaceneth node  (as in the [`all platforms`](https://nethermindworkshop.readthedocs.io/en/latest/build.html#all-platforms) section of the docs). Here is the docker file which I created (named `Dockerfile_workshop`)

```
FROM microsoft/dotnet:2.2-sdk AS build
COPY . .
RUN git submodule update --init
RUN apt-get update && apt-get -y install libsnappy-dev libc6-dev libc6 unzip
RUN cd src/Nethermind && dotnet build Nethermind.sln -c Release

EXPOSE 8345 30312

WORKDIR src/Nethermind
```

and then to start the container instance I run

```
git clone https://github.com/nethermindeth/nethermind nethworkshop --recursive -b workshop
cd nethworkshop
docker build  -t nethermind  --file Dockerfile_workshop .
docker run -d -t --name spaceneth nethermind
```

Finally, the user can continue in the all platforms section but skip the first part of cloning the repository. The only additional step is to start a new terminal one needs to run the following command to attach to the container shell:

```
docker exec -it spaceneth /bin/bash 
```

By using this flow I did not have issues with RocksDB as I previously encountered on my Mac.

If you think this is useful for your upcoming workshops I can create a PR for it (documentation + dockerfile) @tkstanczak

**Comment by tkstanczak** [comment]
@motatoes added it to the workshop docs. Thanks!

**Comment by motatoes** [comment]
@tkstanczak please also merge https://github.com/NethermindEth/workshop/pull/5 to the docs to fix code formatting

**Comment by tkstanczak** [comment]
@motatoes done, thanks
