### ISSUE TITLE
Resolve or hide "Unhandled packet type" logs

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#4718]
**Describe the bug**
During every sync there are a few "Unhandled packet type" logs which are marked as Errors when in reality it is just something invalid and does not affect syncing process.
We need to think if we can do something about that (if something like this occurs give some additional data - try to resolve it to see if this is really a error or nothing to worry about or if all of them are things which we can't do anything about and is not a problem to sync, then hide it or change log level to Info.

Here screen from mainnet-teku sync:
![image](https://user-images.githubusercontent.com/43241881/194264841-2b602afb-7e82-4626-b81d-37697fbea204.png)

**Comment by MarekM25** [comment]
Related issue: https://github.com/NethermindEth/nethermind/issues/86
