### ISSUE TITLE
"Failed to notify enode" - root cause analysis of NullReferenceException 

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#4722]
**Describe the bug**
From time to time it happens that we have multiple failures on SmokeTests runs with "Failed to notify enode" and NullReferenceException.
Need to investigate and fix a root-cause for that since it was not appearing most probably on pre-merge version.

This is a minor issue - no issues with syncing happens because of that.
![image](https://user-images.githubusercontent.com/43241881/194316520-0a8c83a1-2cb2-4b70-b3fa-88ba76e67b3a.png)

**Comment by kamilchodola** [comment]
@smartprogrammer93 @MarekM25 
Any info there? It still appears from time to time on nodes and just wanted to ensure if this can make any issue on node.

**Comment by smartprogrammer93** [comment]
I will check on it tomorrow @kamilchodola

**Comment by kamilchodola** [comment]
@smartprogrammer93 Great! Thanks

**Comment by kamilchodola** [comment]
https://seq.nethermind.io/#/events?filter=Contains(NodeName,%20'Smoke-Tests-Snap-144-FastSync-goerli')%20and%20not%20%22Big%20Snappy%20messag%22%20and%20not%20%22block%20producer%20%26%20sealer%22&from=2022-10-21T23:50:00.000Z&to=2022-10-22T00:00:00.000Z

Appeared there on goerli on current smoke tests

**Comment by smartprogrammer93** [comment]
Hey @kamilchodola ,

Let me know if you still see this issue from a version after https://github.com/NethermindEth/nethermind/pull/4874 is merged.

**Comment by kamilchodola** [comment]
@smartprogrammer93 
I can see that one again but only once in one node.
https://seq.nethermind.io/#/events?filter=Contains(NodeName,%20'Smoke-Tests-master125v2-goerli-lighthouse')%20and%20%22failed%20to%22
![image](https://user-images.githubusercontent.com/43241881/205869391-1601e8a1-5632-4edc-84f2-f5979b8d24d8.png)

**Comment by kamilchodola** [comment]
@smartprogrammer93 
Got spammed with those messages again
![image](https://user-images.githubusercontent.com/43241881/207705252-982ec171-aeb7-4a7c-8da1-670def0fdf71.png)
Unfortunately I got spammed with Debug logs and app removed file with logs for this specific situation - but seems like it is getting a bit stronger now

**Comment by kamilchodola** [comment]
@smartprogrammer93 
Will try to reproduce it or will be more careful about those logs and will try to catch debug logs for You 0 maybe that would help.

**Comment by smartprogrammer93** [comment]
@kamilchodola  are we still seeing these?

**Comment by smartprogrammer93** [comment]
@kamilchodola  let me know if you are still seeing these exceptions or not. If not i will close this one.

**Comment by kamilchodola** [comment]
@smartprogrammer93 
Just happened again... Wondering about problems it may cause for us or network in such case.
This time it was on mainnet-lighthouse pair.
<img width="565" alt="image" src="https://github.com/NethermindEth/nethermind/assets/43241881/97b0c712-9331-48d8-88ee-faa4b53479c6">

**Comment by smartprogrammer93** [comment]
@kamilchodola same stack trace (exception details?)

**Comment by kamilchodola** [comment]
@smartprogrammer93 
Yeah - looks slightly different:
<img width="774" alt="image" src="https://github.com/NethermindEth/nethermind/assets/43241881/d1c0fd75-2563-4e89-ab60-ad515169f011">

**Comment by MarekM25** [comment]
@smartprogrammer93 still happening

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Nethermind.Network.P2P.ProtocolHandlers.SyncPeerProtocolHandlerBase.TxsToSendAndMarkAsNotified(IEnumerable`1 txs, Boolean sendFullTx)+MoveNext() in /_/src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs:line 229
   at Nethermind.Network.P2P.Subprotocols.Eth.V65.Eth65ProtocolHandler.SendNewTransactionsCore(IEnumerable`1 txs, Boolean sendFullTx) in /_/src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandler.cs:line 167
   at Nethermind.TxPool.TxBroadcaster.Notify(ITxPoolPeer peer, IEnumerable`1 txs, Boolean sendFullTx) in /_/src/Nethermind/Nethermind.TxPool/TxBroadcaster.cs:line 310
```

**Comment by smartprogrammer93** [comment]
Yup, @MarekM25 cant figure out the reason. Will try to investigate again once possible

**Comment by smartprogrammer93** [comment]
i spend a couple more hours on this, cant find a way for a null tx to reach this point of the code. I traced it back all the way to `TxPool`. Only solution i see (workaround) is to check if Tx is null before entering here.

**Comment by smartprogrammer93** [comment]
i spend a couple more hours on this, cant find a way for a null Tx ref to reach this point of the code. I traced it back all the way to TxPool. Only solution i see (workaround) is to check if Tx is null before trying to read it's hash.
@MarekM25 let me know if you want me to follow this approach, or any other possible action.

**Comment by kamilchodola** [comment]
Didn't had that for a looong time so closing for now.
