### ISSUE TITLE
Return Logging Level explicitly. 

### ISSUE THREAD

**Issue by DigiDr** [NethermindEth/nethermind#4729]
**Is your feature request related to a problem? Please describe.**
Currently logs are visualised with colours by default. This is nice, but we want to be able to filter them by text to discover any issues. 

**Describe the solution you'd like**

-  Consider including logging level in every line by default
- E.g. <timestamp> <logging level> <module> <log>
 
**Describe alternatives you've considered**
Can probably be done with NLog.config manually, but should be baked in by default.

**Comment by pxyxyrus** [comment]
Can I work on this?

**Comment by marcindsobczak** [comment]
Logging level is already included in logs saved to the file and in seq, it was added a few month ago
