### ISSUE TITLE
Metrics endpoint is not working for Gnosis/Chiado

### ISSUE THREAD

**Issue by dharmendrakariya** [NethermindEth/nethermind#4746]
**Describe the bug**

When giving ```--Metrics.Enabled=true``` I am expecting to see something in grafana dashboard!

When I hit the http://localhost:8545/metrics I see 
```
# curl localhost:8545/metrics
Nethermind JSON RPC# 
```

**To Reproduce**

Go to 'https://github.com/gnosischain/nethermind-client/blob/main/docker-compose.yml' and give above  lag
Run docker-compose up --build -d
Check the docker logs
Deploy the monitoring stack using https://github.com/NethermindEth/metrics-infrastructure/blob/master/docker-compose.yml
Try to see the metrics

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Additional context**

**Comment by MarekM25** [comment]
Hi @dharmendrakariya,

8545 port is for JsonRpc, not for metrics. Could you take a look at Metrics configuration Metrics.ExposePort? https://docs.nethermind.io/nethermind/ethereum-client/configuration/metrics
