### ISSUE TITLE
Beacon Headers stucked on downloading with a negative total speed

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#4772]
**Describe the bug**
On Smoke tests run, noticed that node mainnet-lodestar stucked on beacon headers with a total download speed set to negative value.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22

**Additional Info**
https://seq.nethermind.io/#/events?filter=Contains(NodeName,%20'Smoke-Tests-Gnosis-Fuzzer-Master-mainnet-lodestar')&to=2022-10-14T15:50:00.000Z
If needed I can download logs but on Seq those should be available.

**Comment by kamilchodola** [comment]
[mainnet.logs.0.zip](https://github.com/NethermindEth/nethermind/files/9800481/mainnet.logs.0.zip)
[mainnet.logs.1.zip](https://github.com/NethermindEth/nethermind/files/9800482/mainnet.logs.1.zip)
[mainnet.logs.2.zip](https://github.com/NethermindEth/nethermind/files/9800483/mainnet.logs.2.zip)
[mainnet.logs.zip](https://github.com/NethermindEth/nethermind/files/9800485/mainnet.logs.zip)

**Comment by asdacap** [comment]
Multiple consecutive start new beacon header. Last one skipped a block.

**Comment by asdacap** [comment]
FCU for `15747311` occurs after FCU for `15747312` instead of before.

**Comment by asdacap** [comment]
No idea why. Need running node.
