### ISSUE TITLE
[Lighthouse] Node not progressing on Fast Sync stage (Downloaded stucked and total speed is almost 0)

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#4788]
**Describe the bug**
On smoke tests run with 14.4 RC version noticed that one of a nodes is stucked on Downloading new blocks (close to the end) and total speed dropped almost to 0. Traces where disabled but maybe we can extract something from logs and make some adjustments.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Version  release\1.14.4

**Logs**
[mainnet.logs.0.zip](https://github.com/NethermindEth/nethermind/files/9837929/mainnet.logs.0.zip)

**Comment by asdacap** [comment]
May be resolved by https://github.com/NethermindEth/nethermind/commit/5ec03811203c0465e3993036eec03dc30e5af2e1. Need new example.
