### ISSUE TITLE
Not starting on ubuntu 19.04

### ISSUE THREAD

**Issue by vbuterin** [NethermindEth/nethermind#479]
```
untrusted@untrusted-Standard-PC-Q35-ICH9-2009:~$ ./Nethermind.Launcher 
? Select network Mainnet
? Select sync Fast sync
No usable version of the libssl was found
```

Running this on fresh Ubuntu 19.04. I haven't been able to find any fixes. Looking at https://github.com/Microsoft/vscode-python/issues/5373 and https://github.com/OmniSharp/omnisharp-vscode/issues/3010 gives me the impression that this needs to be fixed inside nethermind somehow, but not sure...

**Comment by tkstanczak** [comment]
@vbuterin, I tested on 19.04 yesterday and there was indeed a compatibility issue with openssl - .NET Core only works with openssl 1.1.0 or lower and 19.04 comes with 1.1.1b. It will work on 16.04, 18.04, 18.10 and it is also confirmed to work on 19.04 with a self-build 1.1.0 openssl (according to @roninkaizen who tested it a few days ago)

**Comment by tkstanczak** [comment]
I was just updating documentation on that yesterday when I found out the issue
https://nethermind.readthedocs.io/en/latest/platforms.html

We expect that with .NET Core 3 release in July we will have an out of the box support for 19.04

**Comment by tkstanczak** [comment]
@matilote , can we check with .NET Core Preview 7 on Ubuntu 19.04 please

**Comment by one-three-three-seven** [comment]
Nethermind 1.1 does run on Kubuntu 19.04 and Ubuntu 19.10.

![OC9iBex5at](https://user-images.githubusercontent.com/35700046/66199070-2155c080-e69e-11e9-9245-c2374e3a909f.png)

**Comment by tkstanczak** [comment]
starting now, fixed
