### ISSUE TITLE
TxPool further improvements

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#4793]
It seems that we made quite significant optimization here: https://github.com/NethermindEth/nethermind/pull/4702

I added metric: PendingTransactionsWithExpensiveFiltering. Ideally, we should filter as many transactions as possible before we reach this metric. 

One potential idea:
When our TxPool is full we shouldn't accept Tx which are worse (in terms of GasPrice) than our worse transaction in TxPool. We're doing something like this in FeeTooLowTxFilter: https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.TxPool/TxPool.cs#L119

However, it should be implemented without accessing the state. If we're accessing state we won't have benefits of optimization.

**Comment by kamilchodola** [comment]
@deffrian @MarekM25 
Shall it be closed since this one is merged?
https://github.com/NethermindEth/nethermind/pull/4820

**Comment by deffrian** [comment]
> @deffrian @MarekM25 Shall it be closed since this one is merged? #4820

@kamilchodola I reopened this issue because #4820 isn't fixing it

**Comment by MarekM25** [comment]
Yes, we can optimize it more :)

**Comment by MarekM25** [comment]
Yes, we can optimize it more :)





> > @deffrian @MarekM25 Shall it be closed since this one is merged? #4820
> 
> @kamilchodola I reopened this issue because #4820 isn't fixing it


Yes, we can optimize it more :)
