### ISSUE TITLE
TrieExceptions after restarting a fastsynced node with Prysm

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#4800]
**Describe the bug**
I've fully synced a node with FastSync configuration and noticed, that after restarting it, a lot of TrieExceptions appeared. Looking at logs seems like it was a graceful shutdown (unfortunately logger did not report this).

No info from other nodes as for now since still syncing.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - mainnet-prysm
 - FastSync

**Logs**
[mainnet-prysm-fastsync.zip](https://github.com/NethermindEth/nethermind/files/9843967/mainnet-prysm-fastsync.zip)

**Comment by asdacap** [comment]
Rerunning block on `15802357`, last processed block is `15802421`, which is exactly 64 block.
