### ISSUE TITLE
Nethermind fills SWAP despite free memory and low vm.swappiness

### ISSUE THREAD

**Issue by 499602D2** [NethermindEth/nethermind#4802]
**Describe the bug**
No matter the `Init.MemoryHint` option, Nethermind always slowly but steadily fills up the swap on my system. The machine has 32 GB of memory, and `vm.swappiness` set to 5. Currently, 3.11/4 GiB of swap is in use, while only 17.1/31.2 GiB of memory is being used.

Only other programs running are Nimbus and mev-boost, both of which behave nicely.

**To Reproduce**
Happens always.

**Expected behavior**
- Nethermind uses available memory instead of swapping onto the disk.
- Increasing `init.MemoryHint` reduces swap usage. It has no effect: only increases memory usage.
- Reducing `init.MemoryHint` reduces swap usage. It has no effect: only decreases memory usage.

**Screenshots**
[Grafana dashboard](https://i.imgur.com/WMqpHLE.png) with evolution of memory usage over the last four days. Initial drop in swap usage is due to a restart of Nethermind.

[Screenshot from htop.](https://i.imgur.com/x8H7ldm.png) Notice the obscure amount of swap usage.

**Desktop (please complete the following information):**
- CPU: 4C/4T i5-6500T
- Memory: 32 GB
- OS: Ubuntu 22.04.1 LTS
- Browser: N/A
- Version: `Nethermind/v1.14.3-0-707461293-20221022/X64-Linux/6.0.9`

**Additional context**
Startup params:

```
/usr/share/nethermind/Nethermind.Runner \
                --config=mainnet \
                --Sync.SnapSync=true \
                --Init.BaseDbPath=/var/lib/nethermind \
                --Init.WebSocketsEnabled=true \
                --Network.MaxActivePeers=50 \
                --JsonRpc.Enabled=true \
                --JsonRpc.Port=8545 \
                --JsonRpc.EnginePort=8551 \
                --JsonRpc.JwtSecretFile=/secrets/jwt \
                --Pruning.CacheMb=4096
```

**Comment by asdacap** [comment]
@kkokosa Any idea why this is the case?

**Comment by 499602D2** [comment]
This behavior still occurs on v1.16.1, just to add a data point

**Comment by OlegJakushkin** [comment]
Dear @499602D2: we are currently working on a prototype fixing this issue, will push it as soon as its testing will be completed.

**Comment by 499602D2** [comment]
Thank you for the update @OlegJakushkin, keep up the great work! 🙏

**Comment by benaadams** [comment]
Resolved in many different changes, but most recent is #6636

**Comment by 499602D2** [comment]
PR looks promising, thank you for your work @benaadams!
