### ISSUE TITLE
Confirm that keystore files can be loaded by MyCrypto App for v1.0

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#483]
surprisingly it does not seem to work but maybe I tested too quickly with wrong passwords.

**Comment by tkstanczak** [comment]
also reported by the users that Geth and Parity style tools do not load these files
We did follow the spec and tests are passing but it seems that there may be an algorithm change in the meantime.

**Comment by mcdee** [comment]
There appear to be three issues, of varying concern:

1. the `id` field is a copy of the `address` field.  Although not critical when dealing with single files, `id` should be a UUID
2. the encoding is `aes-128-cbc`.  This has been abandoned in favour of  `aes-128-ctr`
3. the keyfile itself is written with a byte order marker (BOM).  This results in the file being invalid JSON (see https://tools.ietf.org/html/rfc7159#section-8.1 for details)

**Comment by tkstanczak** [comment]
Still outstanding, awaiting implementation, remains important.

**Comment by spetz** [comment]
@mcdee fixed, you can use MyCrypto or MetaMask to manage an account now.

**Comment by tkstanczak** [comment]
@mcdee this is fixed now in version 1.2.0
