### ISSUE TITLE
Nonce increment bugs

### ISSUE THREAD

**Issue by gituser** [NethermindEth/nethermind#4845]
**Describe the bug**
1) If you send transaction via `eth_sendRawTransaction` under certain conditions (e.g. with lower `gasPrice` than required curently by the network) transactions one after another, nonce isn't incremented correctly resulting in errors like:

```
NonceGap, Future nonce. Expected nonce: 62
```

When in fact nonce is correctly specified in the raw signed transaction and it's 63 (specified manually), nonce of the account isn't updated until the transaction is confirmed. Nonce should be calculated including pending transactions in the queue.

2) Another case if you use `eth_sendTransaction` and don't unlock account or get any type of error (e.g. not enough funds or incorrect gas amount for the transaction) nonce is being incremented but actual transaction never sent and on the next try you will have a nonce gap. This bug is very similar to - https://github.com/openethereum/parity-ethereum/issues/9040

 
**To Reproduce**

1) send two pre-signed transactions with low gas price simultaneously or one after another right after, in both transactions specify nonce manually and consequently, e.g. in 1st: 5 in 2nd: 6
 
2) a) `eth_sendTransaction` nonce increment when parallel transactions from the same address:

```
array (
    'code' => -32010,
    'message' => 'NonceGap, Future nonce. Expected nonce: 28486',
  ),
```

b) `eth_sendTransaction` when account isn't unlocked nonce is incremented anyway and there will be a gap in future transactions
c) `eth_sendTransaction` nonce is incremented when there is an error - not enough gas, amount is too high, etc
d) might be other cases as well, see https://github.com/openethereum/parity-ethereum/issues/9040

**Expected behavior**
Nonce should be correctly incremented including pending transactions.

 - OS: Linux x64 (Ubuntu 18.04 LTS)
 - Nethermind version: `1.14.5`

**Comment by gituser** [comment]
Hi! Any update on this? This is a very annoying bug happening from time to time on our Nethermind node.

**Comment by deffrian** [comment]
@gituser Hi, I probably know what caused the issue, but I'm not sure that I fully understand the second case. In both scenarios, do you have NonceGap error? What do you mean by nonce is being incremented? When a transaction with some nonce fails, the next transaction should have the same nonce.
For example:
1). send_transaction(Nonce: 1) -> fail due to locked account.
2). send_transaction(Nonce: 2) -> will fail due NonceGap, Nonce should be 1.
As I said I probably misunderstood your case. Can you correct me?

Btw, this issue happens because we don't count transactions that are not good enough to fit in a mempool(in terms of gas price). As a temporary solution you can increase mempool size or increase gas price of your transactions.

**Comment by gituser** [comment]
@deffrian 
> @gituser Hi, I probably know what caused the issue, but I'm not sure that I fully understand the second case. In both scenarios, do you have NonceGap error? 

Yes I do have this error. 

>What do you mean by nonce is being incremented? 

After you've tried to post transaction from unlocked account or specified too much ETH etc etc, the next correct try will result in nonce being incremented e.g. if you had nonce=2 originally in correct try you will have nonce=4 instead of 3.

>When a transaction with some nonce fails, the next transaction should have the same nonce. For example: 1). send_transaction(Nonce: 1) -> fail due to locked account. 2). send_transaction(Nonce: 2) -> will fail due NonceGap, Nonce should be 1. As I said I probably misunderstood your case. Can you correct me?

Yes, this is correct.

> Btw, this issue happens because we don't count transactions that are not good enough to fit in a mempool(in terms of gas price). As a temporary solution you can increase mempool size or increase gas price of your transactions.

Well, we need  a correct fix for nethermind similar what parity guys did in OE.
