### ISSUE TITLE
fix transition creation after timestamp - no unit tests

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#4856]
https://github.com/NethermindEth/nethermind/pull/4851/files

**Comment by MarekM25** [comment]
ChainSpecBasedSpecProviderTests - no unit tests for Shanghai EIPs

**Comment by MarekM25** [comment]
chainSpec.ShanghaiTimestamp = chainSpec.Parameters.Eip1153TransitionTimestamp ?? (long.MaxValue - 1);
            
            Line: 228

**Comment by MarekM25** [comment]
Should we add new ForkId calculation tests?

**Comment by smartprogrammer93** [comment]
Yes i will add forkId calculation tests for the old one and for the new one once the spec or geth implementation is known
