### ISSUE TITLE
[RocksDB] Check downgrade possibilities of Nethermind whenever RocksDb is upgraded

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#4885]
**Describe the bug**
As per this article:
https://github.com/facebook/rocksdb/wiki/RocksDB-Compatibility-Between-Different-Releases
RocksDB should be able to be downgraded without any issue if no major settings are being changed between versions.

We are planning to upgrade RocksDB to latest version but before that we need to check if this downgrade option can be used by us to prevent any major problems with this.

**Comment by kamilchodola** [comment]
Besu done that, so we can think of it as well in terms of performance for sure:
https://github.com/hyperledger/besu/pull/4517

**Comment by smartprogrammer93** [comment]
I believe we can close this now @kamilchodola already done with the upgrade and did the investigation.
