### ISSUE TITLE
BlockValidator should return reason/validationMessage

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#4891]
In case of invalid blocks, BlockValidator & HeaderValidator should return the reason. We can send this info to CL later.

The validationMessage for CL should be set in NewPayloadHandler
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/NewPayloadV1Handler.cs#L161
https://github.com/NethermindEth/nethermind/blob/0934dd2fd7181bfbeea2b9717feedf1f93a12610/src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/NewPayloadV1Handler.cs#L301

**Comment by ak88** [comment]
This is important for Hive test, since the error messages are used for correct fail condition. 
List of errors used in Hive:
https://github.com/marioevz/execution-spec-tests/blob/0927bb639be6319ebff64cbe5bb99a0d4202cb01/src/ethereum_test_tools/exceptions/exceptions.py#L58

**Comment by kamilchodola** [comment]
@ak88 Is it already fixed?

**Comment by ak88** [comment]
> @ak88 Is it already fixed?

Yes by #6804
