### ISSUE TITLE
Rlp decoders should have access to specProvider

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#4893]
We don't have access to specProvider in Header/BlockDecoder. It is a problem when we're changing how we decode/encode blocks. As a result, we added ugly static EIP1559TransitionBlock, and we're adding one more for withdrawals now: 
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Serialization.Rlp/HeaderDecoder.cs#L29

**Comment by LukaszRozmej** [comment]
I Thin `ReleaseSpec` would suffice
