### ISSUE TITLE
(Concurrent request limit reached) ON mainnet-teku when syncing with master branch

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#4899]
**Describe the bug**
On master branch few nodes (each time teku for sure but also on lighthouse once) that there is a exception:
`Failure when executing request System.AggregateException: One or more errors occurred. (Concurrent request limit reached) ---> System.InvalidOperationException: Concurrent request limit reached at Nethermind.Network.P2P.MessageDictionary`3.Send(Request`2 request) in /src/Nethermind/Nethermind.Network/P2P/MessageDictionary.cs:line 56 at Nethermind.Network.P2P.Subprotocols.Eth.V66.Eth66ProtocolHandler.SendRequestGenericEth66[T66,TRequest,TResponse](MessageDictionary`3 messageQueue, T66 message, TransferSpeedType speedType, Func`2 describeRequestFunc, CancellationToken token) in /src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs:line 302 at Nethermind.Network.P2P.Subprotocols.Eth.V66.Eth66ProtocolHandler.SendRequest(GetBlockHeadersMessage message, CancellationToken token) in /src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs:line 235 at Nethermind.Network.P2P.ProtocolHandlers.SyncPeerProtocolHandlerBase.Nethermind.Blockchain.Synchronization.ISyncPeer.GetBlockHeaders(Int64 number, Int32 maxBlocks, Int32 skip, CancellationToken token) in /src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs:line 130 at Nethermind.Synchronization.FastBlocks.HeadersSyncDispatcher.Dispatch(PeerInfo peerInfo, HeadersSyncBatch batch, CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Synchronization/FastBlocks/HeadersSyncDispatcher.cs:line 61 --- End of inner exception stack trace ---`

https://seq.nethermind.io/#/events?filter=Contains(NodeName,%20'Smoke-Tests-master-mainnet-teku')

It is syncing well further but those my affect peers I think and download speeds.

**Comment by kamilchodola** [comment]
https://seq.nethermind.io/#/events?filter=Contains(NodeName,%20'Smoke-Tests-BP-FullSync-Master-mainnet-teku')
Next example. Seems like something which is happening pretty often with teku.

**Comment by asdacap** [comment]
This should not block syncing, but does reduce performance. It seems like it could happen on a peer that does not response to a request. Wonder why it keep requesting to it... it should have throttle it via sleep or something. As for teku... not sure. Could indicate something more problematic.

**Comment by asdacap** [comment]
Only 6 record I can found in seq. I'm inclined to say this should be treated as timeout exception (which happen significantly more often).

**Comment by asdacap** [comment]
Seems to be peer refresher which run outside of peer allocation. It could be that some peer is really slow, causing this issue.

**Comment by kamilchodola** [comment]
@asdacap Yeah but noticed it happening more and more on teku like here:
![image](https://user-images.githubusercontent.com/43241881/202167104-7a1e988e-dcd4-4263-a3d8-7939a3536b7b.png)
Isn't there anything which may cause that or is it just a peering problem as You mentioned?

**Comment by kamilchodola** [comment]
https://seq.nethermind.io/#/events?filter=Contains(NodeName,'Smoke-Tests-db-repair-on-corruption-mainnet-teku')&signal=(signal-m33301~signal-m33302)

**Comment by kamilchodola** [comment]
Previously I had like 5-6 logs - now full page of them

**Comment by kamilchodola** [comment]
+ some logs from lighthouse

**Comment by kamilchodola** [comment]
https://seq.nethermind.io/#/events?filter=Contains(NodeName,'Smoke-Tests-db-repair-on-corruption-mainnet-lighthouse')&signal=(signal-m33301~signal-m33302)
