### ISSUE TITLE
Loading custom tracers, also persisting data while syncing a full node

### ISSUE THREAD

**Issue by veikkoeeva** [NethermindEth/nethermind#490]
This could be considered a sort of a memo and a discussion ticket on loading custom transaction tracers in Nethermind without compiling the main code source code.

I had a question with @tkstanczak on the channel about persisting transaction data to a separate database while syncing a full node. In effect this would allow one to build a system functionally like an archive node if being able to maintain the information otherwise but without managing a large storage in a flat file system. Basically the case described at https://github.com/ethereum/go-ethereum/issues/2104#issuecomment-168748944 while syncing. A similar case is storing VM trace data to a separate system.

To do this currently one needs:

1. Acquire the source code.
2. Implement a custom tracer and compile a custom version of the software.
3. Run a custom version of the software.

During the discussion the following pieces of software were presented as points of modifications:

[IBlockProcessor](https://github.com/NethermindEth/nethermind/blob/061cbbd4fbba989def9147ad2713680f5af53d8a/src/Nethermind/Nethermind.Blockchain/IBlockProcessor.cs)

[IBlockTracer](https://github.com/NethermindEth/nethermind/blob/27583b10b8326d1fee43c9d0c5b1280af498c5cd/src/Nethermind/Nethermind.Evm/Tracing/IBlockTracer.cs)

[ITxTracer](https://github.com/NethermindEth/nethermind/blob/9b2ec7c624ea983f92d262de3d3adeacdd1ce413/src/Nethermind/Nethermind.Evm/Tracing/ITxTracer.cs)

And as concrete examples

[GethLikeTxTracer](https://github.com/NethermindEth/nethermind/blob/9b2ec7c624ea983f92d262de3d3adeacdd1ce413/src/Nethermind/Nethermind.Evm/Tracing/GethLikeTxTracer.cs)

[ParityLikeTxTracer](https://github.com/NethermindEth/nethermind/blob/9b2ec7c624ea983f92d262de3d3adeacdd1ce413/src/Nethermind/Nethermind.Evm/Tracing/ParityLikeTxTracer.cs)

It appears respecting the license the modifications ought to be available somewhere. Either in this repository or perhaps a fork and one question then is what quality of work should be added to the main project and if it would be purposeful to have very purpose specific code and examples available outside of the main codebase.

The need to implement the tracers in the source code and compile a custom binary and the license together prompts a consideration as to what would be needed to build a plugin where one can load external tracers into the system? What would such a subsystem need and what could be the extension points?

**Comment by tkstanczak** [comment]
Probably easiest if we define an interface for add-ons / extensions and Tracers seem to be a great starting point.

The more general framework for this will be sketched probably next month. Let us see.

**Comment by tkstanczak** [comment]
This requires a fix to module loading.

**Comment by tkstanczak** [comment]
!!! Add custome tracers to the plugins!

**Comment by macrocan** [comment]
Is parity tracer action persisted now? How can i get that from a full node?
