### ISSUE TITLE
An assembly specified in the application dependencies manifest (Nethermind.Runner.deps.json) was not found

### ISSUE THREAD

**Issue by igorbarinov** [NethermindEth/nethermind#492]
When I'm running Launcher on Ubuntu 16.10 I have an error

```
ubuntu@ip-10-1-0-189:/rinkeby/nethermind$ ./Nethermind.Launcher
? Select network Rinkeby
? Select sync Full archive
Error:
  An assembly specified in the application dependencies manifest (Nethermind.Runner.deps.json) was not found:
    package: 'DotNetty.Transport', version: '0.6.0'
    path: 'lib/netstandard1.3/DotNetty.Transport.dll'
```

I'm using 0.9.9 release and followed all instructions and installed.Net runtime https://github.com/NethermindEth/nethermind/releases/tag/0.9.9

**Comment by tkstanczak** [comment]
Looking into it, I think we had a related issue for the .NET Core packager for this one.

**Comment by tkstanczak** [comment]
https://github.com/dotnet/core/issues/2471

**Comment by tkstanczak** [comment]
@igorbarinov we will investigate - one question - did you use any cloud VM image that was coming with preinstalled .NET? - or clean Ubuntu?

Would you be able to post the exact Ubuntu build that you are using?

**Comment by igorbarinov** [comment]
Sorry, it's Ubuntu 18.04

```
ubuntu@ip-10-1-0-189:/rinkeby/n/src/Nethermind/Nethermind.Runner$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

It was Ubuntu without .NET installed. Installed it from here: https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current

**Comment by tkstanczak** [comment]
@igorbarinov Nethermind.Launcher is self contained - you should not need to install any .NET versions on your own

Specifically SDK are developer tools and not runtime dotnet.

(this should not cause trouble but it seems it does).

Can you try the same system but just do not install .NET at all?

**Comment by igorbarinov** [comment]
I see. I installed it to compile on the host from sources after the release version didn't work. 
I didn't get how to launch the Launcher after building 😀
I removed the SDK and it's still not working for me.
I'll run release on another host which is will create from scratch.

**Comment by spetz** [comment]
Hi,
Did you install the required packages using the following command?
```
sudo apt-get update && sudo apt-get install libsnappy-dev libc6-dev libc6 unzip
```
Are you still getting the same error as before?

**Comment by igorbarinov** [comment]
yes, still the same error on the existing host.
I am trying a new host now.
```
ubuntu@ip-10-1-0-189:/rinkeby/nethermind/nethermind$ sudo apt-get update && sudo apt-get install libsnappy-dev libc6-dev libc6 unzip
Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:5 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic InRelease [15.4 kB]
Hit:6 https://packages.microsoft.com/ubuntu/18.10/prod cosmic InRelease
Get:7 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic-updates/main Sources [271 kB]
Get:8 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [617 kB]
Get:9 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic/main amd64 Packages [3488 B]
Fetched 1158 kB in 2s (520 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
libc6 is already the newest version (2.27-3ubuntu1).
libc6-dev is already the newest version (2.27-3ubuntu1).
libsnappy-dev is already the newest version (1.1.7-1).
unzip is already the newest version (6.0-21ubuntu1).
The following packages were automatically installed and are no longer required:
  aspnetcore-runtime-2.2 dotnet-host dotnet-hostfxr-2.2 dotnet-runtime-2.2 dotnet-runtime-deps-2.2 liblttng-ust-ctl4 liblttng-ust0 liburcu6 linux-aws-headers-4.15.0-1027
  linux-aws-headers-4.15.0-1029 linux-aws-headers-4.15.0-1031 linux-aws-headers-4.15.0-1032 linux-aws-headers-4.15.0-1033 linux-aws-headers-4.15.0-1034
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 137 not upgraded.
ubuntu@ip-10-1-0-189:/rinkeby/nethermind/nethermind$ ./Nethermind.Launcher
? Select network Rinkeby
? Select sync Full archive
Error:
  An assembly specified in the application dependencies manifest (Nethermind.Runner.deps.json) was not found:
    package: 'DotNetty.Transport', version: '0.6.0'
    path: 'lib/netstandard1.3/DotNetty.Transport.dll'
ubuntu@ip-10-1-0-189:/rinkeby/nethermind/nethermind$
```

**Comment by spetz** [comment]
Are you able to start the Nethermind.Runner application using dotnet run command (after cloning the Nethermind repository), or it's happening for both, Runner and Launcher?

**Comment by igorbarinov** [comment]
```
ubuntu@ip-10-1-0-189:/rinkeby/nethermind/nethermind$ ./Nethermind.Runner
Error:
  An assembly specified in the application dependencies manifest (Nethermind.Runner.deps.json) was not found:
    package: 'DotNetty.Transport', version: '0.6.0'
    path: 'lib/netstandard1.3/DotNetty.Transport.dll'
```

Happening for both. For the source code one, I don't have SDK now. Should I install and try it?

**Comment by igorbarinov** [comment]
Yes, it works with compiled from source version and doesn't work with the release  version
<img width="1276" alt="Screen Shot 2019-05-20 at 6 08 55 PM" src="https://user-images.githubusercontent.com/424628/58036036-6aabd600-7b2a-11e9-8bf7-01432b0fba46.png">

**Comment by spetz** [comment]
Ok, thank you for the update, we will need to check if the same issue happens on our side when it comes to using the release version running on Linux.

**Comment by igorbarinov** [comment]
On a fresh 18.04 on both AWS and Vultr is works as expected. 
I will keep the bugged one running if we need to make tests on it. If you have time for it.
