### ISSUE TITLE
Typo in pruning message: "loose" vs "lose"

### ISSUE THREAD

**Issue by yorickdowne** [NethermindEth/nethermind#4937]
**Describe the bug**

"Full Pruning Waiting for state: Current best saved finalized state 8018898, waiting for state 8019032 in order to not loose any cached state."

should be

"Full Pruning Waiting for state: Current best saved finalized state 8018898, waiting for state 8019032 in order to not lose any cached state."

One of those utterly critical bugs 🤣

Reference for non-English speakers: https://ielts.idp.com/canada/prepare/article-grammar-101-loose-vs-lose

**Comment by MarekM25** [comment]
@yorickdowne thx, fixed ;)
