### ISSUE TITLE
Node under heavy JSON-RPC load reports incorrect height from metric module

### ISSUE THREAD

**Issue by nicexe** [NethermindEth/nethermind#4943]
**Describe the bug**
When a node receives a heavy JSON-RPC load (using lots of `trace_call` or `trace_rawTransaction` for example) it reports wrong block heights from metrics.

**To Reproduce**
1. Fully sync an archive node for an AuRa chain (like Gnosis Chain)
2. Set up blockscout to use the archive node's RPC (no WS)
3. Observe node height on Grafana
4. Compare with imported blocks reported in the node's logs

**Expected behavior**
Grafana should show the latest imported block (matching with the node's logs)

**Screenshots**
![image](https://user-images.githubusercontent.com/867535/204319301-5e59976d-71a3-4d63-9c36-758f5cf7753b.png)
On the left side is when blockscout starts indexing the blockchain where the height reported by the metrics module immediately drops to about 450000.
On the right side it looks like the height reported by the metrics module reached some kind of a tri-stable equilibrium.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 (dockerized)
 - Image: [nethermind/nethermind:1.14.6](https://hub.docker.com/layers/nethermind/nethermind/1.14.6/images/sha256-f908e36cd213337c865f2012950810cef5b3787c698928017617d676ca80b9e3?context=explore) (same behavior is also seen on 1.13.x)

**Comment by nicexe** [comment]
stopping blockscout makes the height graph jump back to the actual height but when blockscout is started again, it drops down, slowly rises and then it fluctuates around certain heights just like seen in the screenshot above.

**Comment by nicexe** [comment]
![image](https://user-images.githubusercontent.com/867535/204503863-633f1b10-4d87-42e4-bb85-cb5cae545403.png)
![image](https://user-images.githubusercontent.com/867535/204504090-3d0e811b-2c02-4979-ba0a-10ae07d728ae.png)

blue dashed line denotes roughly when blockscout was restarted

**Comment by asdacap** [comment]
Hmm.. run `RunProcessingLoop` has `UpdateStats` and `BlockchainProcessor.Process` also have `UpdateStats` but wrapper around `!notReadOnlyChain`. I'm guessing the later is the right one? As this issue is likely due to the first `UpdateStats` which is probably triggered during trace calls.

**Comment by nicexe** [comment]
I have changed the query to use `nethermind_last_persisted_block_number` instead of `nethermind_blocks` and it seems like the node under heavy use is now reporting the latest block it has.
I'm not sure if there is any downside when relying on `nethermind_last_persisted_block_number` over `nethermind_blocks`
