### ISSUE TITLE
8545 port not opened although I specified --JsonRpc.Port=8545

### ISSUE THREAD

**Issue by Aracki** [NethermindEth/nethermind#4945]
Version: `nethermind/nethermind:1.14.6`

Although I have specified `--JsonRpc.Port=8545` & `--JsonRpc.Enabled=true`, when I run `netstat -tunlp` within a container I'm getting:

```
tcp        0      0 127.0.0.1:5052          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:5054          0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:5055            0.0.0.0:*               LISTEN      1/./Nethermind.Runn
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      -
tcp6       0      0 :::9368                 :::*                    LISTEN      -
tcp6       0      0 0.0.0.0:30303           :::*                    LISTEN      1/./Nethermind.Runn
udp        0      0 0.0.0.0:11000           0.0.0.0:*                           -
udp6       0      0 10.2.54.7:30303         :::*                                1/./Nethermind.Runn
```

Am I missing something or docs about [configuration of JsonRpc module](https://docs.nethermind.io/nethermind/ethereum-client/configuration/jsonrpc) is misleading?

**Comment by begetan** [comment]
RPC is not started unless you node in sync with the chain head. Check you logs for this message: 
`Syncing previously downloaded blocks from DB (partial offline mode until it finishes)`

**Comment by Aracki** [comment]
Thanks I got it!
