### ISSUE TITLE
Unable to set empty ExtraData

### ISSUE THREAD

**Issue by hukkin** [NethermindEth/nethermind#4952]
**Describe the bug**
It seems to be impossible to set extra data of produced blocks to `0x00`. Allowing it would be nice for privacy reasons.

**To Reproduce**
1. Set the environment variable `NETHERMIND_MININGCONFIG_EXTRADATA=''`
2. Start Nethermind
3. Produce a locally built block
4. Observe that the block's extra data is `Nethermind` (Hex:0x4e65746865726d696e64)

**Expected behavior**
I expected the block's extra data to be empty (Hex:0x00)

**Desktop (please complete the following information):**
 - Docker image: https://hub.docker.com/layers/nethermind/nethermind/1.14.6/images/sha256-f908e36cd213337c865f2012950810cef5b3787c698928017617d676ca80b9e3

**Comment by Marchhill** [comment]
The environment variable `NETHERMIND_MININGCONFIG_EXTRADATA` is deprecated since v1.14.6

**Comment by hukkin** [comment]
Yes the variable is now called `NETHERMIND_BLOCKSCONFIG_EXTRADATA` but the issue still remains, no?

**Comment by Marchhill** [comment]
It is possible to set extradata to be empty by passing the argument `--Blocks.ExtraData=`, but not through the environment variable `NETHERMIND_BLOCKSCONFIG_EXTRADATA`

**Comment by Marchhill** [comment]
Also it may be difficult to distinguish whether an [environment variable is empty or unset](https://unix.stackexchange.com/questions/27708/is-there-a-difference-between-setting-an-environment-variable-to-the-empty-strin). It doesn't seem worth it to me to change this behaviour as you can set extradata to be empty with a command line argument, or set it to an arbitrary string of your choice if you want to hide what client you are using.
