### ISSUE TITLE
PPA provide arm64 arch ?

### ISSUE THREAD

**Issue by abcfy2** [NethermindEth/nethermind#4959]
**Is your feature request related to a problem? Please describe.**
Seems now official ppa: https://launchpad.net/~nethermindeth/+archive/ubuntu/nethermind only support amd64. Would you please also support arm64 ?

**Comment by FalcoXYZ** [comment]
Will pick this up end of next week or the week after.

**Comment by abcfy2** [comment]
Any update ?

**Comment by abcfy2** [comment]
1.150 already released, but I still cannot find arm64 in PPA.

**Comment by FalcoXYZ** [comment]
@abcfy2 I've enabled ARM64 support for Nethermind. It should be available on the next release.
