### ISSUE TITLE
[Goerli][Old Headers] From time to time progress stucks on Old headers stage and unable to progress further

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#5012]
**Describe the bug**
Noticed a few times - especially reproducible on goerli.
There are situations when Old Headers are getting stucked in the middle of process and are not progressing in any way. This cannot be CL related so seems like some networking issue or we lost peers for Headers and unable to restore them.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Chain: goerli
 - Version: master

**Debug Logs**
[goerli.logs (2).zip](https://github.com/NethermindEth/nethermind/files/10231498/goerli.logs.2.zip)

**Comment by asdacap** [comment]
I looks to me on several of this case, when switching peer for forward sync, sometimes the global lock in `SyncPeerAllocation._allocationLock` did not get unlocked. Causing all sync to hangs. I have no idea what blocks it. It is bizzare.

**Comment by asdacap** [comment]
Same as #5043
