### ISSUE TITLE
[State Sync] State Sync stucked on mainnet for a long time even when Span Sync was fast

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#5013]
**Describe the bug**
We have a situations when were machine is weak (especially disk) then we can stuck on State Sync - but this should also result with slow SnapSync.
I have a situation where Snap took about 3h, but StateSync is already at 5h and is unable to progress.

I have noticed, that after restart, "Downloaded" was like 300-400 blocks behind which should not happen since we are syncing blocks (HEAD-32) for the time when Snap and State syncs are in progress.

Attaching logs before restart and after restart.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Chain: Mainnet
 - Version master

**Logs**
Here are Debug logs before restarting BUT those are very verbose and are automatically truncated so having only a few ones
[mainnet before.zip](https://github.com/NethermindEth/nethermind/files/10231568/mainnet.before.zip)

And those are after restarting
[mainnet after.zip](https://github.com/NethermindEth/nethermind/files/10231569/mainnet.after.zip)

**Comment by asdacap** [comment]
Added cpu info log with https://github.com/NethermindEth/nethermind/pull/5016, need to double check the CPU when using linode as older cpu have slow SSD which significantly reduce statesync performance.
