### ISSUE TITLE
Incorrect `ExampleResponse` in `ITxPoolRpcModule`

### ISSUE THREAD

**Issue by marcindsobczak** [NethermindEth/nethermind#5024]
**Describe the bug**
`ExampleResponse` of `txpool_content` and `txpool_inspect` in `ITxPoolRpcModule` are incorrect

**Comment by wslyvh** [comment]
Feel free to assign to me. Happy to fix those

**Comment by marcindsobczak** [comment]
Thanks for your willingness to contribute @wslyvh!

These lines are incorrect and need a fix:
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.JsonRpc/Modules/TxPool/ITxPoolRpcModule.cs#L14
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.JsonRpc/Modules/TxPool/ITxPoolRpcModule.cs#L19

Our docs are generated automatically, using reflection, so changes made in the file above will be reflected here:
https://docs.nethermind.io/nethermind/ethereum-client/json-rpc/txpool
