### ISSUE TITLE
"Unrecognized option" when running with --BlocksConfig.TargetBlockGasLimit on v1.14.7

### ISSUE THREAD

**Issue by sandakersmann** [NethermindEth/nethermind#5040]
"Unrecognized option" when running with --BlocksConfig.TargetBlockGasLimit on v1.14.7

**Comment by sandakersmann** [comment]
--Mining.TargetBlockGasLimit still works

**Comment by smartprogrammer93** [comment]
@sandakersmann  you need to use `--Blocks.TargetBlockGasLimit` so its `Blocks` not `BlocksConfig`
apologies for the confusion. Was it the docs that confused you?

**Comment by sandakersmann** [comment]
Yes, your PR should fix that :)
