### ISSUE TITLE
Refactor bloom storage to use memory mapped files

### ISSUE THREAD

**Issue by LukaszRozmej** [NethermindEth/nethermind#5088]
Benchmark it too.

**Comment by DemuirGos** [comment]
@LukaszRozmej are they supported in dotnet in linux ? last I checked it only supported persistence mode

**Comment by LukaszRozmej** [comment]
@DemuirGos I think so, @Scooletz is using them in Paprika.

**Comment by benaadams** [comment]
The implementation is fairly straightforward however I think need to know all the filesizes upfront unlike with files (as can't write to random memory position to expand the file)

**Comment by Scooletz** [comment]
I use them currently on Windows, ready to replace them, if needed, with direct PAL-like layer. This is just a few calls.
Also, aren't blooms persistent?

**Comment by LukaszRozmej** [comment]
Don't do it, lets try new receipt index instead.
