### ISSUE TITLE
Update Health Checks documentation

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5103]
Update Health Checks documentation https://docs.nethermind.io/nethermind/ethereum-client/monitoring-node-health

We're missing the latest changes in our health check documentation:
- [Free space check](https://github.com/NethermindEth/nethermind/pull/4837) 
- [Post-merge health checks](https://github.com/NethermindEth/nethermind/pull/4286)

**Comment by damian-orzechowski** [comment]
Added the following for Free Space Check:
https://app.gitbook.com/o/-LQf-hsLohtZj6I5yvSC/s/-LQf-hsMLYBdJYXFr5R0-887967055/~/changes/qA5TaVV2VTLZzI9qw1Qk/ethereum-client/monitoring-node-health
