### ISSUE TITLE
PPA upgrade deletes secret

### ISSUE THREAD

**Issue by LukaszRozmej** [NethermindEth/nethermind#5118]
From discord: "Hey everyone, I have Nethermind installed via the Ubuntu PPA and I have noticed that whenever I update it, the JWT secret which is located at "/var/lib/nethermind/keystore/jwt.hex" gets deleted. Then when I start Nethermind again, it generates a new JWT secret meaning that the beacon node does not communicate with Nethermind anymore as they are different. Then I have to stop Nethermind and copy the JWT secret back over again and start it up. This happens every time so now I copy the JWT secret over before I start Nethermind, but I also wanted to raise this here as it doesn't seem like it is expected behaviour."

**Comment by rubo** [comment]
Closing in favor of #5192
