### ISSUE TITLE
Inconsistent data in eth_getBlockByHash and eth_getBlockByNumber

### ISSUE THREAD

**Issue by michaelsproul** [NethermindEth/nethermind#5161]
**Describe the bug**

There is an inconsistency in the data returned by Nethermind for `eth_getBlockByHash` compared to Geth and Besu. A Lighthouse user reported this for block [16352147](https://beaconcha.in/block/16352147) at slot [5519765](https://beaconcha.in/slot/5519765).

I've collected the output from the 3 clients here: https://gist.github.com/michaelsproul/40760b5e7f9ae3bc0e6efba2bcbc510a.

It has been processed with `jq --sorted-keys` to facilitate easy diffing. At a quick glance it looks like there is some disagreement on the `accessList`s of a few transactions, along with some cosmetic differences. The responses of Geth and Besu are exactly identical, and the byNumber/byHash responses of Nethermind are also identical.

Nethermind processed the block correctly without a chain split, so **there is no consensus risk as a result of this bug**. I think it must be an issue in the post-processing for the API, or maybe the database storage (speculating wildly).

**To Reproduce**

Can be reproduced by calling `eth_getBlockByHash` directly on a Nethermind node for the block hash `0x0339d7de69b88225973e1aada3fdf9bb745b817fda9ae1d4cc6034ce57800ff0`.

Can also be reproduced indirectly by calling Lighthouse's HTTP API at slot 5519765 on a node using Nethermind:

```bash
curl -s "http://localhost:5052/eth/v2/beacon/blocks/5519765" | jq
```

```json
{
  "code": 500,
  "message": "UNHANDLED_ERROR: InconsistentPayloadReconstructed { slot: Slot(5519765), exec_block_hash: 0x0339d7de69b88225973e1aada3fdf9bb745b817fda9ae1d4cc6034ce57800ff0, canonical_payload_root: 0xbbee3ca0aab5d79be087055701494d590b839e85ba3c77fcc189facbf1d44397, reconstructed_payload_root: 0xca254e695e0120443020bb41d9d95697ce0c62edd09716a568a3d6fefd0c30c7, canonical_transactions_root: 0x71aa57644eab6c4baa3cdda12d591bedc5d00a70e38bcfcdb85c2aec58ff4234, reconstructed_transactions_root: 0xccac7ed2f7fc531c2b59e3a095adea526d63895b889b2ec7f219a16878a653ee }",
  "stacktraces": []
}
```

(NB: once Capella arrives Lighthouse will no longer use `eth_getBlockByHash` in this way)

**Version Info**

The Ligthouse user reported this issue with `Nethermind/v1.14.1-0-1a32d4541-20221014/X64-Linux/6.0.8`. I successfully reproduced it with 1.15.0:

```
Version: 1.15.0+2b708761
Commit: 2b7087613a6fde63a9d1173ca6e4e5b8f669e6f5
Build Date: 2022-12-28 12:42:33Z
OS: Linux x64
Runtime: .NET 6.0.12
```

**Comment by michaelsproul** [comment]
Just upgraded my node to `Nethermind/v1.16.1+644fe89f/linux-x64/dotnet7.0.2` and can confirm this is still an issue.

**Comment by kamilchodola** [comment]
Differences (Left is Besu, right is Nethermind):
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/43241881/214521370-beb5cb3c-10fe-4453-97df-fc7f6110f84d.png">
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/43241881/214521430-1f7e162b-cc73-42aa-bb46-0b8b358b2bcd.png">
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/43241881/214521468-52b90799-80f1-4be6-b83a-4a34c7e56564.png">
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/43241881/214521516-dfd98401-78bc-45be-a7e3-39f3ce07525b.png">
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/43241881/214521544-daab0962-9d4a-4f0e-b619-e5b8dd67aa50.png">

Those are just few ones but looking now through it is way much different in Besu vs Nethermind.

**Comment by emlautarom1** [comment]
@kamilchodola From where did you get Besu's response? A public RPC or are you running an instance?

**Comment by emlautarom1** [comment]
With #6031, #6079, #6061, #6145 and https://github.com/ethereum/go-ethereum/issues/27727, Nethermind produces (almost) the same responses as Geth (Nethermind includes a block author).

Feel free to open a new ticket if discrepancies show up again.

**Comment by michaelsproul** [comment]
Fantastic, thank you!
