### ISSUE TITLE
Node syncing latest blocks, but missing some from the past

### ISSUE THREAD

**Issue by timjrobinson** [NethermindEth/nethermind#5177]
**Describe the bug**

My Nethermind node seems to be receiving and syncing the lastest blocks, but for every block it says: `Syncing... Parent wasn't processed. Inserting block 123456`. 

When I run `eth_getBlockByNumber` (with `curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}' localhost:8545`)  it returns block `16225137` instead of the latest (which as of posting is 16439045). It doesn't seem to be trying to fetch this missing block. 

I'm using Lighthouse as my consensus client. Lighthouse is fully synced. 

I've tried restarting and it doesn't help. The node has 50 connected peers. 

**To Reproduce**
- Sync Nethermind node using Rocketpool default configuration. 

**Expected behavior**
I expect Nethermind to be fully synced. Instead it's syncing the latest blocks but complaining it doesn't have parents and never retrieving the parents. 

**Desktop (please complete the following information):**
 - OS: Debian 10

**Comment by timjrobinson** [comment]
I restarted with the healthchecks UI enabled and it's saying this in the UI:

``
The node is still syncing, CurrentBlock: 16225137, HighestBlock: 16439155. The status will change to healthy once synced. Peers: 48.
```

I also see this in the logs on occasion:

```
rocketpool_eth1  | 2023-01-19 06:52:03.2108|Changing state FastSync, StateNodes to StateNodes at processed:16225137|state:16225137|block:16439150|header:16439150|chain difficulty:58750003716598352816469|target block:16439182|peer block:16439182|peer total difficulty:58750003716598352816469 
rocketpool_eth1  | 2023-01-19 06:52:03.2108|Sync mode changed from FastSync, StateNodes to StateNodes 
```

The node has also been like this for hours, doesn't seem to be downloading that missing block.

**Comment by nodesup** [comment]
https://docs.gnosischain.com/updates/tags/bootnodes/

**Comment by timjrobinson** [comment]
@nodesup that could have been the cause. I left it running and it did eventually sync that block after a few days.
