### ISSUE TITLE
Nethermind v1.16 disables engine WS

### ISSUE THREAD

**Issue by yorickdowne** [NethermindEth/nethermind#5188]
**Describe the bug**

Either a bug or a breaking change

Nethermind v1.16.0 disables websockets on the engine port when using `--JsonRpc.EnginePort 8551`. This can break existing Nimbus setups.

http works.

**Comment by MarekM25** [comment]
Hey @yorickdowne
1. I checked websockets with` --JsonRpc.EnginePort 8551` locally with  - everything is fine
2. I checked two nimbus nodes - everything is fine

Did you notice anything wrong in the logs? Could you share more information?

**Comment by kamilchodola** [comment]
Hi @yorickdowne! :)

Some configuration would be necessary for us to reproduce any issue.
On my side I've just configured node (using Sepolia) to be Nethermind with nimbus using WebSockets communication and works well.

**Comment by yorickdowne** [comment]
Yep will get you the deets. From what I can see mainnet.config has an additionalRpcUrls. I overwrite that, by specifying one used for pruning on CLI, and use the EnginePort parameter. Which used to work with http and ws, and now Nimbus complains it can’t connect on ws. Give me a little time to get coffee and I will get you logs and config instead of just a narrative.

**Comment by yorickdowne** [comment]
Gah ... so sorry guys, this is a Nimbus issue not a Nethermind one. It lost WS connection and did not reestablish it so I thought Nethermind was to blame - but actually a restart of Nimbus would have solved it. Switching back to WS on Nimbus and restarting it has it working.

Sorry for wasting your time!
