### ISSUE TITLE
Timestamps defined on the spec instead of spec provider level.

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#5202]
**Describe the bug**
Withdrawals and 4844 timestamps should be defined on the spec provider and not spec level.
At the moment seemingly incorrect placement leads to a necessity of referring to Genesis spec as below:
![image](https://user-images.githubusercontent.com/498913/214009935-14de91e7-5244-46ab-90c0-8bee5b10010e.png)

**Expected behavior**
Timestamps to be defined on the ISpecProvider level

**Comment by MarekM25** [comment]
Related (or even duplicated) issue: https://github.com/NethermindEth/nethermind/issues/4893
