### ISSUE TITLE
Update Nethermind.EvmPlayground

### ISSUE THREAD

**Issue by DemuirGos** [NethermindEth/nethermind#5225]
The project [Nethermind.EvmPlayground](https://github.com/NethermindEth/nethermind/tree/master/src/Nethermind/Nethermind.EvmPlayground) doesn't compile, it still targets dotnet 6 and uses deprecated submodules.

**Comment by tkstanczak** [comment]
anybody using it? it was built for my workshops from 2018/9

**Comment by DemuirGos** [comment]
No one is using it (it was removed by this https://github.com/NethermindEth/nethermind/pull/5226)
