### ISSUE TITLE
EIP-170 Limits on Gnosis Chain as a prerequisite to Shanghai Gnosis

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5227]
We have maxCodeSize limit on mainnet (example from Sepolia, because of the size of mainnet chainspec) https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Chains/sepolia.json#L29

This EIP is a prerequisite to Shanghai EIP3860. The problem is that we don't have it activated on the Gnosis chain. In theory, there might be transactions/applications that are using more than the limit on the gnosis chain. Should we scan the gnosis mainnet to confirm that we can introduce this limit during Gnosis Shanghai?

**Comment by jmederosalvarado** [comment]
Before the merge there was a transaction permission contract that checked, amongst other things, the size of the transaction data, the check basically used the same limits as eip170, but it allowed the posdao owner to override this limit for some addresses. However, post-merge this contract is not active.

See [here](https://github.com/poanetwork/posdao-contracts/blob/0315e8ee854cb02d03f4c18965584a74f30796f7/contracts/base/TxPermissionBase.sol#L268-L271) and [here](https://github.com/poanetwork/posdao-contracts/blob/0315e8ee854cb02d03f4c18965584a74f30796f7/contracts/base/TxPermissionBase.sol#L177-L185)

**Comment by MarekM25** [comment]
@Demuirgos I think it is ready, so I'm closing it :)
