### ISSUE TITLE
Remove unused hashlib code

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#53]
We have incorporated HashLib into our solution but are only using a small subset of the assembly (Keccak256/512, RIPEMD, SHA3). It would make sense to remove everything else and add back only if needed.

**Comment by tkstanczak** [comment]
Most of it removed, Keccak256 replaced, need to replace Keccak512 implementation.

**Comment by dceleda** [comment]
@tkstanczak is it still valid or we can close it?
