### ISSUE TITLE
Remove Ropsten network from Nethermind repo

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5331]
Remove Ropsten from our repository.

Ropsten has been deprecated. We can remove configs & chainspecs etc. from our codebase

**Comment by Coollaitar** [comment]
Should I remove all the files containing Ropsten Network?

**Comment by MarekM25** [comment]
That is the goal of this issue :)

**Comment by julio4** [comment]
Many tests use `RopstenSpecProvider`. Should we change them with Goerli/Sepolia SpecProvider?
Are there any Ropsten 'specific' tests that do not require an upgrade to an up-to-date testnet?
I could try to work on this one

**Comment by Coollaitar** [comment]
I will be working on this issue tomorrow!

**Comment by shouryam-kumar** [comment]
Hey, can I get involved to close this issue?

**Comment by MarekM25** [comment]
> Hey, can I get involved to close this issue?

Sure, go for it! Not sure if @Coollaitar plans to continue ;)
