### ISSUE TITLE
[Gnosis][FullSync] On gnosis fullsync exception for Nethermind.Abi.AbiException: System call to RewardContract.Reward

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#5386]
**Steps to Reproduce**
In order to replicate the behavior, please provide a detailed list of steps:
1. Start Nethermind Node with fullsync config (archive config+ Pruning.Mode=Hybrid)
2. Wait for sync procedure to progress a bit
3. On block 3452477 or 3452478 issues are starting to appear like below:
![image](https://user-images.githubusercontent.com/43241881/223390177-3b94fdda-bc6d-40ca-a72a-2d7534f56260.png)
Node is down - unable to progress after that block so it is critical issue.

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Ubuntu 22.04
 - Version: 1.18.0-unstable
 - Installation Method: Docker
 - Consensus Client: Any

**Logs**
https://seq.nethermind.io/#/events?filter=Contains(NodeName,%20%22Smoke-Tests-1.18.0-Full-gnosis-lodestar%22)%20and%20not%20%22eth_getLogs%22%20and%20not%20%22Attempt%20to%20request%20ENR%20before%20bonding%22%20and%20not%20%22DEBUG%2FERROR%22%20and%20not%20%22when%20synchronizing%20(Timeout)%22&to=2023-03-07T00:50:46.449Z

**Comment by Neozaru** [comment]
Encountered the same issue on January 5th 2024.
Turns out that I was still running release `1.20.3` and missed the renamed binary (compiling from source) that would have let me run `1.24.0`. Just running the `1.24.0` seems to have solved the issue with re-sync.

Leaving this here in case somebody else is confused by this.

**Comment by MarekM25** [comment]
@kamilchodola should we close it?

**Comment by kamilchodola** [comment]
it was fixed some time ago and never encountered that again so we can close it.
