### ISSUE TITLE
Add a new line at the end of all JSON RPC requests

### ISSUE THREAD

**Issue by vbaranov** [NethermindEth/nethermind#546]
**Problem**: Nethermind JSON RPC API methods responses don’t return line break at the end of the response and response is stuck together with the next line.

For example, now, the response looks like:
```
MacBook-Pro-Viktor:blockscout viktor$ curl -H "Content-type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","id":1}' http://nethermind
{"jsonrpc":"2.0","id":1,"result":"0x460254"}MacBook-Pro-Viktor:blockscout viktor$
```

**Solution**: Add a newline character at the end of all responses

Thus, the above example will look like this:
```
MacBook-Pro-Viktor:blockscout viktor$ curl -H "Content-type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","id":1}' http://nethermind
{"jsonrpc":"2.0","id":1,"result":"0x460254"}
MacBook-Pro-Viktor:blockscout viktor$
```

Though the linebreak a the end of the response is not a part of a [jsonrpc standard](https://www.jsonrpc.org/specification), it will increase the readability of the response data.

**Comment by spetz** [comment]
Already fixed https://github.com/NethermindEth/nethermind/issues/543 (will be released with next RC).
