### ISSUE TITLE
[Cleanup] Remove Shandong & withdrawal_devnet configs

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5464]
Remove config & chainspecs 
Example:
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Chains/shandong.json
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Runner/configs/withdrawals_devnet.cfg

**Comment by Arun9650** [comment]
hi, i like to work on this issue .
the task is to remove these to flies only or these they of file ?

**Comment by Arun9650** [comment]
hi, I like to work on this issue.
the task is to remove these to flies only or these types of files?

**Comment by MarekM25** [comment]
These types of files. Search for: "withdrawal_devnet" and "shandong" in our repository

**Comment by Arun9650** [comment]
In all the repositories or just the nethermind I have checked on the nethermind and it has only 2 files that you already show in the example so should I raise a pr for that?

**Comment by MarekM25** [comment]
Already removed on master
