### ISSUE TITLE
[Cleanup] Remove all *.aa.cfg and _mev.cfg configs

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5465]
Example:
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Runner/configs/xdai_aa.cfg

**Comment by Arun9650** [comment]
I LIKE TO WORK ON THIS ISSUE

**Comment by Arun9650** [comment]
i like to work on this issue
