### ISSUE TITLE
Fix `TestBlockHashAnnounce`

### ISSUE THREAD

**Issue by marcindsobczak** [NethermindEth/nethermind#5468]
**Description**
`TestBlockHashAnnounce` is a test from HIVE devp2p eth protocol tests

**Steps to Reproduce**
In order to replicate the behavior, please provide a detailed list of steps:
1. Go to `Actions` -> `Hive tests`
2. Choose test suite: `devp2p`, limit: `eth`
3. `TestBlockHashAnnounce` is failing

**Additional context**
This test is failing, because for block headers without transactions and uncles (TxRoot = Keccak.EmptyTreeHash, UncleRoot = Keccak.EmptyTreeHash) we are requesting body. Test is expecting us to not request it, as from roots we know, that there are no transactions or uncles, so we can just add empty body.
It was fixed in the past:
https://github.com/NethermindEth/nethermind/pull/3916
But it was failing HIVE engine tests so was reverted before the merge:
https://github.com/NethermindEth/nethermind/pull/4463/files#diff-93f65ec12db68833d8c83643b5074a15f803171d26c4aed24415e1927e4e5892

Now we should fix it to pass both eth protocol and engine HIVE tests

**Comment by deffrian** [comment]
I think we decided with @MarekM25 that we not gonna fix it, as it's disabled after the merge
