### ISSUE TITLE
Investigate low peer count on EWF

### ISSUE THREAD

**Issue by smartprogrammer93** [NethermindEth/nethermind#5474]
On EWF, It was expressed that the NM client seems to fluctuate a lot on number of peers when compared to other clients. The number of peers seems to hover around 16-20 (mostly 16) and never really reaches the 20-25 max zone. 

This seems to only affect EWF as it is not seen on other networks running our client.

**Comment by MarekM25** [comment]
@asdacap @smartprogrammer93 can we close it?
