### ISSUE TITLE
Ten percent gas price increase for replacing/superseding a transaction

### ISSUE THREAD

**Issue by astralmaster** [NethermindEth/nethermind#5510]
Does it follow the Ethereum standard to require at least ten percent increase in gas price to replace a transaction? What is the motivation behind it? The line I refer to in code is:
https://github.com/NethermindEth/nethermind/blob/110e53d3e4e82cdd5cb5621a1acc0b1ef55f23a3/src/Nethermind/Nethermind.TxPool/Comparison/CompareReplacedTxByFee.cs#L21

The comment above the line says _It is required to avoid acceptance and propagation of transaction with almost the same fee as replaced one._ Why would such a transaction not be propagated? What is the exact issue prevented by this? If a transaction has higher gas price than the old transaction, then it gets superseded. If the idea is to prevent bulk transactions from replacing each other, then one could argue that those transactions may very well have a higher gas price difference than ten percent.

**Comment by benaadams** [comment]
Denial of service protection; or you could make the tx pool do excessive work by sending thousands of txs with the gas only going up by a gwei each time; instead there is an escalating cost to it e.g. such as the txn pool churn that caused Geth's outage on the Goerli testnet on Mar 13th https://twitter.com/vdWijden/status/1635218368155488262 (Nethermind didn't have an outage)

**Comment by astralmaster** [comment]
Ah, that does make sense. Thanks.
