### ISSUE TITLE
Archive sync speed - request empirical data

### ISSUE THREAD

**Issue by jamescarter-le** [NethermindEth/nethermind#5516]
I am trying to sync a full Archive node of Mainnet, and have been doing so for approx. 1.5 months. I am currently about Dec 2021, and block speed has fallen slowly to a crawl at <0.5BPS.

I am asking for some empirical data from those who have synced Mainnet in Archive mode, is this speed to be expected on modern hardware, or is something wrong with my configuration?

Example Block Process:
`2023-03-30 18:34:49.7610|Processed   13749184 |    1,401ms of   1,401ms, mgasps   29.00 total   14.47, tps  461.78 total  220.68, bps    0.71 total    0.47, recv queue 4971, proc queue 2000`

Nethermind Version: `v1.17.3`.
OS: `Windows 11`
Hardware: `Ryzen 7950X` (so 16 core, 32 thread) with `128GB RAM`

I am using the standard mainnet_archive.cfg configuration:
```
"MemoryHint": 2048000000
"Pruning": {
    "Mode": "None"
```

The disk drives are a RAID0 tiered stripe of 2x 4TB NVMe, and 2x 8TB SSD, giving 22TB of space.

Here is an output for run of DISKSPD with the usual settings for determining general IOPS:

```
D:\diskspd_test\diskspd.exe -b8K -d60 -o32 -t8 -h -r -w25 -L -c10G D:\dskspd_test\1

Total IO
thread |       bytes     |     I/Os     |    MiB/s   |  I/O per s |  AvgLat  | LatStdDev |  file
-----------------------------------------------------------------------------------------------------
     0 |     23661674496 |      2888388 |     376.00 |   48128.33 |    0.664 |     0.420 | D:\dskspd_test\1 (10240MiB)
     1 |     22893346816 |      2794598 |     363.79 |   46565.54 |    0.687 |     0.425 | D:\dskspd_test\1 (10240MiB)
....
     7 |     23454048256 |      2863043 |     372.70 |   47706.02 |    0.670 |     0.416 | D:\dskspd_test\1 (10240MiB)
-----------------------------------------------------------------------------------------------------
total:      183708631040 |     22425370 |    2919.27 |  373667.13 |    0.685 |     0.479

Read IO
thread |       bytes     |     I/Os     |    MiB/s   |  I/O per s |  AvgLat  | LatStdDev |  file
-----------------------------------------------------------------------------------------------------
     0 |     17741996032 |      2165771 |     281.93 |   36087.58 |    0.685 |     0.427 | D:\dskspd_test\1 (10240MiB)
     1 |     17168326656 |      2095743 |     272.82 |   34920.73 |    0.707 |     0.436 | D:\dskspd_test\1 (10240MiB)
....
     7 |     17587281920 |      2146885 |     279.48 |   35772.89 |    0.691 |     0.426 | D:\dskspd_test\1 (10240MiB)
-----------------------------------------------------------------------------------------------------
total:      137766076416 |     16817148 |    2189.21 |  280219.03 |    0.706 |     0.489

Write IO
thread |       bytes     |     I/Os     |    MiB/s   |  I/O per s |  AvgLat  | LatStdDev |  file
-----------------------------------------------------------------------------------------------------
     0 |      5919678464 |       722617 |      94.07 |   12040.75 |    0.603 |     0.393 | D:\dskspd_test\1 (10240MiB)
     1 |      5725020160 |       698855 |      90.98 |   11644.81 |    0.625 |     0.385 | D:\dskspd_test\1 (10240MiB)
....
     7 |      5866766336 |       716158 |      93.23 |   11933.12 |    0.608 |     0.376 | D:\dskspd_test\1 (10240MiB)
-----------------------------------------------------------------------------------------------------
total:       45942554624 |      5608222 |     730.06 |   93448.10 |    0.621 |     0.441
```

With a 75% read to 25% write spread of 350K IOPS/SEC at 8K size, this should not be a bottleneck for Nethermind, or am I mistaken?

RAM consumption is fully pegged of course, often pushing into page file on another dedicated NVMe disk.

Am I wrong in expecting mainnet to sync at this speed? This is basically telling me that when I am at head, blocks will take ~1.5 seconds to process?

Here are the IOPS while Nethermind is running:
![image](https://user-images.githubusercontent.com/1643692/228923910-c37814c3-d8fc-4b25-b26a-5b297a671814.png)

And also a reporting showing that the majority of reads are not even touching the SSD layer of storage, coming almost totally from NVMe:
![image](https://user-images.githubusercontent.com/1643692/228924076-a0242aa9-bf5d-47c5-ad57-74ea71e54b59.png)

My state/0 contains approx 200K *.sst files, incase this is relevant.

I feel like there is something wrong with either my hardware configuration (do I just need 4x the memory, or the Nethermind configuration I'm running). Being able to interop with the chain at the DB level with C# through the Trie directly is something that I've been sticking it out with Nethermind for, maybe you can help me get this node synced before the estimated time of another 2 months.

Many thanks for all your hard work on Nethermind.

**Comment by jamescarter-le** [comment]
Reading more into RocksDB, here are the DB Stats after the sync had been running about 15 hrs since last stop.

This shows it is waiting a significant amount of time (5 Hours) on Cumulative stall:
`Cumulative stall: 05:34:0.428 H:M:S, 35.5 percent`

Cumulative stall is the amount of time that writes cannot take place due to _compaction debt_.

Reading more of my RocksDb LOG output, it appears the main cause of stall is this:
`Stalling writes because of estimated pending compaction bytes 117875697590 rate 8589904`

Can someone who knows RocksDb more intimately explain what exactly the issue is here. Is it due to:
1) Too much data for RocksDb, unlikely?
2) Too many files existing for it to build it's tree?
3) Too many levels exist in the tree? I have 7 levels listed below.

Would we be able to both reduce the number of levels, and reduce the number files by increasing the BlockDb file size to say, 512MB, or 1GB for archive nodes?


```
** DB Stats **
Uptime(secs): 56489.2 total, 600.0 interval
Cumulative writes: 5827K writes, 232M keys, 5827K commit groups, 1.0 writes per commit group, ingest: 81.97 GB, 1.49 MB/s
Cumulative WAL: 5827K writes, 0 syncs, 5827263.00 writes per sync, written: 81.97 GB, 1.49 MB/s
Cumulative stall: 05:34:0.428 H:M:S, 35.5 percent
Interval writes: 42K writes, 1648K keys, 42K commit groups, 1.0 writes per commit group, ingest: 591.75 MB, 0.99 MB/s
Interval WAL: 42K writes, 0 syncs, 42809.00 writes per sync, written: 0.58 GB, 0.99 MB/s
Interval stall: 00:00:0.000 H:M:S, 0.0 percent

** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      9/0    1.12 GB   4.5    106.4     0.0    106.4     189.9     83.5       0.0   2.3      1.0      1.8 106144.98              0.00      3406   31.164    294M   498K       0.0       0.0
  L1     28/6    1.60 GB   5.1    120.6    82.3     38.2     120.0     81.8       0.0   1.5      3.5      3.5  35509.72              0.00        42  845.470    334M  1388K       0.0       0.0
  L2     45/4    2.61 GB   1.0    136.9    64.5     72.4     136.8     64.3      18.2   2.1      1.4      1.4  99626.71              0.00       885  112.573    379M   474K       0.0       0.0
  L3    486/0   24.98 GB   1.0    423.2    83.3    340.0     422.8     82.8       0.1   5.1      1.3      1.3 322099.88              0.00      1342  240.015   1171M  1579K       0.0       0.0
  L4   8551/42  251.67 GB   1.0    514.9    82.8    432.1     514.6     82.4       0.0   6.2      1.3      1.3 402053.56              0.00      1501  267.857   1423M  1870K       0.0       0.0
  L5  77521/351  2.44 TB   1.0    561.2    76.2    485.0     560.8     75.9       4.6   7.4      1.6      1.6 365514.87              0.00      1797  203.403   1544M  1518K       0.0       0.0
  L6 103561/0    5.49 TB   0.0     64.5    22.7     41.7      64.4     22.7      56.1   2.8      3.4      3.4  19203.42              0.00       355   54.094    176M   114K       0.0       0.0
 Sum 190201/403  8.21 TB   0.0   1927.7   411.8   1515.8    2009.2    493.4      79.0  24.0      1.5      1.5 1350153.13              0.00      9328  144.742   5324M  7443K       0.0       0.0
 Int      0/0    0.00 KB   0.0     24.0     4.2     19.7      24.5      4.8       0.2  42.3      1.4      1.4  17808.23              0.00        96  185.502     66M    92K       0.0       0.0
```

**Comment by asdacap** [comment]
The num of file it need to lookup per node (not per key as it need to traverse the trie, so multiple node per key), is the num of file in L0 + num of level. Index cache can significanty reduce that.

**Comment by asdacap** [comment]
There are rocksdb options to:
1. Increase buffer size (which is L0 file size)
2. File size (default to 64MB).
3. File size multiplier where each additional level have increasingly larger file. (default to 1).
4. Level base, which is the size of L1 (default to 256MB). L0 and L1 ideally need to have the same size, so increasing this means, ideally L0 need to be larger, meaning larger memory buffer.
5. Level multiplier, which is how large the next level is in total compared to prev level. default to 10. Increasing that decrease level at expense of write amplification.

**Comment by jamescarter-le** [comment]
Thanks @asdacap 
For now I am running just the DbOnTheRocks and letting it compact slowly the database.
I have noticed before that restarting the node will speed it up temporarily.
I can't see it being IOPS limited, there is plenty of available IOPS on the drive when it's running.
After running no block processing, just instantiated the database it is _slowly_ compacting to better scores. 

Here is the current usage: 
![image](https://user-images.githubusercontent.com/1643692/228976698-3d82e349-92ed-4082-aef2-6071b36eba7f.png)

Disc utilization (very rough metric, is about ~15% active).

Currently:
```
** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L1      3/0   192.85 MB   0.8      2.1     1.3      0.7       2.1      1.3       0.0   1.5     18.0     17.9    118.05              0.00         1  118.051   5788K    46K       0.0       0.0
  L2     46/0    2.48 GB   1.0      4.9     1.7      3.2       4.9      1.7       0.1   2.8      2.4      2.4   2088.02              0.00        28   74.572     13M    23K       0.0       0.0
  L3    500/0   24.95 GB   1.0     11.2     1.9      9.4      11.2      1.9       0.0   6.0      1.7      1.7   6951.95              0.00        30  231.732     31M    47K       0.0       0.0
  L4   7118/1   227.81 GB   0.9     12.0     1.9     10.1      12.0      1.9       0.0   6.4      1.4      1.4   8515.93              0.00        35  243.312     33M    48K       0.0       0.0
  L5  81252/18   2.44 TB   1.0    280.6    24.0    256.6     280.5     23.9       0.1  11.7     19.5     19.5  14745.33              0.00       730   20.199    772M   528K       0.0       0.0
  L6 106699/0    5.66 TB   0.0      0.0     0.0      0.0       0.0      0.0      24.3   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
 Sum 195618/19   8.35 TB   0.0    310.8    30.9    280.0     310.7     30.7      24.5   0.0      9.8      9.8  32419.28              0.00       824   39.344    856M   694K       0.0       0.0
 Int      0/0    0.00 KB   0.0     17.1     1.5     15.6      17.1      1.5       1.4 18311101483.0     30.5     30.5    572.52              0.00        44   13.012     46M    32K       0.0       0.0
```

I think trying to increase buffer size from `DbConfig.WriteBufferSize = 16MB` to something like 512MB makes more sense, it gives Rocks chance to compact it's old memtable while we are writing new data.
I'm not sure exactly what `CacheIndexAndFilterBlocks` does internally, but Rocks seems to recommend having this true.

I will let this run until it stops compacting, and maybe we can try a larger buffer size and larger file size. I assume setting this will start compacting the files into these larger sizes, but I'll test this on an already synced Goerli archive first.

**Comment by asdacap** [comment]
The CacheIndexAndFilterBlocks thing is an option to store the index within block cache, which reduce memory usage as block cache size is limited. Probably does not help you much as surprisingly it seems that you are write limited.

**Comment by LukaszRozmej** [comment]
@jamescarter-le just FYI we are currently working on state db layout redesign that we hope will significantly speed up archive nodes too.

**Comment by jamescarter-le** [comment]
> @jamescarter-le just FYI we are currently working on state db layout redesign that we hope will significantly speed up archive nodes too.

Is there a branch for this currently or still in design phase?

Appreciate what you've done with Nethermind, I've used it extensively and just now need a lot of archive data for which I would prefer to interop via Nethermind TreeVisitors and State DB directly, which is why I really want to push forward with this sync rather than go RPC via Erigon.

**Comment by LukaszRozmej** [comment]
It is very work in progress both in terms of stability, feature completeness as well as performance. I don't recommend running it yet.

Another experiment here is https://github.com/NethermindEth/Paprika which will be explored in next months.

https://github.com/NethermindEth/nethermind/tree/feature/state_db_layout_by_path

**Comment by jamescarter-le** [comment]
I have a Mainnet (non-archive) that is at 16697653, about a month old.
This was build with (I believe `v1.16.1`).

Booting this up with `Sync.NetworkingEnabled: false` it is immediately starting compaction of all databases (receipts, blocks, state etc) so I assume a RocksDb upgrade between 1.16.3 and 1.17.1 requires, or at least recommends this process internally. The background compactions are doing this.

This is compacting currently at a rate of ~900MBps on this drive. I will let this continue with no new blocks until compacting stops, then take a copy of this whole database.

Testing by setting `Db.WriteBufferSize: 536870912` on a test Goerli instance that was also 35 days out of date, shows while it won't recompact files to this size (that I've seen so far) all new state will go to 512MB new files, which are then compacted at over 2.5GBps (basically instant for Goerli).
(I set `RocksDbSharp.DbOptions.SetTargetFileSizeBase(writeBufferSize)` for State database).

Once I have Mainnet (non Archive) compacted (or activity slows down despite no new blocks) I will try syncing from this position with both the previous WriteBufferSize and the new 512MB size.

Correct me if wrong - but I believe BPS speed should be identical between this node, and the archive node, except that the archive node has significantly more state. Assuming it has sufficient memory for indexing it should theoretically be the same speed within margin?

I'm expecting that it will be faster, and that is due to the large number of files.

I will report back.

**Comment by asdacap** [comment]
BTW in our internal archive note, bps is around 0.6 to 1.0.

**Comment by jamescarter-le** [comment]
Thank you for providing your data, that helps show perspective.
