### ISSUE TITLE
Can't run five nethermind instances on the same machine

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5528]
Reported by SeaMonkey: https://discord.com/channels/629004402170134531/629004402170134537/1091388913186263140

It must be some sort of limitation of .NET 7, but I'm having a heck of a time getting five instances of Nethermind to run concurrently now.  The fifth one that is launched keeps hanging at 
2023-03-31 11:44:01.6552|ChainSpecPath matched an embedded resource inside the binary. Loading chainspec from embedded resources instead of file!

If I close one of the other Nethermind processes and then restart that one, it runs fine.  It seems like a full system restart temporarily fixes it, and sometimes dotnet build-server shutdown seems to resolve it, but if anyone has any suggestions on an actual cause and solution, I'd appreciate it.

**Comment by SeaMonkey82** [comment]
Last time I updated, only one of five processes would proceed beyond the aforementioned message until after I rebooted the machine.

**Comment by benaadams** [comment]
Gets stuck in the hardware check which just logs out the cpu type to local logs (should skip it is logging is less than info; e.g. warn, error or critical)

![image](https://user-images.githubusercontent.com/1142958/230703189-aaff3d80-57bd-4b44-8a91-ee86fcb07e6b.png)

So made a PR that's much lighter for that check https://github.com/NethermindEth/nethermind/pull/5547
