### ISSUE TITLE
Unable to start archive sync - Unable to find beacon header at height 1

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5549]
`Unable to find beacon header at height 1. This is unexpected, forcing a new beacon sync. `

I guess it is a false alarm warning. If that is the case we can remove it. However, it would be great to confirm & investigate

**Comment by MarekM25** [comment]
Okay, reported by yorick that he is unable to start archive sync.
More details on discord: https://discord.com/channels/629004402170134531/629004402170134537/1094270094999310346

**Comment by yorickdowne** [comment]
Resolved by setting `--Sync.PivotNumber=0`
