### ISSUE TITLE
Nethermind Prometheus metrics improvements

### ISSUE THREAD

**Issue by cbermudez97** [NethermindEth/nethermind#5553]
**Is your feature request related to a problem? Please describe.**
Right now Nethermind does have metrics exported in the Prometheus format but there are some other metrics that could be useful as well that are not exported right now. Also including some of the existing metrics will be useful as well.

**Describe the solution you'd like**
Will like to have new metrics and tags for information like this ones:
* `nethermind_network`: This metric can be used to store some general metadata about the network a Nethermind node is running. Like for example the network name and other configuration values. This information could be added as tags to this metric, a gauge probably, and have its value always set to one.
* `nethermind_sync_time`: It could contain the number of milliseconds needed for the node to sync or how much time it has been in a sync state.
* `nethermind_db_size`: The size of the existing database size in bytes.
* `nethermind_state_db_size`: The size of the current, or all, states dbs in bytes. Mentioned having different since it could keep track of the new state created by a Full prune and differentiate them with tags.
* Add general tags for all variables like the `node_name` if defined.

Added here the ones that have been used the most by me but I think there may be other cases of metrics that could be very helpful as well.

**Describe alternatives you've considered**
Currently, I had to add most of these metrics and tags manually by either adding manually some of the tags to the Prometheus configuration or configuring the Prometheus Node Exporter to collect some of them as well via Text collector.

**Additional context**
Having these metrics and tags could improve the monitoring and performance analysis done over the nodes. Also, having them could contribute to keeping an updated source of info from where to update the existing Docs.

**Comment by MarekM25** [comment]
I would love to see nethermind_db_size, nethermind_state_db_size or even metrics for others DBs like receipts, blocks, headers

**Comment by dceleda** [comment]
@MarekM25 very simple to implement
