### ISSUE TITLE
Not listening to 30303 on IPv6

### ISSUE THREAD

**Issue by Jack-Works** [NethermindEth/nethermind#5565]
**Description**
Not listening to 30303 on IPv6

**Steps to Reproduce**
Start with `--Network.LocalIp=::1`

```
$ nc -zvw10 127.0.0.1 30303
Connection to 127.0.0.1 30303 port [tcp/*] succeeded!
$ nc -zvw10 ::1 30303
nc: connect to ::1 port 30303 (tcp) failed: Connection refused
```

**Actual behavior**
Not listening on IPv6 even explicitly specified

**Expected behavior**
Listen on IPv6 address.

**Screenshots**

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Linux
 - Version: 1.17.3+671d60ad
 - Installation Method: GitHub Release
 - Consensus Client: Not related

**Additional context**
I have a public IPv6 address but no IPv4. I want to be an IPv6 public peer.

**Logs**

**Comment by yorickdowne** [comment]
If I can add a wish list item here, I'd love v4/v6 dual-stack for P2P. Lighthouse for example does `--listen-address '0.0.0.0' --listen-address '::'` (or any combination thereof) and then P2P listens on both v4 and v6. The `0.0.0.0` is the default and then they're v4-only.
