### ISSUE TITLE
Nethermind does not start

### ISSUE THREAD

**Issue by confleux** [NethermindEth/nethermind#5572]
**Description**
Nethermind does not start after upgrade to 1.17.3. 
Before upgrade it was installed with apt package manager and run as systemd service. Before upgrade I removed nethermind as a package to use manually downloaded package from downloads page. Shortly, I followed guide ["Manage Nethermind with systemd"](https://docs.nethermind.io/nethermind/first-steps-with-nethermind/manage-nethermind-with-systemd)

**Steps to Reproduce**

1.  Follow [guide](https://docs.nethermind.io/nethermind/first-steps-with-nethermind/manage-nethermind-with-systemd)

**Actual behavior**
Nethermind does not start and throws an error

**Expected behavior**
Nethermind working

**Desktop:**
 - Operating System: Ubuntu
 - Version: 18.04.06 Bionic Beaver
 - Installation Method: Realease from downloads page (Linux-amd64)
 - Consensus Client: Prysm v. 4.0.1

**Additional context**
A person from discord support told me that RocksDB is included into the Nethermind package, so I have no RocksDB installed manually. However, Nethermind prints RocksDB version to logs: `RocksDb Version: 7.7.3` and then throws error: `RocksDb was not found, please make sure it is installed on your machine`.

**Logs**
```Apr 15 15:04:12 Ubuntu-1804-bionic-64-minimal Nethermind.Runner[32194]: 2023-04-15 15:04:12.0018|RocksDb Version: 7.7.3
Apr 15 15:04:12 Ubuntu-1804-bionic-64-minimal Nethermind.Runner[32194]: 2023-04-15 15:04:12.0154|Loading chainspec from embedded resources: /home/nethermind/archive/nethermind/bui
ld/chainspec/foundation.json
Apr 15 15:04:12 Ubuntu-1804-bionic-64-minimal Nethermind.Runner[32194]: 2023-04-15 15:04:12.5894|RocksDb was not found, please make sure it is installed on your machine.
Apr 15 15:04:12 Ubuntu-1804-bionic-64-minimal Nethermind.Runner[32194]:  On macOs : 'brew install rocksdb' System.TypeInitializationException: The type initializer for 'RocksDbSha
rp.Native' threw an exception.
Apr 15 15:04:12 Ubuntu-1804-bionic-64-minimal Nethermind.Runner[32194]:  ---> NativeImport.NativeLoadException: Unable to locate rocksdb native library, either install it, or use
RocksDbNative nuget package```

**Comment by quilir** [comment]
Make sure you executed the `sudo apt-get update && sudo apt-get install libsnappy-dev libc6-dev libc6 unzip -y` command from the linked guide. Those libraries are necessary for correct dynamic linking.

Otherwise you could also try executing `scripts/pullandbuild.sh` file https://github.com/NethermindEth/nethermind/pull/4351#issuecomment-1207507351. Anyway those are just my findings from some searches

**Comment by confleux** [comment]
Thanks for reply, libraries are installed and I dont' do build, I use prebuilt runner.

**Comment by confleux** [comment]
Had to switch to Geth
