### ISSUE TITLE
Receiving abuse from hosting provider because of aggressive local nodes discovery

### ISSUE THREAD

**Issue by murich** [NethermindEth/nethermind#5583]
**Description**
After refreshing nethermind to latest ppa-available version, hosting provider sends an abuse. According to the log we can see that all the requests they not like are going out to the local network. 

I see similar issue here: https://github.com/ledgerwatch/erigon/issues/6034
Possible reason outlined here: https://github.com/sigp/lighthouse/issues/3006#issuecomment-1039691245

**Steps to Reproduce**
In order to replicate the behavior, please provide a detailed list of steps:
install following version:
Version: 1.17.3+671d60ad
Commit: 671d60ad71c68f6d443637c74b6d84de4d13c8f6
Build Date: 2023-03-23 12:26:44Z
OS: Linux x64
Runtime: .NET 7.0.4
and run sync

**Actual behavior**
Node tries to connect to potential nodes in local network.
**Expected behavior**
To have option to not seek for nodes in local network in this way
 

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Ubuntu 20.04.6 LTS
 - Version: 1.17.3+671d60ad
 - Installation Method: PPA
 - Consensus Client: Prysm

**Logs**
```
time                protocol src_ip src_port          dest_ip dest_port
---------------------------------------------------------------------------
Mon Apr 17 18:41:13 2023 TCP   155.x.x.x 13000 =>    10.43.130.23 34500
Mon Apr 17 18:42:50 2023 TCP   155.x.x.x 13000 =>  10.100.136.235 39999
Mon Apr 17 18:42:50 2023 TCP   155.x.x.x 13000 =>  10.100.136.235 39999
Mon Apr 17 18:46:06 2023 TCP   155.x.x.x 13000 =>  10.100.136.235 39999
Mon Apr 17 18:41:24 2023 TCP   155.x.x.x 13000 =>   10.100.140.41 39999
Mon Apr 17 18:40:23 2023 TCP   155.x.x.x 13000 =>  10.100.142.192 39999
Mon Apr 17 18:47:23 2023 TCP   155.x.x.x 13000 =>  10.100.142.192 39999
Mon Apr 17 18:40:56 2023 TCP   155.x.x.x 13000 =>  10.100.143.203 39999
Mon Apr 17 18:47:17 2023 TCP   155.x.x.x 13000 =>  192.168.178.96 56413
Mon Apr 17 18:47:17 2023 TCP   155.x.x.x 13000 =>      172.18.0.4 9003 
Mon Apr 17 18:40:20 2023 TCP   155.x.x.x 13000 =>   10.113.127.75 56752
Mon Apr 17 18:40:21 2023 TCP   155.x.x.x 13000 =>   10.113.127.75 56752
```

**Comment by MarekM25** [comment]
Hey @murich 
I remember news that Hetzner banned Ethereum nodes. Check this: https://www.coindesk.com/business/2022/08/26/ethereum-could-get-kicked-off-cloud-host-that-powers-10-of-crypto-network/

**Comment by murich** [comment]
@MarekM25 definitely would be better to move out but still many many nodes using hezner

**Comment by yorickdowne** [comment]
Is this Hetzner?

If so, Hetzner is actively hostile to crypto and has stated they will shut down any crypto nodes they become aware of.

**Comment by stephanep** [comment]
It may help, and is generally a good security practice, to block bogons using nftables output rules.
