### ISSUE TITLE
Error when using ~ in path

### ISSUE THREAD

**Issue by deffrian** [NethermindEth/nethermind#5632]
**Description**
When ~ symbol used in path variables it have to refer to home directory, but causes error

**Steps to Reproduce**
In order to replicate the behavior, please provide a detailed list of steps:
1. Set `Init.ChainSpecPath="~/chain.json"` or any other path variable
2. Run and see something like:
` System.IO.FileNotFoundException: Chainspec file does not exist /folder/[...]/~/chain.json`

**Actual behavior**
File not found error

**Expected behavior**
Should correctly read chainspec from /home/username/chain.json

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Ubuntu
 - Version: 20.04

**Comment by emlautarom1** [comment]
Since this is bash specific feature and there is no native C# method on how to handle this we'll leave it to the user to deal with path expansion.
