### ISSUE TITLE
Store the peer info before exit to speed up next startup

### ISSUE THREAD

**Issue by Jack-Works** [NethermindEth/nethermind#5648]
**Is your feature request related to a problem? Please describe.**

<img width="559" alt="image" src="https://user-images.githubusercontent.com/5390719/235970867-542ecd90-8023-4f34-9add-f5221a07321b.png">

Every time I restart the nethermind, I'll need about 10m to 1h to get connected with other peers.

**Describe the solution you'd like**
Remember the peer when nethermind exiting and try to re-connect them next connect. If I restart Nethermind in no time, most of the peers previously connected will still be online.

**Describe alternatives you've considered**

**Additional context**

**Comment by Jack-Works** [comment]
<img width="794" alt="image" src="https://user-images.githubusercontent.com/5390719/236113062-3e938d8e-d1a4-4c94-aaef-f7eeb1d5052d.png">

I try to do it manually. (See "Loaded 10 static nodes from file: /home/nethermind/Data/static-nodes.json") but it still need to waiting for peers for a very long time

**Comment by MarekM25** [comment]
are you sure your network connection is okay? is it mainnet? we store peers before exist so it is not normal

**Comment by Jack-Works** [comment]
> are you sure your network connection is okay?

I'm not sure... but my ISP has problems with connecting foreign IPs

> is it mainnet?

Yes.

> we store peers before exist so it is not normal

Oh... you mean the feature I requested already existed?

**Comment by kamilchodola** [comment]
@MarekM25 We have peers DB which stores Peers and after restart we try to connect to them at first shoot, right? Not sure if there is anything to be done here.
