### ISSUE TITLE
IsAuthenticated and MaxBatchSize/MaxBatchResponseBodySize 

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5660]
For weird reasons, IsAuthenticated is not working in these two places as expected:

1. https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.JsonRpc/JsonRpcProcessor.cs#L178
2. https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs#L201

The expectation is MaxBatchSize and MaxBatchResponseBodySize should be ignored for requests from CL (on the authenticated port).
To debug this issue we can set MaxBatchSize and later MaxBatchResponseBodySize to low value and run Nethermind with CL.

Let's debug it and fix it.

**Comment by MarekM25** [comment]
It happens for Lodestar<>Nethermind combo:
https://seq.nethermind.io/#/events?filter=MaxBatchResponseBodySize

**Comment by emlautarom1** [comment]
After a lot of trial and error I haven't been able to reproduce the issue locally. Changing `--JsonRpc.MaxBatchResponseBodySize` to smaller values (ex. 2000) has no effect since connections are always authenticated:

https://github.com/NethermindEth/nethermind/blob/1df2cf4d140641e67c700d417fef152ea3e5ece9/src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs#L200-L204

**Comment by benaadams** [comment]
I might have fixed this in https://github.com/NethermindEth/nethermind/pull/6372

**Comment by kamilchodola** [comment]
@MarekM25 This probably works - only place where we see some errors is Lodestar - maybe for some reason they are sending some of the rpc batches not by 8551 but by 8545 - we need some extended logs for that.

**Comment by MarekM25** [comment]
@kamilchodola I know, but I have still see it on Lodestar nodes (for example, lodestar goerli, so it might be misconfiguration in sedge or Lodestar bug)

**Comment by MarekM25** [comment]
Reported to sedge and Lodestar team - closing on Nethermind client side
