### ISSUE TITLE
Switch the escape sequence format

### ISSUE THREAD

**Issue by astralmaster** [NethermindEth/nethermind#5699]
https://github.com/NethermindEth/nethermind/blob/15d2378663704e13d780782b992b4c9b44368718/src/Nethermind/Nethermind.JsonRpc/Modules/Personal/PersonalRpcModule.cs#L84

Change the "\x" escape sequence expression to "\u" in order for the compiler to correctly interpret the desired Unicode characters. Regardless of this, the line of code I referenced has extra "\\" escape characters for the "x19" and the newline characters for some reason. It won't be encoded correctly by the following [line](https://github.com/NethermindEth/nethermind/blob/15d2378663704e13d780782b992b4c9b44368718/src/Nethermind/Nethermind.JsonRpc/Modules/Personal/PersonalRpcModule.cs#L85).  

[Reasoning](https://stackoverflow.com/a/284374/997633).

**Comment by AnmolSirola** [comment]
@MarekM25 Can I work on this issue ?
