### ISSUE TITLE
Tracing - Differences from Erigon/OpenEthereum

### ISSUE THREAD

**Issue by Uxio0** [NethermindEth/nethermind#5732]
We were testing the tracing features in Nethermind, and even if not critical for our indexer it would be good to be aligned with the other RPC nodes. For example, we have checked that subTraces fields usually don't match the ones returned from Erigon or OpenEthereum. Take this example from calling trace_transaction 0xc27273dc6e631d275baa527e1b07cd9097887317c26034bf8ea7bbe38c9353f0: https://www.diffchecker.com/vIN4SPEu/ . You can check etherscan Parity trace on https://etherscan.io/vmtrace?txhash=0xc27273dc6e631d275baa527e1b07cd9097887317c26034bf8ea7bbe38c9353f0&type=parity#raw

Other difference would be that for error: Reverted traces there's no result in that trace. You can check it for trace_transaction 0x5327768b86412dc5a79b2c38a3780e61aa13894875f154d2aa275bc75e32c606 and check etherscan trace on https://etherscan.io/vmtrace?txhash=0x5327768b86412dc5a79b2c38a3780e61aa13894875f154d2aa275bc75e32c606&type=parity#raw

First issue is a duplicate of https://github.com/NethermindEth/nethermind/issues/5456
Second one I think is new

**Comment by luarx** [comment]
Hey @deffrian , is there any update on this? Looking forward!

**Comment by deffrian** [comment]
Subtraces issueis fixed. #5916

**Comment by MarekM25** [comment]
Closing the issue
@Uxio0 @luarx feel free to reopen if needed
