### ISSUE TITLE
Receiving "Reverted 0x" on reverts instead of the actual error

### ISSUE THREAD

**Issue by leonprou** [NethermindEth/nethermind#5740]
**Description**
The Nethermind JSON-RPC returns "Reverted 0x" instead of the actual value when reverting with a null-like value. This issue occurs with values such as 0, "", and MyCustomError(0). The lack of meaningful information in the error message makes it difficult to understand the original revert reason, especially when custom errors are involved.

**Steps to Reproduce**

To reproduce the issue, I deployed the following contract on Goerli (Geth) and Fuse Spark (Nethermind):

``` solidity
pragma solidity >=0.7.0 <0.9.0;

/** 
 * @title Ballot
 * @dev Implements voting process along with vote delegation
 */
contract ErrorV4 {
    error Debug(uint);

    // 0xc2985578
    function foo() external {
        revert Debug(0);
    }

    // 
    // 0x274cdd5c
    function goo() external  {
        revert Debug(1);
    }

    function hoo() external {
        revert("");
    }
}
```

1.  Invoke the goo() method to effectively demonstrate the problem:
``` bash
curl --location --request POST 'https://explorernode.fusespark.io/' \
--header 'Content-Type: application/json' \
--data-raw '{
  "jsonrpc": "2.0",
  "method": "eth_call",
  "params": [
    {
      "to": "0xc06fd20541FB2b0385D0AeF2e76941594095EA21",
      "data": "0xc2985578"
    },
    "latest"
  ],
  "id": 1
}
```

**Actual behavior**
The data field returns "Reverted 0x":

``` JSON
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32015,
        "message": "VM execution error.",
        "data": "Reverted 0x"
    },
    "id": 1
}
```
**Expected behavior**
I expect to receive the data from which I can decode the original error. When calling the same method with Geth:

``` bash
curl --location --request POST 'https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161' \
--header 'Content-Type: application/json' \
--data-raw '{
  "jsonrpc": "2.0",
  "method": "eth_call",
  "params": [
    {
      "to": "0xfF283c39bD63C647b656c1C4DF6e158F3d65621a",
      "data": "0xc2985578"
    },
    "latest"
  ],
  "id": 1
}'
```

In the data field, you can see the error signature and error parameters are received:

``` JSON
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": 3,
        "data": "0x8a36f5a20000000000000000000000000000000000000000000000000000000000000000",
        "message": "execution reverted"
    }
}
```

**Screenshots**

The encoded data can be decoded with [tools.deth](https://tools.deth.net/calldata-decoder)

Decoded data:
![image](https://github.com/NethermindEth/nethermind/assets/7228844/5a30b85e-f558-4fc7-b260-977cfa6f89dd)

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Linux
 - Version: v1.18.0+96b555a8/linux-arm64/dotnet7.0.5
 - Installation Method: Docker (we use our own build)
 - Consensus Client:  N/A

**Additional context**
We've found the issue when we ran [ERC-4337](https://eips.ethereum.org/EIPS/eip-4337). The spec and the actual [bundlers](https://github.com/eth-infinitism/bundler) rely heavily on revert reasons. 
More examples and context are in the [notion page](https://north-crocus-61d.notion.site/Nethermind-Revert-Bug-c31aa206fbef4d67abe28879a2e977eb)

**Comment by LukaszRozmej** [comment]
PR #5727 solved the `0x` part and now proper `0x8a36f5a20000000000000000000000000000000000000000000000000000000000000000` is returned.

**Comment by LukaszRozmej** [comment]
looks like it helped
