### ISSUE TITLE
Update System Requirements page

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5754]
Update:
https://docs.nethermind.io/nethermind/first-steps-with-nethermind/system-requirements

**Comment by sidhant-shr** [comment]
can you specify what all needs to be updated so that I make the amends as per requirement.

**Comment by bitcoinbrisbane** [comment]
> can you specify what all needs to be updated so that I make the amends as per requirement.

Things I can see 
- Disk space

**Comment by MarekM25** [comment]
I think we've already updated what we wanted :)
