### ISSUE TITLE
eth_getLogs should not spam warnings while we're still in old bodies or receipts

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5757]
Like in the title + we don't need those warnings in NonvalidatorMode
![Screenshot from 2023-06-02 17-22-57](https://github.com/NethermindEth/nethermind/assets/9356351/99a94d3a-67f8-49cf-941d-eae6843c2369)

**Comment by kamilchodola** [comment]
@MarekM25 To be closed - it was done by @LukaszRozmej, we recently discovered regression on that which is also now fixed on master
