### ISSUE TITLE
[Cleanup] Remove RInkeby support

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5762]
Rinkeby is deprecated. Let's remove it from the repository

**Comment by yash251** [comment]
please assign me

**Comment by MarekM25** [comment]
@yash251 done :)

**Comment by yash251** [comment]
Should I remove or comment out everything related to Rinkeby?

eg. https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Chains/rinkeby.json

**Comment by MarekM25** [comment]
yes, chainspec should be removed

**Comment by AnmolSirola** [comment]
@MarekM25 is anyone working on this issue?

**Comment by yash251** [comment]
> @MarekM25 is anyone working on this issue?

I am @AnmolSirola

**Comment by jasonaw98** [comment]
Hi there I'm from LearnWeb3 can I assist this as well. Hope to work together
