### ISSUE TITLE
Impossible to build on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by Neozaru** [NethermindEth/nethermind#5794]
**Description**
I am install Nethermind for the 4th and the 3 previous times I "capitulated" to running the precompiled binary because it is impossible to build from source by following instructions.

**Steps to Reproduce**
1. Fresh **Ubuntu 22.04** install
2. Install **dotnet 6.0** from the base Ubuntu repo (following https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2204)
3. Run `dotnet build Nethermind.sln -c Release` (following https://docs.nethermind.io/nethermind/installing-nethermind/building-nethermind)

**Actual behavior**
`The function "UtcNow" on type "System.DateTimeOffset" is not available for execution as an MSBuild property function. `

**Expected behavior**
Get some binaries that I can then run

**Screenshots**

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Ubuntu 22.04
 - Version: `master`

**Additional context**
Just try it out on a fresh Ubuntu 22.04 install. As far as I can tell I have never been able to compile it for a year with that distribution. Not sure I've always got the same error. I think I tried with dotnet 7 in the past.

**Comment by benaadams** [comment]
Need to install dotnet 7.0 rather than 6.0

**Comment by Neozaru** [comment]
> Need to install dotnet 7.0 rather than 6.0

https://docs.nethermind.io/nethermind/installing-nethermind/building-nethermind -> Is that the right guide ? Did it change recently ?

**Comment by benaadams** [comment]
Changed in https://github.com/NethermindEth/nethermind/pull/4889 not sure what version but was several ago (might be the merge version)

> https://docs.nethermind.io/nethermind/installing-nethermind/building-nethermind -> Is that the right guide ? Did it change recently ?

Looks like that page was missed; it was updated on this one

https://docs.nethermind.io/nethermind/first-steps-with-nethermind/running-nethermind-post-merge#installing-dependencies

**Comment by Neozaru** [comment]
Thanks. I think we can close this issue.

**Comment by benaadams** [comment]
Still need to update that doc
