### ISSUE TITLE
`eth_call`s To The  `pending` Execute With `latest` Block Number

### ISSUE THREAD

**Issue by nlordell** [NethermindEth/nethermind#5810]
**Description**

Executing an `eth_call` RPC request when specifying the `pending` block executes the call with the block number of the `latest` block and not `latest + 1`.

According to the Ethereum [JSON RPC specification](https://ethereum.github.io/execution-apis/api-documentation/#eth_call), the `pending` block is used to:

> A sample next block built by the client on top of `latest` and containing the set of transactions usually taken from local mempool.

The specification is not extremely precise, but I interpret "on top of `latest`" as meaning the block number would be `latest + 1`.

This can have an unintended effect for `eth_call`s for Solidity code that is sensitive to `block.number` (for example, a vesting contract where you want to know how much is available if a transaction were included in the next block, and not the current `latest`).

Note that Geth will execute the `eth_call` with block number as `latest + 1`.

**Steps to Reproduce**

The behaviour can be reproduced by executing a bit of EVM code in an `eth_call`. The following EVM instructions should return 32 bytes corresponding to the block number that is accessible to the EVM.

```
NUMBER
SUB
PUSH 0
MSTORE
PUSH 32
PUSH 0
RETURN
```

For example:

```sh
curl -s $NODE_URL --data '@-' <<JSON | jq '.[] | .result'
[
  {
    "id": 0,
    "jsonrpc": "2.0",
    "method": "eth_blockNumber",
    "params": []
  },
  {
    "id": 1,
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [
      {
        "data": "0x4360005260206000f3"
      },
      "latest"
    ]
  },
  {
    "id": 2,
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [
      {
        "data": "0x4360005260206000f3"
      },
      "pending"
    ]
  }
]
JSON
```

**Actual behavior**

The above cURL request returns:

```
"0x10aae6d"
"0x00000000000000000000000000000000000000000000000000000000010aae6d"
"0x00000000000000000000000000000000000000000000000000000000010aae6d"
```

Notice how the `pending` and `latest` `eth_call`s simulate on the same block number.

**Expected behavior**

The above cURL request should return:

```
"0x10aae6d"
"0x00000000000000000000000000000000000000000000000000000000010aae6d"
"0x00000000000000000000000000000000000000000000000000000000010aae6e"
```

Notice how the `pending` `eth_call` is simulated on block `latest + 1`. This is the behaviour observed with Geth for example.

**Setup:**

Please provide the following information regarding your setup:
 - Operating System: Ubuntu
 - Version: 1.17.3
 - Installation Method: PPA
 - Consensus Client: Lighthouse

**Comment by fleupold** [comment]
Adding a slightly more minimal reproduction showing that indeed latest/pending block number (and hash) return the same value

```bash
curl -s $NODE_URL --data '@-' <<JSON | jq '.[] | .result.number'
[
  {
    "id": 0,
    "jsonrpc": "2.0",
    "method": "eth_getBlockByNumber",
    "params": ["latest"]
  },
  {
    "id": 1,
    "jsonrpc": "2.0",
    "method": "eth_getBlockByNumber",
    "params": ["pending"]
  },
]
JSON
```

**Comment by MarekM25** [comment]
Pending transactions are not supported in Nethermind and generally, there is a plan to drop support for pending transactions in Ethereum.
ACDE call summary about pending transactions:
https://www.galaxy.com/research/insights/ethereum-all-core-developers-execution-call-156/
