### ISSUE TITLE
Gnosis: `eth_getTransactionReceipt` missing `contractAddress`

### ISSUE THREAD

**Issue by theod-cryptio** [NethermindEth/nethermind#5823]
**Description**
On the gnosis network, calls to `eth_getTransactionReceipt` on some contract creation transactions (e.g `0xdff4563e305339719107cb3db9e9043d92e6d0159319ef5d2383195c3b69b38a`) have a `null` `contractAddress` field.

**Steps to Reproduce**
```sh
curl $RPC --json '{"method":"eth_getTransactionReceipt","params":["0xdff4563e305339719107cb3db9e9043d92e6d0159319ef5d2383195c3b69b38a"],"id":1,
"jsonrpc":"2.0"}' | jq '.result'
```

**Actual behavior**
On a 1.19.2 Neithermind node:
```json
{
    "transactionHash": "0xdff4563e305339719107cb3db9e9043d92e6d0159319ef5d2383195c3b69b38a",
    "transactionIndex": "0x0",
    "blockHash": "0x580469139ad0ee63aa99dd91282710d2e856a4546737c1f7b7a54ef5cd31bf12",
    "blockNumber": "0x1b09d04",
    "cumulativeGasUsed": "0x29def3",
    "gasUsed": "0x29def3",
    "effectiveGasPrice": "0x138eca4807",
    "from": "0x0f41e71f39e8671d0e301c544007d4d90910e0b7",
    "to": null,
    "contractAddress": null,
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "status": "0x1",
    "type": "0x2"
  }
```
**Expected behavior**
On an Erigon node:
```json
{
    "blockHash": "0x580469139ad0ee63aa99dd91282710d2e856a4546737c1f7b7a54ef5cd31bf12",
    "blockNumber": "0x1b09d04",
    "contractAddress": "0xa1dea36b62dae165072d914527e97fe4e2eed199",
    "cumulativeGasUsed": "0x29def3",
    "effectiveGasPrice": "0x138eca4807",
    "from": "0x0f41e71f39e8671d0e301c544007d4d90910e0b7",
    "gasUsed": "0x29def3",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "status": "0x1",
    "to": null,
    "transactionHash": "0xdff4563e305339719107cb3db9e9043d92e6d0159319ef5d2383195c3b69b38a",
    "transactionIndex": "0x0",
    "type": "0x2"
  }
```

**Comment by klefevre** [comment]
Hi @rachit77,

A `debug_traceTransaction` call seems to indicate that this transaction is using the `create` opcode:

```
curl $RPC --json '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0xdff4563e305339719107cb3db9e9043d92e6d0159319ef5d2383195c3b69b38a", {"tracer": "callTracer"}],"id":1}' | jq '.result'
```

**Comment by duongvansang** [comment]
Hello @MarekM25 @emlautarom1 do you have any timeframe for this fix?

**Comment by emlautarom1** [comment]
I could not give you an estimate on how long this will take. First, we need to set up an archive node to be able to reproduce the issue from our side. I will keep the ticket updated with any progress.

**Comment by duongvansang** [comment]
archieve node will take alot of time to get full sync. at least 2 months, but I think it happens on all kind of node, could you try with full node?

btw, how can I download this version?
BlockPi-Nethermind/v1.19.3+e8ac1da4/linux-x64/dotnet7.0.8 (https://gnosis.blockpi.network/v1/rpc/public) contractAddress: '0xa1dea36b62dae165072d914527e97fe4e2eed199'

**Comment by emlautarom1** [comment]
> btw, how can I download this version?

Unfortunately I could not tell you that since we don't manage that RPC. Supposedly, if you're running our `1.19.3` release you should be using that version, but different RPCs that are running the same version yield different results.

We're currently setting up everything to try to reproduce the issue.

**Comment by Enigmatic331** [comment]
Am affected as well - Problem doesn't seem to be strictly affecting archive node as we have full nodes which are exhibiting the same symptoms (1.20.1)

**Comment by duongvansang** [comment]
Hi @emlautarom1 I tried but stil the same, contractAddress is null

**Comment by emlautarom1** [comment]
Could you check if the code on #5989 fixes the issue on your end? To test it out, please run Nethermind and add the following flags: `--Sync.FixReceipts=true --Sync.AncientReceiptsBarrier=28351748`.

**Comment by wchuan11** [comment]
Hello, the same issue continues to occur sporadically, even with v1.21.0-rc. Each time it happens, need to rerun the flags mentioned above to resolve the receipts. Regarding the "Sync.AncientReceiptsBarrier" flag, does it need to specify the block number for the problematic transaction hash where "contractAddress" is returning Null, or should it always be set to "28351748"? Is there a permanent solution available to address this issue?
