### ISSUE TITLE
Nethermind stops log output if NLog.config is changed

### ISSUE THREAD

**Issue by turboboost55** [NethermindEth/nethermind#5847]
**Description**
If I modify and save NLog.config while Nethermind is running, all output to the log file stops. Console output continues, and the program seems to work as normal in all other ways.  

**Steps to Reproduce**
1. Start Nethermind
2. Modify and save NLog.config.  The change can be anything ... even changing the wording of a comment.

**Actual behavior**
All output to log file folder stops.

**Expected behavior**
Output to log file should continue.

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Ubuntu 22.04.2
 - 1.19.2
 - Github release
 - Nimbus 23.5.1

**Logs**
I've included mainnet.logs.txt, console.txt (a log of the console output of Nethermind), and my NLog.config file, which I have modified to reduce verbosity to the console, but keep full detail to the log folder.

 - you can see the most recent start was at approximately 2023-06-21 08:49:22
 - at approximately 2023-06-21 08:52:24 I modified NLog.config, by simply changing the wording of a comment
 - when I saved NLog.config, you can see that all output to mainnet.logs.txt stopped, but output to the console continued.

[mainnet.logs.txt](https://github.com/NethermindEth/nethermind/files/11820328/mainnet.logs.txt)
[console.txt](https://github.com/NethermindEth/nethermind/files/11820331/console.txt)
[NLog.config.txt](https://github.com/NethermindEth/nethermind/files/11820336/NLog.config.txt)

**Comment by turboboost55** [comment]
Any response on this?

**Comment by snakefoot** [comment]
Have you tried to startup with [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) enabled, and capture what happens when changing the NLog.config ?

**Comment by turboboost55** [comment]
I set `internalLogLevel="Debug"` in the config file and started Nethermind.  The resulting log output is attached.  

I didn't examine the log output in great detail, but I did notice that at initial startup, the following line appears, indicating it is opening the log file target at the expected location (my datadir is `/mnt/lv0/data/nethermind`) :

```
2023-07-15 10:03:47.0666 Debug FileTarget(Name=file-async_wrapped): Creating file appender: '/mnt/lv0/data/nethermind/logs/mainnet.logs.txt'
```

But when I modify and save NLog.config, which I did at 2023-07-15 10:06:22.2987, it opens the log file target at a completely different location (under `~/.net`)

```
2023-07-15 10:06:24.9503 Debug FileTarget(Name=file-async_wrapped): Creating file appender: '/home/russel/.net/Nethermind.Runner/Lz3ZyQq4a7Y_Cjbif5CARJstSoh1mOA=/log.txt'
```

I was able to verify that after the change, log output was indeed appearing in the new location, underneath `~/.net`.  I guess somehow, during the reload, it is not considering the `--datadir` setting and just using some internal default or something.



[nlog-internal.txt](https://github.com/NethermindEth/nethermind/files/12062992/nlog-internal.txt)

**Comment by snakefoot** [comment]
NLog FileTarget uses the [AppDomain.BaseDirectory](https://learn.microsoft.com/en-us/dotnet/api/system.appdomain.basedirectory) as base-directory when no file-path specified for `FileName`.

Seems that AppDomain.BaseDirectory is returning different value between initial startup, and the following configuration-reload.
