### ISSUE TITLE
JSON-RPC replay tool sends invalid JSON

### ISSUE THREAD

**Issue by emlautarom1** [NethermindEth/nethermind#5881]
**Description**
The current JSON-RPC replay tool (Kute) submits invalid RPC messages to the EL. Also, since execution takes a long time, the JWT token expires and it's never renewed.

**Steps to Reproduce**
Run the Kute tool following the examples on the README.

**Actual behavior**
Errors will pop up on the EL immediately since the messages are not valid JSON. After a while, errors about the token being expired will also show up.

**Expected behavior**
The tool should send valid JSON and deal with JWT token lifetimes.

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Fedora
 - Version: 38 Workstation
 - Installation Method: Built from source
 - Consensus Client: Teku

**Comment by MarekM25** [comment]
@kamilchodola @emlautarom1 @stdevMac  just skip JWT and run Nethermind with `--JsonRpc.UnsecureDevNoRpcAuthentication true`

It is for testing so it is okay

**Comment by emlautarom1** [comment]
> just skip JWT and run Nethermind with `--JsonRpc.UnsecureDevNoRpcAuthentication true`

Good point, I didn't know about that flag. Still, considering that the code is already implemented and working (and it's not a lot of code), I would suggest to keep it as is, specially since disabling authentication diverges from the "normal" behavior (ex. if we make an optimization on the authentication code we have no way of measuring the performance gains).
