### ISSUE TITLE
Update Networks page

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5893]
Open question: worth automating?
https://docs.nethermind.io/nethermind/ethereum-client/networks

**Comment by bitcoinbrisbane** [comment]
Might want to add Sepolia here too:  https://nethermindeth.github.io/docs/get-started/system-requirements 

<img width="675" alt="image" src="https://github.com/NethermindEth/nethermind/assets/8411406/1ab14a6d-8864-4779-aa62-57064b7311ed">

**Comment by smartprogrammer93** [comment]
Closing as resolved. Opened another for the system requirements:
https://github.com/NethermindEth/nethermind/issues/6336
