### ISSUE TITLE
Remove operating systems table from Hardware requirements

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5898]

**Comment by bitcoinbrisbane** [comment]
https://nethermindeth.github.io/docs/get-started/system-requirements

<img width="995" alt="image" src="https://github.com/NethermindEth/nethermind/assets/8411406/345a21a3-4361-495e-baf7-24331419cd75">

**Comment by bitcoinbrisbane** [comment]
> _No description provided._

Not sure if I should do the PR from the sub repo, but here is one.  https://github.com/NethermindEth/docs/pull/138

**Comment by rubo** [comment]
@bitcoinbrisbane This issue should have been closed long ago as fixed, and now it looks misleading. Anyway, thank you for your contribution and for bringing our attention to it.
