### ISSUE TITLE
Implement eth_getBlockReceipts

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5944]
Spec: https://github.com/ethereum/execution-apis/pull/438/files

Basically, we've already had this method here: https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.JsonRpc/Modules/Parity/ParityRpcModule.cs#L67 so the task is to copy this method to eth_ module and refactor the code. Please, double check with eth_ spec if there is no differences between eth_getBlockReceipts and parity_getBlockReceipts

**Comment by MarekM25** [comment]
@lazyfuhrer done!

**Comment by lazyfuhrer** [comment]
can you specify at which file do I need to copy the parity_getBlockReceipts method ?

**Comment by emlautarom1** [comment]
@lazyfuhrer You need to copy the method to the `EthRpcModule` (https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs) with the name of `eth_getBlockReceipts`. Then, add a couple of test to validate the method (you could use the one defined here: https://github.com/ethereum/execution-apis/pull/438/files#diff-f983c87e77429d84b2b77cf1aec3d83f91ac9e8c01a0bcd882aec118d234ea4d)
