### ISSUE TITLE
`eth_estimateGas` returns too low gas estimate when sending ETH to fallback method

### ISSUE THREAD

**Issue by KillariDev** [NethermindEth/nethermind#5946]
**Description**
When trying to estimate gas for sending ETH to fallback method, the estimate is too low. Here's the estimate gas RPC query:
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "method":"eth_estimateGas",
    "params":[{
        "from": "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
        "to": "0x6978a05bbb01fcc27a41ff34f60472652bb04cfc",
        "value": "0xde0b6b3a7640000"
    }]
}
```

This returns `0xbef9` which is 48889. For the same query Geth gives 54036. When executing the call itself, it consumes `41173` gas, which is less than the estimates, but the contract probably gets some discounts and might be doing some weird stuff with GAS opcode. Geths estimate is enough to make the call work, but Netherminds is not.

Nethermind version: 1.17.3 and <https://github.com/NethermindEth/nethermind/tree/feature/eth_multicall>

**Comment by emlautarom1** [comment]
Could you try making the RPC call with the following params:

```json
"params": [{
        "from": "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
        "to": "0x6978a05bbb01fcc27a41ff34f60472652bb04cfc",
        "value": "0xde0b6b3a7640000",
        "gas": "0x1c9c380"
}]
```

Note the additional `"gas": "0x1c9c380"` field. With this extra field, you should might get the correct estimation.

**Comment by MicahZoltu** [comment]
Is this just for testing and/or as a workaround, or is the expectation that all callers set a gas limit when doing estimate gas?

**Comment by emlautarom1** [comment]
This is just a workaround. If it works, then #5973 will fix your issue.

**Comment by MicahZoltu** [comment]
Very odd behavior.  The first time I tried with the `gas` property set to `0x1c9c380` I got back `0xbef9`, just like without it.  However, when I sent again with the `gas` property set (after submitting again without) I got `0xd314`.  I now reliably get back the correct gas limit.  Perhaps this is some kind of caching issue in Nethermind that was causing me to get the cached result initially?

```bash
curl https://ethereum.zoltu.io -H 'Accept: application/json' --data '{ "jsonrpc": "2.0", "id": 1, "method":"eth_estimateGas", "params":[{ "from": "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045", "to": "0x6978a05bbb01fcc27a41ff34f60472652bb04cfc", "value": "0xde0b6b3a7640000" }] }'
{"jsonrpc":"2.0","result":"0xbef9","id":1}
```
```bash
curl https://ethereum.zoltu.io -H 'Accept: application/json' --data '{ "jsonrpc": "2.0", "id": 1, "method":"eth_estimateGas", "params":[{ "from": "0xd8dA
6BF26964aF9D7eEd9e03E53415D37aA96045", "to": "0x6978a05bbb01fcc27a41ff34f60472652bb04cfc", "value": "0xde0b6b3a7640000", "gas": "0x1c9c380" }] }'
{"jsonrpc":"2.0","result":"0xd314","id":1}
```

It does appear this works around the issue, I suspect that getting the wrong result the first time was some sort of caching issue (different bug).

**Comment by emlautarom1** [comment]
> Perhaps this is some kind of caching issue in Nethermind that was causing me to get the cached result initially?

As far as I know there is no form of caching for JSON-RPC calls on Nethermind. I see that you're making the requests to `https://ethereum.zoltu.io` so maybe the caching is done there?

Since #5973 fixes this issue I'll be closing the ticket. Feel free to open a new one if you happen to have a new issue with gas estimation (or caching if that's the case).
