### ISSUE TITLE
Remove mining from eth_ namespace

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5949]
https://github.com/ethereum/execution-apis/pull/430

**Comment by bitcoinbrisbane** [comment]
Id like to try resolve this guy...

**Comment by MarekM25** [comment]
Cool, I assigned you! :) just remove all mentioned methods from codebase

**Comment by bitcoinbrisbane** [comment]
> Cool, I assigned you! :) just remove all mentioned methods from codebase

Great.  I started last night:  https://github.com/NethermindEth/nethermind/compare/master...bitcoinbrisbane:nethermind:master

**Comment by bitcoinbrisbane** [comment]
Trying to get my env working.  Getting this...`error MSB4185`
![image](https://github.com/NethermindEth/nethermind/assets/8411406/9d32835e-b2af-49bb-b145-7ca468f2d5b5)

**Comment by bitcoinbrisbane** [comment]
> [ethereum/execution-apis#430](https://github.com/ethereum/execution-apis/pull/430)

Ive got a draft PR in https://github.com/NethermindEth/nethermind/pull/6106.  Seems simple enough, will update the readme on the PR tonight.
