### ISSUE TITLE
Move NewPayload timeout to MergeConfig

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5951]
Move this value https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs#L77
To mergeConfig: https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Merge.Plugin/MergeConfig.cs

**Comment by vikasosmium** [comment]
I would like to work on this issue @MarekM25. Please assign this to me.

**Comment by kamilchodola** [comment]
Didn't noticed and also created PR for this one:
https://github.com/NethermindEth/nethermind/pull/5970

**Comment by Maitrayee94** [comment]
I would like to work on this issue @MarekM25. Please assign this to me.
