### ISSUE TITLE
Update Nethermind executables names in docs

### ISSUE THREAD

**Issue by rubo** [NethermindEth/nethermind#5961]
Update Nethermind executables names in docs once the corresponding change is released:

- `Nethermind.Runner` to `nethermind`
- `Nethermind.Launcher` to `nethermind-launcher`
- `Nethermind.Cli` to `nethermind-cli`

**Comment by bitcoinbrisbane** [comment]
> Update Nethermind executables names in docs once the corresponding change is released:
> 
> * `Nethermind.Runner` to `nethermind`
> * `Nethermind.Launcher` to `nethermind-launcher`
> * `Nethermind.Cli` to `nethermind-cli`

Does this apply to windows too?

Is this what you're after? https://github.com/NethermindEth/docs/pull/139

![image](https://github.com/NethermindEth/nethermind/assets/8411406/826d2dc1-ebb6-46a0-9ebb-e484966ba542)

![image](https://github.com/NethermindEth/nethermind/assets/8411406/122c3eef-01c0-4adf-a383-008916380ee0)
