### ISSUE TITLE
Change xDai to gnosis on Nethermind.Launcher

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#5987]
In Nethermind.Launcher we are using still xDai configs which are not relevant post-shapella.
We need to change it to gnosis.cfg/gnosis_archive.cfg

**Comment by rubo** [comment]
The right place for this issue is the launcher's [repo](https://github.com/NethermindEth/nethermind.launcher).

Done in https://github.com/NethermindEth/nethermind.launcher/pull/29
