### ISSUE TITLE
Block Processing suddenly stopped after SnapSync phase During initial OldBodies

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#5998]
**Description**
After Healing phase of my node docker container was killed and restarted shortly after. Node was doing fine for some blocks but then suddenly stopped processing new blocks (or stopped downloading them).
Seems like CL is sending blocks properly during that time but it is not processing them on EL side.
Debug logs:
[mainnet_grepped_no_block_processing.zip](https://github.com/NethermindEth/nethermind/files/12320427/mainnet_grepped_no_block_processing.zip)

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Ubuntu
 - Version: 1.21.0-unstable
 - Installation Method: Sedge
 - Consensus Client: Lodestar

**Comment by MarekM25** [comment]
@kamilchodola close?

**Comment by kamilchodola** [comment]
@MarekM25 On mainnet I did not reproduced that - for gnosis we have a separate issue for that which is much more reproducible so we can close this one
