### ISSUE TITLE
[Peers] Sepolia-archive peering works fine on 3 out of 4 nodes but on 1 it lost all peers and unable to find new ones

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#6014]
**Description**
On one of sepolia_archive node after getting max of 10 peers started to only go down with this amount until it reached 0 peers. From some moment it never added any new peer to pool.
Looking at some debug logs it has a lot of "Incorrect discovery message" messages (more than 1,2k in a day) where on healthy node it is like 30-40 of those messages per day.

**Comment by asdacap** [comment]
Could be dead bootnodes, which is addressed by #6035, or randomly hanging discovery task scheduler, which is addressed by #6038.

**Comment by kamilchodola** [comment]
Closing for now since seems like peering issue.
