### ISSUE TITLE
ReceiptsRecovery.cs -> RecoverReceiptData() incorrect logic

### ISSUE THREAD

**Issue by astralmaster** [NethermindEth/nethermind#6041]
In the current release of 1.20.1, `RecoverReceiptData(TxReceipt receipt) ` method of [ReceiptsRecovery.cs](https://github.com/NethermindEth/nethermind/blob/9f39c0c7902374a210fc313ff59f27292ce3ac20/src/Nethermind/Nethermind.Blockchain/Receipts/ReceiptsRecovery.cs#L91) has incorrect logic for recovering `SenderAddress` and `ContractAddress` for a receipt. On [this ](https://github.com/NethermindEth/nethermind/blob/9f39c0c7902374a210fc313ff59f27292ce3ac20/src/Nethermind/Nethermind.Blockchain/Receipts/ReceiptsRecovery.cs#L105) line, instead of updating `transaction` object's `SenderAddress `property, the logic updates the `receipt` object's `Sender` property, which causes `ContractAddress` not to be recovered, since its recovery is contingent on `SenderAddress `not being null.  The same issue is not shown in master however.

**Comment by asdacap** [comment]
Sorry, my bad. I think @emlautarom1 fixed it.

**Comment by MarekM25** [comment]
@astralmaster closing, feel free to reopen
