### ISSUE TITLE
Add Kurtosis to Nethermind private network docs

### ISSUE THREAD

**Issue by leeederek** [NethermindEth/nethermind#6047]
**Is your feature request related to a problem? Please describe.**
[Kurtosis' eth2-package](https://github.com/kurtosis-tech/eth2-package/) is used to instantiate reproducible Ethereum testnets with Nethermind and any other CL client combination. We believe the nethermind community would benefit from a guide for how to use the eth2-package to spin up private testnets to validate and test functionality against a Nethermind client for various applications and projects.

**Describe the solution you'd like**
Add a short guide in the nethermind private network docs: https://docs.nethermind.io/nethermind/ethereum-client/private-networks to help users spin up Ethereum testnets for themselves with Nethermind.

**Describe alternatives you've considered**
Tweets, discord announcements/bookmarks, tutorials, etc. But having content in the developer docs is by far the best spot for a resource like this. 

**Additional context**

**Comment by leeederek** [comment]
Tagging @MarekM25 as well for awareness!

**Comment by MarekM25** [comment]
Closing it - thx @leeederek !
