### ISSUE TITLE
eth_syncing is returning false even though sync in not completed

### ISSUE THREAD

**Issue by shashankshampi** [NethermindEth/nethermind#6050]
**Describe the bug**
eth sync api is returning false even though complete sync is not done. At the start of the process this api is giving fasle.
API documentation: https://docs.nethermind.io/nethermind/ethereum-client/json-rpc/eth#eth_syncing

**To Reproduce**
Steps to reproduce the behaviour:
Sedge config:
# Run Sedge
  ./sedge deps install
  ./sedge generate \
    --logging none \
    full-node \
    --map-all \
    --no-mev-boost \
    --no-validator \
    --network chiado \
    -e nethermind:nethermindeth/nethermind:master \
    -c lighthouse:sigp/lighthouse:latest \
    --el-extra-flag Network.EnableUPnP=true \
    --el-extra-flag Metrics.Enabled=true \
    --el-extra-flag Metrics.NodeName="arch_sync_test_master_chiado_lighthouse" \
    --el-extra-flag Seq.ServerUrl=https://seq.nethermind.io/ \
    --el-extra-flag Seq.ApiKey=${SEQ_API_KEY} \
    --el-extra-flag Seq.MinLevel=Info \
    --el-extra-flag Metrics.PushGatewayUrl=${GRAFANA_CONNECTION_STRING} \
    --el-extra-flag JsonRpc.EnabledModules=[Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug] \
    --el-extra-flag config=chiado_archive \
    --el-extra-flag JsonRpc.ReportIntervalSeconds=3600
    --cl-extra-flag checkpoint-sync-url=http://139.144.26.89:4000
    
curl --location 'localhost:8545' \
--header 'Content-Type: application/json' \
--data '{
    "method": "eth_syncing",
    "params": [],
    "id": 1,
    "jsonrpc": "2.0"
}'
Response
{
    "jsonrpc": "2.0",
    "result": false,
    "id": 1
}

**Comment by kamilchodola** [comment]
To be closed.

"Updating Pivot" is not a part of syncing process - we are waiting for data to properly start a sync so we cannot treat this for now as a "syncing node".

cc @MarekM25
