### ISSUE TITLE
Gnosis mainnet : eth_getLogs gives an empty result when "address" in the payload is an empty array

### ISSUE THREAD

**Issue by qn-srikanth** [NethermindEth/nethermind#6084]
**Description**
Gnosis mainnet : `eth_getLogs` responds with an empty response for  `"address": []`

**Steps to Reproduce**
Client version : `{"jsonrpc":"2.0","result":"Nethermind/v1.20.1+9f39c0c7/linux-x64/dotnet7.0.9","id":1}`
I'm including two payloads tested on Nethermind.

-  Payload 1 :
```
curl localhost:8545 \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{
  "method": "eth_getLogs",
  "id": 1,
  "params": [
    {
      "toBlock": "0x1C7123C",
      "fromBlock": "0x1C711D8",
      "address": []
    }
  ],
  "jsonrpc": "2.0"
}'
```

- Payload 2 :
```
curl localhost:8545 \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{
  "method": "eth_getLogs",
  "id": 1,
  "params": [
    {
      "toBlock": "0x1C7123C",
      "fromBlock": "0x1C711D8",
      "topics": [
        "0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822"
      ],
      "address": []
    }
  ],
  "jsonrpc": "2.0"
}'
```

**Actual behavior**

Response : Empty result array
```
{"jsonrpc":"2.0","result":[],"id":1}
```

**Expected behavior**

* Payload 1 : Public RPCs(https://rpc.gnosischain.com/
, https://rpc.gnosis.gateway.fm) respond with the matching logs consistently.

* Payload 2 : 
  * https://rpc.gnosis.gateway.fm responds with matching logs consistently.
  * https://rpc.gnosischain.com responds with either an empty response (or) matching logs. Screenshots below.

**Screenshots**

![Screenshot 2023-09-08 at 9 13 37 PM](https://github.com/NethermindEth/nethermind/assets/107944932/58a88283-30f8-436c-b488-339dab1e4259)

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Ubuntu
 - Version: "22.04.2 LTS)"
 - Installation Method: [GitHub Release]
 - Consensus Client: [Lighthouse : v4.3.0-dfcb336]

**Additional context**

---
Based on testing done on different clients, the result should not be empty when "address" is an empty array. 
(Should check for a match on other parameters.)

Please clarify if this is intended.

---

**Comment by emlautarom1** [comment]
Thanks for the report. We were able to reproduce the issue on our machines and we already have a fix implemented on #6094.

Just FYI, the reason why the official RPC returns different results on different executions is that their nodes are behind a load balancer and they use various clients, Nethermind among them.
