### ISSUE TITLE
Notify about hive test failures

### ISSUE THREAD

**Issue by flcl42** [NethermindEth/nethermind#6119]
**Is your feature request related to a problem? Please describe.**
No notification about hive tests failures

**Describe the solution you'd like**
Slack bot spamming with new issues in a related slack channel.

**Additional context**
Test results come from https://hivecancun.ethdevops.io and other sites of the same structure, we need to react to failing tests as soon as they appear there.
It's possible to employ one of dev machines to run the checker if needed

**Comment by kamilchodola** [comment]
@flcl42 Marcos is working on hive reporter for slack channel.
