### ISSUE TITLE
Ethstats Status Updates are sent at a higher rate than other clients

### ISSUE THREAD

**Issue by InvisibleSymbol** [NethermindEth/nethermind#6139]
**Description**
ethstats status updates are reported every second instead of every 15 seconds as is standard across geth erigon and besu. this spams the logs of the server full. i dont consider it as an ethstats server issue as the other clients arent causing it.

**Steps to Reproduce**
1. configure ethstats server (https://github.com/goerli/ethstats-server)
2. configure nethermind to use ethstats server
3. observe log spam on ethstats server

**Actual behavior**
nethermind reports its status to the server every second

**Expected behavior**
nethermind reports ist status to the server every 15 seconds

**Screenshots**
none

**Desktop (please complete the following information):**
 - Operating System: not relevant
 - Version: 1.20.4
 - Installation Method: not relevant
 - Consensus Client: not relevant

**Additional context**
1 second per update is overkill. i recommend making the default 15 seconds and offering an option to configure it if higher update rates are required.

**Logs**
```
ethstats  | 2023-09-27 07:10:59.764 [API] [STA] Stats from: EthStaker1-0x2c84f4abf289593affa64c7756a689898772f365d2619766567fa65e0082780d
ethstats  | 2023-09-27 07:11:00.765 [API] [STA] Stats from: EthStaker1-0x2c84f4abf289593affa64c7756a689898772f365d2619766567fa65e0082780d
ethstats  | 2023-09-27 07:11:01.764 [API] [STA] Stats from: EthStaker1-0x2c84f4abf289593affa64c7756a689898772f365d2619766567fa65e0082780d
ethstats  | 2023-09-27 07:11:02.765 [API] [STA] Stats from: EthStaker1-0x2c84f4abf289593affa64c7756a689898772f365d2619766567fa65e0082780d
ethstats  | 2023-09-27 07:11:03.768 [API] [STA] Stats from: EthStaker1-0x2c84f4abf289593affa64c7756a689898772f365d2619766567fa65e0082780d
ethstats  | 2023-09-27 07:11:04.764 [API] [STA] Stats from: EthStaker1-0x2c84f4abf289593affa64c7756a689898772f365d2619766567fa65e0082780d
ethstats  | 2023-09-27 07:11:05.765 [API] [STA] Stats from: EthStaker1-0x2c84f4abf289593affa64c7756a689898772f365d2619766567fa65e0082780d
ethstats  | 2023-09-27 07:11:06.766 [API] [STA] Stats from: EthStaker1-0x2c84f4abf289593affa64c7756a689898772f365d2619766567fa65e0082780d
ethstats  | 2023-09-27 07:11:07.764 [API] [STA] Stats from: EthStaker1-0x2c84f4abf289593affa64c7756a689898772f365d2619766567fa65e0082780d
ethstats  | 2023-09-27 07:11:08.766 [API] [STA] Stats from: EthStaker1-0x2c84f4abf289593affa64c7756a689898772f365d2619766567fa65e0082780d
ethstats  | 2023-09-27 07:11:09.765 [API] [STA] Stats from: EthStaker1-0x2c84f4abf289593affa64c7756a689898772f365d2619766567fa65e0082780d
```

**Comment by emlautarom1** [comment]
Thanks for reporting this issue. A new option has been added (`--EthStats.SendInterval`) and the default interval is now 15 seconds.
