### ISSUE TITLE
[v1.21.0] `eth_syncing` no longer reports that NM is synced on Holesky

### ISSUE THREAD

**Issue by jclapis** [NethermindEth/nethermind#6153]
**Description**

Starting with Nethermind `v1.21.0`, when running on the Holesky testnet, Nethermind no longer reports that it's synced via the `eth_syncing` route even though it is:

```
$ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' http://localhost:8545
{"jsonrpc":"2.0","result":{"startingBlock":"0x0","currentBlock":"0x723a","highestBlock":"0x723a"},"id":1}
```

Nethermind `v1.20.1` through `v1.20.4` didn't exhibit this, so it's new to `v1.21.0`. This doesn't happen on Mainnet, just Holesky.

**Steps to Reproduce**
1. Create a new node targeting Holesky.
2. Wait for it to sync.
3. Run `eth_syncing` once it's done.
4. Observe this behavior.

**Actual behavior**
```
$ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' http://localhost:8545
{"jsonrpc":"2.0","result":{"startingBlock":"0x0","currentBlock":"0x723a","highestBlock":"0x723a"},"id":1}
```

**Expected behavior**
```
$ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' http://localhost:8545
{"jsonrpc":"2.0","result":false,"id":1}
```

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Debian 11
 - Version: v1.21.0
 - Installation Method: Docker
 - Consensus Client: Nimbus v23.9.1, Lighthouse v4.5.0

**Logs**
Likely unrelated, but this line started showing up with v1.21.0 in the logs:
```
rocketpool_eth1  | 03 Oct 03:37:37 | Synced chain Head to 18267374 (0xc46d8c...551236) 
rocketpool_eth1  | 03 Oct 03:37:38 | No incoming messages from the consensus client that is required for sync. 
rocketpool_eth1  | 03 Oct 03:37:43 | No incoming messages from the consensus client that is required for sync. 
rocketpool_eth1  | 03 Oct 03:37:48 | No incoming messages from the consensus client that is required for sync.
```

This occurs on both Holesky and Mainnet, though the syncing problem doesn't manifest on Mainnet so it is probably a red herring.

**Comment by Kuplynx** [comment]
I have also experienced the `No incoming messages from the consensus client that is required for sync.` spam since 1.21.0-rc on mainnet with an identical lighthouse setup

**Comment by jclapis** [comment]
> Thanks for reporting this issue. Could you please list the full set of flags that you're using to run Nethermind and your CL of choice?

I am using the Docker v1.21.0 image, and here is the full command I'm running: 

```
/nethermind/nethermind --config holesky --Sync.SnapSync true --datadir /ethclient/nethermind --JsonRpc.Enabled true --JsonRpc.Host 0.0.0.0 --JsonRpc.Port 8545 --JsonRpc.EnginePort 8551 --JsonRpc.EngineHost 0.0.0.0 --Init.WebSocketsEnabled true --JsonRpc.WebSocketsPort 8546 --Merge.Enabled true --JsonRpc.JwtSecretFile=/secrets/jwtsecret --JsonRpc.EnabledModules Eth,Net,Web3 --JsonRpc.AdditionalRpcUrls ["http://127.0.0.1:7434|http|admin"] --Init.MemoryHint 1024000000 --Network.MaxActivePeers 25 --Metrics.Enabled true --Metrics.ExposePort 9105 --Network.DiscoveryPort 30303 --Network.P2PPort 30303 --Pruning.Mode Memory --Pruning.CacheMb 1024
```

I have also tried with `--Merge.NewPayloadTimeout=20` but that doesn't make a difference.

This was tested with Nimbus v23.9.1 and Lighthouse v4.5.0. I can run it against the other CLs if you want to verify this happens with all of them.

**Comment by emlautarom1** [comment]
We are currently looking at the issue and it seems like Holesky is triggering an edge case on our code given how recent the chain is. If you use `--log TRACE` you should see a message stating that receipts are still being downloaded, and that is the reason why Nethermind is reporting that it's still syncing. We'll be working on a proper fix for this scenario in the following days.

**Comment by jclapis** [comment]
> We are currently looking at the issue and it seems like Holesky is triggering an edge case on our code given how recent the chain is. If you use `--log TRACE` you should see a message stating that receipts are still being downloaded, and that is the reason why Nethermind is reporting that it's still syncing. We'll be working on a proper fix for this scenario in the following days.

I see stuff like this - is that what you're referring to?

```
rocketpool_eth1  | 05 Oct 00:32:08 | Sync config - fast sync with fast blocks from block 0 + bodies + receipts 
rocketpool_eth1  | 05 Oct 00:32:13 | Sync config - fast sync with fast blocks from block 0 + bodies + receipts 
rocketpool_eth1  | 05 Oct 00:32:18 | Sync config - fast sync with fast blocks from block 0 + bodies + receipts 
```

If that's the case then I'm glad you guys found it - looking forward to the fixed release!

**Comment by emlautarom1** [comment]
Not those in particular, but they still give you an idea that Nethermind is syncing from Genesis (block 0). The ones you should see are:

```
2023-10-05 10:20:30.1000|TRACE|58|Receipts not finished - EthSyncingInfo - HighestBlock: 45339, CurrentBlock: 45339, AncientReceiptsBarrier: 1. LowestInsertedBodyNumber:  LowestInsertedReceiptBlockNumber:
```

Note that `HighestBlock` and `CurrentBlock` are equal, and those are the values that you're seeing in `eth_syncing` (in hex).

**Comment by jclapis** [comment]
Yep, you're right - I'm seeing those as well:
```
rocketpool_eth1  | 06 Oct 01:30:09 | Start - EthSyncingInfo - BestSuggestedNumber: 48949, HeadNumberOrZero: 48949, IsSyncing: False SyncConfig details. FastSync True, PivotNumber: 0 DownloadHeadersInFastSync True, DownloadBodiesInFastSync True, DownloadReceiptsInFastSync True, AncientBodiesBarrier 0, AncientReceiptsBarrier 0. LowestInsertedBodyNumber:  LowestInsertedReceiptBlockNumber:  
rocketpool_eth1  | 06 Oct 01:30:09 | Receipts not finished - EthSyncingInfo - HighestBlock: 48949, CurrentBlock: 48949, AncientReceiptsBarrier: 1. LowestInsertedBodyNumber:  LowestInsertedReceiptBlockNumber:  
rocketpool_eth1  | 06 Oct 01:30:09 |    RECEIPTS            : yes(fastBodiesFinished, notInStateSync, stateSyncFinished), no(fastReceiptsNotFinished) 
rocketpool_eth1  | 06 Oct 01:30:10 |    RECEIPTS            : yes(fastBodiesFinished, notInStateSync, stateSyncFinished), no(fastReceiptsNotFinished) 
rocketpool_eth1  | 06 Oct 01:30:11 |    RECEIPTS            : yes(fastBodiesFinished, notInStateSync, stateSyncFinished), no(fastReceiptsNotFinished) 
rocketpool_eth1  | 06 Oct 01:30:12 |    RECEIPTS            : yes(fastBodiesFinished, notInStateSync, stateSyncFinished), no(fastReceiptsNotFinished) 
```
