### ISSUE TITLE
Does EthStats give up too easily?

### ISSUE THREAD

**Issue by rocknet** [NethermindEth/nethermind#6154]
**Description**
It seems that EthStats sometimes gives up, never to retry until you restart.  I'm running 1.20.4 on Holesky, connected to http://ethstats.invis.tools/, and it's been fine for 5.5 days.  About 45 mins ago now, I got disconnected and it won't come back up automatically.  The node itself is fine.  I'm synced and attesting.

**Steps to Reproduce**
In order to replicate the behavior, please provide a detailed list of steps:
1. Start NM, configured to send EthStats
2. Wait some amount of time, seemingly for a network blip (or restart the EthStats endpoint)

**Actual behavior**
NM disconnects from EthStats and doesn't reconnect (after maybe 4 retries)?

**Expected behavior**
Continue to retry, maybe with a back-off policy.  It seems weird that it has many disconnect and hello messages in 1 second.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Debian
 - Version: 12.1
 - Installation Method: Docker
 - Consensus Client: Lodestar

**Additional context**
N/A

**Logs**
```
27 Sep 20:56:15 |   EthStats by Nethermind
27 Sep 20:56:15 |   EthStats by Nethermind initialized in 0ms
27 Sep 20:56:16 | Initializing ETH Stats for the instance: 🚀 rocknet-0xe1649fcc4c024ba47ca1dc4fbc1d3ab3dc06fe314ab7b70ef9df68a8b8d6f171, server: ws://ethstats.invis.tools:80/api
03 Oct 11:47:03 | ETH Stats disconnected, reason: Websocket.Client.DisconnectionInfo
03 Oct 11:47:03 | ETH Stats disconnected, reason: Websocket.Client.DisconnectionInfo
03 Oct 11:47:04 | ETH Stats reconnected, sending 'hello' message...
03 Oct 12:15:21 | ETH Stats disconnected, reason: Websocket.Client.DisconnectionInfo
03 Oct 12:15:21 | ETH Stats disconnected, reason: Websocket.Client.DisconnectionInfo
03 Oct 12:15:21 | ETH Stats reconnected, sending 'hello' message...
03 Oct 12:15:21 | ETH Stats disconnected, reason: Websocket.Client.DisconnectionInfo
03 Oct 12:15:21 | ETH Stats disconnected, reason: Websocket.Client.DisconnectionInfo
03 Oct 12:15:22 | ETH Stats reconnected, sending 'hello' message...
03 Oct 12:15:22 | ETH Stats disconnected, reason: Websocket.Client.DisconnectionInfo
03 Oct 12:15:22 | ETH Stats disconnected, reason: Websocket.Client.DisconnectionInfo
03 Oct 12:15:22 | ETH Stats disconnected, reason: Websocket.Client.DisconnectionInfo
03 Oct 12:15:22 | ETH Stats reconnected, sending 'hello' message...
```

**Comment by emlautarom1** [comment]
Hello, thanks for reporting this issue. On https://github.com/NethermindEth/nethermind/pull/6147 we introduced a new option to configure the interval between stats updates and changed the default from 1 second to 15 seconds. As for lost connections, Nethermind will try to reconnect every 5 seconds (not configurable at the moment).

During testing we were not able to reproduce the issue you describe (Nethermind not trying to reconnect). Please, update to 1.22 and verify if the issue persists and if that is the case then feel free to open a new ticket.
