### ISSUE TITLE
Expose command(s) to execute blocktests and statetests on a per-test fixture basis

### ISSUE THREAD

**Issue by danceratopz** [NethermindEth/nethermind#6236]
**Is your feature request related to a problem? Please describe.**
I'm currently working on a generic test runner for test fixture consumers within [ethereum/execution-spec-tests](https://github.com/ethereum/execution-spec-tests) which would help the Testing Team and potentially client teams to execute  test fixtures against client fixture consumers (it's still WIP: https://github.com/ethereum/execution-spec-tests/pull/339).

**Describe the solution you'd like**
#6185 introduces a command to execute JSON test fixtures from a URL and filter by the JSON filename:
```console
dotnet test --filter "FullyQualifiedName=Ethereum.Blockchain.Pyspec.Test.ManualTests.Test" --environment TEST_URL_AND_PATH="https://github.com/ethereum/execution-spec-tests/releases/download/v1.0.6/fixtures_develop.tar.gz||fixtures/istanbul"
```
In order to add per-fixture execution to this generic test runner, it would be helpful if this command could be extended to allow regex filtering of test fixtures within a single JSON file by name. 

Background: Test fixtures JSON files generally contain multiple fixtures which each represent a single test case. Each fixture consist JSON key, value pairs, where the key is the test name and the value is the test data (more on the Blockchain Test format [here](https://ethereum-tests.readthedocs.io/en/latest/test_filler/blockchain_filler.html#test-structure)).

Additionally, as this test runner can be pointed to any test fixtures, an analogous command for [State Transition Tests](https://ethereum-tests.readthedocs.io/en/latest/state-transition-ref.html) would also be helpful, but could be added at a later stage.
 

**Describe alternatives you've considered**
If the effort is too high to add this command, the alternative is don't add it? :smiling_face_with_tear: 

**Additional context**
AFAIK, there is no equivalent command in other client tooling. There is an open PR (https://github.com/ethereum/go-ethereum/pull/28421) to add an analogous command to geth:
```
$  go run ./cmd/evm blocktest --run 100-fork=Cancun-empty_memory-length=0-src=0-dest=0 ./tests/spec-tests/fixtures/cancun/eip5656_mcopy/mcopy/mcopy_on_empty_memory.json
```

**Comment by danceratopz** [comment]
I just realized that `TEST_URL_AND_PATH` didn't make it into #6185 (as used in the command above).

This does run wonderfully on the latest execution-spec-tests release, however:
```console
dotnet test src/Nethermind/Ethereum.Blockchain.Pyspec.Test/
```

I do wonder if the startup time (even with `--no-restore --no-build` on subsequent runs) might be prohibitive to execute all test fixtures individually using an external runner. Perhaps worth discussing first. To mitigate it, we could consider runner per JSON fixture file instead of per fixture.

**Comment by LukaszRozmej** [comment]
> ```
> dotnet test 
> ```

You could filter it: https://learn.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=mstest

**Comment by LukaszRozmej** [comment]
> I just realized that `TEST_URL_AND_PATH` didn't make it into #6185 (as used in the command above).
> 
> This does run wonderfully on the latest execution-spec-tests release, however:
> 
> ```
> dotnet test src/Nethermind/Ethereum.Blockchain.Pyspec.Test/
> ```
> 
> I do wonder if the startup time (even with `--no-restore --no-build` on subsequent runs) might be prohibitive to execute all test fixtures individually using an external runner. Perhaps worth discussing first. To mitigate it, we could consider running per JSON fixture file, instead of per fixture.

You could filter it: https://learn.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=mstest

**Comment by danceratopz** [comment]
> You could filter it: https://learn.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=mstest

Thanks! Filtering by fixture name works nicely. Btw, we'll soon change the fixture names to the exact ID as generated when filling the fixtures, so that the test's intent is better expressed.

If the effort is not too high on your side, it would still be helpful if there was a way of configuring a generic blockchain (and state test) consumer to consume test fixtures from a local directory. Perhaps this already exists and I missed it?

Please note, this is no longer specific to execution-spec-tests; it could also be used with ethereum/tests as both use the same json test fixture format for blockchain tests (execution-spec-tests doesn't support state tests yet).

**Comment by smartprogrammer93** [comment]
@danceratopz Yeah, it's not a problem. I will get to it today

**Comment by LukaszRozmej** [comment]
> > You could filter it: https://learn.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=mstest
> 
> Thanks! Filtering by fixture name works nicely. Btw, we'll soon change the fixture names to the exact ID as generated when filling the fixtures, so that the test's intent is better expressed.
> 
> If the effort is not too high on your side, it would still be helpful if there was a way of configuring a generic blockchain (and state test) consumer to consume test fixtures from a local directory. Perhaps this already exists and I missed it?
> 
> Please note, this is no longer specific to execution-spec-tests; it could also be used with ethereum/tests as both use the same json test fixture format for blockchain tests (execution-spec-tests doesn't support state tests yet).

Is https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.State.Test.Runner/Program.cs#L16-L17 sufficient? It could use a readme.

**Comment by smartprogrammer93** [comment]
> > > You could filter it: [learn.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=mstest](https://learn.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=mstest)
> > 
> > 
> > Thanks! Filtering by fixture name works nicely. Btw, we'll soon change the fixture names to the exact ID as generated when filling the fixtures, so that the test's intent is better expressed.
> > If the effort is not too high on your side, it would still be helpful if there was a way of configuring a generic blockchain (and state test) consumer to consume test fixtures from a local directory. Perhaps this already exists and I missed it?
> > Please note, this is no longer specific to execution-spec-tests; it could also be used with ethereum/tests as both use the same json test fixture format for blockchain tests (execution-spec-tests doesn't support state tests yet).
> 
> Is [`master`/src/Nethermind/Nethermind.State.Test.Runner/Program.cs#L16-L17](https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.State.Test.Runner/Program.cs?rgh-link-date=2023-11-03T11%3A03%3A47Z#L16-L17) sufficient? It could use a readme.

Unfortunately, it is not the case for `Nethermind.Blockchain.Test.Runner`. that one does not take arguments. @LukaszRozmej should i use that and make the needed changes to enable the functionality?

**Comment by danceratopz** [comment]
> > > You could filter it: https://learn.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=mstest
> > 
> > 
> > Thanks! Filtering by fixture name works nicely. Btw, we'll soon change the fixture names to the exact ID as generated when filling the fixtures, so that the test's intent is better expressed.
> > If the effort is not too high on your side, it would still be helpful if there was a way of configuring a generic blockchain (and state test) consumer to consume test fixtures from a local directory. Perhaps this already exists and I missed it?
> > Please note, this is no longer specific to execution-spec-tests; it could also be used with ethereum/tests as both use the same json test fixture format for blockchain tests (execution-spec-tests doesn't support state tests yet).
> 
> Is https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.State.Test.Runner/Program.cs#L16-L17 sufficient? It could use a readme.

Yes, thanks! This is much closer to what I was looking for (and also much faster to execute than the `dotnet test` machinery).

So yes, if this existed for blockchain tests that would be amazing. And, if not too much effort, the ability to run a single fixture from a json fixture file, as initially described. In the meantime, geth's `evm blocktest` command landed up taking a regex to select which fixtures to execute from within a fixture file (https://github.com/ethereum/go-ethereum/pull/28421).
