### ISSUE TITLE
No option to choose which SSD to pick up VolumeFreeSpace trigger from

### ISSUE THREAD

**Issue by sandakersmann** [NethermindEth/nethermind#6258]
Just installed a second SSD on my server. I moved the data dir over to the new SSD. I have VolumeFreeSpace as trigger for pruning. The issue I ran into is that VolumeFreeSpace is picked up from old system disk. Would be great if you could choose which disk you should pick up the trigger from. Hope you can implement a solution for this.

**Comment by emlautarom1** [comment]
Hello, thanks for reporting this issue. Could you please share:
- Operating System: [e.g. Windows]
- Version: [e.g. 1.17.0]
- Installation Method: [e.g. GitHub Release/PPA/Homebrew/Docker]

Also, please share the options that you're using to set up `VolumeFreeSpace` as trigger (config, CLI arguments, environment variables).
