### ISSUE TITLE
Backwards compatibility of nethermind client to older version above 1.19.X crashes the nethermind client on start

### ISSUE THREAD

**Issue by shashankshampi** [NethermindEth/nethermind#6261]
**Description**
Downgrade of nethermind latest client to older version above 1.19.X crashes the nethermind client when launched from master image

**Steps to Reproduce**

1. Launch a pair of lighthouse with mainnet (any config is fine as tested with default and fastSync)
2. Wait for sync to finish 
3. Login to node box and update .env with lower supported versions like 1.19.1 or 1.19.2
4. stop and start the node with docker-compose command

**Actual behavior**
Nethermind client fails to start and throws error and shuts down.

**Expected behavior**
EL should start as 1.19.X version support backwards compatibility

**Screenshots**
<img width="1723" alt="Screenshot 2023-11-08 at 7 36 04 PM" src="https://github.com/NethermindEth/nethermind/assets/20582834/1aba0cf7-fa4f-49d3-a14c-b5537d9e162e">

**Logs**
[mainnet_crash_log.log](https://github.com/NethermindEth/nethermind/files/13297589/mainnet_crash_log.log)

**Comment by emlautarom1** [comment]
It seems like compatibility broke starting from this PR due to changes on headers storage: https://github.com/NethermindEth/nethermind/pull/6172

**Comment by asdacap** [comment]
"backward compatibility" means it can start with older database, not necessarily newer database. So we just need to advertise that 1.23 can't be downgraded.

**Comment by kamilchodola** [comment]
Summary:
PR mentioned by Lautaro introduces a change in DB Schema which if used won't allow user to downgrade to previous version.
Thing wasn't well informed for the team so that's why QA was confused.

**Comment by MarekM25** [comment]
@kamilchodola @emlautarom1 closing this
