### ISSUE TITLE
[Holesky] Peering for Holesky stopped working on master

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#6278]
**Description**
For some reason in three attempts in a row Holesky failed to find any peers
Here is a sample run from our action which hanged until timeout of 90 minutes
https://github.com/NethermindEth/nethermind/actions/runs/6915382667/job/18814247534

**Comment by kamilchodola** [comment]
Seems like issue with bootnodes.
Holesky worked 2 days ago with 2 bootnodes and now not syncing and this warning appears:
`18 Nov 17:45:17 | Could not communicate with any nodes (bootnodes, trusted nodes, persisted nodes). `

**Comment by MarekM25** [comment]
We should check bootnodes at first:
`./devp2p rlpx ping enode://....`
https://geth.ethereum.org/docs/tools/devp2p

**Comment by kamilchodola** [comment]
Works now - Both bootnodes crashed on Holesky - EF DevOps revived them and everything cool now.
