### ISSUE TITLE
Error in MetricServer: System.Net.HttpListenerException (master)

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#6299]
![Screenshot from 2023-11-25 21-21-05](https://github.com/NethermindEth/nethermind/assets/9356351/957572e6-3f98-4cd9-be34-455c9d71fc0c)
https://discordapp.com/channels/629004402170134531/629004402170134537/1176775497758277683

**Comment by asdacap** [comment]
Metric server was changed from kestral server as kestral server override exit code during shutdown leading to incorrect #6215. it could just be an overly verbose log.

**Comment by benaadams** [comment]
Change disables non system grafana metrics for Windows 😢

As it uses HttpListener and you need to explicitly give it permissions (outside in OS) to listen on that port or run in Admin mode.

Perhaps switch on OS as I assume Windows isn't paying attention to `SIGTERM`?
