### ISSUE TITLE
Refactor EVM to use error codes instead of exceptions for byte code processing.

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#63]
We have already done it for most of the cases but still have a few where we actually throw exceptions (e.g. overflow, underflow).
We want to only use exception for client failures. EVM exceptions should be error codes / included in execution status.

**Comment by benaadams** [comment]
Resolved by https://github.com/NethermindEth/nethermind/pull/6425, https://github.com/NethermindEth/nethermind/pull/6406, https://github.com/NethermindEth/nethermind/pull/5727
