### ISSUE TITLE
eth_getTransactionReceipt is null for new transactions

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#6344]
Reported by user on discord: https://discordapp.com/channels/629004402170134531/629004402170134537/1182057002130747442

It is reported on Chiado network.

```
curl --data '{"method":"eth_getTransactionReceipt", "params":["0xd1a7a6ddd31237f9485a82c69a10c1702f545fc5a31d5a7c77ddcb14d408612d"], "id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST https://gnosis-chiado.publicnode.com

{"jsonrpc":"2.0","result":null,"id":1}
```

This transaction is 6 days old, so **it is not about TxLookupLimit** (at least if correctly implemented)
https://gnosis-chiado.blockscout.com/tx/0xd1a7a6ddd31237f9485a82c69a10c1702f545fc5a31d5a7c77ddcb14d408612d
![Screenshot from 2023-12-08 10-24-34](https://github.com/NethermindEth/nethermind/assets/9356351/06fab5fc-2096-4f4d-8907-a6050a29aeee)

**Comment by locothedev** [comment]
Here are some more example transaction hashes all from the same block.

Block Number: 7213503
Block Hash: 0xa07d1fc8735c1b0e8a1705101f249e0971f8d8a0bd411e1fc39e644902e43996

0x16ab56ef6650e562ce305f9ea15cb06fb78eb815ca6737523592e556b74f2577
0x51319014039d41494a20e969cb19b8f6196011c35d1dbf34f2a1c9f5ced9d4da

there are more for this block.
