### ISSUE TITLE
Improve newPayload response in case of InvalidBlock.

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#6473]
EF Testing team is preparing new kind of tests for Invalid Blocks checks but seems like our response on invalid block to newPayload seems to be not informative enough.

Geth as an example is throwing messages like "Could not apply transaction N" and trying to output as much as possible out of invalid block to understand the issue better.

This was raised by Mario Vega so more details can be discussed with him.

**Comment by ak88** [comment]
Related to #4891

**Comment by MarekM25** [comment]
closing duplicate
