### ISSUE TITLE
Memory growth - mainnet archive

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#6556]
![Screenshot from 2024-01-18 10-56-43](https://github.com/NethermindEth/nethermind/assets/9356351/d2c57aa8-44f4-44ac-bafc-b40f8c220e94)
Managed memory started growing significantly. Looks like some kind of memory leak.

**Comment by LukaszRozmej** [comment]
Can you grab memory dump?

**Comment by kamilchodola** [comment]
Having same observation on 1.24.0 on my DappNode instance.

Will check for dumps if I have any because something was set by Ahmad once for that.
