### ISSUE TITLE
Incresased networking traffic in 1.25 version?

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#6559]
On some nodes we observed increased networking traffic. This should be investigated further on more nodes. Example from Nethermind archive node
![Screenshot from 2024-01-18 11-07-54](https://github.com/NethermindEth/nethermind/assets/9356351/da057ff5-bd7b-4703-9986-89a03379118b)

**Comment by kamilchodola** [comment]
@brbrr 

So I've noticed that when any node was upgraded from older version to 1.25.0/1.25.1 Traffic chart on our Grafana is bumping quite a lot - but it was one of the observation and not sure if this is only about restart or 1.25.0 actually is doing something weird with it.

it is worth to:
1. Sync 1.24.0
2. Restart it few times in 1h windows and observe Traffic if there is anything unusual happens
3. Bump to 1.25.1 and see what is happening
4. Restart few times on 1.25.1 and observe Traffic

**Comment by brbrr** [comment]
seems like the same behavior is on 1.24

**Comment by LukaszRozmej** [comment]
> seems like the same behavior is on 1.24 <img alt="Screenshot 2024-01-26 at 10 23 30" width="1494" src="https://private-user-images.githubusercontent.com/5654161/299936146-df5d2746-69aa-46ff-b38e-e0b7f32bcb94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjMyODIsIm5iZiI6MTcwNjI2Mjk4MiwicGF0aCI6Ii81NjU0MTYxLzI5OTkzNjE0Ni1kZjVkMjc0Ni02OWFhLTQ2ZmYtYjM4ZS1lMGI3ZjMyYmNiOTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjZUMDk1NjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmQ0NjA2ZmQ4YjZkODFmNTEyNDRmODQ5OWU5MDE0NjQyNDY4Njg5YjBmZjBlNmI3YjA5ZjUyMTg5NzZmMjkwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rIYR2NRfN9Tzj8GhJL1TWDV5upP1WpjYS_Y0e5OId_s">

Nope, this is traffic sent and correlates with high block db usage - someone syncs blocks from us.
