### ISSUE TITLE
Verify eth_call memory with node tests tool

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#6564]
We improved our memory management a lot, but we haven't verified improved with [node tests](https://github.com/NethermindEth/nethermind-node-tests)

**Comment by MarekM25** [comment]
1. Would be great to do profiling dottrace & dotmemory

**Comment by kamilchodola** [comment]
@brbrr 
In case I won't be able to make it soon You can look on that on my leave.

**Comment by kamilchodola** [comment]
@MarekM25 
For sure we improved on flood scenarios with eth_Call - no memory movement at all on very high eth_call load.

Still to check on gnosis with that eth_call scenario.

**Comment by kamilchodola** [comment]
Memory jumped as expected but without any OOM it cleared well back to the initial around 4GB of usage. All looks good!

![Image](https://github.com/NethermindEth/nethermind/assets/43241881/c3fab622-6afb-4712-9272-35439f74acdb)
