### ISSUE TITLE
Run Nethermind Docker image as non-root by default

### ISSUE THREAD

**Issue by luarx** [NethermindEth/nethermind#6567]
**Is your feature request related to a problem? Please describe.**
For security reasons, it would be good to run Nethermind as **non-root by default**
To bring  some context, Erigon runs using a non-root user from a long time ago https://github.com/ledgerwatch/erigon/blob/v2021.07.04/Dockerfile#L20

**Describe the solution you'd like**
Create a user in the Dockerfile and make it the default one

**Comment by rubo** [comment]
We're going to introduce a [chiseled](https://ubuntu.com/engage/chiselled-ubuntu-images-for-containers) and rootless Docker image very soon. That will be a separate image to avoid breaking existing setups that depend on root access. 

We're currently testing that, so it will likely be published in one of the upcoming releases.
