### ISSUE TITLE
Provide additional JSON RPC methods for retrieving AuRa finality status

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#659]
Blocks pending finality, chain scores, list of misbehaving validators, etc...

**Comment by tkstanczak** [comment]
@LukaszRozmej I have added debug.getChainLevel recently - does it cover this scenario enough?

WOuld be gret to have aura module with aura.getValidators aura.getPendingValidators and so on

This may help you in debugging when using CLI against AuRa so might be a good investment now.

**Comment by dceleda** [comment]
@LukaszRozmej @tkstanczak 
Is it still valid or we can close it?

**Comment by LukaszRozmej** [comment]
Closing, not needed
