### ISSUE TITLE
1.25.2 trying to download Old Bodies?

### ISSUE THREAD

**Issue by xanatos** [NethermindEth/nethermind#6590]
I have an old installation of Nethermind. I had the problem that 1.25 was trying to download the old blocks so I had changed the config to add the AncientBodiesBarrier/AncientReceiptsBarrier and restarted. It stopped downloading old blocks. I hadn't updated to 1.25.1 . This morning I've discovered of what happened yesterday (I didn't notice that everything had stopped 13h ago... aaaargh)... I've updated to 1.25.2 and removed the AncientBodiesBarrier/AncientReceiptsBarrier and the Nethermind in its log began writing:

22 Jan 08:54:11 | Old Bodies    8,363,266 / 18,900,000 ( 44.25 %) | queue       689 | current            0 Blk/s | total           17 Blk/s 
22 Jan 08:54:11 | Downloaded   19,056,952 / 19,060,917 ( 99.98 %) | current            0 Blk/s | total            0 Blk/s 
22 Jan 08:54:16 | Old Bodies    8,363,266 / 18,900,000 ( 44.25 %) | queue     4,440 | current            0 Blk/s | total            6 Blk/s 
22 Jan 08:54:16 | Downloaded   19,056,981 / 19,060,917 ( 99.98 %) | current            6 Blk/s | total            4 Blk/s 
22 Jan 08:54:21 | Old Bodies    8,365,026 / 18,900,000 ( 44.26 %) | queue     7,626 | current          352 Blk/s | total          142 Blk/s 

I stopped it, readded the AncientBodiesBarrier, restarted and now it stopped writing those two messages.

Was it trying again to download old bodies? Or was it simply resyncing the last half day of blocks but the log message was "wrong"?

**Comment by smartprogrammer93** [comment]
Closing, feel free to reopen the issue if you still have the problem after applying the suggestion above.
