### ISSUE TITLE
No incoming messages from the consensus client that is required for sync.

### ISSUE THREAD

**Issue by thedavidmeister** [NethermindEth/nethermind#6647]
I just get this error over and over again on initial sync from mainnet, seems that syncing can't proceed for either nethermind or lighthouse

```
01 Feb 15:53:17 | Waiting for Forkchoice message from Consensus Layer to set fresh pivot block [2690s] 
01 Feb 15:53:21 | No incoming messages from the consensus client that is required for sync. 
01 Feb 15:53:26 | No incoming messages from the consensus client that is required for sync. 
01 Feb 15:53:27 | Waiting for Forkchoice message from Consensus Layer to set fresh pivot block [2700s] 
01 Feb 15:53:29 | ***** JSON RPC report *****
-------------------------------------------------------------------------------------------------------------------------------------------------------------
method                                  | successes |  avg time (µs) |  max time (µs) |    errors |  avg time (µs) |  max time (µs) | avg size | total size |
-------------------------------------------------------------------------------------------------------------------------------------------------------------
engine_exchangeCapabilities             |         1 |            597 |            597 |         0 |              0 |              0 |      293 |        293 | 
eth_chainId                             |         5 |            106 |            110 |         0 |              0 |              0 |       39 |        195 | 
eth_getBlockByNumber                    |         5 |            271 |            537 |         0 |              0 |              0 |     1526 |       7630 | 
eth_syncing                             |       145 |            103 |            146 |         0 |              0 |              0 |       99 |      14355 | 
-------------------------------------------------------------------------------------------------------------------------------------------------------------
TOTAL                                   |       156 |            112 |            597 |         0 |              0 |              0 |      144 |      22473 | 
-------------------------------------------------------------------------------------------------------------------------------------------------------------
 
01 Feb 15:53:31 | No incoming messages from the consensus client that is required for sync. 
01 Feb 15:53:31 | Peers | with best block: 98 | all: 99 | eth66 (5 %), eth67 (8 %), eth68 (87 %) | Active: None | Sleeping: All | Geth (67 %), Erigon (16 %), Nethermind (11 %), Besu (5 %) 
01 Feb 15:53:36 | No incoming messages from the consensus client that is required for sync. 
01 Feb 15:53:37 | Waiting for Forkchoice message from Consensus Layer to set fresh pivot block [2710s] 
01 Feb 15:53:41 | No incoming messages from the consensus client that is required for sync. 
01 Feb 15:53:44 | Removing 1467 out of 11467 peer candidates (candidates cleanup). 
01 Feb 15:53:46 | No incoming messages from the consensus client that is required for sync. 
01 Feb 15:53:47 | Waiting for Forkchoice message from Consensus Layer to set fresh pivot block [2720s] 
```

I'm using lighthouse and see that it is saying it's waiting on nethermind, and nethermind is saying its waiting on lighthouse?

```
Feb 01 16:01:28.971 ERRO Error updating deposit contract cache   error: Failed to get remote head and new block ranges: EndpointError(FarBehind), retry_millis: 60000, service: deposit_contract_rpc
Feb 01 16:01:29.001 INFO Syncing                                 est_time: --, distance: 8149558 slots (161 weeks 4 days), peers: 80, service: slot_notifier
Feb 01 16:01:29.001 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Feb 01 16:01:29.001 WARN Not ready for merge                     info: The execution endpoint is connected and configured, however it is not yet synced, service: slot_notifier
Feb 01 16:01:29.001 INFO Ready for Capella                       info: ensure the execution endpoint is updated to the latest Capella/Shanghai release, service: slot_notifier
Feb 01 16:01:41.001 INFO Syncing                                 est_time: --, distance: 8149559 slots (161 weeks 4 days), peers: 80, service: slot_notifier
Feb 01 16:01:41.001 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Feb 01 16:01:41.001 WARN Not ready for merge                     info: The execution endpoint is connected and configured, however it is not yet synced, service: slot_notifier
Feb 01 16:01:41.001 INFO Ready for Capella                       info: ensure the execution endpoint is updated to the latest Capella/Shanghai release, service: slot_notifier
Feb 01 16:01:53.001 INFO Syncing                                 est_time: --, distance: 8149560 slots (161 weeks 4 days), peers: 80, service: slot_notifier
Feb 01 16:01:53.001 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Feb 01 16:01:53.001 WARN Not ready for merge                     info: The execution endpoint is connected and configured, however it is not yet synced, service: slot_notifier
Feb 01 16:01:53.001 INFO Ready for Capella                       info: ensure the execution endpoint is updated to the latest Capella/Shanghai release, service: slot_notifier
```

I've setup the jwt, and am not seeing any auth or connectivity related errors in the logs, just the above output over and over on both

docker images:

nethermind/nethermind:1.25.3
sigp/lighthouse:v4.6.0-modern

I have no idea whether it is nethermind or lighthouse that is the problem, but as i understand "initializing deposits" in the lighthouse logs means that nethermind is supposed to be doing something.

**Comment by thedavidmeister** [comment]
https://github.com/NethermindEth/nethermind/issues/6358 maybe related? except that my node does NOT seem to be running fine, it's been stuck in this loop for about 20 hours now

**Comment by thedavidmeister** [comment]
https://github.com/NethermindEth/nethermind/issues/6050 maybe related?? i've managed to sync nethermind on goerli, as a node that i've been running for some months, but i'm seeing this issue for a fresh sync on mainnet

**Comment by jkjx** [comment]
same issue

**Comment by thedavidmeister** [comment]
```
05 Feb 02:58:11 | No incoming messages from the consensus client that is required for sync. 
05 Feb 02:58:16 | No incoming messages from the consensus client that is required for sync. 
05 Feb 02:58:17 | Waiting for Forkchoice message from Consensus Layer to set fresh pivot block [301790s] 
05 Feb 02:58:21 | No incoming messages from the consensus client that is required for sync. 
05 Feb 02:58:26 | No incoming messages from the consensus client that is required for sync. 
05 Feb 02:58:27 | Waiting for Forkchoice message from Consensus Layer to set fresh pivot block [301800s] 
05 Feb 02:58:31 | No incoming messages from the consensus client that is required for sync. 
05 Feb 02:58:36 | No incoming messages from the consensus client that is required for sync. 
05 Feb 02:58:37 | Waiting for Forkchoice message from Consensus Layer to set fresh pivot block [301810s] 
```

i'm bringing the container down til this issue moves a bit, but i thought i'd post the logs to show it never resolved itself even after several days of looping

**Comment by kamilchodola** [comment]
Did any of You used checkpoint sync for CL?

Feb 01 16:01:29.001 WARN Not ready for merge                     info: The execution endpoint is connected and configured, however it is not yet synced, service: slot_notifier
Feb 01 16:01:29.001 INFO Ready for Capella                       info: ensure the execution endpoint is updated to the latest Capella/Shanghai release, service: slot_notifier
Feb 01 16:01:41.001 INFO Syncing                                 est_time: --, distance: 8149559 slots (161 weeks 4 days), peers: 80, service: slot_notifier


These log shows 161 weeks of sync on CL giving me a hint that maybe Checkpoint sync wasn't used properly

**Comment by thedavidmeister** [comment]
<img width="995" alt="Screenshot 2024-02-18 at 22 24 41" src="https://github.com/NethermindEth/nethermind/assets/629710/18d25a6e-e125-4129-a2cd-2028c59f472c">

@kamilchodola nope no checkpoint sync, docs say it is optional

**Comment by kamilchodola** [comment]
That is valid point.

I'd say it is of course optional but highly recommended - will apply change to docs.

Without checkpoint sync You are syncing whole beacon chain which is already 3 years old. This means You are downloading tons of data which are not necessary needed for anything in regards of validating so there is this simple way to have beacon chains synced within minutes.

**Comment by lucyxliu** [comment]
Same issue. Switching eth2 now.

**Comment by thedavidmeister** [comment]
@kamilchodola so how do i sync my node without checkpoint sync?

i'm fine to wait longer for a sync but the issue here is that the node makes _zero_ progress even if i let it loop for days

**Comment by kamilchodola** [comment]
@thedavidmeister Checkpoint sync is a CL matter, nothing to be done on this side on EL.

Without checkpoint sync CL will sync but it may take weeks to finish and will take plenty of disk space.
None of ELs (Geth, Nethermind, Besu, Erigon, Reth) will start sync process if CL is not ready, that is why Checkpoint sync is highly recommended to be applied since then EL will start syncing within minutes.

**Comment by thedavidmeister** [comment]
> Since 4.6.0, checkpoint sync is required by default and genesis sync will no longer work without the use of --allow-insecure-genesis-sync.

https://lighthouse-book.sigmaprime.io/checkpoint-sync.html

**Comment by kamilchodola** [comment]
@thedavidmeister 
Big change, wasn't aware of it. That shows the importance of checkpointsync now

**Comment by thedavidmeister** [comment]
@kamilchodola yeah massive change, i just happened to spot this one line in the docs while debugging 😅 

i guess it explains why i could continue to sync my existing goerli but couldn't get mainnet working

i think we can close this
