### ISSUE TITLE
Sepolia transaction can't be found

### ISSUE THREAD

**Issue by sunce86** [NethermindEth/nethermind#6663]
**Description**
Specific transaction can't be found by sepolia nethermind node, while it can be found in the list of transactions in the block which contains it.

**Steps to Reproduce**
Issue a request on Sepolia Nethermind node and no tx was found:

`{"method":"eth_getTransactionByHash","params":["0xaa634f11a3818c701f292e89e8a7c40a0a9a8c91cc7783956a1a5d4198d6d1b7"],"id":1,"jsonrpc":"2.0"}`

Response: 
```
{
    "jsonrpc": "2.0",
    "result": null,
    "id": 1
}
```

Issuing another request on the same Sepolia Nethermind node:

`{"method":"eth_getBlockByNumber","params":["0x4FE3DE"],"id":1,"jsonrpc":"2.0"}`

and the transaction `0xaa634f11a3818c701f292e89e8a7c40a0a9a8c91cc7783956a1a5d4198d6d1b7` can be found under the "transactions" field.

By the way, I tried searching for other transactions from the problematic block, and it seems none of them can be fetched.

**Actual behavior**
No tx is found.

**Expected behavior**
Transaction can be found by hash.

**Desktop (please complete the following information):**
Version: 1.25.3
Commit: e64bee7033c6d74cb53323b703cb573a739cd9dd
Build Date: 2024-01-22 15:11:29Z
OS: Linux x64
Runtime: .NET 8.0.1

**Comment by flcl42** [comment]
Hello @sunce86 ! Could you confirm you have receipts for the block? A call to `eth_getBlockReceipts` may help with it. What flags do you start the client with?
