### ISSUE TITLE
ShaMerkleTree class uses SHA256 HashAlgorithm in a thread unsafe manner

### ISSUE THREAD

**Issue by roktomc** [NethermindEth/nethermind#6684]
**Description**
Using [Nethermind.Merkleization.ShaMerkleTree](https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Merkleization/ShaMerkleTree.cs) from multiple threads at the same time produces concurrency issues.  
For example a simple insert operation might randomly break calculation of the Root.

After some investigating it turns out the issue is that the class uses a static instance of SHA256 HashAlgorithm which is not thread safe (more on that can be found here https://stackoverflow.com/questions/73006466/is-hashalgorithm-computehash-thread-safe or here https://wanderingdeveloper.medium.com/c-cautionary-tail-the-dangers-of-sha256-reuse-2b5bb9c6fde9).

**Steps to Reproduce**
```
        [Test]
        public async Task Multiple_threads_create_ShaMerkleTree_instance__root_calculated_properly()
        {
            var bytes = new byte[32];
            bytes[0] = 1;
            var leaf = Bytes32.Wrap(bytes);

            void RunTestForTwoSeconds()
            {
                DateTime endAt = DateTime.Now.AddSeconds(2);
                while (DateTime.Now < endAt)
                {
                    MerkleTree baselineTree = new ShaMerkleTree();
                    baselineTree.Insert(leaf);
                    Convert.ToHexString(baselineTree.Root!.Bytes).ShouldBe(
                        "83D0895A8C6806894FCEB91E47A96F8E75C47A9D27DD3FE1B7CC127E3AAF2244",
                        StringCompareShould.IgnoreCase | StringCompareShould.IgnoreLineEndings
                    );
                }
            }

            Task[] tasks = Enumerable.Range(1, 5).Select(_ => Task.Run(RunTestForTwoSeconds)).ToArray();
            await Task.WhenAll(tasks);
        }
```

**Actual behavior**
On random occasions the root calculation is broken.

From posted test:
(baselineTree.Root!.Bytes)
    should be 
"83D0895A8C6806894FCEB91E47A96F8E75C47A9D27DD3FE1B7CC127E3AAF2244"
    but was
"11953D70B04149241088BBB393116DAE607C0B5EA58DAD4029500CA16CFA2A3D"

**Expected behavior**
Root should always be the same after adding the same leaf to an empty tree.

**Proposed solution**
Lock when accessing [Sha256 instance](https://github.com/NethermindEth/nethermind/blob/aa6ad9baa8539b85b05d7e8e8b6c8ec1a709c253/src/Nethermind/Nethermind.Merkleization/ShaMerkleTree.cs#L15) or create an instance per thread.

**Comment by benaadams** [comment]
https://github.com/NethermindEth/nethermind/pull/6687
