### ISSUE TITLE
Add post state values for block execution to the execution witness

### ISSUE THREAD

**Issue by tanishqjasoria** [NethermindEth/nethermind#6690]
Post verkle, we include ExecutionWitness in the ExecutionPayload
Draft PR: https://github.com/ethereum/consensus-specs/pull/3230/files
In ExecutionWitness, aside from VerkleProof, we also include Keys that were modifed and the corresponding values before(pre-state) and after(post-state) modification.

In the current implemenation, we already include the kpre-state values, now we just need to collect the changed values and add it to the ExecutionWitness.

**Comment by shubham-sonthalia** [comment]
Hi @tanishqjasoria is this issue still relevant? Can I give it a shot?

**Comment by tanishqjasoria** [comment]
yes, this is still relevent.
