### ISSUE TITLE
add a cli tool to convert a synced merkle tree to verkle tree

### ISSUE THREAD

**Issue by tanishqjasoria** [NethermindEth/nethermind#6695]
We need to implement a tool that can convert the merkle tree of the synced state to a verkle tree. We need this to be able to test and get estimates for post-verkle mainnet.

**Comment by murluki** [comment]
is this still relevant? would like to work on it

**Comment by rishabhRsinghvi** [comment]
@tanishqjasoria Interested to do this too.

**Comment by Nityam573** [comment]
I’m interested in this one.
