### ISSUE TITLE
Post mortem on Jan 2024 consensus bug

### ISSUE THREAD

**Issue by kavehtehrani** [NethermindEth/nethermind#6707]
I think a post mortem for the Jan 2024 consensus bug on the mainnet is still outstanding.  The issue has been fixed, but the technical details are still unclear.

https://github.com/NethermindEth/nethermind/releases/tag/1.25.2

Could you please provide a status update?  Thanks.

**Comment by MarekM25** [comment]
We are working on a post-mortem, which we plan to share after the upcoming Dencun hardfork. We appreciate your patience.

**Comment by wga22** [comment]
REF: #6588

**Comment by kavehtehrani** [comment]
https://hackmd.io/@nethermindclient/ByW9sX_R6
