### ISSUE TITLE
Rewrite KnownChainSizesTests

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#6791]
We have to frequently adjust the value in this test, which is irritating. There must be a better way to write this test.

https://github.com/NethermindEth/nethermind/pull/6788/files

**Comment by Demuirgos** [comment]
what is this test exactly testing? it still confuses me

**Comment by benaadams** [comment]
> what is this test exactly testing? it still confuses me

Numbers go up. Not sure really

**Comment by Demuirgos** [comment]
ig it would be more logical if we have some ratio we test for, and we test for state-post-prunning/state-pre-prunning < excpeted-ratio, or something similar, but again it would just move the problem to chosing the ratio ig

**Comment by benaadams** [comment]
Resolved by https://github.com/NethermindEth/nethermind/pull/7291
