### ISSUE TITLE
Exception during BeaconHeaders on archive stops BeaconHeaders from syncing

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#6856]
Started a chiado archive sync.
Noticed that after 1 hour it is not growing at all - looked at logs and there is such exception:
<img width="777" alt="image" src="https://github.com/NethermindEth/nethermind/assets/43241881/df7ff83c-9059-4d0b-8a36-69899335411a">

Right before it BeaconHeaders were syncing properly but afterwards it stopped.

Running 3 chiado archives and 2 of them are working fine.

**Comment by kamilchodola** [comment]
@ak88 Correct me if I'm wrong but this is fixed with gnosis, right?

**Comment by ak88** [comment]
> @ak88 Correct me if I'm wrong but this is fixed with gnosis, right?

Yes its the same bug.
