### ISSUE TITLE
When we use reflection there is an issue with mvc 2.2.5 loading

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#699]
System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=2.2.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

**Comment by tkstanczak** [comment]
private void Initialize()
        {
            var assemblies = AppDomain.CurrentDomain.GetAssemblies().Where(a => a.FullName.StartsWith("Nethermind")).ToArray();
            var type = typeof(IConfig);
            var interfaces = assemblies.SelectMany(x => x.GetTypes()).Where(x => type.IsAssignableFrom(x) && x.IsInterface).ToArray();

**Comment by tkstanczak** [comment]
[Test]
        public void Test1()
        {
            ConfigProvider configProvider = new ConfigProvider();
            var configPath = Path.Combine(TestContext.CurrentContext.TestDirectory, "configs", "ropsten_archive.cfg");
            configProvider.AddSource(new JsonConfigSource(configPath));

            IInitConfig syncConfig = configProvider.GetConfig<IInitConfig>();
            Assert.True(syncConfig.SynchronizationEnabled);
        }

**Comment by tkstanczak** [comment]
This solves it but it should not be required:
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netcoreapp2.2</TargetFramework>

        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="nunit" Version="3.11.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="3.11.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
        **<PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.5"/>**
    </ItemGroup>

**Comment by develorem** [comment]
I have this issue with a brand new .Net Core 2.2 project, and a .Net core unit test project using Nunit (all setup with the default template in VS2019). Wrote a unit test that loaded the assembly of my .Net core services project, and hit this issue. Adding the package reference fixed it.  Thanks @tkstanczak

**Comment by tkstanczak** [comment]
Glad we couls help @develorem. Closing, since we have moved to 3
0.
