### ISSUE TITLE
Compare locust results between Geth, Parity and Nethermind

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#703]
![image](https://user-images.githubusercontent.com/498913/62045117-d6827d00-b204-11e9-9002-c93e6c534c35.png)

Run locust from (benchmarks) against full archive nodes (running locally) of Parity, Geth and Nethermind (they have to be fully synced first).

**Comment by WyseNynja** [comment]
Are the results of these performance checks available anywhere?
