### ISSUE TITLE
When creating contract code, nethermind behavior some weird.

### ISSUE THREAD

**Issue by kimdora** [NethermindEth/nethermind#706]
Hi, I am trying to analyze nethermind's evm. Then I discovered some weird behavior on evm. When I deploy a contract code using `PrepareInitTx` in VirtualMachineTestBase.cs, it always sets the transaction value is 1.

I know that a contract code without constructor sets that value is 0. So, when I tried to deploy this code using `PrepareInitTx`, I failed because it always sets value is 1. But if I set the value in the transaction is 0, then success to deploy.

my bytecode is here.
```
60806040526000805534801561001457600080fd5b506101ec806100246000396000f3fe608060405234801561001057600080fd5b50600436106100625760003560e01c806319e4afbd14610067578063653721471461009557806387db03b7146100b35780638acf5861146100e1578063de2927891461010f578063fa3bd6c51461012d575b600080fd5b6100936004803603602081101561007d57600080fd5b810190808035906020019092919050505061015b565b005b61009d61017e565b6040518082815260200191505060405180910390f35b6100df600480360360208110156100c957600080fd5b8101908080359060200190929190505050610184565b005b61010d600480360360208110156100f757600080fd5b8101908080359060200190929190505050610192565b005b6101176101a0565b6040518082815260200191505060405180910390f35b6101596004803603602081101561014357600080fd5b81019080803590602001909291905050506101a9565b005b600081141561016957600080fd5b806000548161017457fe5b0560008190555050565b60005481565b806000540160008190555050565b806000540260008190555050565b60008054905090565b80600054036000819055505056fea265627a7a72305820311f62e152844af0418110463ce69518037cc73f5d90f052f1907b46b5accc5164736f6c63430005090032
```

**Comment by tkstanczak** [comment]
Possibly the test code sets the value to 1 to have a better test coverage. This is just behaviour of the test code. Please set it to zero as you did for your scenario to work. We can also arrange some time on chat or a zoom call when we can discuss your use cases and suggest solutions. I am interested to see if I can give some better hints.

**Comment by kimdora** [comment]
I don't get the gist of what you say `Possibly the test code sets the value to 1 to have a better test coverage.`.

When I build a transaction like below (without `WithValue`), its value always sets 1.
```
Transaction transaction = Build.A.Transaction
    .WithTo(null)
    .WithData(Bytes.Empty)
    .WithGasLimit((ulong) gasLimit)
    .WithGasPrice(1)
    .WithInit(code)
    .SignedAndResolved(_ethereumEcdsa, TestItem.PrivateKeyA, blockNumber)
    .TestObject;
```
Then it happens quite a critical problem that can't deploy contract code.

When I use below contract code and deploy this code, it always compares 0 with CALLVALUE. And if they are different, always execute `REVERT'. But if setting with value = 0, then success to deploy (return `RETURN`).  
```
60806040526000805534801561001457600080fd5b506101ec806100246000396000f3fe608060405234801561001057600080fd5b50600436106100625760003560e01c806319e4afbd14610067578063653721471461009557806387db03b7146100b35780638acf5861146100e1578063de2927891461010f578063fa3bd6c51461012d575b600080fd5b6100936004803603602081101561007d57600080fd5b810190808035906020019092919050505061015b565b005b61009d61017e565b6040518082815260200191505060405180910390f35b6100df600480360360208110156100c957600080fd5b8101908080359060200190929190505050610184565b005b61010d600480360360208110156100f757600080fd5b8101908080359060200190929190505050610192565b005b6101176101a0565b6040518082815260200191505060405180910390f35b6101596004803603602081101561014357600080fd5b81019080803590602001909291905050506101a9565b005b600081141561016957600080fd5b806000548161017457fe5b0560008190555050565b60005481565b806000540160008190555050565b806000540260008190555050565b60008054905090565b80600054036000819055505056fea265627a7a72305820311f62e152844af0418110463ce69518037cc73f5d90f052f1907b46b5accc5164736f6c63430005090032
```

**Comment by tkstanczak** [comment]
What I mena here:

this is test code only

Transaction transaction = Build.A.Transaction
    .WithTo(null)
    .WithData(Bytes.Empty)
    .WithGasLimit((ulong) gasLimit)
    .WithGasPrice(1)
    .WithInit(code)
    .SignedAndResolved(_ethereumEcdsa, TestItem.PrivateKeyA, blockNumber)
    .TestObject;


it is designed to provide good test coverage and it sets the value to
1 by default to cover corner cases when value is non zero.


You can just set the value to zero on the transaction object.

**Comment by kimdora** [comment]
According to you, without `WithValue`, always set value = 1 in only this case, right? Then another case's default value is 0?

**Comment by tkstanczak** [comment]
I am travelling and will be in the office in ~35 minutes. Will confirm the
code for you then. The default should be the same for all the cases.

**Comment by tkstanczak** [comment]
Checking it now.

**Comment by tkstanczak** [comment]
public TransactionBuilder()
        {   
            TestObjectInternal = new Transaction();
            TestObjectInternal.GasPrice = 1;
            TestObjectInternal.GasLimit = 21000;
            TestObjectInternal.To = Address.Zero;
            TestObjectInternal.Nonce = 0;
            TestObjectInternal.Value = 1;
            TestObjectInternal.Data = new byte[0];
            TestObjectInternal.Timestamp = 0;
        }

**Comment by tkstanczak** [comment]
Look at the test object constructor - it assigns Value of one.
It will suffice to call:
WithInit(code).WithValue(0) to get the desired behaviour.

**Comment by kimdora** [comment]
Oh I see. Thank you for your gentle checking and reply :)
