### ISSUE TITLE
Failed Handhaske with Geth when adding static Nethermind peer

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#7068]
1. Sync Nethermind node
2. Capture its enode
3. Start Geth node with --nodiscover=true flag and with logelevel=5 (trace)
4. Execution admin_addPeer on Geth node with Nethermids enode
5. Observe Geth logs to find:
```
DEBUG[05-24|09:20:06.611] Adding p2p peer                          peercount=1 id=0db02c0fadc9cbe9 conn=staticdial addr=172.232.175.224:30303 name=Nethermind/v1.26.0+0...
TRACE[05-24|09:20:06.611] Starting protocol eth/68                 id=0db02c0fadc9cbe9 conn=staticdial
TRACE[05-24|09:20:06.611] Starting protocol snap/1                 id=0db02c0fadc9cbe9 conn=staticdial
DEBUG[05-24|09:20:06.611] Ethereum handshake failed                id=0db02c0fadc9cbe9 conn=staticdial err=EOF
DEBUG[05-24|09:20:06.611] Message handling failed in `snap`        peer=0db02c0f err=EOF
DEBUG[05-24|09:20:06.611] Removing p2p peer                        peercount=0 id=0db02c0fadc9cbe9 duration="254.845µs" req=false err="snappy: corrupt input"
```

For some reason after several attempts it starts workings but for very long time it does not connect well.

**Comment by asdacap** [comment]
Yes, I've seen this. Its random.

**Comment by asdacap** [comment]
Does not reliably reproduce. In fact, now it does not look like it reproduce at all.

**Comment by kamilchodola** [comment]
@asdacap So it is only reproducible when Nethermind is not reachable (turned off for example). Other than that seems like we can connect easily - onlt question is if this is Geth side bug that they got this when unable to reach static peer or we respond in some not unified way that is weird for Geth?

**Comment by kamilchodola** [comment]
Not sure if actual issue - node is now able to connect easily
