### ISSUE TITLE
How to get the historical snapshot/state?

### ISSUE THREAD

**Issue by tczpl** [NethermindEth/nethermind#7156]
Dear all,

I need the traces started from #19000000 block to now on ETH mainnet.
So I need the client to execute those transactions that with the TraceStore option.
Hence I need the snapshot/state at #19000000. 

(Time/space costs too much for other ways. My current solution is to modify an OpenEthereum client for the recent hard forks. But that seems to be a unsustainable way. So this time I try to change to Nethermind for the Cancun upgrade.)

Unfortunately, the following pivot settings do not work.
    "MaxAttemptsToUpdatePivot": 0,
    "PivotNumber": 19000000,
It will be automatically updated to the latest blockby the client.

So is there any way for me to get the historical snapshot/state?

Thanks for your attentions and help!

**Comment by LukaszRozmej** [comment]
Ah archive is always a problem, to be honest until we implement archive index - which I hope we will release this year - I would recommend syncing Erigon or Reth for your use case. You can archive sync Nethermind too, but with current architecture it would take more time and more disk space.
