### ISSUE TITLE
`FastBlocks` flag is deprecated, but we still have it in default config files

### ISSUE THREAD

**Issue by marcindsobczak** [NethermindEth/nethermind#7166]
We recently deprecated `FastBlocks` flag:
https://github.com/NethermindEth/nethermind/pull/6792

But it wasn't removed from config files (only from a few of them) and we have it in e.g. `mainnet.cfg`, which is printing a log:
`Reading config file from /nethermind/configs/mainnet.cfg
Incorrect config settings found:
ConfigType:JsonConfigFile|Category:SyncConfig|Name:FastBlocks`

We need to remove `FastBlocks` flag from all configs:
https://github.com/NethermindEth/nethermind/tree/master/src/Nethermind/Nethermind.Runner/configs

**Comment by johannesappenzeller** [comment]
Please. Stuff like this is confusing for non-expert node operators, and reduces trust that these config files are actually representing a best-practice default setup.
