### ISSUE TITLE
Nethermind 1.26 and 1.27 returns null to JSON array of requests over websocket

### ISSUE THREAD

**Issue by martinkonecny** [NethermindEth/nethermind#7253]
Nethermind 1.26 and 1.27 returns [null,null] to JSON array request. Nethermind version 1.25 returns array of responses.

_**Steps to Reproduce**_
Connect to Nethermind 1.26 or 1.27 via websocket and send this request:

[{"jsonrpc":"2.0","id":5,"method":"eth_getBlockByNumber","params":["finalized",false]},{"jsonrpc":"2.0","id":6,"method":"eth_getBlockByNumber","params":["safe",false]}]

_**Actual behavior**_
Nethermind 1.26 and 1.27 returns array of "null" 
[null,null]

_**Expected behavior**_
Return answer - safe and finalized block.

 [{"jsonrpc":"2.0","result":{"author":"0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97","difficulty":"0x0","extraData":"0x546974616e2028746974616e6275696c6465722e78797a29","gasLimit":"0x1c9c380","gasUsed":"0xbbdca2","hash":"0x1f447d1635836cf939a9f84cb2ffcdebc13a703f72839b7ecc5c3430bf2c9f9b","logsBloom":"0x1da56027600041944efa1011e6037a011a8c381114020545c6891800bc1339c244a5048d50a822b58282a9420ac769f1cb2ba8a08a31e8d1232d9c6304eb28a00d3e8499414c8b2d7a24e14ae0d689ea279ad0e900462c94c1198e4098e111052b40118b0e66402d035bb9d1a1022fd7560e4011000d4f218702891c01aa504746a85245662881a1f8e1337415b28524c80de5110941a1ca85a9d1d790715a680be9d909c89172068bbec6c3bacb8da1842782ca80b390ad11074f0630006257fb1296d6c51865412268000159d3b8e8085460aa7471c0dd21656642e08ae124101aaa6d218504f52a4603c43fc5c3d693a0b3321b2873c908889d487f317cc0","miner":"0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97","mixHash":"0xb74e2db16ac0fbee72f7b3a07765ec54d47d1f93610849964acfe6bc7a6f433e","nonce":"0x0000000000000000","number":"0x1343b01","parentHash":"0xa47c0b2b7cc9cf2ae398a1f481ba2e5a0c289553babf040b03cd6be47c474741","receiptsRoot":"0x3d71273395e1b0310a6b61cdc3885fcf3fd335d1e785f4716cc9733024967c2f","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x1364d","stateRoot":"

**Comment by LukaszRozmej** [comment]
Thanks for report!

**Comment by martinkonecny** [comment]
> Thanks for report!

Thank you for the fix!
