### ISSUE TITLE
[Gnosis] eth_call - Invalid params

### ISSUE THREAD

**Issue by tibineacsu95** [NethermindEth/nethermind#7306]
**Description**
We are getting an unexpected response when using `eth_call` against our Gnosis Mainnet nodes.

**Steps to Reproduce**
In order to replicate the behavior, please provide a detailed list of steps:

Example request:

`curl -H 'Content-Type: application/json' \
--data-raw '{"id": "1","method":"eth_call","params":[{"to":"0x74Cb5e4eE81b86e70f9045036a1C5477de69eE87","data":"0xc18f52260000000000000000000000000000000071727de22e5e9d8baf0edac6f37da03200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000009a00000000000000000000000000000000000000000000000000000000000000924263934db000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000df4517e772e83eb4e8d082bcd6acbe6428b610e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000540000000000000000000000000009896800000000000000000000000000098968000000000000000000000000000000000000000000000000000000000000f424000000000000000000000000067f16f1f00000000000000000000000067f16f1f0000000000000000000000000000000000000000000000000000000000000620000000000000000000000000000000000000000000000000000000000000064000000000000000000000000000000000000000000000000000000000000003f84e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec671688f0b900000000000000000000000029fcb43b46531bca003ddc8fcb67ffe91900c762000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000344b63e800d0000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000100000000000000000000000038869bf66a61cf6bdb996a6ae40d5853fd43b526000000000000000000000000000000000000000000000000000000000000014000000000000000000000000075cf11467937ce3f2f357ce24ffc3dbf8fd5c2260000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000fd90fad33ee8b58f32c00aceead1358e4afc23f900000000000000000000000000000000000000000000000000000000000001c48d80ff0a00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000172012dd68b007b46fbe91b9a7c3eda5a7a1063cb5b47000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000648d0dc49f0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000075cf11467937ce3f2f357ce24ffc3dbf8fd5c22601fd90fad33ee8b58f32c00aceead1358e4afc23f9000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000640dd9692fe37347be72e261ac1f27f2cbd51b304ca058ee8c9b7efc36c414507fa75f1a5c461e134b6d59c17e25970052fcb7df3eabe4da7a8d614de481668a7d11433a92000000000000000000000000445a0683e494ea0c5af3e83c5159fbe47cf9e76500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a47bb37428000000000000000000000000f64da4efa19b42ef2f897a3d533294b892e6d99e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024d000000000000000000000000000000000000000000000000fd90fad33ee8b58f32c00aceead1358e4afc23f900000000000000000000000000000000000000000000000000000000000000410000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e0ececececececececececececececececececececececececececececececececd5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5af0000000000000000000000000000000000000000000000000000000000000025fefefefefefefefefefefefefefefefefefefefefefefefefefefefefefefefe04fefefefe00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c1226f726967696e223a22687474703a2f2f736166652e676c6f62616c222c2270616464696e67223a225468697320706164732074686520636c69656e74446174614a534f4e20736f20746861742077652063616e206c6561766520726f6f6d20666f72206164646974696f6e616c20696d706c656d656e746174696f6e207370656369666963206669656c647320666f722061206d6f72652061636375726174652027707265566572696669636174696f6e4761732720657374696d6174652e220000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ac4baa220440000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000096000000000000000000000000000000000000000000000000000000000000009a000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000df4517e772e83eb4e8d082bcd6acbe6428b610e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000540000000000000000000000000009896800000000000000000000000000098968000000000000000000000000000000000000000000000000000000000000f424000000000000000000000000067f16f1f00000000000000000000000067f16f1f0000000000000000000000000000000000000000000000000000000000000620000000000000000000000000000000000000000000000000000000000000064000000000000000000000000000000000000000000000000000000000000003f84e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec671688f0b900000000000000000000000029fcb43b46531bca003ddc8fcb67ffe91900c762000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000344b63e800d0000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000100000000000000000000000038869bf66a61cf6bdb996a6ae40d5853fd43b526000000000000000000000000000000000000000000000000000000000000014000000000000000000000000075cf11467937ce3f2f357ce24ffc3dbf8fd5c2260000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000fd90fad33ee8b58f32c00aceead1358e4afc23f900000000000000000000000000000000000000000000000000000000000001c48d80ff0a00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000172012dd68b007b46fbe91b9a7c3eda5a7a1063cb5b47000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000648d0dc49f0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000075cf11467937ce3f2f357ce24ffc3dbf8fd5c22601fd90fad33ee8b58f32c00aceead1358e4afc23f9000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000640dd9692fe37347be72e261ac1f27f2cbd51b304ca058ee8c9b7efc36c414507fa75f1a5c461e134b6d59c17e25970052fcb7df3eabe4da7a8d614de481668a7d11433a92000000000000000000000000445a0683e494ea0c5af3e83c5159fbe47cf9e76500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a47bb37428000000000000000000000000f64da4efa19b42ef2f897a3d533294b892e6d99e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024d000000000000000000000000000000000000000000000000fd90fad33ee8b58f32c00aceead1358e4afc23f900000000000000000000000000000000000000000000000000000000000000410000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e0ececececececececececececececececececececececececececececececececd5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5ad5af0000000000000000000000000000000000000000000000000000000000000025fefefefefefefefefefefefefefefefefefefefefefefefefefefefefefefefe04fefefefe00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c1226f726967696e223a22687474703a2f2f736166652e676c6f62616c222c2270616464696e67223a225468697320706164732074686520636c69656e74446174614a534f4e20736f20746861742077652063616e206c6561766520726f6f6d20666f72206164646974696f6e616c20696d706c656d656e746174696f6e207370656369666963206669656c647320666f722061206d6f72652061636375726174652027707265566572696669636174696f6e4761732720657374696d6174652e2200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000df4517e772e83eb4e8d082bcd6acbe6428b610e00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000a47bb37428000000000000000000000000f64da4efa19b42ef2f897a3d533294b892e6d99e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"},"latest",{"0xdf4517e772e83eb4E8d082bCd6aCbe6428b610e0":{"balance":"0x152d02c7e14af6800000"}}]}' \
localhost:8545`

Response:

`{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params","data":"Incorrect parameters count, expected: 2, actual: 3"},"id":"1"}`

**Actual behavior**
We should get an actual response, as the call works on other binaries, such as Erigon.

**Expected behavior**

Expected response:

`{"jsonrpc":"2.0","id":"1","result":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000001c49941055400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000191e82000000000000000000000000000000000000000000000000001075eb54e26b7900000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000023078000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000104994105540000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000002b1c00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"}`

**Environment**
 
- Operating System:  Ubuntu 22.04 LTS
 - Version:  Nethermind 1.27.1+d2d5d4ae
 - Installation Method: GitHub Release
 - Consensus Client: Lighthouse v5.2.1-9e12c21

**Logs**

<img width="831" alt="image" src="https://github.com/user-attachments/assets/3e6259fe-2358-4678-9012-ca247ec0e11b">

**Comment by rubo** [comment]
As the error message says, it [expects 2 parameters](https://docs.nethermind.io/interacting/json-rpc-ns/eth#eth_call) while got 3. This is the problem:
```json
{"0xdf4517e772e83eb4E8d082bCd6aCbe6428b610e0":{"balance":"0x152d02c7e14af6800000"}}
```

**Comment by MarekM25** [comment]
It is about blockOverrides/stateOverrides, which Nethermind does not currently support. We plan to add support for this. There is also a new JSON-RPC method, eth_simulate, which is more powerful than eth_call and is currently supported by Geth and Nethermind.
