### ISSUE TITLE
Feature Request:  JSON-RPC method eth_getRawTransactionByHash needed

### ISSUE THREAD

**Issue by web3dev2023** [NethermindEth/nethermind#7370]
I have migrated to Nethermind recently and found out that the `eth_getRawTransactionByHash` JSON-RPC method is not implemented on Nethermind.

Reconstructing the raw transaction using `eth_getTransactionByHash` and the（v, r, s）signatures is possible but very hard for most users. Therefore I hope `eth_getRawTransactionByHash` can be implemented.

**Comment by KevinMB0220** [comment]
This is my first issue, and I’m excited to contribute. My name is Kevin, and I’m a member of Dojo Coding. I’ve noticed that the JSON-RPC method `eth_getRawTransactionByHash` is not implemented in Nethermind. Implementing this function would make it easier to obtain raw transactions directly, improving the user experience by avoiding the complexity of reconstructing them manually. I’m willing to collaborate on its development and contribute my experience to help bring this solution forward. @web3dev2023
