### ISSUE TITLE
Remove totalDifficulty from block in json reponse

### ISSUE THREAD

**Issue by smartprogrammer93** [NethermindEth/nethermind#7397]
based on this merged PR:
https://github.com/ethereum/execution-apis/pull/570

**Comment by Elianfarias** [comment]
@smartprogrammer93 Hello! I would like to do this, I come from dojo coding, I would like to contribute to the project!

**Comment by smartprogrammer93** [comment]
@Elianfarias sure go ahead.

**Comment by Elianfarias** [comment]
Hi @smartprogrammer93!
I'm doing my first issue of the Nethermind project.
I understand the context, that the scheme underwent a change, the TotalDifficulty property in the Type Block was removed.
I see in the nethermind solution, there is a "Core" project in which the Block and HeaderBlock classes have the totalDifficulty property, should I delete it and fix the errors that the solution throws?
I don't know which section of discord to send this query, could you tell me so I don't bother you in private next time?

**Comment by LukaszRozmej** [comment]
@smartprogrammer93 are we sure this is good idea? We still support AuRa and Clique networks, where total difficulty has meaning. We still support block explorers like blockscout which could use it.

**Comment by LukaszRozmej** [comment]
To be honest I wouldn't merge that PR. Just because Main Ethereum doesn't need it (and spec is about main Ethereum), doesn't mean we should remove it because our clients are using other consensus algorithms and may still need it. Just let it be until proven unnecessary.
