### ISSUE TITLE
Boot nodes refuse connection when running InitializeBootnodes() @ DiscoveryApp.cs | Optimism mainnet 

### ISSUE THREAD

**Issue by astralmaster** [NethermindEth/nethermind#7463]
**Description**

Nethermind 1.28.0, every single bootnode from `ChainSpec` returns connection reset `RST,ACK` when attempting to contact them during normal startup procedures in `Nethermind.Network.Discovery`'s `DiscoveryApp.cs`.

Default `op-mainnet.cfg`;
Client execution command line args: `-c op-mainnet  -dd  \"x:/xxxxxxxx\" --JsonRpc.JwtSecretFile \"x:/xxxxxxxx/jwt/jwtsecret\"  --JsonRpc.Host \"x.x.x.x\"  --JsonRpc.EnginePort 8552 --JsonRpc.EngineHost \"x.x.x.x\" --JsonRpc.Enabled true --HealthChecks.Enabled true --HealthChecks.UIEnabled true --Network.MaxActivePeers 250 --Pruning.Mode=Hybrid --Pruning.FullPruningTrigger=StateDbSize --Pruning.FullPruningThresholdMb=500000 --JsonRpc.EnabledModules=\"[Eth, Subscribe, Trace, TxPool, Web3, Personal, Proof, Net, Parity, Health, Rpc, Admin]\"`

 - Consensus Client `op-node` compiled from source ([op-stack v1.9.1](https://github.com/ethereum-optimism/optimism/releases/tag/v1.9.1))

Tested on two separate systems with different WAN IPs and the same exact config:
Ubuntu 22.04/i9 14900KF/64GB RAM
Windows 10/i9 13900KF/32GB RAM

**Screenshots**

![2024-09-19_154111](https://github.com/user-attachments/assets/d05ebe76-eab6-408f-b9b1-2f5a24cb5ece)

`PingMsg` object's fields when constructed and sent:

![2024-09-19_155801](https://github.com/user-attachments/assets/177d2d72-88f1-478b-b418-729b2c3e0843)

**Logs**

`Could not communicate with any nodes (bootnodes, trusted nodes, persisted nodes).` Since none of the nodes actually establish connection and therefore `NodeLifecycleState.Active` is never set.

**Comment by flcl42** [comment]
Bootnodes are just for discovery(UDP), still the client tries to connect to them via devp2p(TCP) to query headers and other things, and it fails, which is OK.

Also the screenshot displays PingMsg usage which is from discv4 - previous version of discovery, which is not expected, op-mainnet has Discv5 enabled. Could you confirm op-mainnet config is used?

**Comment by astralmaster** [comment]
Ah, then I suggest adding `"DiscoveryVersion": "V5"` to `op-mainnet.cfg`'s `Discovery` config object, since otherwise it wont be expressly set from any `IConfigSource`  and will [default ](https://github.com/NethermindEth/nethermind/blob/1fc24b68dfe9edcbe89a5b933a442f7c48c4acd8/src/Nethermind/Nethermind.Network.Discovery/DiscoveryConfig.cs#L46) to `V4` unless user specifies it.  You probably meant to refactor this line 

https://github.com/NethermindEth/nethermind/blob/1fc24b68dfe9edcbe89a5b933a442f7c48c4acd8/src/Nethermind/Nethermind.Runner/configs/op-mainnet.cfg#L24-L26

**Comment by flcl42** [comment]
Indeed! This is definitely a config issue, thanks for the report! Let me make a pr
