### ISSUE TITLE
Implement 7702 related changes for pectra-devnet-4

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#7523]
7702 alignment of specs with tests: https://github.com/ethereum/EIPs/pull/8906
Do not allow authorization nonce equal to 2**64 - 1: https://github.com/ethereum/EIPs/pull/8905
execution: Eip 7702 schema and authlist in receipt schema: https://github.com/ethereum/execution-apis/pull/592

**Comment by ak88** [comment]
Merged in #7590
