### ISSUE TITLE
Remove `Stopwatch.StartNew()` and `new Stopwatch` where makes sense

### ISSUE THREAD

**Issue by LukaszRozmej** [NethermindEth/nethermind#7553]
Change to new non-allocating api: https://github.com/dotnet/runtime/issues/65858
Will remove a bit of allocations

**Comment by ssonthal** [comment]
Hey @LukaszRozmej , did you mean: 

Replace: 
`StopWatch stopwatch = new StopWatch();`
`stopwatch.Start();` 
With: 
`StopWatch.StartNew();`

**Comment by LukaszRozmej** [comment]
No:

``
long starting = Stopwatch.GetTimestamp();
...
TimeSpan time = Stopwatch.GetElapsedTime(starting);

```

**Comment by ssonthal** [comment]
@LukaszRozmej Thanks for clarification. Can you take a look at the PR once? I have updated the same at places where we are using stopwatch object as a local variable.
