### ISSUE TITLE
GetBlobsV1 with Teku

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#7574]
rocketpool_eth2          | 2024-10-08 10:57:21.860 WARN  - Local EL blobs lookup failed: CompletionException: tech.pegasys.teku.ethereum.executionclient.response.InvalidRemoteResponseException: Invalid remote response from the execution client: Cannot deserialize value of type `java.util.ArrayList<tech.pegasys.teku.ethereum.executionclient.schema.BlobAndProofV1>` from Object value (token `JsonToken.START_OBJECT`)
rocketpool_eth2          |  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 27] (through reference chain: tech.pegasys.teku.ethereum.executionclient.web3j.Web3JExecutionEngineClient$GetBlobsVersionV1Web3jResponse["result"])

Details: https://discordapp.com/channels/629004402170134531/629004402170134537/1293170041256280138

**Comment by LukaszRozmej** [comment]
Would be good to have the json

**Comment by tbenr** [comment]
the other curious thing is that, on our holesky fleet, the nethermind node never retrieve any blobs from local EL, while all the besus give us results most of the times:


<img width="1162" alt="image" src="https://github.com/user-attachments/assets/41ee89fd-1a70-4b81-a14c-d0f710e6805a">

**Comment by tbenr** [comment]
there are not causing any error, I guess they are just empty responses.

**Comment by tbenr** [comment]
checking I see 5 errors in the last 24h. So I think most of the times it returns an empty list. Rarely it's giving us an error.

**Comment by marcindsobczak** [comment]
@tbenr We were sending results in wrong format, it should be fine with current master

**Comment by tbenr** [comment]
@marcindsobczak nice! will be able to test on your next release
