### ISSUE TITLE
Old Headers sync crashes on op-mainnet

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#7626]
On recent master branch during OldHeaders on op-mainnet quite often started getting this exception:

```
System.OverflowException: Underflow in subtraction 0 - 2
   at Nethermind.Int256.UInt256.ThrowOverflowException(String message)
   at Nethermind.Synchronization.FastBlocks.HeadersSyncFeed.InsertHeaders(HeadersSyncBatch batch) in /src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs:line 616
   at Nethermind.Synchronization.FastBlocks.HeadersSyncFeed.HandleDependentBatches(CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs:line 278
   at Nethermind.Synchronization.FastBlocks.HeadersSyncFeed.PrepareRequest(CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs:line 303
   at Nethermind.Synchronization.ParallelSync.SyncDispatcher`1.Start(CancellationToken cancellationToken)
```

From two consecutive runs I can say it happened both times around progress 21,470,000.

**Comment by emlautarom1** [comment]
Issue seems to be here:

https://github.com/NethermindEth/nethermind/blob/81cb4f5c2e3351b371eb50c942e600704026221b/src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs#L715-L719

That is, `TotalDifficulty` is `null` while `Difficulty` is `!= 0`. This is not the first time we have inconsistencies where `TotalDifficulty < Difficulty`

**Comment by emlautarom1** [comment]
Here is a similar issue: https://github.com/NethermindEth/nethermind/issues/6125

**Comment by kamilchodola** [comment]
This time this is easily reproducible

**Comment by jmederosalvarado** [comment]
We default to total difficulty being valid when it's null [here](https://github.com/nethermindeth/nethermind/blob/81cb4f5c2e3351b371eb50c942e600704026221b/src/Nethermind/Nethermind.Consensus/Validators/HeaderValidator.cs#L262-L287)

```cs
        protected virtual bool ValidateTotalDifficulty(BlockHeader parent, BlockHeader header, ref string? error)
        {
            bool result = true;

            if (header.TotalDifficulty is not null)
            {
                if (header.TotalDifficulty == 0)
                {
                    // Same as in BlockTree.SetTotalDifficulty
                    if (!(_blockTree.Genesis!.Difficulty == 0 && _specProvider.TerminalTotalDifficulty == 0))
                    {
                        if (_logger.IsDebug) _logger.Debug($"Invalid block header ({header.Hash}) - zero total difficulty when genesis or ttd is not zero");
                        result = false;
                        error = BlockErrorMessages.InvalidTotalDifficulty;
                    }
                }
                else if (parent.TotalDifficulty + header.Difficulty != header.TotalDifficulty)
                {
                    if (_logger.IsDebug) _logger.Debug($"Invalid block header ({header.Hash}) - incorrect total difficulty");
                    result = false;
                    error = BlockErrorMessages.InvalidTotalDifficulty;
                }
            }

            return result;
        }
```

**Comment by emlautarom1** [comment]
Issue was introduced on #7613, an auto-update which changed the pivot value for OP-mainnet among other chains. On a previous PR (#7588) we manually changed the `PivotTotalDifficulty` from `0` to `210470125` which allowed us to sync, but the automatic update has broken this configuration.

During the first PR some questions were raised regarding the source of this `PivotTotalDifficulty`, particularly its mismatch with what you can find on the Optimism block explorer: we changed the value from `0` to `210470125` but according to the Optimism block explorer it should be `0`.

Rolling back the changes introduced by the auto-update fix this issue and we don't get an error while downloading old headers, yet I fear that this is just masking the real problem.

**Comment by kamilchodola** [comment]
@emlautarom1 More likely issue is in here then:
https://github.com/NethermindEth/nethermind/pull/7448

Mine was just using the action edited adding small change to packages installation

**Comment by emlautarom1** [comment]
@kamilchodola I don't think that is particularly the issue but rather that the "working" config is hiding another problem: in blocks `[105235063, ...]`, `TotalDifficulty == Difficulty == 0` while in blocks `[1, ... 105235062]`, all blocks have `Difficulty == 2`, while `TotalDifficulty` is the `TotalDifficulty` of the previous block + the current Difficulty, while block 0 has a `TotalDifficulty == 1`.

This later computation can be rewritten as "the previous block `TotalDifficulty` is the current block `TotalDifficulty - Difficulty`". For block `105235063` we compute that the `TotalDifficulty` of its predecessor (block `105235062`) is `0 - 0 == 0`, but in the next iteration, when processing block 105235062 we compute `0 - 2`, which triggers the exception.
