### ISSUE TITLE
Broken link for https://docs.nethermind.io/nethermind/

### ISSUE THREAD

**Issue by vanshika-srivastava** [NethermindEth/nethermind#7654]
**Description**
Launchpad Ethereum inlcudes this link which is broken : https://launchpad.ethereum.org/en/nethermind

**Steps to Reproduce**
In order to replicate the behavior, please provide a detailed list of steps:
1. Go to 'https://launchpad.ethereum.org/en/nethermind'
2. Click on '[Documentation on running Nethermind](https://docs.nethermind.io/nethermind/)'
4. Scroll down to click on the link

**Actual behavior**
Goes to a dead link on nethermind docs

**Expected behavior**
Can there be a link that points towards a working link

**Screenshots**
If applicable, please include screenshots to help illustrate the problem.

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: [e.g. Windows]
 - Version: [e.g. 1.17.0]
 - Installation Method: [e.g. GitHub Release/PPA/Homebrew/Docker]
 - Consensus Client: [e.g. Lodestar v1.4.3]

**Additional context**
Please provide any additional context about the problem.

**Logs**
Please include any relevant logs that may help identify the issue.

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by MarekM25** [comment]
@brbrr can you find the person from EF responsible for launchpad and propose the changes?

I mean update descriptions, links to docs etc.

**Comment by MarekM25** [comment]
https://github.com/rubo/staking-launchpad/commit/425e4b35f40d93e5bce0ae834085febd24a425b5 @rubo solved it :)
