### ISSUE TITLE
After changing the data directory for nethermind client, default jwt secret is still generated in default directory.

### ISSUE THREAD

**Issue by obasekiosa** [NethermindEth/nethermind#7746]
**Description**
In the absense of jwt-secret file and a change in default data directory, jwt-secret file is still generated in default data directory.

Note:
check for similar behaviour if data directory is specified using env or config file.

**Steps to Reproduce**
In order to replicate the behavior, please provide a detailed list of steps:
1) change the default data directory using `--dd <new_data_dir>`
2) delete previous jwt-secret
3) ensure jwt-secret is not specified in config file or as config  parameter (so it gets auto generated)

**Actual behavior**
jwt-secret file is generated in `src/Nethermind/Nethermind.Runner/keystore.`

**Expected behavior**
jwt-secret file should be generated in `<new_data_dir>/keystore`

**Comment by ssonthal** [comment]
Hey @obasekiosa , can you check if the linked PR addresses the issue.

**Comment by mimisavage** [comment]
Can I take care of this issue?

**Comment by Nityam573** [comment]
May I take this issue on?

**Comment by mymiracle0118** [comment]
Can I take this from here?
