### ISSUE TITLE
Nethermind client should log when it auto-generates jwt-secret file

### ISSUE THREAD

**Issue by obasekiosa** [NethermindEth/nethermind#7747]
**Is your feature request related to a problem? Please describe.**

Right now the client only logs on start up when it doesn't see a keystore directory in the data directory and generates one.

**It should log when it also generates a new jwt-secret file.**

**Comment by MarekM25** [comment]
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Core/Authentication/JwtAuthentication.cs#L48

Do we need something more?

**Comment by obasekiosa** [comment]
> https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Core/Authentication/JwtAuthentication.cs#L48
> 
> Do we need something more?

When i ran the code, it seemed to silently do this, when it sees a `keystore dir` but no `jwt-secret` file
it does log when there's no `keystore dir`

**Comment by obasekiosa** [comment]
@ssonthal 
want to try this?

**Comment by ssonthal** [comment]
Sure. Will work on this.

**Comment by obasekiosa** [comment]
> Sure. Will work on this.
@ssonthal 

so.
the first step is to reproduce the issue, especially because @MarekM25  thinks it's not an issue since there's reference code that should perform the expected action.


To reproduce:
1) ensure keystore directory is deleted

2) simply start a nethermind client (no need for consensus client, no need for change of data directory or setting JWTSecretFile option in config)

3) check that the jwt-secret file is created and theres a log on console showing that.

4) now shutdown the client and go into the keystore directory, delete the jwt-secret file.

5) restart the client and  repeat the check line 3.

**Comment by ssonthal** [comment]
Hey @MarekM25 / @obasekiosa 

I could reproduce this issue locally. Here's a screenshot of the logs after 1. running the client 2. verifying that jwt-secret file exists at Nethermind.Runner/keystore path. 3. shutting down the client, 4. deleting the jwt-secret file at keystore and 5. restarting the client.

![Screenshot 2024-11-22 at 10 54 24 PM](https://github.com/user-attachments/assets/6b360466-e2a7-454b-89fb-3ddbaf410796)

**Comment by obasekiosa** [comment]
> Hey @MarekM25 / @obasekiosa
> 
> I could reproduce this issue locally. Here's a screenshot of the logs after:
> 
> 1. running the client
> 2. verifying that jwt-secret file exists at Nethermind.Runner/keystore path.
> 3. shutting down the client
> 4. deleting the jwt-secret file at keystore
> 5. restarting the client.
> 
> ![Screenshot 2024-11-22 at 10 54 24 PM](https://private-user-images.githubusercontent.com/54079322/389034984-6b360466-e2a7-454b-89fb-3ddbaf410796.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyOTY4OTAsIm5iZiI6MTczMjI5NjU5MCwicGF0aCI6Ii81NDA3OTMyMi8zODkwMzQ5ODQtNmIzNjA0NjYtZTJhNy00NTRiLTg5ZmItM2RkYmFmNDEwNzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDE3Mjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOWY2MzQ1NTA1NDVjOTY0ZTQ1ZjI3MTU0M2MxY2I2ODI1YTBkOTE3ODRmYzA3NzA0YjQ4NzdjYmQ4MDEyMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h5DWYxoufDbDuXgrTe3ifrcTSWPxaZqiHHBhCF2rDRg)
> 
> As you can see the jwt-secret was auto-generated by the client but no warning logs appeared.

Nice!

So the expected log level should be **info** not **warning**.

[The default level of logs displayed by the client is info ](https://docs.nethermind.io/next/fundamentals/configuration#log)

now that you know this and can reproduce it, you could attempt finding out what the issue is 
then how to fix it. 
could start by looking for the code that regenerates the file, and then also the link @MarekM25  [posted ](https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Core/Authentication/JwtAuthentication.cs#L48)

another place to check is the location of the code that logs the "Reading authentication secret..." line of the logs.

good luck.

**Comment by ssonthal** [comment]
Hey @obasekiosa , I must have done something wrong the prev time. I tried multiple time to reproduce that issue again. but it seems to be logging the msgs fine. Tried thrice after the first attempt.

![Screenshot 2024-11-22 at 11 28 28 PM](https://github.com/user-attachments/assets/142c8685-f136-454f-82df-a786dcd14d53)

**Comment by obasekiosa** [comment]
> Hey @obasekiosa , I must have done something wrong the prev time. I tried multiple time to reproduce that issue again. but it seems to be logging the msgs fine. Tried thrice after the first attempt.
> 
> ![Screenshot 2024-11-22 at 11 28 28 PM](https://private-user-images.githubusercontent.com/54079322/389047015-142c8685-f136-454f-82df-a786dcd14d53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyOTg3ODYsIm5iZiI6MTczMjI5ODQ4NiwicGF0aCI6Ii81NDA3OTMyMi8zODkwNDcwMTUtMTQyYzg2ODUtZjEzNi00NTRmLTgyZGYtYTc4NmRjZDE0ZDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDE4MDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTVmNjYwOGU3NmRkZGYzYzRhZmI4ZTRjNzczMTNiMjM4NWYyOWQ3Y2YxODcyODcyMmIxN2ZiNGQ0MzMyYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fLLcMWUdwiZcWGCa6A0OxyfSmD-eMm0-JP_0OSxCf80)

@ssonthal 
looking at your log, i can see what the issue is.

its being logged as a warning. (colored)
Seems your log level is now higher than info.

in the mean time wanna try [7748](https://github.com/NethermindEth/nethermind/issues/7748)

I'll close this as closed

**Comment by obasekiosa** [comment]
closing this.
