### ISSUE TITLE
Format of `engine_getBlobsV1` response is incorrect

### ISSUE THREAD

**Issue by michaelsproul** [NethermindEth/nethermind#7803]
**Description**

Testing our upcoming Lighthouse v6.0.0 release with Nethermind v1.29.1, I noticed a lot of errors:

> ERRO Error fetching or processing blobs from EL, block_root: 0xe18b4a4eee03c2bf781f5aa9d5e5a1d62b01a9be4e4fe4bab106f9463b73a80c, error: RequestFailed(EngineError(Api { error: Json(Error("invalid type: map, expected a sequence", line: 0, column: 0)) }))

The issue is that Lighthouse is expecting a response of the form:

```
[
   [{"blob": "..", "proof": ".."}]
]
```

i.e. a list of `BlobAndProofV1` as the 0th element of the `params` list.

What Nethermind returns is just:

```
[{"blob": "..", "proof": ".."}]
```

i.e. a list of `BlobsAndProofV1` without the outer `params` list.

I think Nethermind is deviating from [the spec](https://github.com/ethereum/execution-apis/blob/main/src/engine/cancun.md#blobandproofv1), which indicates that the list should be nested. This is also how the API is implemented by Reth and Besu, which Lighthouse works correctly with.

**Steps to Reproduce**

Run `sigp/lighthouse:latest-unstable` with Nethermind v1.29.1.

**Configuration**

 - Operating System: Linux
 - Version: v1.29.1
 - Installation Method: Docker
 - Consensus Client: Lighthouse v6.0.0 RC (https://github.com/sigp/lighthouse/pull/6605)

**Comment by LukaszRozmej** [comment]
So from spec:

```
result: Array of BlobAndProofV1 - Array of BlobAndProofV1

BlobAndProofV1
    blob: ...
    proof: ...
```

So I read this as 
```
[{"blob": "..", "proof": ".."}]
```

Where do yo get additional array and expect below?

```
[
   [{"blob": "..", "proof": ".."}]
]
```

**Comment by marcindsobczak** [comment]
We already adjusted format of our response here: https://github.com/NethermindEth/nethermind/pull/7650
It is on master, but not released yet. You were testing a version without it. Not sure if it is what you are expecting

**Comment by marcindsobczak** [comment]
And it was (a fix from master) tested with Teku and Lodestar, working fine

**Comment by michaelsproul** [comment]
Oh yeah I got mixed up, sorry 😅 I meant to test manually and look at the response but it was too hard to convert KZG committments to versioned hashes in bash so I did not. My bad.

I will test the master branch ASAP, but sounds like this is solved!
