### ISSUE TITLE
Implement admin_datadir for admin module.

### ISSUE THREAD

**Issue by obasekiosa** [NethermindEth/nethermind#7812]
**Is your feature request related to a problem? Please describe.**
https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-admin#admin-datadir

Basically returns the  db base path

**Comment by AlakaTahir** [comment]
I am excited to contribute to this issue., with my experience in backend development.

**Comment by obasekiosa** [comment]
@AlakaTahir 
sure go ahead.

you can ask questions in this thread.

**Comment by mimisavage** [comment]
I'd love to work on this!
