### ISSUE TITLE
Create apt-get install package for Nethermind

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#79]
https://askubuntu.com/questions/336130/create-apt-get-install-for-own-software

**Comment by rlanga** [comment]
What about packaging it into a snap package or flatpak? Those seem to have significant adoption now. Plus with flatpak you can target more Linux distros as apt is limited to Debian based distros

**Comment by tkstanczak** [comment]
I will read about flatpak and snap

**Comment by tkstanczak** [comment]
we will go with snapcraft, thanks @rlanga
