### ISSUE TITLE
Keep switching to low latency nodes when synchronizing

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#87]
Sync manager should keep trying different nodes to test their latency (either solely based on ping response times or by testing the block requests). Then if the latency offered is much better it should start synchronization and if it remains stable it should switch from the current sync node to the new one.

**Comment by tkstanczak** [comment]
this improved sync a lot, just need to stabilize behaviour now

**Comment by glesniakiewicz** [comment]
Found a bug related to UInt256 overflow issue, fixed it. It removes situation when sync switch is requested and new sync is performed with the same Node. 

Overall latency based sync switch works very well - the algorithm gives a chance to new nodes to try sync and if latency is worse switches back to old once which were faster.
