### ISSUE TITLE
Issue when launching

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#915]
by @roninkaizen

update-
with ubuntu 19.04 i got a close related error from the system while starting,
it "goes like this":
The application to execute does not exist: '/home/ubuntu/.local/share/warp/packages/Nethermind.Runner/Nethermind.Runner.dll'.

**Comment by tkstanczak** [comment]
this is on german language version

**Comment by spetz** [comment]
We're moving towards .NET Core 3.0 single file publish feature, so hopefully, it will be resolved soon.
