### ISSUE TITLE
Prepare 5.18.3 librocks build for Alpine Linux

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#923]
Our Linux lib is built on ubuntu, we would need either a working build script or an Alpine build.

There are sime instructions for it on our Confluence

-> NativeImport.NativeLoadException: Unable to locate rocksdb native library, either install it, or use RocksDbNative nuget package
Searched:
/nethermind/runtimes/linux-x64/native/librocksdb-5.18.3.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/runtimes/linux-x64/native/librocksdb-5.18.3.so: No such file or directory
/nethermind/runtimes/linux-x64/native/librocksdb-5.18.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/runtimes/linux-x64/native/librocksdb-5.18.so: No such file or directory
/nethermind/runtimes/linux-x64/native/librocksdb-5.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/runtimes/linux-x64/native/librocksdb-5.so: No such file or directory
/nethermind/runtimes/linux-x64/native/librocksdb.so: (NativeLoadException) dlopen: Error loading shared library libsnappy.so.1: No such file or directory (needed by /nethermind/runtimes/linux-x64/native/librocksdb.so)
/nethermind/native/amd64/librocksdb-5.18.3.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/native/amd64/librocksdb-5.18.3.so: No such file or directory
/nethermind/native/amd64/librocksdb-5.18.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/native/amd64/librocksdb-5.18.so: No such file or directory
/nethermind/native/amd64/librocksdb-5.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/native/amd64/librocksdb-5.so: No such file or directory
/nethermind/native/amd64/librocksdb.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/native/amd64/librocksdb.so: No such file or directory
/nethermind/native/librocksdb-5.18.3.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/native/librocksdb-5.18.3.so: No such file or directory
/nethermind/native/librocksdb-5.18.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/native/librocksdb-5.18.so: No such file or directory
/nethermind/native/librocksdb-5.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/native/librocksdb-5.so: No such file or directory
/nethermind/native/librocksdb.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/native/librocksdb.so: No such file or directory
/nethermind/amd64/librocksdb-5.18.3.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/amd64/librocksdb-5.18.3.so: No such file or directory
/nethermind/amd64/librocksdb-5.18.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/amd64/librocksdb-5.18.so: No such file or directory
/nethermind/amd64/librocksdb-5.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/amd64/librocksdb-5.so: No such file or directory
/nethermind/amd64/librocksdb.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/amd64/librocksdb.so: No such file or directory
/nethermind/librocksdb-5.18.3.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/librocksdb-5.18.3.so: No such file or directory
/nethermind/librocksdb-5.18.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/librocksdb-5.18.so: No such file or directory
/nethermind/librocksdb-5.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/librocksdb-5.so: No such file or directory
/nethermind/librocksdb.so: (NativeLoadException) dlopen: Error loading shared library /nethermind/librocksdb.so: No such file or directory
librocksdb-5.18.3.so: (NativeLoadException) dlopen: Error loading shared library librocksdb-5.18.3.so: No such file or directory
librocksdb-5.18.so: (NativeLoadException) dlopen: Error loading shared library librocksdb-5.18.so: No such file or directory
librocksdb-5.so: (NativeLoadException) dlopen: Error loading shared library librocksdb-5.so: No such file or directory
librocksdb.so: (NativeLoadException) dlopen: Error loading shared library librocksdb.so: No such file or directory
   at NativeImport.Importers.Import[T](INativeLibImporter importer, String libName, String version, Boolean suppressUnload)
   at NativeImport.Auto.Import[T](String name, String version, Boolean suppressUnload) in /source/src/rocksdb-sharp/RocksDbSharp/AutoNativeImport.cs:line 39
   at RocksDbSharp.Native..cctor() in /source/src/rocksdb-sharp/RocksDbSharp/Native.Load.cs:line 18
   --- End of inner exception stack trace ---
   at RocksDbSharp.BlockBasedTableOptions..ctor() in /source/src/rocksdb-sharp/RocksDbSharp/BlockBasedTableOptions.cs:line 18
   at Nethermind.Db.DbOnTheRocks.BuildOptions(IDbConfig dbConfig) in /source/src/Nethermind/Nethermind.Db/DbOnTheRocks.cs:line 87
   at Nethermind.Db.DbOnTheRocks..ctor(String basePath, String dbPath, IDbConfig dbConfig, ILogManager logManager) in /source/src/Nethermind/Nethermind.Db/DbOnTheRocks.cs:line 57
   at Nethermind.Db.Databases.BlocksRocksDb..ctor(String basePath, IDbConfig dbConfig, ILogManager logManager) in /source/src/Nethermind/Nethermind.Db/Databases/BlocksRocksDb.cs:line 33
   at Nethermind.Db.RocksDbProvider..ctor(String basePath, IDbConfig dbConfig, ILogManager logManager, Boolean useTraceDb, Boolean useReceiptsDb) in /source/src/Nethermind/Nethermind.Db/RocksDbProvider.cs:line 30
   at Nethermind.Runner.Runners.EthereumRunner.InitBlockchain() in /source/src/Nethermind/Nethermind.Runner/Runners/EthereumRunner.cs:line 421
   at Nethermind.Runner.Runners.EthereumRunner.Start() in /source/src/Nethermind/Nethermind.Runner/Runners/EthereumRunn

**Comment by one-three-three-seven** [comment]
https://github.com/one-three-three-seven/nethermind-docker

That's the Dockerfile I'm working on. Currently it's using librocksdb from the rocksdb-dev package.

**Comment by tkstanczak** [comment]
@one-three-three-seven got problems to prioritize it, we are focusing on running the full JSON RPC test suite, then will look at this again
I remember that JSON RPC / eth_call was important for you too so hope that you are not too much affected by the delay here.
