### ISSUE TITLE
Errors calling `eth_getCode` JSON RPC method

### ISSUE THREAD

**Issue by Mikerah** [NethermindEth/nethermind#948]
I have a nethermind node setup on an AWS instance for processing.
When trying to query the node using the JSON RPC API, I get two different errors depending on what I use to query the node:
- An "eth_getCode method is not implemented error" when using curl, or
- An "json parser couldn't parse the POST request" when using Python's request library through a jupyter notebook.

I have ran both `Nethermind.Launcher` and `Nethermind.Runner` with the configs that come with the default installation. 

What steps am I missing to get data from my node?

Thank you

**Comment by tkstanczak** [comment]
Hi, which version of Nethermond are you using? Which python library are you calling? The curl should work, can you past the exact request here?

**Comment by tkstanczak** [comment]
Current master / version 1.1.5 works ok with CLI. There must be something specific about the formatting or maybe you are using a very old version. Let me know.
![image](https://user-images.githubusercontent.com/498913/67981631-f74dda80-fc18-11e9-81d9-40606539343f.png)
![image](https://user-images.githubusercontent.com/498913/67981660-07fe5080-fc19-11e9-8341-b77b7f670483.png)

**Comment by tkstanczak** [comment]
Hmmm, @Mikerah this might be that you just passed the account without the block parameter and we may need to add a support for the default value for the block parmeter.

**Comment by tkstanczak** [comment]
@Mikerah there is a fix for default values in https://github.com/NethermindEth/nethermind/pull/949
this will be merged and released (probably tomorrow)
---
not sure if this is exactly the problem you are facing - most likely something different but it will be hard to find it unless you send some details of the lib / curl used

**Comment by Mikerah** [comment]
I am running Nethermind 1.1.0. The curl version is 7.61.1. The version of the requests library is 2.22.0.

The curl request I was using is the example from the JSON RPC page:
`curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getCode","params":["0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b", "0x2"],"id":1}'`

**Comment by tkstanczak** [comment]
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getCode","params":["0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b", "0x2"],"id":1}'

{"id":1,"jsonrpc":"2.0","result":"0x"}

===

>>> response = requests.post('http://', data={"jsonrpc":"2.0","method":"eth_getCode","params":["0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b", "0x2"],"id":1})
>>> response.headers
{'Date': 'Fri, 01 Nov 2019 09:10:56 GMT', 'Transfer-Encoding': 'chunked', 'Server': 'Kestrel'}
>>> response.json()
{u'jsonrpc': u'2.0', u'id': u'0x0', u'error': {u'message': u'Incorrect message', u'code': -32700, u'data': None}}

**Comment by tkstanczak** [comment]
Python requests failing - need to check why, curl looks good, for now tested only against 1.1.5

**Comment by tkstanczak** [comment]
@Mikerah have you enabled JSON RPC in the config file?
  "JsonRpc": {
    "Enabled": true, <-----------------

**Comment by tkstanczak** [comment]
This seems to be an error on the request side - so either in Python or Jupyter notebook?
An "json parser couldn't parse the POST request" when using Python's request library through a jupyter notebook.

**Comment by Mikerah** [comment]
I got the following message when using the Nethermind CLI

`Failed to respond to eth_getCode Method eth_getcode is not supported|`

When using the requests library through jupyter notebook, I get the following error

`{'id': '0x0', 'jsonrpc': '2.0', 'error': {'code': -32700, 'message': 'Incorrect message', 'data': None}}`

I tried with curl again and it works.

**Comment by Mikerah** [comment]
I forgot to mention, the json rpc attribute is indeed enabled in the mainnet config file.

**Comment by Mikerah** [comment]
It turns out the reason why it doesn't work in python is because one needs to pass in the entire json object as a string. So, instead of passing something like `requests.post('http://localhost:8545', data={'jsonrpc': '2.0',...})` one needs to pass in `request.post('http://localhost:8545, data="""{'jsonrpc': '2.0',...}"""')`

**Comment by Mikerah** [comment]
I got everything to work after some more troubleshooting with my collaborators. Nothing was wrong from the Nethermind side. 

Thank you very much for your help and for creating such a great client.
