### ISSUE TITLE
Introduce granular access configuration for JSON RPC modules and methods.

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#952]

**Comment by tkstanczak** [comment]
We should have a config test to confirm that the right modules are enabled by default and no other modules.

**Comment by tkstanczak** [comment]
`RpcModuleProvider` class is responsible for loading modules that are approved. Currently we allow to enable / disable whole modules in order to avoid risk of exposing potentially dangerous operations to public. 
We should define the subset of safe modules to be enabled by default and require unsafe modules to be explicitly enabled via configuration by users.

We should enable `JSON RPC` method level controls (so we can say that for example `eth_getBlockByNumber` can be called via `WebSockets` and `HTTP` and 'eth_sign' can only be called via [IPC](https://en.wikipedia.org/wiki/Inter-process_communication). Please note that IPC support needs to be added and will be part of a separate task.

**Comment by MysticRyuujin** [comment]
I saw this while searching for an issue and I thought I should tag #2196 as related

**Comment by tkstanczak** [comment]
thanks @MysticRyuujin I will close this one and track IPC separately now
