### ISSUE TITLE
Key structure of the RocksDB instance for Nethermind

### ISSUE THREAD

**Issue by Mikerah** [NethermindEth/nethermind#954]
I'm working on a project in which I need to query a nethermind node for bytecode. Currently, I have a list of addresses and using parallelization, have retrieve a subset of the bytecodes for these addresses. A way to do this is to traverse the state trie stored in the database directly. In order to do this, we need to be familiar with the key structure of the RocksDB instance for our Nethermind node.

Is there a way to get this information?

**Comment by tkstanczak** [comment]
To retrieve the bytecodes you only need to call eth_getCode JSON RPC method.

Retrieving them in any other way would be complex - yoj would need to
follow the patricia tree nodes all the way down to leaves where accounts
are stored and then get the bytecodes via the bytecode hash.

**Comment by Mikerah** [comment]
My collaborator traced through the code and decided to use the python wrapper for RocksDB and interact with the CodeRockDb instance.
