### ISSUE TITLE
Correct answer for -2**255/-1 is -2**255 but the result is 2**255

### ISSUE THREAD

**Issue by kimdora** [NethermindEth/nethermind#974]
Hi.

According to the Ethereum yellow paper, (-2\**255)/(-1) is -2\**255.
![sdiv-eth-yellow](https://user-images.githubusercontent.com/35003495/68468723-ed9d2600-025b-11ea-95a6-92400c07e29f.PNG)
But the result of Nethermind' virtual machine is (2\**255).
```
(SDIV)
a => -57896044618658097711785492504343953926634992332820282019728792003956564819968
b => -1
a / b => 57896044618658097711785492504343953926634992332820282019728792003956564819968
```

I tested using below code.
```
contract divTest {
	function div() public pure returns (int256) {
		int256 x = (-2) ** 255;
		int256 y = x / (-1);
		return y;
	}
}
```

**Comment by tkstanczak** [comment]
checking

**Comment by tkstanczak** [comment]
[Test]
        public void Representations()
        {
            byte[] a = BigInteger.Parse("-57896044618658097711785492504343953926634992332820282019728792003956564819968").ToBigEndianByteArray(32);
            byte[] b = BigInteger.Parse("57896044618658097711785492504343953926634992332820282019728792003956564819968").ToBigEndianByteArray(32);

            Assert.AreEqual(a, b);
        }

**Comment by tkstanczak** [comment]
It is a matter of interpretation of the number
If you tried to represent on 2^256 number from -2^255 up to 2^255 and 0 then you would need 2*2^255 + 1 items
Since it is not possible the ranges of signed numbers are either from -2^255 up to 2^255 - 1 or from -2^255 + 1 up to 2^255. Then it is a matter of interpretation of the number [128,0,0,...,0,0].

**Comment by tkstanczak** [comment]
![image](https://user-images.githubusercontent.com/498913/68509887-090f2d80-026a-11ea-8871-dd5da3d5d01f.png)
It is customary that the range is wider on the negative side.

**Comment by tkstanczak** [comment]
Hence the yellow paper interpretation.

**Comment by tkstanczak** [comment]
Now - you are showing a contract which would suggest that you are actually testing Solidity interpretation?

**Comment by tkstanczak** [comment]
@kimdora please have a look at:
https://github.com/NethermindEth/nethermind/pull/981

And let me know if I am mistaken here.

**Comment by kimdora** [comment]
So, did you mean the range of numbers that EVM can represent are
- from -2\**255 to (2\**255) - 1

or
- from (-2\**255) + 1 to 2\**255

right?

**Comment by kimdora** [comment]
And if the EVM implements -2**255 == 2**255, then you are right! 😄

**Comment by tkstanczak** [comment]
-2**255 to (2**255) - 1

**Comment by tkstanczak** [comment]
Nonetheless, thank you for asking the question @kimdora  - a potentially critical vulnerability. I think that this scenario is covered with Ethereum tests and also there is a special case for this in the Virtual Machine code.
